### ISSUE TITLE
Receiving push alerts from unsubscribed channels (iOS)

### ISSUE THREAD

**Issue by SachinAhujaWork** [parse-community/Parse-SDK-iOS-OSX#1002]
In some iPhone 6s/6s plus devices (iOS 9.3.3), the push alerts sent through a channel are being received even if the channel is unsubscribed. I am using the latest parse version 1.14.2. These are test devices where we keep installing/uninstalling apps with parse integration. 

As we are migrating the apps from parse, the below code is used to unsubscribe all the parse channels :-

```
PFInstallation *currentInstallation = [PFInstallation currentInstallation];
currentInstallation.channels = [NSArray array];
[currentInstallation saveEventually];
```

But, still the notifications are received from parse. Is there any parse channel/installation settings that are cached on the device ? Please advise.

**Comment by claesjacobsson** [comment]
Did you solve this? If not, is the Installation + channel updated on the server?
