### ISSUE TITLE
How to cancel a query?

### ISSUE THREAD

**Issue by devmsh** [parse-community/Parse-SDK-iOS-OSX#1004]
We develop a search screen, and we need to support instant result.

Once the user start entering any character, we try to fetch the results from the back-end, but when the user enter another character, the new query will take longer time because it wait the previous request response?

How can we cancel the first query before we start the new one?

**Comment by akshit-zaveri** [comment]
PFQuery queryExample;
[queryExample cancel];

**Comment by andresteves** [comment]
When trying to cancel query I got:
` [Bolts] Warning: `BFTask` caught an exception in the continuation block. This behavior is discouraged and will be removed in a future release. Caught Exception: *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array`
