### ISSUE TITLE
PFUser() is going in infinite loop

### ISSUE THREAD

**Issue by ankushmittal87** [parse-community/Parse-SDK-iOS-OSX#1007]
Hi,

I am new to parse sdk. I have a project in which I need to create PFUser object. But while creating an object of PFUser(), my application is going into infinite loop.I am facing this issue after I upgrade my parse library. Right now I am using **parse 1.14.2**. Before that it was working fine. Below is my code. 

```
     `  var user = PFUser()
        print("After Parse object creation")
        user["fullname"] = nameTextField.text!.lowercaseString
        user.username = emailTextField.text!.lowercaseString
        user.password = "test"
        user.email = emailTextField.text!.lowercaseString`
```

Please assist.

Thanks,
Ankush

**Comment by tahoecoop** [comment]
I am getting something similar, just upgraded the sdk. Now when I'm doing a check for ```PFUser.currentUser()```, my app just holds up there and doesn't get past that line of code. It was working fine before when I had the framework files in my app, but I just updated the sdk with cocoa pods.

**Comment by brianyyz** [comment]
FWIW I had a similar problem which I "fixed" by removing the calls to registerSubClass in my subclasses of PFObject. The SDK now automatically registers subclasses of PFObject.

**Comment by tahoecoop** [comment]
Thanks brianyyz, just tried that, still stalling out at ```User.currentUser()```, which is my PFUser subclass. 
<img width="340" alt="screen shot 2016-08-14 at 1 27 08 pm" src="https://cloud.githubusercontent.com/assets/12720941/17651816/de8176d0-6222-11e6-85de-d3b69dd3ecb0.png">

**Comment by brianyyz** [comment]
That semaphore_wait_trap was exactly what I was having on my first call to Parse - in my case it was PFInstallation.currentInstallation() but after taking that out the trap occurred on PFUser.currentUser().

I went back through my Git commits and see that I also took out the class init method - here's a stripped down version of one of my working classes

```
class SharedLocation: PFObject, PFSubclassing {
    
    @NSManaged var latitude:        Double
    @NSManaged var locationName:    String
    @NSManaged var locationAddress: String
    @NSManaged var locationNotes:   String
    @NSManaged var longitude:       Double
    @NSManaged var team:            Teams
    @NSManaged var locationOwner:   PFUser

    class func parseClassName() -> String {
        return sharedLocationClassName
    }
    
    /*
    override class func initialize() {
        var onceToken: dispatch_once_t = 0
        dispatch_once(&onceToken) {
            self.registerSubclass()
        }
    }
    */
    
    override class func query() -> PFQuery? {
        
        // return all shared locations in ascending name order
        let query = PFQuery(className: SharedLocation.parseClassName())
        query.cachePolicy = PFCachePolicy.IgnoreCache
        query.orderByAscending(locationNameString)
        return query
    }
    
    override init() {
        super.init()
    }
// other stuff 
}
```

**Comment by tahoecoop** [comment]
@brianyyz You are the man, this totally did it! Thanks for taking the time. I'm sure this will help other people too.

**Comment by brianyyz** [comment]
Glad I could help @tahoecoop

**Comment by ankushmittal87** [comment]
Thank you @brianyyz and @tahoecoop . I was stuck there and left it there only. Glad to know that now I can move my code ahead. 

Cheers!

**Comment by tylerarnold** [comment]
yup I had the same issue, fixed by removing the class initialize/registerSubclass code.

**Comment by davidrothera** [comment]
Was seeing this as well (hanging upon startup) and commenting out the `registerSubclass` fixed things:

```swift
class SugarProduct: PFObject, PFSubclassing {
    @NSManaged var name: String
    @NSManaged var productDesc: String
    @NSManaged var enabled: Bool
    @NSManaged var productImageHeader: PFFile
    @NSManaged var productImageSmall: PFFile

//    override class func initialize() {
//        // swiftlint:disable nesting
//        struct Static {
//            static var onceToken: dispatch_once_t = 0
//        }
//        // swiftlint:enable nesting
//        dispatch_once(&Static.onceToken) {
//            self.registerSubclass()
//        }
//    }

    static func parseClassName() -> String {
        return "Products"
    }

}
```

Can we get a change in the SDK to at least give a pointer towards this required change / raise an error?

**Comment by tealshift** [comment]
Hi, can anyone help me with this in Objective C?
I'm getting the same symptom and this is my User class's init code:
```
+ (void)load {[self registerSubclass];}

-(instancetype)init{
    if(self = [super init]){
        // This is to refresh synthesized properties when PFObject properties change from a fetch.
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(resyncCounts) name:@"PFObjectRefreshed" object:self];
    }
    return self;
}
```
