### ISSUE TITLE
Question: is there a way to connect multiple Parse backend?

### ISSUE THREAD

**Issue by caoer** [parse-community/Parse-SDK-iOS-OSX#1008]
I'm wondering if I can create multiple Parse instance pointed to different server? 
I understand in current code, it can't. but just took a look at Parse.m. If I modify it a little bit. like adding ability to switch current ParseManager( `+ (ParseManager *)_currentManager`), is it doable? 
Not sure if there is any other things to watch out. Do you guys have any suggestions?

**Comment by alexblack** [comment]
👍

**Comment by Elegia** [comment]
👍
