### ISSUE TITLE
Support for new iMessage Apps

### ISSUE THREAD

**Issue by talkaboutdesign** [parse-community/Parse-SDK-iOS-OSX#1014]
Would be great if you can add support for new Messaging App templates in Xcode. This would require to add ability to initialize parse outside of AppDelegate since there is no such thing in Messages Extension. 

Just for reference if you try to do it today the error is the following: 

```
dyld: Library not loaded: @rpath/Bolts.framework/Bolts
  Referenced from: /Users/mpetriv/Library/Developer/CoreSimulator/Devices/C858D5BE-9C5F-48D2-91D5-0D8D697B6D22/data/Containers/Bundle/Application/238ED164-0CF9-46B8-B522-DDEF2147D0EE/Alamo Stickers.app/PlugIns/MessagesExtension.appex/MessagesExtension
  Reason: image not found
```

**Comment by lastMove** [comment]
This error is not related to initializing Parse outside of AppDelegate IMO. 
Are you using Carthage to include Bots /  Parse ?

**Comment by talkaboutdesign** [comment]
Cocoapods Xcode 8 Beta

**Comment by dtalbert** [comment]
I'm currently working on this. However, I'm having issues with Parse & Swift 3. Once I resolve that I'll be on to working on iMessage extensions. BTW, does iMessage extensions require Swift 3?

**Comment by CaptainKurt** [comment]
Anyone find a solution to this issue?

**Comment by pMalvasio** [comment]
+1 to find a solution for this

**Comment by pMalvasio** [comment]
@dtalbert I'm developing an iMessage extension with Swift 2.3 without problems. You only need to build with the SDK of iOS 10 and the version of Swift can be 2.3 or 3

**Comment by mariiio** [comment]
+1 to find a solution for this
