### ISSUE TITLE
Swift 3 beta 6: PFQuery whereKey(key:equalTo) doesn't work with Bool

### ISSUE THREAD

**Issue by jsslai** [parse-community/Parse-SDK-iOS-OSX#1019]
I'm trying to use following query constraint and it doesn't work with the latest Swift beta: 

`query.whereKey("public", equalTo: true)`

Is this correct way to pass boolean in Swift? I guess this happens because latest Swift 3 beta imports Objective-C id type as Any instead of AnyObject and something happens when Bool is bridged to NSNumber. If I explicitly cast to NSNumber the query works:

`query.whereKey("public", equalTo: true as NSNumber)`

**Comment by PaulHuynh3** [comment]
query.whereKey("pubic", equalTo: true) still works on Swift 4. The below method will not work.

**Comment by flovilmart** [comment]
@PaulHuynh3 so we can close this one&

**Comment by PaulHuynh3** [comment]
Yup, I tried it yesterday and everything was good.

**Comment by flovilmart** [comment]
Thanks!@
