### ISSUE TITLE
No support for multiple subclassings of PFUser

### ISSUE THREAD

**Issue by hughhan1** [parse-community/Parse-SDK-iOS-OSX#1023]
I would like to create two different types of `PFUser`s. I would like to create both a student and a teacher like so:

``` swift
class Teacher : PFUser {

    // class variables

    override class func initialize() {
        struct Static {
            static var onceToken : dispatch_once_t = 0;
        }
        dispatch_once(&Static.onceToken) {
            self.registerSubclass()
        }
    }

    // class functions
}
```

``` swift
class Student : PFUser {

    // class variables

    override class func initialize() {
        struct Static {
            static var onceToken : dispatch_once_t = 0;
        }
        dispatch_once(&Static.onceToken) {
            self.registerSubclass()
        }
    }

    // class functions
}
```

However, when I try to instantiate either a `Teacher` or a `Student`, I get the following error. 

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException',
reason: 'Tried to register both School.Teacher and School.Student as
the native PFObject subclass of _User. Cannot determine the right class to use
because neither inherits from the other.'
```

It seems that I cannot have two different subclasses of `PFUser`. Whether or not this is the case, what should I do to work around this issue?

**Comment by brianyyz** [comment]
Registration of sub classes of PFObject is now automatic. Removing the call to registerSubclass worked for me.

**Comment by sash83** [comment]
Not working for me. I subclass PFUser and get this error: 'The class "......" must be registered with registerSubclass before using Parse.'
Everything worked before I updated pods.

**Comment by brianyyz** [comment]
Can you be more specific ?  Versions of parse-server, ios sdk, sample code, etc.? Is this Swift3?

**Comment by sash83** [comment]
My parse-server is on Heroku platform. iOS 10 in Xcode 8 with Swift 2.3. I basically use the same code as above. Subclassing PFUser and registerSubclass() in AppDelegate.

**Comment by brianyyz** [comment]
In addition to removing the call to registerSubclass() in AppDelegate I also commented out the following in my subclass.
```
    override class func initialize() {
        var onceToken: dispatch_once_t = 0
        dispatch_once(&onceToken) {
            self.registerSubclass()
        }
    }

```

**Comment by sash83** [comment]
Not working for me :(
Where did you find that solution to leave registering out?

**Comment by brianyyz** [comment]
I'm on parse-server 2.2.16 and I'm using the parse-library-1.12.0. What level of the IOS SDK are you at? The breaking change that introduced automatic subclass registration was fairly recent but I don't recall specifically. 

If I had to guess I'd say your IOS SDK is from before that change?

**Comment by sash83** [comment]
I'm on the latest version Xcode 8. The iOS SDK is integrated. I'm using Parse 1.14.2

**Comment by brianyyz** [comment]
Are you able to post your subclass ?  If it is confidential I can send you a couple of mine if it helps

**Comment by brianyyz** [comment]
See issue [1035](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/1035#issuecomment-248533963) for a suggestion from @steveRobert
