### ISSUE TITLE
Cannot send push messages in Swift 3

### ISSUE THREAD

**Issue by francisjervis** [parse-community/Parse-SDK-iOS-OSX#1028]
I am encountering a "Cannot convert value of type 'PFQuery<PFObject>' to expected argument type 'PFQuery<PFInstallation>?' after updating to xCode 8 GM and converting a project to Swift 3. This code was working correctly before. 

The query is unchanged and looks like it should return a PFInstallation:

```
let acceptPushQuery: PFQuery = PFInstallation.query()!
acceptPushQuery.whereKey("isOwnedBy", equalTo: matchedUser.objectId!)
```

**Comment by devladinci** [comment]
@francisjervis You may cast to `PFQuery<PFInstallation>` in order to get it working.

``` guard let query = PFInstallation.query() as? PFQuery<PFInstallation> else { return }```

**Comment by jaimeagudo** [comment]
Your cast works just fine @devladinci, thanks

I experienced this compiler error 

`Cannot convert value of type 'PFQuery<PFObject>' to expected argument type 'PFQuery<PFInstallation>?'`

following the oficial docs sample at https://parseplatform.github.io/docs/ios/guide/#using-advanced-targeting

```

// Create our Installation query
let pushQuery = PFInstallation.query()
pushQuery.whereKey("injuryReports", equalTo: true)

// Send push notification to query
let push = PFPush()
push.setQuery(pushQuery) // Set our Installation query
push.setMessage("Willie Hayes injured by own pop fly.")
push.sendPushInBackground()

```
