### ISSUE TITLE
Progress call block .getDataInBackgroundWithBlock not being called.

### ISSUE THREAD

**Issue by HackShitUp** [parse-community/Parse-SDK-iOS-OSX#1030]
After upgrading to Xcode 8.0, the call block isn't being called, leaving an empty UIImageView - I don't think the image was fetched, if at all called. I'm aware that the Parse framework for the iOS SDK is also updated. I don't know what's causing this.

**Comment by nitrag** [comment]
Same, what's the proper:

`PFUser.logInWithUsername()`
`user.signUpInBackground()`

**Comment by HackShitUp** [comment]
@nitrag did you by any chance covert your Swift syntax to version 3?

**Comment by nitrag** [comment]
Yes it converted automatically. #muchnewb

**Comment by HackShitUp** [comment]
@nitrag Yea I think we're going to have to update our frameworks via cocoapods lol...

**Comment by dallin** [comment]
Has anyone found a fix for this? Or figured out what the proper method is?
