### ISSUE TITLE
Casting a subclassed PFObject causes 'error: use of undeclared type 'Parse' '

### ISSUE THREAD

**Issue by jboo1212** [parse-community/Parse-SDK-iOS-OSX#1031]
I have read through every github PFObject subclassing thread issue and still can't find a workaround.  Some background information: 1) the class is registered in AppDelegate.  2) I used https://www.appcoda.com/advanced-parse-tips/ for subclassing (didn't get any compile-time errors).  3) Posting to my Heroku-hosted mongoDB works with Parse API as I've already submitted several post requests.  4) I used CocoaPods to get the Parse SDK.  
## Inside lldb I printed the PFObject I 'GET' from mongoDB and something interesting pops up...

1) Could not cast value of type 'PFObject' (0x10f4ce0b8) to 'Culinarian.Post' (0x10f1a11e0).

2) Printing description of object:
expression produced error: /var/folders/qd/t7ht0b3n6k3_2xw4jsqlmc340000gn/T/lldb/12773/expr7.swift:1:46: error: use of undeclared type 'Parse'
$__lldb__DumpForDebugger(Swift.UnsafePointer<Parse.PFObject>(bitPattern: 0x120ca79f0).memory)
                                             ^~~~~
/var/folders/qd/t7ht0b3n6k3_2xw4jsqlmc340000gn/T/lldb/12773/expr7.swift:1:45: note: while parsing this '<' as a type parameter bracket
$__lldb__DumpForDebugger(Swift.UnsafePointer<Parse.PFObject>(bitPattern: 0x120ca79f0).memory)

---

Below is the code block...

func loadPosts() {

```
    // Go to our follow table
    let followQuery = PFQuery(className: "follow")

    // obtain all the entries such that it looks like (follower: me, following: [ ] )
    followQuery.whereKey("follower", equalTo: "Robin")
    followQuery.findObjectsInBackgroundWithBlock({ (objects: [PFObject]?, error: NSError?) in


        if error == nil {

            self.followingPeople.removeAll(keepCapacity: false)

            for object in objects! {

                self.followingPeople.append(object.objectForKey("following") as! String)

            }

            // Add ourself to the list because we want to see our posts too
            self.followingPeople.append("Robin")


            let postQuery = PFQuery(className: "posts")
            postQuery.whereKey("username", containedIn: self.followingPeople)
            postQuery.limit = self.page
            postQuery.addDescendingOrder("createdAt")
            postQuery.findObjectsInBackgroundWithBlock({ (objects: [PFObject]?, error: NSError?) in

                // Loop through the object and and then add the data unwrapped to the current index.

                if error == nil {

                    self.feedPost.removeAll(keepCapacity: false)


                    for object in objects! {

                        let post = object as! Post
                        self.feedPost.append(post)
                    }

                }


                else {
                    print(error!.localizedDescription)
                }

            }) // Inner block completion

        }
        else {
            print(error!.localizedDescription)
            }

    }) // Outer block completion


    }
```

**Comment by HackShitUp** [comment]
@jboo1212 Has this issue been resolved? I'm facing the same difficulty

**Comment by jboo1212** [comment]
Hi @HackShitUp I've converted to Swift 3 but haven't tried if this works or not in Xcode 8, Swift 3.  I'll try again a little later
