### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by katopz** [parse-community/Parse-SDK-iOS-OSX#1033]
Can I expect Swift 3.0 support? Thanks

**Comment by otymartin** [comment]
@katopz it's an `objective-c framework` so it should work in swift 3 projects.

**Comment by katopz** [comment]
@otymartin Oh, sorry I mean `ParseStarterProject-Swift` and some other Swift example.

**Comment by danipolo** [comment]
same here... it's a nightmare to move all to swift 3 :(

**Comment by nyxee** [comment]
yes please, i had gotten excited about this Parse thing but after trying to get it to work for a week, i think its better to move on.. I wonder how it is on the Android side.. I already have my own API in php but i was hoping to give this thing a chance...

**Comment by flovilmart** [comment]
There's no issue with Swift 3 per-se. we use and run it in production. I'M not sure what you need that is swift 3?

**Comment by nyxee** [comment]
I need a Sample please.
So far all the Samples are not working on OSX and iOS.
For example, creating a NEw Project and importing the Parse and Bolts frameworks does not work.
It would be nice if u would provide a working example.

According to what you're saying, that should be extremely easy for you, but, i've spent a week trying to get past four lines. If i had a starting point, I would be ahead by now. 

We have no where to start please.

**Comment by otymartin** [comment]
@nyxee you should use cocoapods. What specfically are you failing at? Theres nothing in this SDK that has failed me. Not even a single warning. IM on xcode 8.3 swift 3

**Comment by flovilmart** [comment]
Merged on master. All samples are compatible with Swift 3 and tested by the CI
