### ISSUE TITLE
PFUser subclass fails on 1.14.2 and Xcode 8 / iOS 10

### ISSUE THREAD

**Issue by Mezaza** [parse-community/Parse-SDK-iOS-OSX#1035]
Since those updates subclassing fails. Standard error message: 'The class User must be registered with registerSubclass before using Parse.'
I'm still using registerSubclass() in AppDelegate. I'm talking about Swift.

Everything worked before. Does anyone have the same issue?

**Comment by steveRobert** [comment]
Yes, last Parse SDK version (1.14.2) crash with registerSubclass when app launch.
Downgrade to 1.13.0 !
Work for me on xCode 8 with Swift 3

**Comment by brianyyz** [comment]
@steveRobert explains why I haven't hit this yet as I'm on 1.12.0 of the IOS SDK. Thanks.

**Comment by steveRobert** [comment]
I tried to upgrade to 1.14.2,  I removed all registerSubclass in my Parse service that called in AppDelegate and I also removed all initialize functions in my subclasses of PFObject . But I'm still on parse-server 2.2.17 version.

Delete it:
```
   override class func initialize() {
        struct Static {
            static var onceToken : Int = 0;
        }
        _ = PMessage.__once
   }
```

See changelog from https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/releases/tag/1.14.0.
Register subclasses is now automatically.

Thank's @brianyyz 

Works like a charm !

**Comment by sash83** [comment]
not working for me with 1.14.2. I downgraded to Parse to 1.13.0 and it works!

As a reminder, I do not subclass PFObject but PFUser!
Maybe automatic registering is only for subclassing PFObject.

**Comment by steveRobert** [comment]
PFUser is a class that inherits from PFObject !
Here is my subclass of PFUser called PUser.

```
import UIKit
import Parse


class PUser: PFUser {
    
    
    // ***********************************************
    // MARK: - Interface
    // ***********************************************
    
    
    var picture:PFFile? {
        get { return self["picture"] as? PFFile }
        set { self ["picture"] = newValue }
    }
    
    
    var lastname:String? {
        get { return self["lastName"] as? String }
        set { self["lastName"] = newValue }
    }
    
    
    var firstname:String? {
        get { return self["firstName"] as? String }
        set { self["firstName"] = newValue }
    }
    
    
    var fbId:String? {
        get { return self["fbId"] as? String }
        set { self["fbId"] = newValue }
    }
    
        
    var visibility:Bool {
        get { return self["visibility"] as! Bool }
        set { self["visibility"] = newValue }
    }
    
    
    var notification:Bool {
        get { return self["notification"] as! Bool }
        set { self["notification"] = newValue }
    }
    
    
    var birthday:Date {
        get { return self["birthday"] as! Date }
        set { self["birthday"] = newValue }
    }

}
```

Works for me with last Parse Version 1.14.2

**Comment by livingstonef** [comment]
The above suggestion by @steveRobert  does not work for me

Parse 1.14.2 
Xcode 8.2 / Swift 3.0

"The class _TtCC6LabDoc8LabCloud4User must be registered with registerSubclass before using Parse."

Even when i add registerSubclass() calls to the AppDelegate it still fails with the above error!

**Comment by AmbroiseCollon** [comment]
I too have the same issue with version 1.14.2 :

```
The class NameOfClass must be registered with registerSubclass before using Parse.
```
I had to downgrade to 1.13.0
I had the issue whether I used registerSubclass or not

**Comment by livingstonef** [comment]
BUMP! Is there any update on this issue? it is practically impossible to subclass PFUser on the current version.

**Comment by flovilmart** [comment]
If the only annoyance is that you need to call registerSubclass on user subclasses i’ll Close as won’t fix

**Comment by kangaroo5383** [comment]
@flovilmart not sure about that I just tried in this `didFinishLaunchingWithOptions` and I'm still getting the same error. Using Parse (1.17.1)
```
PFUser.registerSubclass()
let aUser = PFUser()
```

**Comment by flovilmart** [comment]
In the code example above you mention Usersubclass and then PFUser. Which is it?

**Comment by kangaroo5383** [comment]
@flovilmart the Usersubclass example isn't my comment.  I've been using `PFUser`

**Comment by flovilmart** [comment]
I’m not sure what’s wrong, you should never need to call registerSubclass with PFUser. Are you able to share a demo project that shows the issue
