### ISSUE TITLE
Parse LiveQuery SDK in Swift 3

### ISSUE THREAD

**Issue by Samigos** [parse-community/Parse-SDK-iOS-OSX#1036]
Hello everyone! I'm about to update to Xcode 8 - Swift 3 and I would like to know, if I'm gonna have any issues with Parse SDK and Parse LiveQuery SDK in my project!

Thanks in advance!

**Comment by iStopped** [comment]
If you use, like me, the BFTask ability to do a bunch of queries and calling a single callback yes, you are going to have a lot of problems.
