### ISSUE TITLE
IPv6 Support?

### ISSUE THREAD

**Issue by idefen1** [parse-community/Parse-SDK-iOS-OSX#1037]
My app was rejected today due to 'not supporting IPv6'. Please help. More info and screenshots here:

http://stackoverflow.com/questions/39605020/ipv6-support-using-parse-com

Please help =*(

**Comment by flamesoft** [comment]
It seems that the latest version from Jul 17, 2016 supports ipv6.

**Comment by idefen1** [comment]
My version is from July 21 2016 and was rejected because it threw an error on IPv6.

**Comment by flamesoft** [comment]
I have no luck with the App Review. I guess it is that the Parse.framework doesn't support IPv6.
