### ISSUE TITLE
Parse swift 3 continue problem

### ISSUE THREAD

**Issue by tmp120210** [parse-community/Parse-SDK-iOS-OSX#1040]
Hello!
I am trying to migrate my parse project to swift 3 and found an issue. Looks like I can't use continuewithtask anymore after search completed, because in swift 3 it's converted to "continue" which is a reserved word.

PFQuery(className: "Post").findObjectsInBackground().continue{(task) -> Any? in 
return nil
}
I can't use Bolts-Swift either because parse return BFTask which is not suitable now.

Will parse sdk support swift 3.0?

**Comment by pjchavarria** [comment]
Use it like this.

```PFQuery(className: "Post").findObjectsInBackground().continue({(task) -> Any? in 
return nil
})```

Compiler won't complain then
