### ISSUE TITLE
Internal Parse SDK crash

### ISSUE THREAD

**Issue by robertodias180** [parse-community/Parse-SDK-iOS-OSX#1049]
I am getting this error with V:1.14.2 

**Fatal Exception: NSInternalInconsistencyException
Cannot register subclasses in a bundle that hasn't been loaded!**

it looks equal to this : #989 

here is the stack trace [stack trace](http://crashes.to/s/7426c386cf4)

```
PFObjectSubclassingController.m line 344
-[PFObjectSubclassingController _registerSubclassesInBundle:]

PFObjectSubclassingController.m line 131
__63-[PFObjectSubclassingController scanForUnregisteredSubclasses:]_block_invoke
```

**Comment by esetnik** [comment]
I have the same crash

**Comment by nguyenphan** [comment]
I am having this crash too!!!

**Comment by thibauddavid** [comment]
Having it too, but couldn't reproduced it. Only Apple during a validation process could ATM

**Comment by emes** [comment]
We have the same crash.

**Comment by MattiaConfalonieri** [comment]
Any solution?

**Comment by myusuf3** [comment]
@nlutsenko i am experiencing same exact crash as others. Would love some help here blocking a release. If you can point me on how to solve issue I can patch it. 

@robertodias180 any workaround?

```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x1928061c0 __exceptionPreprocess
1  libobjc.A.dylib                0x19124055c objc_exception_throw
2  CoreFoundation                 0x192806108 -[NSException initWithCoder:]
3  App                      0x1001f24a4 -[PFObjectSubclassingController _registerSubclassesInBundle:]
4  App                      0x1001f0f88 __63-[PFObjectSubclassingController scanForUnregisteredSubclasses:]_block_invoke
5  Foundation                     0x1931ee24c -[__NSObserver _doit:]
6  CoreFoundation                 0x1927a022c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
7  CoreFoundation                 0x19279f930 _CFXRegistrationPost
8  CoreFoundation                 0x19279f6ac ___CFXNotificationPost_block_invoke
9  CoreFoundation                 0x19280eb9c -[_CFXNotificationRegistrar find:object:observer:enumerator:]
10 CoreFoundation                 0x1926e1bf4 _CFXNotificationPost
11 Foundation                     0x193246a30 -[NSBundle loadAndReturnError:]
12 UIAccessibility                0x19ec9ad34 -[NSBundleAccessibility loadAndReturnError:]
13 UIAccessibility                0x19ec9c5c4 +[UIAccessibilityLoader __loadActualAccessibilityBundle:didLoadCallback:loadSubbundles:]
14 UIAccessibility                0x19ec9bce4 +[UIAccessibilityLoader _loadAXBundleForBundle:didLoadCallback:forceLoad:loadSubbundles:loadAllAccessibilityInfo:]
15 UIAccessibility                0x19ec9ac50 __70-[NSBundle(UIAccessibilityLoader) _loadAXBundleForBundleOffMainThread]_block_invoke
16 UIAccessibility                0x19ec9bc94 +[UIAccessibilityLoader _loadAXBundleForBundle:didLoadCallback:forceLoad:loadSubbundles:loadAllAccessibilityInfo:]
17 UIAccessibility                0x19ec9a9c0 -[NSBundle(UIAccessibilityLoader) _loadAXBundleForBundleOffMainThread]
18 UIAccessibility                0x19ec9ae08 __44-[NSBundleAccessibility loadAndReturnError:]_block_invoke_2
19 libdispatch.dylib              0x191691200 _dispatch_call_block_and_release
20 libdispatch.dylib              0x1916911c0 _dispatch_client_callout
21 libdispatch.dylib              0x19169f444 _dispatch_queue_serial_drain
22 libdispatch.dylib              0x1916949a8 _dispatch_queue_invoke
23 libdispatch.dylib              0x19169f940 _dispatch_queue_override_invoke
24 libdispatch.dylib              0x1916a138c _dispatch_root_queue_drain
25 libdispatch.dylib              0x1916a10ec _dispatch_worker_thread3
26 libsystem_pthread.dylib        0x19189a2b8 _pthread_wqthread
27 libsystem_pthread.dylib        0x191899da4 start_wqthread
```

**Comment by myusuf3** [comment]
@nlutsenko any ideas or progress on this front?

**Comment by sylvioleblanc** [comment]
Also seeing this in production app on iOS.  Does anyone know of a workaround / solution?

**Comment by myusuf3** [comment]
@nlutsenko I understand you have other stuff, but its been a month now. Suggestion on how to fix? Or where the issue is cropping up?

**Comment by robertodias180** [comment]
Sorry for the delay, but i fixed the problem with this: 8523fbfd0e5a3a976015929ed7d88771306e7ee2

**Comment by myusuf3** [comment]
@robertodias180 has that version been released? thanks man! what version of sdk?

**Comment by robertodias180** [comment]
@myusuf3 yes it is on release for almost 3 weeks. I changed my parse to that fork (pod 'Parse', :git =>'https://github.com/sirioz/Parse-SDK-iOS-OSX')

**Comment by myusuf3** [comment]
why hasn't there been a release with this fix? @robertodias180 i would like to stay on main version here.

**Comment by robertodias180** [comment]
@myusuf3 there is PR already

**Comment by myusuf3** [comment]
@robertodias180 ahh ok, is there a reason why it will take so much time?

**Comment by mtrezza** [comment]
The discussion about this bug is happening in #1006.

**Comment by myusuf3** [comment]
@robertodias180 ok, but who can we ping about this?

**Comment by fishandphil** [comment]
is a release fixing this problem coming soon? this is affecting many of our users

<img width="1076" alt="screen shot 2017-02-14 at 14 49 24" src="https://cloud.githubusercontent.com/assets/1768773/22933938/0dde3214-f2c5-11e6-8a3c-def5a7f7f5ec.png">

**Comment by robertodias180** [comment]
@fishandphil check this https://github.com/sirioz/Parse-SDK-iOS-OSX it solved the problem for me

**Comment by fishandphil** [comment]
Thanks @robertodias180, I was just hoping for an "official" release to come out. But will def go for that branch.
