### ISSUE TITLE
Can't add object to array. 

### ISSUE THREAD

**Issue by mkaya93** [parse-community/Parse-SDK-iOS-OSX#1050]
Hi,

I'm trying to add object to the my array on data.

But when I'm trying to save it I'm getting this error.

`Warning:`BFTask`caught an exception in the continuation block. This behavior is discouraged and will be removed in a future release. Caught Exception: Invalid type in JSON write (_SwiftValue)`

also this is my code.

```
userNotification.addObjects(from: [currentUser], forKey: "readMembers")
            userNotification.saveInBackground(block: { (bool, error) in
                if error == nil {
                    print(bool)
                }else{
                    print(error)
                }
            })
```

also its returning false

**Comment by iStopped** [comment]
In my experience this means that you performed a PFQuery using a swift option without unwrapping it.

**Comment by mkaya93** [comment]
@iStopped no I just used swift option with unpwrapping it but its not working too.
