### ISSUE TITLE
Array type relationship fails to PIN when working purely on LDS (without using the server)

### ISSUE THREAD

**Issue by skulas** [parse-community/Parse-SDK-iOS-OSX#106]
There are two classes that inherit from PFObject:
1. PFComment
2. PFPost

PFPost has an array of comments as one of its dynamic properties.

I define a three PFPost objects, with two comments each. Pin them.
I query and see there are three PFPost objects and six PFComment objects in the LDS.

I define three more PFPost objects, with two comments each. Pin them.
When I query I see six PFPost objects and only six PFComments. The newly created comments were not saved into the LDS.

Has anybody found a way to overcome this, without saving the data in the server?
Using iOS SDK v1.7.5
Reproduces always.

**Comment by nlutsenko** [comment]
@skulas There is a known limitation of LDS, where if you never loaded objects from the pin in a run of the application - pinning additional objects to the same pin will make the previous objects pinned loose their children.
So the question here that would help us better understand the problem: In the flow that you are describing, are you pinning all objects to the LDS in a single run of the app, or in few runs?

**Comment by skulas** [comment]
Nikita, thank you for your response.

This is what I do (In a single run of the App)

. Create three PFPost objects, with an array containing two PFComment objects each
. PIN the PFPost objects (using an array of PFPost objects)
* * * NOTE: I don't explicitly pin the PFComment objects.
. Query and see there are three PFPost objects and six PFComment objects
. Create three new PFPost objects with an array of two PFComment objects each
. Query and see there are six PFPost objects but only six PFComment objects

So, in a single run of the App I perform two pins, but with a query in the middle. Is it the known limitation you mention?
Is there a work around for it?

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
