### ISSUE TITLE
PFKeychainStore failed to set object for key 'currentUser', with error: -34018

### ISSUE THREAD

**Issue by jose46moreno** [parse-community/Parse-SDK-iOS-OSX#1060]
Hi, i am trying to save a user with Parse but when i call the method saveInBackground through the PFUser.current(), Xcode returned this error.

What can i do?
How can i solve it?

**Comment by jose46moreno** [comment]
?

**Comment by JunaidUmer** [comment]
im having save issue with swift 3 i cant update my user and it give me this "PFKeychainStore failed to set object for key 'currentUser', with error: -34018" error in log  @flovilmart

**Comment by flovilmart** [comment]
ENable keychain sharing in your app capabilies

**Comment by jeremypiednoel** [comment]
Thanks @flovilmart.
@jose46moreno you need ton uninstall and rebuild your app as well.

**Comment by felixk** [comment]
I'm curious as to why Enabling Keychain sharing fixes this issue. It fixed it for me, but KeyChain sharing is used to share keychains between apps, why does this help in this case? Thanks!

**Comment by jeremypiednoel** [comment]
It looks like it's iOS10 simulator 
https://forums.developer.apple.com/thread/60617
http://stackoverflow.com/questions/38456471/secitemadd-always-returns-error-34018-in-xcode-8-in-ios-10-simulator
