### ISSUE TITLE
Conver to swift 3.0 failed

### ISSUE THREAD

**Issue by futureinapps** [parse-community/Parse-SDK-iOS-OSX#1061]
I'm install Parse && ParseLiveQuery from Pod. And when it ask me to convert it gives me tone of errors ...

**Comment by gateway** [comment]
We are seeing the same.. @nlutsenko have you tried parse with Xcode 8.1 Swift 3 yet?

**Comment by flovilmart** [comment]
The project is now fully compliant with Swift 3
