### ISSUE TITLE
User login/logout notifications

### ISSUE THREAD

**Issue by flovilmart** [parse-community/Parse-SDK-iOS-OSX#1065]
In order to make sure the LiveQuery SDK is properly registering automatically new subscription when the currentUser changes (sessionToken), we'd need the Parse SDK to send NSNotifications upon user login and logout events.

**Comment by hatpick** [comment]
save something (whatever) under current user object upon login and logout. For example use a boolean, when it's true means login, when it's false it's logout, now user before save in your cloud code on user class to detect what user is login in/or logging out, use this information to send notifications.

**Comment by flovilmart** [comment]
That's not for cloud code, for for communicating with the live query sdk
