### ISSUE TITLE
NSInternalInconsistencyException in PFObjectSubclassingController _registerSubclassesInBundle:

### ISSUE THREAD

**Issue by levigroker** [parse-community/Parse-SDK-iOS-OSX#1068]
We are still seeing multiple crashes due to an `NSInternalInconsistencyException` in `PFObjectSubclassingController _registerSubclassesInBundle:`, all against some version (10.0.x, 10.1.x, etc.) of iOS 10.

This has been an issue for some time and is directly and measurably impacting our customers. Your insight into the root cause and appropriate fix would be greatly appreciated.

Please see https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/pull/967

We are running `Parse (1.14.2)` with this pull request in place https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/pull/1000 which allows the `NSInternalInconsistencyException` to tell us what bundle is causing the issue.

Here are a handful of the output we are getting from this `NSInternalInconsistencyException`:

- Cannot register subclasses in an unloaded bundle: NSBundle </System/Library/AccessibilityBundles/ContactsUI.axbundle> (not yet loaded)

- Cannot register subclasses in an unloaded bundle: NSBundle </System/Library/AccessibilityBundles/WebKit.axbundle> (not yet loaded)

- Cannot register subclasses in an unloaded bundle: NSBundle </System/Library/AccessibilityBundles/SafariServices.axbundle> (not yet loaded)

- Cannot register subclasses in an unloaded bundle: NSBundle </System/Library/AccessibilityBundles/VectorKit.axbundle> (not yet loaded)

- Cannot register subclasses in an unloaded bundle: NSBundle </System/Library/AccessibilityBundles/WebKitLegacy.axbundle> (not yet loaded)

- Cannot register subclasses in an unloaded bundle: NSBundle </System/Library/AccessibilityBundles/CameraKit.axbundle> (not yet loaded)

- Cannot register subclasses in an unloaded bundle: NSBundle </System/Library/AccessibilityBundles/MessageUIFramework.axbundle> (not yet loaded)

- Cannot register subclasses in an unloaded bundle: NSBundle </System/Library/AccessibilityBundles/StoreKitFramework.axbundle> (not yet loaded)

- Cannot register subclasses in an unloaded bundle: NSBundle </System/Library/AccessibilityBundles/PreferencesFramework.axbundle> (not yet loaded)

- Cannot register subclasses in an unloaded bundle: NSBundle </System/Library/AccessibilityBundles/CoreRecognition.axbundle> (not yet loaded)

(and so on).

The stack looks like this:

```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x183bf61c0 __exceptionPreprocess
1  libobjc.A.dylib                0x18263055c objc_exception_throw
2  CoreFoundation                 0x183bf6108 -[NSException initWithCoder:]
3  <app>                          0x100346684 -[PFObjectSubclassingController _registerSubclassesInBundle:] (PFObjectSubclassingController.m:344)
4  <app>                          0x100345164 __63-[PFObjectSubclassingController scanForUnregisteredSubclasses:]_block_invoke (PFObjectSubclassingController.m:131)
5  Foundation                     0x1845de24c -[__NSObserver _doit:]
6  CoreFoundation                 0x183b9022c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
7  CoreFoundation                 0x183b8f930 _CFXRegistrationPost
8  CoreFoundation                 0x183b8f6ac ___CFXNotificationPost_block_invoke
9  CoreFoundation                 0x183bfeb9c -[_CFXNotificationRegistrar find:object:observer:enumerator:]
10 CoreFoundation                 0x183ad1bf4 _CFXNotificationPost
11 Foundation                     0x184636a30 -[NSBundle loadAndReturnError:]
12 UIAccessibility                0x190084d34 -[NSBundleAccessibility loadAndReturnError:]
13 UIAccessibility                0x1900865c4 +[UIAccessibilityLoader __loadActualAccessibilityBundle:didLoadCallback:loadSubbundles:]
14 UIAccessibility                0x190085ce4 +[UIAccessibilityLoader _loadAXBundleForBundle:didLoadCallback:forceLoad:loadSubbundles:loadAllAccessibilityInfo:]
15 UIAccessibility                0x190087048 __54+[UIAccessibilityLoader _accessibilityLoadSubbundles:]_block_invoke_2
16 libdispatch.dylib              0x182a81200 _dispatch_call_block_and_release
17 libdispatch.dylib              0x182a811c0 _dispatch_client_callout
18 libdispatch.dylib              0x182a85d6c _dispatch_main_queue_callback_4CF
19 CoreFoundation                 0x183ba3f2c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
20 CoreFoundation                 0x183ba1b18 __CFRunLoopRun
21 CoreFoundation                 0x183ad0048 CFRunLoopRunSpecific
22 GraphicsServices               0x185556198 GSEventRunModal
23 UIKit                          0x189ab52fc -[UIApplication _run]
24 UIKit                          0x189ab0034 UIApplicationMain
25 <app>                          0x100233168 main (main.m:16)
26 libdispatch.dylib              0x182ab45b8 (Missing)
```

**Comment by mbrauwers** [comment]
We're also experiencing those crashes.
Thanks

**Comment by zekechan1** [comment]
We're also experiencing the same crashes. Any idea when it will be fixed please?  Thanks.

**Comment by levigroker** [comment]
Looks like https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/pull/1087 might be a fix for this.

**Comment by levigroker** [comment]
ParsePlatform#1087 fixes this.
