### ISSUE TITLE
Session Error Handling swift 3

### ISSUE THREAD

**Issue by kwstasna** [parse-community/Parse-SDK-iOS-OSX#1070]
In Parse Documentation we can find this Session Error Handling in Swift.

    // Swift
    class ParseErrorHandlingController {
      class func handleParseError(error: NSError) {
        if error.domain != PFParseErrorDomain {
          return
        }
    
        switch (error.code) {
        case kPFErrorInvalidSessionToken:
          handleInvalidSessionTokenError()
    
        ... // Other Parse API Errors that you want to explicitly handle.
      }
    
      private class func handleInvalidSessionTokenError() {

      }
    }
    
    // In all API requests, call the global error handler, e.g.
    let query = PFQuery(className: "Object")
    query.findObjectsInBackgroundWithBlock { (objects: [AnyObject]!, error: NSError!) -> Void in
      if error == nil {
        // Query Succeeded - continue your app logic here.
      } else {
        // Query Failed - handle an error.
        ParseErrorHandlingController.handleParseError(error)
      }
    }

Can someone help me make it to swift 3?

Till now I have done the following

        import Foundation
        import Parse
        
        class ParseErrorHandlingController {
            class func handleParseError(error: NSError) {
                if error.domain != PFParseErrorDomain {
                    return
                }
                
                switch (error.code) {
                case kPFErrorInvalidSessionToken:
                    handleInvalidSessionTokenError()
                        
                     // Other Parse API Errors that you want to explicitly handle.
                }
                
                 func handleInvalidSessionTokenError() {
    
      //logout the user
                    PFUser.logOutInBackground { (error) -> Void in
                        if error == nil {
                            print("the user is logged out")
                            
                        }
                        
                    }
              
        
                  
                }
            }
        }

And i call the function with the following code.

    ParseErrorHandlingController.handleParseError(error: error as! NSError)

But i get the following errors

1) Use of unresolved identifier 'kPFErrorInvalidSessionToken'
2) Use of local variable 'handleInvalidSessionTokenError' before its declaration

Any idea?

Thanks a lot!

**Comment by bre7** [comment]
Always use syntax highlighting 😉 

---

ParseErrorHandlerController.swift:
```swift
import Foundation
import enum Parse.PFErrorCode

struct ParseErrorHandlerController {

    static func handleParseError(error: Error) {

        switch error {
        case PFErrorCode.errorInvalidSessionToken:
            handleInvalidSessionTokenError()
            // Other Parse API Errors that you want to explicitly handle.
        default:
            return
        }
    }

    private static func handleInvalidSessionTokenError() {
        // Do something
    }

}
```

Simple yet useful extension when dealing with Parse errors.

Error+PFErrorCode.swift
```swift
import Foundation
import enum Parse.PFErrorCode

extension PFErrorCode {

    static func == (lhs: NSError, rhs: PFErrorCode) -> Bool {
        return lhs.code == rhs.rawValue
    }

    static func == (lhs: Error, rhs: PFErrorCode) -> Bool {
        return lhs._code == rhs.rawValue
    }

    static func ~= (pattern: Error, value: PFErrorCode) -> Bool {
        return pattern == value
    }

    static func ~= (pattern: NSError, value: PFErrorCode) -> Bool {
        return pattern == value
    }
}
```

**Comment by nickgeorge32** [comment]
When trying to call the function `ParseErrorHandlerController.handleParseError(error: error as! Error)` I receive the following error "Use of unresolved identifier 'error'"

**Comment by sabarivasagan** [comment]
I also having this same issue... I can't Import Parse in my project... even I created pod file in my project...Now I searching for help
