### ISSUE TITLE
Notification not stable

### ISSUE THREAD

**Issue by allen8300** [parse-community/Parse-SDK-iOS-OSX#1072]
I currently have a mobile-ios chat app working with Cloud Code, which can send messages.   

But the push notifications seems to be very very very unstable. 

Only a very small percentage of the notifications can actually get through to the devices even in the foreground.

 I have tried following checking but still no luck. 
1. Upload a new .p12 and updated provisioning files accordingly.
2. Toggle the "Client push enabled setting.

I don't dare to upload the app to AppStore before I can figure out where the problems is. 

Please help out and advice!

**Comment by mtrezza** [comment]
@allen8300 Can you post your code and more info about your system?

**Comment by allen8300** [comment]
@mtrezza , thanks so much for your reply. It's late, I already used other services. Thanks anyway.

**Comment by grahamito** [comment]
@allen8300 , what were the other services you ended up using ? thanks.
