### ISSUE TITLE
Network connection failed. Making attempt #...

### ISSUE THREAD

**Issue by JoseVigil** [parse-community/Parse-SDK-iOS-OSX#1073]
His guys, I am running parse on my own ubuntu server and I deliberately try to connect from my iOS app via swift when the server is down. And I naturally get.

> Network connection failed. Making attempt 4 after sleeping for 12.360906 seconds.
> Could not connect to the server. (Code: 100, Version: 1.13.0)

However I would like to catch this error and handle it myself to provide information to the user. I have not been able to catch it.

Does anybody knows how I can do this?

Thanks,
Jose

**Comment by Prateekrajdasari** [comment]
i'm facing the same issue with version 1.14.4

**Comment by Noodlekim** [comment]
We have the same issue, too.
Is this issue sloved?

**Comment by flovilmart** [comment]
This means the network connection to your was lost or that your server didn’t respond in a reasonable amount of time.

**Comment by dekple** [comment]
Has anyone found a solution to handling this error so we can display an alert to the user?

**Comment by flovilmart** [comment]
@dekple this would be nice to expose however, Bolts only allows for a single response to resolve, instead of many.
