### ISSUE TITLE
Local Datastore is deprecated; how do we achieve the same functionality? Esp retrieving objects from local storage...

### ISSUE THREAD

**Issue by drdaz** [parse-community/Parse-SDK-iOS-OSX#1074]
Having experienced a lot of trouble with LDS, I started looking for answers and discovered that it's deprecated: https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/237

@richardjrossiii I've been building on https://github.com/eladb/Parse-NSCoding to get NSCoding implementations for the Parse objects and have run into the issue that I can't seem to regenerate my objects from storage without using internal APIs, since some of the values I need to store are stored in private state objects.

For example, if I want to get an object out of storage, it's 'isDirty' flag is going to be set to YES, since the dirty property is calculated with private variables. Similarly, if I want to regenerate a saved PFFile, I need to access it's private state object to set the url field.

Is there any reliable way of regenerating your objects from local storage without diving into private APIs?

**Comment by acudworth** [comment]
I recently stumbled across this too. If it is deprecated why isn't this clearly marked in the docs? Can we get some clarification here please

**Comment by bryanbartow** [comment]
+1 Would like clarification

**Comment by pupoo** [comment]
+1 very hard to find anything about this

**Comment by pupoo** [comment]
Will it still work with swift 4?  What's the workaround for this? Completely migrate to realm or can you stop the data out of the pfobject and save it to a local SQLite instance?
