### ISSUE TITLE
Local data lost on Application id change

### ISSUE THREAD

**Issue by khetaram** [parse-community/Parse-SDK-iOS-OSX#1078]
Hi team,
My app is running and i had pinned data. Now i changed the application id of Parse server and trying to run app my local data is lost. Do you guys have idea about it. Why it is happening?

**Comment by MartinHerman** [comment]
I'm pretty sure, this is not an issue, but rather a feature.
I don't think it's too common for someone to change their App ID at any point - and you wouldn't want local data stores of 2 different apps to mix.

Anyway, I the local datastore should be used for caching. Why don't you just check for changes between the local data and the server on launch and update the data / create it if its a "clean" start?
