### ISSUE TITLE
Massive amount of memory leaks in Framework

### ISSUE THREAD

**Issue by prettyponygirl** [parse-community/Parse-SDK-iOS-OSX#1079]
I'm seeing anywhere from 30 to 200+ memory leaks from Parse IOS framework, there's too many to list so here's a screenshot. Let me know if you're seeing the same sort of thing. I just starting seeing this after IOS 10. Before IOS10, I never saw leaks like this, not sure if it's my doing something wrong or the framework itself. Let me know if you've seen the same thing. I can link more screenshots of the guts if need, but here' s a couple of shots. 
<img width="1014" alt="screen shot 2016-12-10 at 10 31 18 pm" src="https://cloud.githubusercontent.com/assets/10607508/21078327/6d42b016-bf28-11e6-8683-7285ed8a93c2.png">

<img width="463" alt="screen shot 2016-12-10 at 10 27 24 pm" src="https://cloud.githubusercontent.com/assets/10607508/21078316/dc9625fc-bf27-11e6-851a-a2816eff35d4.png">

**Comment by bryanbartow** [comment]
Seeing the same thing and noticing a lot more low memory situations in my apps' logs.
