### ISSUE TITLE
Local Data Store Deprecated?

### ISSUE THREAD

**Issue by pupoo** [parse-community/Parse-SDK-iOS-OSX#1081]
Has this been deprecated?

i can not get anything to pin to the LDS
//----------------------------------------------
//  Pin
//----------------------------------------------
let contact = PFObject(className: "temp")
contact["firstName"] = "steve"
contact["lastName"] = "smith"
contact["email"] = "steve.smith@example.com"
contact.pinInBackground()

//----------------------------------------------
//  Get
//----------------------------------------------
let query = PFQuery(className: "temp")
query.whereKey("firstName", equalTo: "steve")
query.fromLocalDatastore()
 
query.findObjectsInBackground { (object, error) in
 
     if error == nil {
          for object in object! {
               print(object["firstName"] as! String)
          }
     }
}

LDS is enabled right at top of app delegate

//----------------------------------------------
//  App Delegate
//----------------------------------------------
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

        Parse.enableLocalDatastore()

**Comment by nitrag** [comment]
No, I am using it. Your last step in App Delegate may not work, you should use:

```
let configuration = ParseClientConfiguration {
    $0.isLocalDatastoreEnabled = true
    ..
}
Parse.initialize(with: configuration)
```

**Comment by pupoo** [comment]
thank you for that you are correct.

there are still some threads saying this is being deprecated but i can't really get an answer about wether this is correct or not.

I'm hesitant to go too far with it if it isn't going to be available in future releases.

**Comment by nitrag** [comment]
There is a bounty open to overhaul caching, feel free to contribute.

https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/301

https://www.bountysource.com/issues/26840483-localdatastore-query-caching
