### ISSUE TITLE
ACL Public Permission Variables (Swift)

### ISSUE THREAD

**Issue by nitrag** [parse-community/Parse-SDK-iOS-OSX#1083]
The setter for public read/write access on an ACL isn't to Swift-spec.

The objective-C property is 
`@property (nonatomic, assign, getter=getPublicReadAccess) BOOL publicReadAccess;` 

docs/examples say you should be able to do:
`acl.publicReadAccess = true`

but Swift only sees `getPublicReadAccess` as a variable.
![image](https://cloud.githubusercontent.com/assets/197010/21596257/db5f1b30-d106-11e6-8afe-b0b014718db1.png)

**Comment by code-K** [comment]
when will this be solved?

**Comment by flovilmart** [comment]
I'll have a look soon, completely was out of my radar.
