### ISSUE TITLE
LocalDataStore race condition ?

### ISSUE THREAD

**Issue by thibauddavid** [parse-community/Parse-SDK-iOS-OSX#1086]
Hi,

I know LDS has been deprecated, but as I'm using it in an app, I'd like to understand an occuring error.
When starting my app offline, I get 7 times on 10 `Caught Exception: Key "UUID" has no data.  Call fetchIfNeeded before getting its value`. The 3 other time, everything load properly without network.
It just seems random.

"UUID" is a string, thus don't need to be specifically added with `includeKey` in query.

I've tried detecting when this case occurs (!error && !object in callback), but event if I retry n time, I get the same result. Could it be a race condition in LDS setup, as I can only bypass this error by relaunching a few time my app ?

The piece of code producting the error:

```
    PFQuery *query = [MyParseCustomObject query]; // Creating online query
    [query includeKey:@"anInnerObject"];
...
    PFQuery *fromCacheQuery = [query copy]; // Creating offline query
    [fromCacheQuery fromPinWithName:@"cache_pin_name"];
    [fromCacheQuery findObjectsInBackgroundWithBlock...  ] // This generate the exception

   // Then triggering online query
```

This is working in several app I use, but I guess some conditions are met here for the exception to be triggered.

If anyone has an idea, I'm in :)

**Comment by pupoo** [comment]
has the LDS been deprecated?  I am currently using but am not sure if it is a good idea if there will bo zero support for it or even if it will be included in future releases?

**Comment by thibauddavid** [comment]
According to several posts yes:

```
Local data store has been deprecated. There is no future planned support for it. The reasons are long and complex, but they come down to being essentially unmaintainable. If you want offline storage, I'd highly recommend a solution like realm.

If you'd like to read more on the subject, check out the many discussions that have been had here: ParsePlatform/Parse-SDK-iOS-OSX#32
```
