### ISSUE TITLE
NSInternalInconsistencyException - when pinning objects in background from array

### ISSUE THREAD

**Issue by pupoo** [parse-community/Parse-SDK-iOS-OSX#1089]
I get the above error when trying to pin object in background when the object is made from an array:

                let firstItem = reducedArray[0]
                
                if let fromPack = firstItem.object(forKey: "fromPack") as? PFObject {
                    
                    let historyClass = PFObject(className: packName)
                
                        historyClass.add(firstItem.objectId as Any, forKey: "partId")
                        historyClass.add(firstItem.object(forKey: "partName") as Any, forKey: "partName")
                        historyClass.add(fromPack.object(forKey: "packName")!, forKey: "packName")
                        historyClass.add(fromPack.objectId as Any, forKey: "packId")
                        historyClass.add(0 as Any, forKey: "partIndex")
                    
                    
                    print(historyClass)
                    
                            PFObject.pinAll(inBackground: [historyClass], block: { (success, error) in
                                if error != nil {
                                    print(error!)
                                } else if success {
                                    print(success)
                                }
                            })
                }

this is the result of printing the PFObject historyClass

<pk00: 0x6000000b9b60, objectId: new, localId: (null)> {
    ACL = "<PFACL: 0x60800022b740>";
    packId =     (
        rHITAAHJYk
    );
    packName =     (
        pk00
    );
    partId =     (
        3XWXN9Hbw4
    );
    partIndex =     (
        0
    );
    partName =     (
        "pk00_pt01"
    );
}

and this is the full error log:

2017-01-08 14:49:12.462 ParseStarterProject-Swift[53605:1520794] [Error]: Caught "NSInternalInconsistencyException" with reason "Attempted to find non-existent uuid C79B818E-6379-4E4A-A7CB-F0FDF347A4AB":
(
	0   CoreFoundation                      0x00000001105d3d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000011003521e objc_exception_throw + 48
	2   CoreFoundation                      0x000000011063d2b5 +[NSException raise:format:] + 197
	3   ParseStarterProject-Swift           0x000000010f12e8d8 __52-[PFOfflineStore _getPointerAsyncWithUUID:database:]_block_invoke + 98
	4   ParseStarterProject-Swift           0x000000010f131962 __65-[PFSQLiteDatabase executeQueryAsync:withArgumentsInArray:block:]_block_invoke_2 + 51
	5   ParseStarterProject-Swift           0x000000010f139bb1 __62-[BFTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke + 83
	6   ParseStarterProject-Swift           0x000000010f139491 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 82
	7   ParseStarterProject-Swift           0x000000010f13ad06 -[BFExecutor execute:] + 65
	8   ParseStarterProject-Swift           0x000000010f139415 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke + 138
	9   ParseStarterProject-Swift           0x000000010f13927b -[BFTask continueWithExecutor:block:cancellationToken:] + 319
	10  ParseStarterProject-Swift           0x000000010f139b1d -[BFTask continueWithExecutor:successBlock:cancellationToken:] + 201
	11  ParseStarterProject-Swift           0x000000010f139a2e -[BFTask continueWithExecutor:withSuccessBlock:] + 53
	12  ParseStarterProject-Swift           0x000000010f108c28 -[BFTask(Private) continueImmediatelyWithSuccessBlock:] + 87
	13  ParseStarterProject-Swift           0x000000010f13189e __65-[PFSQLiteDatabase executeQueryAsync:withArgumentsInArray:block:]_block_invoke + 144
	14  ParseStarterProject-Swift           0x000000010f139491 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 82
	15  libdispatch.dylib                   0x00000001137d70cd _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x00000001137b42b6 _dispatch_barrier_sync_f_invoke + 340
	17  libdispatch.dylib                   0x00000001137b921d _dispatch_barrier_sync_f_slow + 609
	18  ParseStarterProject-Swift           0x000000010f0feb75 PFThreadsafetySafeDispatchSync + 68
	19  libdispatch.dylib                   0x00000001137ad978 _dispatch_call_block_and_release + 12
	20  libdispatch.dylib                   0x00000001137d70cd _dispatch_client_callout + 8
	21  libdispatch.dylib                   0x00000001137b6312 _dispatch_queue_override_invoke + 1426
	22  libdispatch.dylib                   0x00000001137b8385 _dispatch_root_queue_drain + 720
	23  libdispatch.dylib                   0x00000001137b8059 _dispatch_worker_thread3 + 123
	24  libsystem_pthread.dylib             0x0000000113c69712 _pthread_wqthread + 1299
	25  libsystem_pthread.dylib             0x0000000113c691ed start_wqthread + 13
).

i have performed virtually the same function in another place but the data is not coming from array and works fine without this error.

**Comment by flovilmart** [comment]
I'll have a look on the latest verison and try to reproduce

**Comment by flovilmart** [comment]
@pupoo did you ever manage to fix the issue? I noticed in your code that you're adding keys to arrays, not setting them as properties. Is it on purpose?

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
