### ISSUE TITLE
How to convert PFFile to Uiimage in Swift 3

### ISSUE THREAD

**Issue by X901** [parse-community/Parse-SDK-iOS-OSX#1093]
Hi ,
I want to convert PFFile to Uiimage 
I'm trying to use 
```
if let userPicture = object.valueForKey("Image")! as! PFFile {
   userPicture.getDataInBackgroundWithBlock({
      (imageData: NSData!, error NSError!) -> Void in
         if (error == nil) {
            let image = UIImage(data:imageData)
            self.ImageArray.append(image)
         }
      })
}
```
but I got error in swift 3

**Comment by X901** [comment]
I solved my problem 

if let userPicture = object.valueForKey("Image")! as! PFFile {
userPicture.getDataInBackground({ (imageData: Data?, error: Error?) -> Void in
let image = UIImage(data: imageData!)
if image != nil {
self.imageArray.append(image!)
 }
 })
}

but I don't know how to access the Image outside the Block 
The imageArray empty outside Block , but have value inside Block =\

**Comment by cyring** [comment]
Set the image in the main thread

**Comment by ZacharyKhan** [comment]
Here is my solution within my own app, using **Swift 3.2** and **Xcode 8.3.1**:

```swift
DispatchQueue.global(qos: .userInteractive).async {
   // Async background process

   if let imageFile : PFFile = somePFFile {
            imageFile.getDataInBackground(block: { (data, error) in
            if error == nil {
                  DispatchQueue.main.async {
                      // Async main thread

                      let image = UIImage(data: data!)
                      self.imageViewToSet.image = image
                  }
            } else {
                 print(error!.localizedDescription)
            }
       })
    }
}
```

What @cyring mentioned above about threading is important. Make sure to handle your network calls on a background thread and always update the UI on the main thread.
