### ISSUE TITLE
Let's see some PR's!

### ISSUE THREAD

**Issue by nitrag** [parse-community/Parse-SDK-iOS-OSX#1096]
Glancing through the Forks, it seems many of you have made some great improvements to the Parse-iOS-OSX SDK. Can we all spend a few minutes reviewing and submitting PR's to share your work with the larger community? Thanks!

@devmynd
@notabasement
@AmpMe
@hulab
@spenceps
@loungebuddy
@crowdtunes

**Comment by ranhsd** [comment]
It looks like the guys from Parse are no longer support this SDK from couple of reasons: 

1. They are not solving issues 
2. The last commit was couple of months ago 
3. No new features are added

I really hope that it is not the case I know that a lot of developers are counting on the parse platform and the platforms SDK's
