### ISSUE TITLE
Batch operations are not working after migration

### ISSUE THREAD

**Issue by suvarnaratna** [parse-community/Parse-SDK-iOS-OSX#1097]
Migrated from parse to Azure.

I am using Parse Rest API from client side i.e iOS application.
Batch operations are not working after migration. I have changed path from 
 /1/classes/ClassName to /parse/classes/ClassName but no use.

 I am getting error as:

{ "code": 107, "error": "cannot route POST \classes\ClassName" }

Please help me to solve this issue.

Regards,
Suvarna Ratna.A

**Comment by SuvarnaRatna-DevRabbit** [comment]
Any help to solve this issue.

**Comment by ranhsd** [comment]
Did you try to test it from REST Client (e.g. postman)?

**Comment by SuvarnaRatna-DevRabbit** [comment]
Yes .tested in postman ..getting same error:
{ "code": 107, "error": "cannot route POST \classes\ClassName" }

Can you please help me?

**Comment by ranhsd** [comment]
for me this one is working http://localhost:1337/parse/classes/{YOUR_CLASS}

You can change localhost  to your server and 1337 to your port. Before you are trying to do that you must make sure that your server is up and running by testing the following URL:

http://localhost:1337/parse

now the /parse is the default mount path. In case you change your default mount path you must also change the URL to http://localhost:1337/{MOUNT_PATH}

**Comment by SuvarnaRatna-DevRabbit** [comment]
@ranhsd Only batch operations are not working remaining services are working fine.
