### ISSUE TITLE
Will the iPhone App Crash if still using Parse SDK after Parse retired?

### ISSUE THREAD

**Issue by 1SimonL** [parse-community/Parse-SDK-iOS-OSX#1098]
We have an iPhone app which using Parse SDK but soon Parse will retired. Will the app be crashed if we cannot remove the SDK in Xcode?

**Comment by StormFactory** [comment]
One way to test is to close your app, put your phone into airplane mode and then restart your app and see what happens.

**Comment by ZacharyKhan** [comment]
@1SimonL yes, **it will crash**. There will be no backend server to respond to your apps calls, but I'm sure you figured that out on **Jan 28, 2017** , when Parse retired its service. 

You can, however, keep the code on your client-side device and spin up your own instance of Parse Server using **AWS** or **Heroku** and point your client application to it.
