### ISSUE TITLE
Type 'Any' Has no Subscript Members, Swift 3

### ISSUE THREAD

**Issue by skynext** [parse-community/Parse-SDK-iOS-OSX#1099]
Hi,
I try to update my Parse's App to Swift 3 but I stuck on the following error:

`let likesNumber: AnyObject! = object.object(forKey: "Likes")![0]
`
> Type "Any" has no subscript members

Can you help me ? Thanks

**Comment by flovilmart** [comment]
You probably need to safely cast your object to an array

let likesNumber = (object.object(forKey: "Likes")? as? [AnyObject])?.first
