### ISSUE TITLE
geoPointForCurrentLocation to Swift 3.0

### ISSUE THREAD

**Issue by Vvaradinov** [parse-community/Parse-SDK-iOS-OSX#1104]
Hi,

I'm trying to migrate my my parse project to Swift 3.0

```
 PFGeoPoint.geoPointForCurrentLocationInBackground {
            
            (geoPoint: PFGeoPoint?, error: NSError?) -> Void in
            
            if let geoPoint = geoPoint {
                
                PFUser.currentUser()? ["location"] = geoPoint
                PFUser.currentUser()?.save()
             }
        }
```

but I get  **Cannot convert value of type (PFGeoPoint?,NSError?) -> Void  to expected argument type PFGeoPointResultBlock**

**Comment by edson-gaspar** [comment]
Hi, this function name has changed in swift 3.1 version:

 PFGeoPoint.geoPointForCurrentLocation { (geoPoint, error) in {
 ...
}
