### ISSUE TITLE
Can we able to migrate existing live project to other technology?

### ISSUE THREAD

**Issue by bfjfm2** [parse-community/Parse-SDK-iOS-OSX#1109]
We have completed a project in iOS/Android and planning to go live soon. We worried that iOS/Android SDKs won't be updated like facebook did. 

What is the best way of migrating Live ParsePlatform project iOS/Android ? Because of Client & Server SDK, everything interconnected.

Guide Us.

https://github.com/ParsePlatform/Parse-SDK-Android/issues/585

**Comment by ZacharyKhan** [comment]
I think it would depend on the technology you're planning on switching to. The data itself is stored via a NoSQL database in JSON format, so there probably wouldn't need to too many changes there as most solutions will use this same structure. 

If you are looking to go over to Firebase though, you will probably have to re-write a lot of your client-side networking code. 

What other services/technologies are you currently looking at switching to?
