### ISSUE TITLE
Doted Notation to increment key

### ISSUE THREAD

**Issue by madsodgaard** [parse-community/Parse-SDK-iOS-OSX#1115]
Hello

I am trying to increment key inside a Object field of a custom PFObject

Like so:
PictureTest
    - comments
            "testing2" : 1,
            "testing1" : 1

I have tried with a different class than PictureTest, and that works fine. The same exact code, just with a different class. It makes no sense...

` var pictureTest : PictureTest = self.rating.pictureTest

        
        rating.incrementKey("comments.testing2", byAmount: 100) // THIS WORKS
        pictureTest.incrementKey("comments.testing2", byAmount: 100) // THIS DOESN'T WORK

        
        pictureTest.saveInBackground()
        rating.saveInBackground()`

**Comment by flovilmart** [comment]
Can you provide the full Error, as well as server logs when running with VERBOSE=1

**Comment by madsodgaard** [comment]
There is no error displayed. It just doesn't update the field within the dictionary. But it does with the other class...

Here is the log:

verbose: REQUEST for [PUT] /parse/classes/PictureTest/ORxXIbfdKQ: {
  "testing.testing1": {
    "amount": 2,
    "__op": "Increment"
  }
} method=PUT, url=/parse/classes/PictureTest/ORxXIbfdKQ, host=192.168.1.163:1337, x-parse-client-version=i1.14.2, accept=*/*, x-parse-session-token=r:7e7d05125441e17fb3f07abaacf335d3, x-parse-application-id=admireapp, x-parse-installation-id=67e30a20-8d41-4bae-a474-129f14926c6e, x-parse-os-version=10.2.1 (14D27), accept-language=da-dk, accept-encoding=gzip, deflate, content-type=application/json; charset=utf-8, content-length=52, user-agent=Admire/70-develop CFNetwork/808.3 Darwin/16.3.0, connection=keep-alive, x-parse-app-build-version=70-develop, x-parse-app-display-version=1.0, amount=2, __op=Increment

Please note "testing.testing1" is just "comments.testing2" (renamed)

**Comment by flovilmart** [comment]
Can you provide the Schema for both classes?

**Comment by madsodgaard** [comment]
The one that doesn't work:

```
{
    "_id": "PictureTest",
    "objectId": "string",
    "updatedAt": "date",
    "createdAt": "date",
    "testing": "object"
}
```

The one that works
```
{
    "_id": "Judgement",
    "objectId": "string",
    "updatedAt": "date",
    "createdAt": "date",
    "testing": "object"
}
```

**Comment by flovilmart** [comment]
And both objects have the object set with the second key being a number? Or is one of the properties not set?

**Comment by madsodgaard** [comment]
Yes both are set to a value of 1 as a number
