### ISSUE TITLE
User cannot be saved unless they have been authenticated via logIn or signUp

### ISSUE THREAD

**Issue by lfarah** [parse-community/Parse-SDK-iOS-OSX#1120]
I have a social network app where you can comment on people's pictures. When I try to save the comment I get the following message:
```
Warning: `BFTask` caught an exception in the continuation block. This behavior is discouraged and will be removed in a future release. Caught Exception: User cannot be saved unless they have been authenticated via logIn or signUp
```

Method used:
``` swift
    class func sendNewComment(_ text: String, object: PFObject, completion: NetworkBoolCompletionClosure?) -> Comment {
        let newComment = Comment(className: "Comment")
        newComment.text = text
        newComment.user = User.current()
        newComment.date = Date()
        newComment.object = object
        newComment.objectType = object.parseClassName
        
        print(User.current() == nil)
        newComment.saveInBackground { (success, error) -> Void in
            
            if !success {
                newComment.saveEventually(nil)
            }
            
            if let c = completion {
                c(success, error as NSError?)
            }
        }
        
        return newComment
    }
```

* I'm using the latest version of Parse.
* `User.current()` returns a `PFUser.current`
* I already checked and User.current().isAuthenticated returns `true`
* User.current() == nil returns false
* `success` returns false, but error returns nil

**Comment by nickgeorge32** [comment]
My guess is it has to do with the publicWriteAccess of the user you are trying to add the comment to.

**Comment by DanGTZ** [comment]
@lfarah you have to enable automatic user in your AppDelegate after Parse initialization.

**Comment by baby03201** [comment]
I have similar issue until i start migrating cachePolicy to local datastore.
The problem is even I am using function such as objectWithoutData to avoid this situation, the library will still help me to find a full object from offline store and return to me.

Secondly, I've tried to revert the temporary changes on the user object but it doesn't work either.
The library will still list it in dirty children.

**Comment by akio46** [comment]
Anyone solved this issue?

**Comment by eeallen1** [comment]
> I have similar issue until i start migrating cachePolicy to local datastore.
> The problem is even I am using function such as objectWithoutData to avoid this situation, the library will still help me to find a full object from offline store and return to me.
> 
> Secondly, I've tried to revert the temporary changes on the user object but it doesn't work either.
> The library will still list it in dirty children.

@nghuiqin Did you ever come up with a workaround? I've also tried reverting the user object, but it doesn't seem to work. It's very frustrating because it seems that 1 failed save results in all subsequent save attempts failing as well, even if I revert the user object
