### ISSUE TITLE
Pinning new PFObjects to Local Datastore deletes existing Objects which are pointers

### ISSUE THREAD

**Issue by dwby** [parse-community/Parse-SDK-iOS-OSX#1124]
Hey,

For the life of me I can't figure out the issue here. I have a PFObject called Post which has two pointers to other PFObjects: Place and Image.

I've enabled the Local Datastore. Say we have 4 posts:
     
    PostA -> with PlaceA and ImageA
    PostB -> with PlaceB and ImageB
    PostC -> with PlaceC but no image
    PostD -> with PlaceD but no image

In my local datastore I have 10 PFObjects. So far so good.

However, when I pin a new PostE to the local datastore, PlaceC and PlaceD are deleted from the local datastore. 

Any ideas why?

**Comment by ranhsd** [comment]
Hi, i experience the same issue along with other issues like circular dependencies etc. After i worked with it i think that all the local data store feature should be deprecated and maybe we need to create a new one (maybe based on Realm). The reason is that i found myself implementing a lot of workarounds in order to make the local data source works and even after that i experience some other issues with it.

**Comment by dwby** [comment]
Hey @ranhsd - yeah I had to do a lot of workaround as well. For example, I saved the components of Post and Image into a single Place object in the Local Datastore only, but then seeing those additional fields appear on the server side for the Place object. Then I decided to create a brand new object for Local Datastore utilising the Post objectId. It's working but sometimes I experience an issue where an error is thrown because the "existing objectId cannot be changed". Strange

I guess there's no easy or obvious fix then?

**Comment by flovilmart** [comment]
If you can make a reproducible test case, we can start fixing from there. That would be the way to go from here.

**Comment by dwby** [comment]
Hey @flovilmart, i'm fairly new to coding, so how do I go about making a reproducible test case? I could create a version of my ios app with the specific issue and dummy data and post it on github. Would that work?

**Comment by flovilmart** [comment]
Yep that would be nice to have a demo project that doesn't work!

**Comment by ranhsd** [comment]
Now i have another issue with **PFRelation** when i am trying to pin the objects that was returned from a PFRelation query sometimes i get the data from the local data store and sometimes it's empty.

So another workaround that i did is to keep an array of ID's inside the object and then query the items from the local data store and use the **whereIn** option. I really think that we should think about refactoring this SDK. I tried to reverse engineer it and it looks like a big mass and also it is has a strong dependency to Bolts.  If we will decide to write a new SDK (sometime...) i think we must decouple the "offline store" from the rest client and also to adopt other popular open sources (e.g. Moya + Almofire, Realm for offline store, ObjectMapper etc.)

**Comment by flovilmart** [comment]
A new local data store can be developed independently of this SDK if there is such need to replace it. 
I'd prefer avoiding a full rewrite / major refactor at that time as with all refactor, major issues can arise.
