### ISSUE TITLE
[Bolts]  Invalid type in JSON write (_SwiftValue)

### ISSUE THREAD

**Issue by lavTeam** [parse-community/Parse-SDK-iOS-OSX#1128]
Error:
2017-04-03 11:37:28.989 fbLoginApp[1950:109853] [Bolts] Warning: `BFTask` caught an exception in the continuation block. This behavior is discouraged and will be removed in a future release. Caught Exception: Invalid type in JSON write (_SwiftValue)

`        fillServicesArray()
        
        print(servicesArray)
        newOrders["servicePrice"] = servicesArray //<----- Eroor
        // Город объявления
        newOrders["orderCity"] = city
        
        //  Дополнительная информация
        newOrders["orderDescription"] = descriptionsOrder.text
        
        newOrders.saveInBackground() //<----- Eroor`

Error appears on save Array: servicesArray.

servicesArray = [(key: "2323", value: "232"), (key: "232323", value: "23232"), (key: "444", value: "444")]

**Comment by flovilmart** [comment]
It seems that you're using tuples instead of proper dictionaries. We don't support swift value types in the SDK such as tuples, enums etc...
