### ISSUE TITLE
http://parseplatform.org/docs/ios/guide is down?

### ISSUE THREAD

**Issue by mmarshak** [parse-community/Parse-SDK-iOS-OSX#1129]
The website with the guides gives a 404 error.

Who is responsible for this website?

**Comment by montymxb** [comment]
Check out #1123. I'm not personally involved but I have been told it's being worked on at the moment. In the meantime you can checkout the docs from github or view them on [docs.parseplatform.org](http://docs.parseplatform.org/), although the asset links are mostly broken at the moment :/

**Comment by flovilmart** [comment]
The docs are back up on `docs.parseplatform.org`.
