### ISSUE TITLE
rake package:frameworks fails if the repos path has spaces.

### ISSUE THREAD

**Issue by Baza207** [parse-community/Parse-SDK-iOS-OSX#113]
When I try and build the project using method "2. Compiling for yourself" I get the following error:

```
$ rake package:frameworks
xcodebuild: error: Unknown build action 'on'.
Failed to build framework for iphoneos.
```

The first 2 steps work fine, however having the repo in a location that means the paths contains spaces seems to cause this error, and means that a file for each work in the path is made (assume that every `<space>` is a `/` instead of `\<space>`).

**Note:** `'on'` is part of my path name where the repo is located.
`/Users/<username>/Documents/Pig on a Hill/Parse-SDK-iOS-OSX`

This is running on OS X 10.10.5, on the master branch at tag 1.8.1 or the current latest commit (670d7ec55e5515a674294f1666f755fd710014b1).

**Comment by nlutsenko** [comment]
Valid bug, indeed.
Fixing now. Thanks for reporting!

**Comment by nlutsenko** [comment]
Will be fixed when #115 is merged.

**Comment by Baza207** [comment]
Hey, just tested it and it started working, got all the way to `▸ Touching Parse.framework` for the second time and then I got the following error.

```
▸ Touching Parse.framework
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/<username>/Documents/Pig (No such file or directory)
Failed to lipo iOS framework.
```

Possibly another place that it's using the path?

**Comment by nlutsenko** [comment]
Quite possibly. Let me reopen this issue, since it doesn't seem to be fixed. It builds no problem via Xcode now, which is good.

**Comment by DazChong** [comment]
I experiencing this issue as well as of today. Build success after changed package path.

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
