### ISSUE TITLE
Can't connect to LiveQuery server

### ISSUE THREAD

**Issue by ruiluo-mobile** [parse-community/Parse-SDK-iOS-OSX#1133]
On the server side I did the configuration step by step. And it worked for clients using Javascripts. Which means the server is working fine.

Here's what I got on server sider when clients sending subscription using javascript:

verbose: Request: {"op":"connect","applicationId":"id","javascriptKey":"unused","masterKey":"maskerKey"}
info: Create new client: 0
verbose: Push Response : "{\"op\":\"connected\",\"clientId\":0}"
verbose: Request: {"op":"subscribe","requestId":1,"query":{"className":"LiveQueryTestObject","where":{"status":5}}}
verbose: Push Response : "{\"op\":\"subscribed\",\"clientId\":0,\"requestId\":1}"
verbose: Create client 0 new subscription: 1
verbose: Current client number: 1

However, the iOS sdk seems can not even connect to the server.
I am using the following code:

let liveQueryClient: Client = ParseLiveQuery.Client(server: "ws://localhost:8000/parse", applicationId: "appId", clientKey: "clientKey")
        
let myQuery = PFQuery(className: "LiveQueryTestObject").whereKey("status", equalTo: 5)
let subscription = liveQueryClient.subscribe(myQuery).handle(Event.updated) { (query, obj) in
    print ("entered the subscription!!")
}

**Comment by flovilmart** [comment]
You're probably not retaining the subscription.

**Comment by ruiluo-mobile** [comment]
@flovilmart Yes I think so. But I double checked the port number and applicationId. Everything matched with the server config. Do I need to do extra configuration on the server side for the websocket? Because the javascript case was within the server like this, which happen internally in the server:
ParseServer.createLiveQueryServer(httpServer, {logLevel: 'VERBOSE'});
var query = new Parse.Query("LiveQueryTestObject");
query.equalTo("status", 5);
var subscription = query.subscribe();

**Comment by flovilmart** [comment]
no, you just need to retain the subscription on a parent object. AFAICS, the subscription is a local variable to a function, an it will be released when the function ends

**Comment by ruiluo-mobile** [comment]
@flovilmart Thanks for your help. Well, I'll keep looking for solution. And could you please update the short snippet of the sample code in README? We should use the new version of this. Just want more new guys to see this:
http://stackoverflow.com/questions/39360601/parse-livequery-not-working

**Comment by flovilmart** [comment]
I'm not sure why you're closing the issue nor if your subscription is properly retained. But given your snippet, I can guarantee that the liveQuerySDK don't retain the subscriptions for you

**Comment by ruiluo-mobile** [comment]
@flovilmart Sorry this is the first time I use this, I didn't know close would be like this. I intended to show people the link, sorry about that. What do you mean by that guarantee?

**Comment by flovilmart** [comment]
I mean that if your nothing retains the subscription returned by th subscribe call, outside your function, the subscription will be deallocated when the function returns

**Comment by ruiluo-mobile** [comment]
@flovilmart I deployed the parse server on heroku and the subscription works from iOS client, but the local server still can not establish the ws connection from the iOS client. As you said, I need to retain the subscription, but I am really new to this, and I didn't find solution anywhere else. Could you please tell me how to retain the subscription?
