### ISSUE TITLE
Best pratice for upload files through the PFFile

### ISSUE THREAD

**Issue by rgipd** [parse-community/Parse-SDK-iOS-OSX#1137]
Hello.

  I have multiples images to upload to a parse-server at a time.
  I know that I can have an dispatch queue serial and I could use it with a for loop (or maybe the dispatch_apply function to replace this loop), but, the PFFileController already (with Bolts) opens a new upload queue and then my queue is "useless". Putting some NSLock, I got a deadlock, it works with deadlock, but it's not a good way to solve the problem.

  So...
  What is the best practice to upload a queue of 2 or more images in iOS in batch?

  PS: I don't want concurrent uploads from PFFile, I want to sent one file at time.

Regards!

**Comment by hermanliang** [comment]
you may use
```objc
[PFObject saveAllInBackground:pfFiles];
```
http://parseplatform.org/Parse-SDK-iOS-OSX/api/Classes/PFObject.html#/Saving%20Many%20Objects

**Comment by rgipd** [comment]
Ok, that's a way, but I need to call a Parse Cloud Code function after each file be uploaded, so I was searching for an upload queue. This is possible?

**Comment by hermanliang** [comment]
1. You can handle it using a `afterSave Trigger`.
http://docs.parseplatform.org/cloudcode/guide/#aftersave-triggers

2. If you want to handle upload queue in your app, you can refer to the following syntax.
https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/13fbd09474f81a8c5d0cb77150e08122b4253ec6/Parse/PFObject.m#L390-L404
