### ISSUE TITLE
Can't install 1.14.4 using Cocoapods

### ISSUE THREAD

**Issue by agordeev** [parse-community/Parse-SDK-iOS-OSX#1140]
pod 'Parse', '~> 1.14.4'
 
 `pod install` returns:
 
> [!] Unable to satisfy the following requirements:
> 
> - `Parse (~> 1.14.4)` required by `Podfile`
> - `Parse (~> 1.14.4)` required by `Podfile`
> 
> None of your spec sources contain a spec satisfying the dependency: `Parse (~> 1.14.4)`.
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> 
> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

The only workaround is `pod 'Parse', :git => 'https://github.com/parse-community/Parse-SDK-iOS-OSX.git', :tag => '1.14.4'`

**Comment by flovilmart** [comment]
Did you try `pod repo update && pod install`

**Comment by agordeev** [comment]
That worked, thanks!
