### ISSUE TITLE
Can I use Spotify as third party login for PFUser?

### ISSUE THREAD

**Issue by kesongxie** [parse-community/Parse-SDK-iOS-OSX#1142]
I need to integrate a Spotify login with parse. I browse the web and found a useful example from @flovilmart for Twitter here  [example](https://gist.github.com/flovilmart/68a6c538496953408bb1).  I spent hours and couldn't locate any information about using Spotify as the third party login. I had no idea how to specify the correct keys for let `authData` as the parameter for the `User.logInWithAuthType(inBackground:)` I tried the following, and apparently it does not work

```
 User.register(AuthDelegate(), forAuthType: "spotify")
    if let token = session.accessToken{
        let authData = ["access_token": token]
        User.logInWithAuthType(inBackground: "spotify", authData: authData).continue({ (task) -> AnyObject? in
       // the PFUser currentUser should not be nil at this point
         return nil
       })
   }

```
It yields 
```
MyApp[1052:326048] [Error]: This authentication method is unsupported. (Code: 252, Version: 1.14.2)
```

Does anyone know where can I find out the required key and value I need for authData, or does Spotify login even supported? From here, I noticed Spotify was one of the provider [links](https://github.com/parse-community/parse-server/blob/master/src/Adapters/Auth/index.js)

Thanks.

**Comment by flovilmart** [comment]
We just implemented it recently, I'll provide you with a code example shortly. 

I believe you have to pass the id of the user alongside the access_token

**Comment by kesongxie** [comment]
Thank you very much for the quick reply. I successfully used `logInWithAuthType` to create a document in the `_User` collection with only a randomly generated string as the `username`, and `_auth_data_spotify` with some `id` and `access token`. Is there any way I can add my own column to this type of `_User`(with third party login). For example, I would like to add a `_Installation` column so that I can use Parse.push to send out remote notification?  Or do I even need to store a installation column for each user in order to send out remote notification from client?

**Comment by flovilmart** [comment]
You can set what you want on the user object, please refer to the documentation or stackoverflow for implementation related questions.

Http://docs.parseplatform.org

**Comment by kesongxie** [comment]
Thank you.
