### ISSUE TITLE
Behavior of PFUser when expired token and relogin from FB

### ISSUE THREAD

**Issue by hopye** [parse-community/Parse-SDK-iOS-OSX#1143]
Hi guys, i need to know about this behavior, im using login thru parse but also have a mysql db and im matching my users details and configurations using the objectId from Users in Parse. im also using Facebook Login, as im matching everything with the User objectid. when login in thru facebook, and then the token expires. this surely Wont create another objectId.. a new "user" right ? . im my matching everything in my other db with the Users objectId from parse. will this work ? is this a best practice ?

**Comment by flovilmart** [comment]
This should be properly covered, if you wanna test for yourself, use a Facebook test account and change the password, this will invalidate access tokens.
