### ISSUE TITLE
Samples for XCode 8.2.1 and Swift 3 needed please.

### ISSUE THREAD

**Issue by nyxee** [parse-community/Parse-SDK-iOS-OSX#1147]
Hello.

I have failed to go past the initial example of your platform (testing objects getting written to the database). I have tried the OSX and iOS SDKs in vain. Please help with a working Parse Starter project for XCode 8.2.1 and Swift 3. I wish its possible to get some information on whether this will not be possible.

**Comment by flovilmart** [comment]
All sample projects have been updated on the master branch for Xcode 8.3 and Swift 3. Let me know if you need anything else.
