### ISSUE TITLE
Pod install target has frameworks with conflicting names: bolts.

### ISSUE THREAD

**Issue by larceneaux** [parse-community/Parse-SDK-iOS-OSX#1148]
I'm trying to install Parse iOS library for my project that includes a Share Extension. I'm using the latest release version of Cocoapods. I'm unable to link my Share Extension to the Parse framework no matter what I try. 

this doesn't work

```
platform :ios, '8.1'
target 'myProject' do
	use_frameworks!
	pod 'ParseFacebookUtilsV4'
	pod 'Parse'
	pod 'ParseUI'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'TwitterKit'
	pod 'TwitterCore'
	pod 'TTTAttributedLabel'
	pod 'pop', '~> 1.0'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'ParseLiveQuery'
	pod 'JSQMessagesViewController'
end
target 'shareExtension' do
	pod 'Parse'
end
```
this gives the error: 

> target has frameworks with conflicting names: bolts.

this doesn't work

```
def shared_pods
	pod 'Parse'
end
target 'myProject' do
	use_frameworks!
	shared_pods
	pod 'ParseFacebookUtilsV4'
	pod 'ParseUI'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'TwitterKit'
	pod 'TwitterCore'
	pod 'TTTAttributedLabel'
	pod 'pop', '~> 1.0'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'ParseLiveQuery'
	pod 'JSQMessagesViewController'
end

target 'shareExtension' do
	use_frameworks!
	shared_pods
end
```

this gives the error: 

> target has frameworks with conflicting names: bolts.

this works for on device and simulator but I can't archive the app for upload, it breaks when trying to link libraries

```
target 'myProject' do
	use_frameworks!
	pod 'Parse'
	pod 'ParseFacebookUtilsV4'
	pod 'ParseUI'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'TwitterKit'
	pod 'TwitterCore'
	pod 'TTTAttributedLabel'
	pod 'pop', '~> 1.0'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'ParseLiveQuery'
	pod 'JSQMessagesViewController'
	target 'shareExtension' do
		inherit! :search_paths
	end
end

```

I can roll back Pods to 1.0.1 and I can get it work, however, then other portions of the Parse framework break, specifically Bolts-umbrella.h not linking correctly. I can make the archive using the Pods version 1.0.1, but it leaves a bunch of warnings. 

Mixpanel had this same problem with extensions and pods, they fixed it about 2-5 days ago, so I'm sure there's a fix for it, I just can't find the fix yet. 

I got everything working with 1.0.1, however, now when linking the extension to Parse the app won't validate with apple due to the Bolts framework linking to Parse linking to disallowed methods in share extensions that reference UIApplication. 

So share extensions are not usable w/ Parse iOS in it's current form. 

One thing that may fix this is creating a new Parse release using this:

> pod 'Bolts/Tasks'

I'm pretty sure this was how Parse was packaged back in 2015 but it seems it's been changed now since it's throwing the warning on archive:

> linking against a dylib which is not safe for use in application extensions

I see from past Parse discussions back in 2015, Parse was hooked only to Bolts/Tasks to avoid the Bolts/Applinks UIApplication references that cause  the warning above. This warning above breaks the payload and prevents it from being validated with ITunes connect in the organizer window. Perhaps there's an easier fix to this, but so far, it seems to be something deeper with the linking of Parse iOS SDK to bolts in full instead of just Bolts/Tasks. However, this is just one problem here, the problem with Pods not working with targeting the share extension itself is also something that needs to be addressed.

Let me know if you've found a solution to this problem.

**Comment by larceneaux** [comment]
I'm still looking for an answer, but for now, I just went with user Parse REST API with session token passing through shared keychain store between app and share extension while using ...

> [NSURLSession sharedSession] dataTaskWithRequest ... 

If anyone else has this problem, the Parse REST API using standard iOS methods and libraries seems to do the trick until this is fixed in Parse iOS SDK.

**Comment by flovilmart** [comment]
can you share a demo project on github that reproduces the issue? That would be the best so I can have a look!

**Comment by larceneaux** [comment]
Yeah, I'll drop you one later today, thank you sir.

**Comment by flovilmart** [comment]
Thanks!

**Comment by larceneaux** [comment]
I'm knee deep in two apps right now, I thought I'd get to this yesterday, it'll be sometime tomorrow, however. This bug is such a problem, I'll be loading 3-4 different projects showing what's wrong, so hold tight, it's coming.

**Comment by flovilmart** [comment]
Awesome! Thanks! I’ll try to get a fix ASAP!

**Comment by flovilmart** [comment]
@larceneaux  any news on that?

**Comment by larceneaux** [comment]
yeah, i'm so slammed with work right now, it's still coming, let me crush
this out in a simple project today, hold up.

**Comment by flovilmart** [comment]
no rush!

**Comment by larceneaux** [comment]
@flovilmart 

here we go

double pod target
[TestingShareExtension with double pod target.zip](https://github.com/parse-community/Parse-SDK-iOS-OSX/files/1104139/TestingShareExtension.with.double.pod.target.zip)

single pod target
[TestingShareExtension with single pod target.zip](https://github.com/parse-community/Parse-SDK-iOS-OSX/files/1104140/TestingShareExtension.with.single.pod.target.zip)

double pod results when trying to install Parse on share extension
<img width="634" alt="screen shot 2017-06-26 at 10 12 07 pm" src="https://user-images.githubusercontent.com/16133244/27570624-d0706dd8-5abc-11e7-8e8c-5811c06b32d6.png">

single pod result for base case

<img width="687" alt="screen shot 2017-06-26 at 10 14 56 pm" src="https://user-images.githubusercontent.com/16133244/27570631-eaf89248-5abc-11e7-9811-fa578b01aadb.png">

Pod file for double pod target

<img width="281" alt="screen shot 2017-06-26 at 10 12 38 pm" src="https://user-images.githubusercontent.com/16133244/27570639-f7cfda8a-5abc-11e7-8a99-ed6aba8fa045.png">

Pod file for single pod target 

<img width="251" alt="screen shot 2017-06-26 at 10 15 52 pm" src="https://user-images.githubusercontent.com/16133244/27570653-09a07ad0-5abd-11e7-9c20-d2053c7cba49.png">

I would show you more, but the same result occurs, no matter how you swing this one, it's showing we have the following error:

> [!] The 'Pods-TestingShareExtension' target has frameworks with conflicting names: bolts

And even if you pull the bolts and hack around this with earlier version of Pods, the archive is immediately rejected by Apple iTunes connect due to the Parse framework accessing Bolts which is then accessing calls to UIApplication. I think the ideal fix would be, if we still have access to this, is to set up a release of Parse IOS SDK that is attached to Bolts/Tasks. Back a year ago, @nlutsenko had written about this problem on Google groups and here and had a fix of sorts where the Parse iOS SDK was only accessing the safe Bolts/Tasks that didn't access UIApplication. It turns out that accessing UIApplication in an extension is a big no no, so even if we do resolve this, it may not be resolved until we separate the Parse SDK from anything that accesses UIApplicaton. This is just me guessing, but again, @nlutsenko had touched upon this briefly. Now, it used to be the case that Pods would build just fine for multi target sharing of libraries, this all changed with the new Pod update, last two updates, I think. Mixpanel had the same sort of targeting issue, supposedly they fixed it. The Pods people are saying that this is a "radr" issue that Apple needs to fix, but I doubt Apple is going to fix this, there's a very good reason, I'm sure, why they won't allow access to library sharing here or whatever is going on, and I'm 100% sure they're not going to allow us to access UIApplication calls in extensions.

**Comment by larceneaux** [comment]
@flovilmart 

now, if I don't use the directive "use_frameworks!", then can build the project with the current stable release version of Pods. So it looks like this has something to do with building for Swift. I would normally keep this all in Objective-C, but I need to use Parse Live Query for this app and haven't had a change to look at Jet to write my own Parse Live Query lib using Objective-C alone. Here's the project with the "use_frameworks!" directive

<img width="248" alt="screen shot 2017-06-26 at 10 36 08 pm" src="https://user-images.githubusercontent.com/16133244/27571030-e3ba2cc8-5abf-11e7-9efe-320b54d5be20.png">

and project:

[TestingShareExtension without use_frameworks directive.zip](https://github.com/parse-community/Parse-SDK-iOS-OSX/files/1104180/TestingShareExtension.without.use_frameworks.directive.zip)

I hope this helps.

**Comment by flovilmart** [comment]
So, the issue is with cocoa pods as it seems (https://github.com/CocoaPods/CocoaPods/issues/6446). I can manage to make it work with cocoapods 1.0.0.

**Comment by larceneaux** [comment]
Nice, I'll try that out,  I wonder if this the achieve can be verified by ITunes connect, I'll check it out later

**Comment by larceneaux** [comment]
@flovilmart 

I rebuilt the app using Pods 1.0.0, everything installed just fine with cocaopods 1.0.0, however, when i tried to validate the archive, the following errors popped up

> iTunes Store operation failed.
> Invalid Bundle. The bundle at 'TestingShareExtension.app/PlugIns/shareExtension.appex' contains disallowed nested bundles.

And while archiving was taking place, these errors popped up
<img width="548" alt="screen shot 2017-06-27 at 10 21 35 am" src="https://user-images.githubusercontent.com/16133244/27598616-4c73450c-5b23-11e7-8ee3-e3dd0c9657a2.png">

So it's a no go even though cocoapods 1.0.0 allows the pods to be installed.

**Comment by larceneaux** [comment]
@flovilmart one more quick thing, I tried the same thing but without use_frameworks! and it worked just fine, I can upload and verify with iTunes connect, so this seems to be another Swift building issue only with the embedded frameworks. I should probably work on building out my own Parse Live Query library in objective-C so I don't have to rely on Swift. Swift is still too broken it seems in too many critical places like this for it to be useful for now. thanks for your help

**Comment by flovilmart** [comment]
Not sure why you mention swift there, but go ahead, ParseLiveQuery is not supported on the WatchKit.
Also you may wanna have a look  at this cocoa pods plugin that allows mixing frameworks and static libraries (through a bridge framework)

https://github.com/flovilmart/cocoapods-mix-frameworks

**Comment by larceneaux** [comment]
Awesome, I'll take a look at it.

**Comment by flovilmart** [comment]
@larceneaux this implies using an additional framework target but it's all well demonstrated in the demo project.

**Comment by larceneaux** [comment]
Yep, that works, I'm going to test it out later today, thanks for everything.
