### ISSUE TITLE
Parse iOS project built with carthage crashes with exception

### ISSUE THREAD

**Issue by aliasad106** [parse-community/Parse-SDK-iOS-OSX#1151]
```
dyld: Library not loaded: @rpath/Parse.framework/Parse
  Referenced from: /Users/aliasadullah/Library/Developer/CoreSimulator/Devices/1768CAB6-2E06-4DFD-9F08-3088BE2C45C4/data/Containers/Bundle/Application/D35ED41F-966B-4A4B-9089-05B893FE792B/CartestProject.app/CartestProject
  Reason: image not found
```

I have imported the frameworks of Parse and Bolts into the project and then when I run I get the above exception.

**Comment by flovilmart** [comment]
I believe you used the static libs and not the dynamic ones. How did you get the frameworks? Did you add them to the copy frameworks phase?

**Comment by aliasad106** [comment]
@flovilmart I just built using these instruction 


_Add the following line to your Cartfile:_
```
github "parse-community/Parse-SDK-iOS-OSX"
```
_Run `carthage update`, and you should now have the latest version of Parse SDK in your Carthage folder._

**Comment by flovilmart** [comment]
Did you add the `carthage copy-frameworks` to your build steps as described here? https://github.com/Carthage/Carthage

**Comment by aliasad106** [comment]
@flovilmart Am I missing something ?

**Comment by flovilmart** [comment]
@aliasad106 any news?

**Comment by aliasad106** [comment]
@fl
