### ISSUE TITLE
iMessage extension crashes because Parse is initialised twice

### ISSUE THREAD

**Issue by AlbinGrans** [parse-community/Parse-SDK-iOS-OSX#1156]
### Issue Description

We are developing an iMessage extension with Swift. And to be able to initialize Parse, we have the put the Parse initialize code inside any of the iMessage controllers. Whenever a controller reopens, the app crashes. We have tried to put both in the override init and viewDidLoad.

### Steps to reproduce

Code in viewDidLoad or override init:

```
Parse.initialize(with: ParseClientConfiguration(block: { (configuration: ParseMutableClientConfiguration) -> Void in
            
            configuration.server = "https://xxxxx.io/parse/"
            configuration.applicationId = "xxxxxxx"
            
        }))
```
Then I run the app, and if I present a new controller it crashes with the error message in xcode:
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Parse is already initialized.'

#### Expected Results

Parse connecting to the server with no errors.

#### Actual Outcome

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Parse is already initialized.'

#### Server

parse-server version 1.15.0
Operating System: macOS Sierra
Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

MongoDB version: v3.4.5
Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Localhost

**Comment by flovilmart** [comment]
You could put something like:

```
let initParse:() = { in
  Parse.initialize....
}()
```

At the top of one of your controllers, this will effectively call the function lazily only once.

And when you need to make sure the SDK is Initialized:

`let _ = initParse`

This should do the trick simliarly to a dispatch_once
