### ISSUE TITLE
XCode 9: PFSubclassing.object() breaks builds on XCode 9 beta 4

### ISSUE THREAD

**Issue by mman** [parse-community/Parse-SDK-iOS-OSX#1162]
Not sure what exactly is happening, but XCode 9 beta 3 started emitting this as a warning message:

```Unavailable class method 'object()' was used to satisfy a requirement of protocol 'PFSubclassing'```

and XCode 9 beta 4 marked this as an error making it impossible to even build the project.

Since ``PFSublcassing.object()`` is an optional requirement, commenting out the method in the ``PFSubclassing.h`` header files makes the project build again - assuming you do not rely on this functionality.

Could be a bug in the XCode 9 beta 4, could be an abuse of ``object()`` method in Parse iOS SDK.

Any thoughts how to fix this?

**Comment by flovilmart** [comment]
Uhm... Can you provide a PR, i’ll Setup a branch for Xcode-9 that we’ll be able to use as a dependency for pods/Carthage and a small notice in the README?

**Comment by mman** [comment]
I have prepared a PR against master, tested locally built framework against on one of my apps and the app builds again using XCode 9 beta 4.

**Comment by CiraciNicolo** [comment]
If you also include the LiveQuery-iOS library on your cartfile the issue appears, because LiveQuery is stuck with ParseSDK 1.15.0. Furthermore, it also refers to the dead ParseCommunity repo.
