### ISSUE TITLE
Subclass of a Subclass Example?

### ISSUE THREAD

**Issue by davewhipps** [parse-community/Parse-SDK-iOS-OSX#1166]
Is there an example of a "Subclass of a Subclass of PFObject" anywhere?

For the life of me I can't get this to work, at all, ever.

**Comment by ogezue** [comment]
Before XCode 9 beta 2 this was possible:

```
import Foundation
import Parse

class Location: PFObject {
    static public let entityName = "Location"
    
    @NSManaged var name: String
    @NSManaged var country: String
   
    
    func update(source: PFObject, successHandler: @escaping () -> Void, errorHandler: @escaping () -> Void) {
        objectId = source.objectId
        name = source["name"] as! String
        country = source["country"] as! String
       
        
        successHandler()
    }
}

extension Location: PFSubclassing {
    
    static func parseClassName() -> String {
        return entityName
    }
}
```

Perhaps this helps you. But now with beta 5 I'm fighting with this error:

> Type 'Location' does not conform to protocol 'PFSubclassing'

**Comment by flovilmart** [comment]
@davewhipps this is not supported by the SDK, and actually discouraged. All data should be stored into a single collection row so you don't have joins to resolve at runtime.
