### ISSUE TITLE
I seem to still get PFCommandCache memory errors

### ISSUE THREAD

**Issue by tealshift** [parse-community/Parse-SDK-iOS-OSX#1168]
I've made a stackoverflow post here: https://stackoverflow.com/q/45683981/1921002

Let me know if there is any more information you need to help resolve.

**Comment by flovilmart** [comment]
We see this as well, we're working on a fix at the comment and expect to release soon.

**Comment by flovilmart** [comment]
@tealshift any STR that would help me reproduce and make sure the fix is 👍

**Comment by flovilmart** [comment]
@tealshift can you try with the branch: `fix/1168-heapcorruption` 

example with Podfile:

```
pod 'Parse', :git => 'https://github.com/parse-community/Parse-SDK-iOS-OSX.git', :branch => 'fix/1168-heapcorruption'
```

**Comment by tealshift** [comment]
@flovilmart Alright, I'll give it a shot. I'm not the best memory debugger but I'll try my best. Can you tell me what an STR is?

**Comment by flovilmart** [comment]
STR: Step To Reproduce, that would be helpful to ensure that this is gone for good, we have the issue as well in production, but never noticed it in our dev or QA builds.

**Comment by tealshift** [comment]
I'm still setting up my project with the new SDK, but did you try profiling Zombies using Release configuration in the scheme? That's what I've done to reproduce and sounds like the ticket.

**Comment by flovilmart** [comment]
yep, seems fixed, can you try again with the same steps with the branch and let me know if that's fixed?

**Comment by tealshift** [comment]
Hmmm I just ran into this with the new SDK. 
![screen shot 2017-08-16 at 9 39 47 am](https://user-images.githubusercontent.com/7879237/29374629-f444d3ee-8266-11e7-93f8-f57cbd640930.png)

**Comment by tealshift** [comment]
Sorry but I'm having trouble converting my framework import from manual to CocoaPods. I'm not 100% certain I had the new framework from pods linked.

**Comment by flovilmart** [comment]
You were importing it manually? That’s trickier. Would you be able to make a sample app that has the issue?

**Comment by flovilmart** [comment]
Also, can you share the bottom of the retain/release list, and that may help identify your issue

**Comment by tealshift** [comment]
![screen shot 2017-08-16 at 10 23 01 am](https://user-images.githubusercontent.com/7879237/29376316-021cc660-826d-11e7-888a-4515762b9175.png)

To clarify, by "manual" I mean I simply dragged the framework file into my project. I'm not terribly familiar with the terminology. 
My issue is with my iMessage target trying to import an objc header that imports <Parse/Parse.h> resulting in "File not found" build error. I don't know why this wasn't an issue without pods.

**Comment by tealshift** [comment]
Ok, I just fixed my pod issues and I've definitely removed the old framework file. The Zombie Messaged event still occurs as I screenshotted so I must have had the new stuff linked. Anything else you'd like to see?

**Comment by flovilmart** [comment]
Do you have a code example that triggers this behavior / sample project?

**Comment by tealshift** [comment]
I made a new project but didn't get the zombie message. It could take me a long time to find the actual cause in my project, sadly. :(

**Comment by tealshift** [comment]
I can't share my project, but I'd gladly take some pointers on finding the cause.

**Comment by flovilmart** [comment]
Yeah, I understand that, i’ll Investigate further.

**Comment by flovilmart** [comment]
I'm seeing something as well, with the zombie tools on that branch, investigating now.

**Comment by flovilmart** [comment]
@tealshift just updated the branch, can you tell me if that's better for you now? I don't see it anymore, an no leaks either are popping.

**Comment by tealshift** [comment]
Looks good! My profiler found a zombie before the **pod update** and didn't right after. Thank you!

**Comment by flovilmart** [comment]
YES! Very nice! And AFAICT, it seems that the deallocation is happening correctly as well :)

**Comment by flovilmart** [comment]
@tealshift do you confirm you don't have any zombie messaging nor leaks around the command cache anymore? Do you mind having a look at the PR and let me know what you think?

**Comment by tealshift** [comment]
Yeah, no issues from Parse so far! I read your recent commits and though I haven't played much with block execution myself, they look correct.

**Comment by flovilmart** [comment]
Good to hear!
