### ISSUE TITLE
PFInstallation on tvOS?

### ISSUE THREAD

**Issue by claesjacobsson** [parse-community/Parse-SDK-iOS-OSX#1169]
Will PFInstallation be included on tvOS? Among other things, my app is using channels to send push notifications so I really need it.

**Comment by matuella** [comment]
Reaaaaaaallly need an update on this one, any plausible solution?

**Comment by flovilmart** [comment]
You can probably get started on that and open a PR ;)

**Comment by matuella** [comment]
I tried to fork and started to do what a branch called "" did, but I faile because of my shallow knowledge :( I'm actually working on a project that I've to deliver it ASAP

**Comment by flovilmart** [comment]
And you should not depend on someone else to implement it, I’m sorry, but that’s not how open source work...

**Comment by matuella** [comment]
I absolutely agree! Just wondering if someone got a solution, not blaming anything here :)

**Comment by flovilmart** [comment]
There's an open PR for the Parse Push on TvOS, we should merge it soon enough

**Comment by flovilmart** [comment]
duplicate of #1198 , keeping the latest one open.
