### ISSUE TITLE
Type 'MyClass' does not conform to protocol 'PFSubclassing'

### ISSUE THREAD

**Issue by ogezue** [parse-community/Parse-SDK-iOS-OSX#1171]
With the latest Version of XCode 9b5 and the Parse SDK 1.15.1 I can not subclass anymore. Any idea what might be wrong?

The error is: 
**Type 'Location' does not conform to protocol 'PFSubclassing'**

```
import Foundation
import Parse

class Location: PFObject {
    static public let entityName = "Location"
    
    @NSManaged var name: String
    @NSManaged var country: String
    @NSManaged var timezone: String
    @NSManaged var latitude: Double
    @NSManaged var longitude: Double
    
    func update(source: PFObject, successHandler: @escaping () -> Void, errorHandler: @escaping () -> Void) {
        objectId = source.objectId
        name = source["name"] as! String
        country = source["country"] as! String
        latitude = source["latitude"] as! Double
        longitude = source["longitude"] as! Double
        timezone = source["timezone"] as! String
        
        successHandler()
    }
}

extension Location: PFSubclassing {
    
    static func parseClassName() -> String {
        return entityName
    }
}
```

**Comment by flovilmart** [comment]
what's the suggested fix?

**Comment by flovilmart** [comment]
@ogezue we have it declared this way in our project:
```
class Location: PFObject, PFSubclassing {
    static public let entityName = "Location"
    static func parseClassName() -> String {
        return entityName
    }
...
}
```

Does it work for you?

**Comment by ogezue** [comment]
To be sure I deleted the extension and implemented it like you with the same result.
I solved it now by going back to Swift 3.2 - here it is working. So it is an issue with Swift 4.

**Comment by flovilmart** [comment]
Ok, we’ll try to figure out something, in the meantime, you can probably file a radar as it seems to be a regression / side effect on the latest swift builds.

**Comment by laurentfarci** [comment]
I have the same issue and had to revert back to swift 3.2 - Please let me know if you find a way to fix this.

**Comment by flovilmart** [comment]
DID you try 1.15.2?

**Comment by laurentfarci** [comment]
@flovilmart Yes I am using Parse SDK 1.15.2 and Xcode 9 GM - The error is the same as ogezue. Type 'PICTURE' does not conform to protocol 'PFSubclassing'

**Comment by flovilmart** [comment]
So that’s good then.

**Comment by craiggrummitt** [comment]
@laurentfarci I'm having this problem too, but I'm not following what your solution was. Can you go into more detail?

**Comment by ogezue** [comment]
The Problem solves with XCode9 GM. Just clean your cache.

**Comment by laurentfarci** [comment]
@craiggrummitt Make sure you are using Parse SDK 1.15.2 and Xcode 9 GM. Clean your build folder in Xcode - and then for my part I had to rewrite the start of my class extensions start i.e "extension PICTURE: PFSubclassing {"

**Comment by craiggrummitt** [comment]
Ok, I'll check all that - but that last part was what I didn't understand. How was that extension declaration different to the extension declaration you had previously?

**Comment by laurentfarci** [comment]
@craiggrummitt You are welcome. There was no difference for the declaration, somehow Xcode was still showing me the error and by re-typing the declaration with auto-complete it made the error message disappear.

**Comment by craiggrummitt** [comment]
@laurentfarci Ha! OK, thanks for clarifying.

**Comment by luispiura89** [comment]
I was having this same issue. I just updated the new Parse and Bolts SDK and everything works well on swift 4
