### ISSUE TITLE
Fails to build when implementing PFSubclassing protocol

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [parse-community/Parse-SDK-iOS-OSX#1172]
In Xcode 8.3.3 using Swift 3 with the latest version of Parse iOS SDK, implementing the PFSubclassing protocol for a PFObject subclass causes the Swift Compiler to fail.

Command failed due to signal: Abort trap: 6 
Merge AppName.swiftmodule

1.    While deserializing decl #150 (XREF)in 'AppName'
2.    Cross-reference to module 'Parse'
    ... PFObject
    ... in an extension in module 'Parse'
    ... object
    ... with type (PFObject.Type) -> () -> Self
3.    If you're seeing a crash here, check that your SDK and dependencies match the versions used to build 'AppName'

    public class Story: PFObject, PFSubclassing {
         @NSManaged var identifier: String?

         public static func parseClassName() -> String {
            return "Story"
        }
    }

Also tried

    extension Story: PFSubclassing {
        static func parseClassName() -> String {
            return "Story"
        }
    }

**Comment by flovilmart** [comment]
If you're using cocapods, can you try using the master branch an let me know? We see a similar issue with Swift 4.

**Comment by jordanhbuiltbyhq** [comment]
Building from master fixed it! Thank you. I'm reading you no longer need to call `registerSubclass` but do still need to adopt `PFSubclassing`. All seems well but haven't tested actually using the object.

**Comment by flovilmart** [comment]
Good to hear! What version of the SDK are you using?

**Comment by jordanhbuiltbyhq** [comment]
1.15.1

**Comment by flovilmart** [comment]
I'm crafting 1.15.2 for today.

**Comment by flovilmart** [comment]
Thanks for reporting the issue :)
