### ISSUE TITLE
Pod - Parse 1.15.1 Missing PFPolygon.h/m

### ISSUE THREAD

**Issue by gateway** [parse-community/Parse-SDK-iOS-OSX#1174]
Trying to build a project today and have the included pod files for parse, throws an error for:

make sure everything was cleaned so I nuked my Pods/ folder and did pod install..

Here are the pods that where pulled in.

```
CocoaPods 1.3.1 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.3.1

Analyzing dependencies
Downloading dependencies
Using Bolts (1.8.4)
Using FBSDKCoreKit (4.25.0)
Using FBSDKLoginKit (4.25.0)
Using FBSDKShareKit (4.25.0)
Using Parse (1.15.1)
Using ParseFacebookUtilsV4 (1.11.1)
Using ParseUI (1.2.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 6 dependencies from the Podfile and 7 total pods installed.
```

Also looked in my Pods/Parse/Parse folder for PFPolygon.h and it clearly doesn't exist.. 

Can anyone else confirm this?

**Comment by flovilmart** [comment]
What platform are you building for?

**Comment by gateway** [comment]
Trying to do a build on my phone, building for iOS 10.. I even nuked the whole folder of our code base, did a clean git clone and pod install.. no dice .. very odd.. not sure what to do..

![image](https://user-images.githubusercontent.com/519563/29539314-2ce7150c-867e-11e7-95c4-0197e1e1bdf2.png)

**Comment by gateway** [comment]
Hold, looking at the issue.. may be that one of our programmers actually checked in their Pods folder causing issue..  verifying now.

**Comment by gateway** [comment]
Ignore, was previous Pods folder issue :( sorry about that.
