### ISSUE TITLE
App needs closing for sharing extension to see update on shared keychain

### ISSUE THREAD

**Issue by thibauddavid** [parse-community/Parse-SDK-iOS-OSX#1177]
Hi,

When I login/logout an user, my app sharing extension won't see any update until I force close containing app. 
For instance, if I logout my user, and open my sharing extension, PFUser.current() returns previous user I've just logged out, instead of nil.

I've tried manually calling .synchronized on my `UserDefaults(suiteName: "my-app-group")` right after login/logout without success.

Is there anything I'm missing ?

Thanks !

**Comment by MobileVet** [comment]
@thibauddavid Does your extension include the PFUser.current().sessionToken?
