### ISSUE TITLE
Issue with PFFile content local persistence

### ISSUE THREAD

**Issue by tealshift** [parse-community/Parse-SDK-iOS-OSX#1178]
Since there is no support yet for Local DataStore of PFFile, and I already have an in-house solution for archiving a PFObject's file (staged) content, is there a way that I can update a PFFile with my own local path for content so it doesn't attempt a network fetch when I use [PFFile getData]?

**Comment by tealshift** [comment]
In an attempt to add this feature myself, I've written a new public method in PFFile:
```
-(void)setFileCachedContent:(NSData*)data{
    NSString *path = [self _cachedFilePath];
    if (path) {
        [data writeToURL:[NSURL URLWithString:path] atomically:YES];
    }
}
```
Seems to work! Does anyone think this would be useful enough to go into a PR?

**Comment by pranjalsatija** [comment]
I'm pretty sure that `PFFile` automatically fetches data from the on disk cache unless the file in question is associated with a dirty key. I'm pretty sure that you can't actually change a `PFFile`, you just have to upload a new one and change an object's reference to the file, and the Parse SDK takes advantage of that immutability to avoid fetching files when it's not necessary to do so.

If this is correct (anyone please feel free to tell me if it's not), wouldn't it be a bad idea to allow people to change the cache that the file points to? This would cause the file to deviate from its automatic local cache. I get that you're saving and modifying files locally, but wouldn't that be a job left best to an external data persistence framework of some kind?

**Comment by tealshift** [comment]
Ideally yes. Parse Subclassing handles nearly all my data interfacing needs so it seemed the logical next step was to wrap the PFFile accessors in a similar fashion. I think you're right in hindsight though. I could have restricted my access of PFFile content to their url property instead of using their [get] methods. Thanks for your input!

**Comment by pranjalsatija** [comment]
Additionally, you may want to subclass `PFFile` and expose a `persist()` member function, so whenever you want to save a file locally, just call `file.persist()`. Additionally, you could create a static function to read files from disk (something like `File.read(fileName: "abcxyz")`), and you could have the `File` class compare the name of the file being read with the name of the file that was just fetched from Parse to see if refetching the file is necessary. This way, you could get real persistence, not just temporary caching, but also have the ability to use `PFFile` the way it was designed. Feel free to reach out if you have any questions.
