### ISSUE TITLE
$0.isLocalDatastoreEnabled = true -> storyboard cannot initialized..

### ISSUE THREAD

**Issue by ShawnBaek** [parse-community/Parse-SDK-iOS-OSX#1180]
Hi, I have a problem with isLocalDatastoreEnabled = true.

I added libsql3.tdb files in my project.

My problem is..

in AppDelegate.swift

------------------------------------------------------------------------------------------------
            guard let mainStoryBoard:UIStoryboard=UIStoryboard(name:"Main", bundle:nil) else { return }
           //error occurs in below!         
            guard let mainPage = mainStoryBoard.instantiateViewController(withIdentifier: "TabBarVC") as? TabBarVC
                else { return }
            //set mainPage
            window?.rootViewController=mainPage
            
------------------------------------------------------------------------------------------------
If I disable the isLocalDatabase,  then It works perfectly.

My error message is

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Method not allowed when Pinning is enabled.'

libc++abi.dylib: terminating with uncaught exception of type NSException

I already check my storyboard and id.

**Comment by ShawnBaek** [comment]
I think this problem related with "instantiateViewController" and $0.isLocalDatastoreEnabled.

If I resolve this issue, then I will share.

**Comment by flovilmart** [comment]
isLoxalDatastoreEnabled is a getter, you should use the setter to set the value to true

**Comment by ShawnBaek** [comment]
@flovilmart Thank you! It was my problem. 

I solved this problem.

$0.isLocalDatastoreEnabled (x) ->  Parse.enableLocalDatastore()
