### ISSUE TITLE
Deadlock in fetchAll

### ISSUE THREAD

**Issue by olleraab** [parse-community/Parse-SDK-iOS-OSX#1184]
There is a deadlock when using fetchAll and two objects has pointers refering to each other, indirectly or directly.

When processing the result from fetchAll, all objects are handled individually in separate BFTasks. This happens in PFObjectController - processFetchResultAsync:forObject: in the method _collectFetchedObjects.

_collectFetchedObjects does a @synchronized (lock) on its object, traverses its connected objects, and when calling allKeys on another object, allKeys locks that object @synchronized (lock). Thus if A locks itself and then locks B, and then B locks itself and then locks A, we get a deadlock. This is confirmed when I look at the stack traces, in a lot of threads, they are waiting on a mutex from allKeys.

<img width="428" alt="skarmavbild 2017-09-06 kl 14 04 30" src="https://user-images.githubusercontent.com/1598666/30162384-e3d8741e-93d4-11e7-8c0d-7a67a9fbd0b3.png">

**Comment by flovilmart** [comment]
We’ll have a look, do you feel you’ll be able to write a breaking unit test?
