### ISSUE TITLE
Xcode 9 / Bolts-Swift error

### ISSUE THREAD

**Issue by Samigos** [parse-community/Parse-SDK-iOS-OSX#1192]
I just upgraded Xcode, now with Swift 4 and an error has occurred at the `Task` swift file, of `Bolts-Swift` directory! See picture below:

<img width="1431" alt="screenshot at sep 23 15-09-58" src="https://user-images.githubusercontent.com/9467442/30773052-4cc9ed74-a071-11e7-8a34-772b9903cdff.png">

It seems the `success` case needs an argument...
Have in mind I already have upgraded the SDK with cocoapods.

Thanks in advance!

**Comment by flovilmart** [comment]
Please open an issue on the boltsSwift project.
