### ISSUE TITLE
XCode 9 and Bolts compile error

### ISSUE THREAD

**Issue by rogerhu** [parse-community/Parse-SDK-iOS-OSX#1193]
PR https://github.com/BoltsFramework/Bolts-Swift/pull/62/files fixes issues with XCode 9.

The current workaround is to force Pods dependencies including Parse to Swift 3.2:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.2'
    end
  end
end
```

@flovilmart

**Comment by flovilmart** [comment]
@rogerhu this should be fixed with the latest versions of the SDK. please reopen the issue if it persists

**Comment by rogerhu** [comment]
Thanks!
