### ISSUE TITLE
Login issue with Facebook in iOS 11

### ISSUE THREAD

**Issue by gabriel-tizkka** [parse-community/Parse-SDK-iOS-OSX#1194]
Does anyone had a problem while authenticating a user (signup/login) with iOS 11 and the latest Facebook SDK (4.27.0)?

**Comment by flovilmart** [comment]
Without more information that’s pretty tough to frame ‘problem’

**Comment by gabriel-tizkka** [comment]
So we are using the latest Parse SDK for iOS 1.15.3 and the latest Facebook SDK 4.27.0 which was released yesterday. Once the a user tries to authenticate/login the app gets frozen with iOS 11 - it is working properly for previous iOS versions.
More info in this link: https://developers.facebook.com/bugs/1970293586573790/
Apparently Facebook released the new SDK and fixed this problem, however it is not working properly. Our doubt is that it might be Parse SDK for iOS.

**Comment by nickmeessen** [comment]
Same issue here, we're investigating.

**Comment by gabriel-tizkka** [comment]
Hi Nickmeessen, 

Have you solved the issue? Any tip?

Thank you!

**Comment by nickmeessen** [comment]
We have used the download from the releases section (https://github.com/parse-community/Parse-SDK-iOS-OSX/releases) and then release 1.15.3, we were using Carthage, which wouldn't work properly.

Also we're using Facebook SDK 4.27.0. 

Hope this helps, it's working for us now.

**Comment by flovilmart** [comment]
So, everything is Ok then? Should we close?

**Comment by gabriel-tizkka** [comment]
Apparently, updating Parse SDK + Facebook SDK 4.27.0 and the latest iOS 11 update everything seems to be working OK. I close the issue. Thank you.

**Comment by erfe1** [comment]
null.OFF
