### ISSUE TITLE
Why is PFPush and PFInstallation excluded for tvOS?

### ISSUE THREAD

**Issue by funkenstrahlen** [parse-community/Parse-SDK-iOS-OSX#1198]
I would like to use PFPush and PFinstallation on tvOS. I see that it is excluded from the pod: https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/98ba23c37f099464287a74df03f2e084ff91f0bb/Parse.podspec#L31-L42

Why is this the case? Is this still necessary because tvOS does support notifications.

**Comment by flovilmart** [comment]
@funkenstrahlen there was some work done in this branch (https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1238) to get the push for tvOS, do you want to pick it up from there?
