### ISSUE TITLE
Parse saveEventually JSON 3840 error (Parse Server on AWS)

### ISSUE THREAD

**Issue by ArchonLight** [parse-community/Parse-SDK-iOS-OSX#1199]
When iOS11 was released it broke our app with the error

> [Error]: Failed to run command eventually with error: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set."

This happens on the saveEventually line of a new object being saved to Parse.

```
[photo saveEventually:^(BOOL succeeded, NSError *error) {
     if(error) {
          completionBlock(nil, error, photo);
     } else {
          completionBlock(YES, nil, photo);
     }
 }];
```

The weird thing is that it doesn't happen all the time. When I add a breakpoint to the code and "po photo" everything looks just fine. Sometimes it works and sometimes it doesn't. I can upload the same photo over and over and 80% of the time it fails but 20% of the time it works. 

I updated Parse to version 1.15.3 (current) and it still fails. It seems to only fail occasionally on iOS11 devices/simulator and has been working for 2 years on many devices and operating systems.

Any ideas?

**UPDATE:**
Switching to saveInBackgroundWithBlock: changes the success percentage listed above. It only fails 40% of the time now.

**Comment by msniff16** [comment]
Seeing the same thing on our end, but it is with the ```saveInBackground``` method. Seems to not like saving arrays, strings seems to save fine each time.

**Comment by flovilmart** [comment]
This seems to be an invalid response from Parse Server, (invalid JSON) You should have a look into your logs there.
