### ISSUE TITLE
Documentation for Full Text Search

### ISSUE THREAD

**Issue by DIMEGLIOM** [parse-community/Parse-SDK-iOS-OSX#1200]
I saw that the newest iOS SDK now includes full-text search capabilities but I have noticed that the docs(http://docs.parseplatform.org/ios/guide/) do not reflect these changes. Is there any way these could be updated?

Thanks

**Comment by dplewis** [comment]
The pull request https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1196 is still pending. Once it is merged we'll update the docs

**Comment by DIMEGLIOM** [comment]
@dplewis I'll go ahead and open an issue there. Thanks.
