### ISSUE TITLE
Client locale different from iOS locale

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-iOS-OSX#1201]
The locale as determined by the request header in Cloud Code is different from the locale determined in iOS locally on the device.

In my example `request.headers['accept-language']` in Cloud code is `zh-cn`, that is:
- language: Chinese
- country: China

Locally on the iOS device the `Locale.current.identifier` is `zh-Hans_US` which is correct and according to the device system settings, that is:
- language: Chinese
- script code: Chinese Simplified
- country: United States

If `accept-language` is determined by the client SDK, that looks like a bug.

Parse-SDK-iOS-OSX 1.15.3
Parse Server 2.5.3

**Comment by flovilmart** [comment]
The client SDK is not setting the `accept-language` header AFAICT, can you point out where you see that issue?

**Comment by mtrezza** [comment]
@flovilmart I had the issue in Cloud Code where I tried to use the header as fallback to guess the user's device language setting. However I think that `zh-cn` implies Chinese as used in China (mainland) and therefore means Simplified Chinese, according to `ISO 639-1, ISO 639-2 and ISO 639-3`.

**Comment by erfe1** [comment]
NO
