### ISSUE TITLE
Parse application - Can't login to user

### ISSUE THREAD

**Issue by Samigos** [parse-community/Parse-SDK-iOS-OSX#1203]
I'm on Parse Server `2.6.3`and since this morning, I can't login to one of my users. I printed the returned error and this is what I got:

`Invalid username/password. (Code: 101, Version: 1.14.2)
Optional(Error Domain=Parse Code=101 "Invalid username/password." UserInfo={code=101, temporary=0, error=Invalid username/password., NSLocalizedDescription=Invalid username/password.})`

The thing is, I'm **100%** sure I'm giving the correct username and password!
I searched to my Parse Dashboard and the user exists without a doubt! In addition, there are other users I login successfully!

Any ideas on what's happening?

Sidenote: The user wasn't registered with Facebook login but, with username, email and password.

**Comment by flovilmart** [comment]
Is it true for all users? Can you try with another username/password? If you reset the password in the dashboard, does it work?

**Comment by Samigos** [comment]
Until now, it's the only user I can't login to... I tried changing both username and password, but the problem remains! Is there any chance it's an iOS 11 issue? Until yesterday, when I had iOS 10.3.3 I could  login successfully!

**Comment by flovilmart** [comment]
does the login work with the API console / pure REST call ?

**Comment by flovilmart** [comment]
Can you provide the logs when running with VERBOSE=1 on the server as well?
