### ISSUE TITLE
Cache Policy making duplicates.

### ISSUE THREAD

**Issue by farhansyed9** [parse-community/Parse-SDK-iOS-OSX#1205]
When I do a query, and do cacheThenNetwork. I have duplicates of all my objects in the array for example. 

Am I doing it wrong? 

I make sure to clear the array before the network call too. 

I am setting the cache like so: 

query.cachePolicy = .cacheThenNetwork

**Comment by georgesjamous** [comment]
Could you post the code that you arr using ?
.cacheThenNetwork will load data from cache (if they are available) call the [query findObjectsInBackgeoud:] callback. Then fetch object again from server (hence ThenNetwork)
Then calls your callback again.

If you are appending these objects to a global array. Yes this could cause duplicates

**Comment by farhansyed9** [comment]
I am appending the objects to an array. Is there a better way to do this?

**Comment by georgesjamous** [comment]
One way of handling this is to use a custom function to append new objects to your global array.

This function would loop through the new objects returned everytime and check for duplicates in the global aray. If the object already exists, you just dont add it(or you can replace it to take advantage of the fact that it is fresh from the server), if not go ahead and add it.

**Comment by georgesjamous** [comment]
Personally i would refrain from using .cacheThenNetwork everytime as it can make unnecessary api calls. 
Use .cacheElseNetwork and give it an appropriate .maxCacheAge to your needs.

**Comment by farhansyed9** [comment]
Yeah thats what i was actually thinking of doing. Thanks for the tip!

**Comment by flovilmart** [comment]
Closing as it seems you guys got it sorted out!
