### ISSUE TITLE
Email value from PFUser object fetches a nil despite having value 

### ISSUE THREAD

**Issue by ashish-naik** [parse-community/Parse-SDK-iOS-OSX#1207]
I have a query "items" object. The class has a "parent" key that points to _User object.The query is successful and fetches 'parent' object and i am able to access some custom keys from this 'parent' object but email is returned as nil !! App crashes with Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0).

Below is stripped down code.Could anyone suggest why is this happening? This was working earlier and i have not made any code change. 

I commented out Parse.enableLocalDatastore() in AppDelegate. I restarted my laptop. Erased contents and settings from simulator. it worked once but started getting issue again. I tried deleting app, reinstalling also. 

i even tried fetchIfNeeded as suggested on [SO](https://stackoverflow.com/questions/18429723/strange-issue-with-parse-com-with-key-not-being-included) but no same result.

Parse-server ver 2.5.3 on Heroku.
Parse SDK ver 1.5.3
Xcode 9.0.1
Simulator - iOS 11.01, 10.3

```
let query = PFQuery(className: "items")
     query.includeKey("parent") // parent points to _User


     do {

         let results = try query.findObjects()

         for result in results {

         let parent = result["parent"] as! PFUser

        let foundUser = User()
        foundUser.user = parent // User.user is of PFUser type

        //custom keys in _User
        foundUser.name = parent["name"] as! String 
        foundUser.city = parent["city"] as! String
        foundUser.geoLocation = parent["location_geopoint"] as! PFGeoPoint 
        foundUser.userAddress = parent["user_address"] as! String

        //this is failing with nil eventhough there is value in Parse
        foundUser.email = parent["email"] as! String

        // also tried this. parent.objectId returns a valid value
        foundUser.email = parent.email


       }

     } catch...
```

What could be the problem?

Thanks
Ashish

**Comment by brianyyz** [comment]
What release of parse-server are you using?

In 2.3.0 there was a breaking change introduced which restricted the fields returned from a query on _User. If I remember correctly, email is taken out by default and you can specify additional fields to be removed from a query result in a configuration setting. In order to retrieve email you either have to specify the master key or be the owner of that object.

**Comment by brianyyz** [comment]
Just saw that you’re using 2.5.3 so this would be why parent[“email”] fails when you force unwrap it.

**Comment by flovilmart** [comment]
@brianyyz is 💯 right. Email is a restricted field for security reasons .

**Comment by ashish-naik** [comment]
@brianyyz thanks. This solves the mystery.
