### ISSUE TITLE
Swift OSX - Change parse server URL

### ISSUE THREAD

**Issue by guidupas** [parse-community/Parse-SDK-iOS-OSX#1209]
I am developing an app using Swift on OSX and Parse server locally. I would like to set the server's url using the app (image attached) and test it, so if I need to migrate to a cloud Parse server I don't need to change it on the code and rebuilt my app, I just need to change the server's url using the app itself.

What happens is that after initializing the Parse on Swift

```
let configuracaoParse = ParseClientConfiguration {
            $0.applicationId = self.appId!
            $0.clientKey = self.appKey!
            $0.server = self.servidor!
        }

        Parse.initialize(with: configuracaoParse)
```

and testing it using a query I am not able to change the server's configuration url or reinitialize Parse with another configuration if the server's name is wrong.

I have tried:

1 - Changing the Parse server property: configuracaoParse.server = "server url". Error: Cannot assign to property: 'server' is a get-only property

2 - Reinitiating it using the new configuration. Result: Parse is already initialized.

Is there a way I can change the current server's url or reinitialize Parse with another configuration without restarting the app?

<img width="972" alt="riqzz" src="https://user-images.githubusercontent.com/12818273/32488477-7b3eaf5e-c38b-11e7-8d54-e64de78c1ba2.png">

**Comment by natanrolnik** [comment]
@guidupas I believe you need to restart the app indeed. As you see from the errors, `server` is a read only property, so it can be configured only in initialization. And from the second error, Parse cannot be reinitialized.

Why do you need to change it in runtime after initializing once?

Abraço!

**Comment by guidupas** [comment]
Because this app is to a client that intend to change it to a cloud service later on.

**Comment by MobileVet** [comment]
I think the better way to approach this is with a build time configuration.  Based on a compiler flag you can substitute in the appropriate parameters depending on where your target is.  We currently reference a plist file in our bundle and based on the configuration point it at a local instance of the server or our cloud based development or production servers.

**Comment by flovilmart** [comment]
@guidupas this is not possible at the moment and unlikely we'll put effort into providing that feature. However, I'll gladly review a PR that would bring that feature in.

**Comment by aBuder** [comment]
Hi, is there an solution. I have already the same problem. In my use case I have multiple parse server and the customer have to enter serverurl, username and password. 

Why i have multiple parse server? This is an security feature. So would there an solution to reinitialize the parse client.

Here is an architecture image.

[Architektur_Trainer_APP.pdf](https://github.com/parse-community/Parse-SDK-iOS-OSX/files/1955572/Architektur_Trainer_APP.pdf)

**Comment by flovilmart** [comment]
@aBuder if you with to open a pull request, feel free, but note that this isn't encouraged as you'd need to log out current users, delete the currently cached data (queries etc...)

**Comment by aBuder** [comment]
@flovilmart Hmm I am only fit on swift. Is there an other solution?

**Comment by flovilmart** [comment]
At runtime, I doubt this will be possible without a major overhaul. Otherwise, at restart ?

**Comment by AliZahr** [comment]
I tried to set a new parse server url while inside the app, but there was no change what so ever.
```
Parse.server = @"https://serverNewUrl.com"; or [Parse setServer:@"https://serverNewUrl.com"];
NSLog(@"%@",Parse.server); -----> This prints the new server set
NSLog(@"%@",Parse.currentConfiguration.server); -----> This prints the old one set
```

How did you achieve the change ?
