### ISSUE TITLE
Download all objects when App is launched the first time

### ISSUE THREAD

**Issue by robin7331** [parse-community/Parse-SDK-iOS-OSX#1210]
Hey there,

not really an issue but a question.
I'm planning on developing an App with offline capabilities.
So I know that I can cache queries with certain policies.
But how would you actually implement an initial download of all (defined) queries when the user starts the app the first time?

Is there a trick or do I have to manually execute all queries so they are stored in the cache?

Thanks for your advice.

Cheers

**Comment by flovilmart** [comment]
I wrote a small framework a while back: https://github.com/flovilmart/ParseZero note that it’s not very actively maintained but you could get some inspiration from it :)

**Comment by brianyyz** [comment]
Not knowing your app my thought is to manage the queries individually that way you’ll know when anything fails in the individual query callback and the app can react accordingly.
