### ISSUE TITLE
Error building Parse(Bolts) in Xcode 9.1

### ISSUE THREAD

**Issue by talkaboutdesign** [parse-community/Parse-SDK-iOS-OSX#1211]
<img width="597" alt="screen shot 2017-11-08 at 3 44 57 pm" src="https://user-images.githubusercontent.com/2926534/32573399-e11a0f42-c49b-11e7-9c78-cd9d4b4f4130.png">

**Comment by johnantoni** [comment]
Same here

**Comment by johnantoni** [comment]
Same here, compiling with carthage and XCode 9.1

**Comment by flovilmart** [comment]
Please open an issue on the Bolts SDK, If we see some unresponsiveness from their side, we'll fork and leverage our own release cycles while keeping up with their master branch.
