### ISSUE TITLE
Where are the tutorials now hosted?

### ISSUE THREAD

**Issue by kennebecstars** [parse-community/Parse-SDK-iOS-OSX#1212]
They were previously at https://parse.com/tutorials.

The starter projects are not what I want. There was AnyPhone and I was wondering if it was updated?

**Comment by montymxb** [comment]
@kennebecstars Most of what was migrated from **parse.com** can be accessed at [parseplatform.org](http://parseplatform.org/). We don't have a tutorials section there, but you can find all the guides for getting started there. I would have though you could use the Wayback Machine to pull up the old tutorials but it was never cached :/.

What specifically were you looking for in the old tutorial by the way?

**Comment by kennebecstars** [comment]
There really aren't a lot of fully functional tutorials out there and the book that are out there are few. I would like a full e-commerce example, more than just login/signup (I found a good one for that in ParseUI-iOS that was actually in swift.)

**Comment by montymxb** [comment]
We don't have any detailed example projects for e-commerce at the moment. However, if anyone were to provide such an example it certainly wouldn't be unappreciated. I know for getting started it's handy to use **parse** + **stripe** or **braintree**. Both are extremely handy for setting up secure and manageable payments, and then parse has got your DB 👍 .
