### ISSUE TITLE
What is the best way to set up a like function?

### ISSUE THREAD

**Issue by farhansyed9** [parse-community/Parse-SDK-iOS-OSX#1213]
More of a question. 

Currently I have the user's likes being saved under their user which is an array of objectId's. 

I feel that it isn't the best thing to put it under the user and it should be it's own class. 

My real question is. Say I have a class for Likes. And on my home page of my iOS app. I am querying photos from a Photo class. How would I grab the likes for all the photos being queried? I can't get my head around that. 

Thanks.

**Comment by brianyyz** [comment]
Sounds like a Like class with a Photo pointer and a User pointer. Each instance of a Like would then be linked to the User who created it and the Photo it relates to.

**Comment by cubycode** [comment]
i would use Arrays in your Photo class by adding a likedBy column of type Array.
 Once a user likes a picture, create an Array [String] called likedBy and add his objectID in it.
Then, in your query.findObjectsInBackground() instance, get the likedBy array and its likedBy.count Int value, and simply print it in your Label ;)
Hope this helps!

**Comment by mtrezza** [comment]
@farhansyed9 The structure of your collections and document fields is individual to your app.

It can save you some trouble of remodeling your data structure if you try to think ahead about things like future app features (requiring their own specific queries) and scalability (a photo may not be liked by 10 but 10.000 people).

An approach could be:
1. Write down your near-term app features
2. Write down what data these feature will interact with
3. Write down the data model that is most efficient to access that data

Parse has a good doc for your many-to-many relation (many different users can like many different images) [here](http://docs.parseplatform.org/js/guide/#many-to-many).
