### ISSUE TITLE
App Extension does not have access to the PFUser.currentUser().sessionToken from main app

### ISSUE THREAD

**Issue by MobileVet** [parse-community/Parse-SDK-iOS-OSX#1220]
I have a project with an embedded app extension for the Today Widget.  The expectation is that this widget should have access to my main application's Parse local cache.

I have setup the **shared group** and it appeared to be working correctly.  Creating a user in the main application and then testing for **PFUser.current()** in the app extension will return the same user object, objectId and username are equal.

However, the **sessionToken** is no longer present on the 'loggedIn' user.  As such, queries with this user do not return the expected results due to ACLs.  

Is this expected behavior that the **sessionToken** is _NOT_ saved locally with the *currentUser()*?  How is it saved locally for the main application?

Setup:
Xcode 9.1 (9B55)
iOS 11.1 Simulator
iOS SDK 1.15.3
Server SDK 2.6.5

**Comment by flovilmart** [comment]
The sessionTokens are actually stored in the keychain, which should work with the keychain sharing groups as to set them up. If it isn’t, there’s either a configuration issue or an issue in the SDK. In either case, this requires more investigation

**Comment by MobileVet** [comment]
I tried this again last night... this time with Keychain sharing turned on and it still didn't work.  The more I thought about it, the more I was surprised and felt like this had to be a bug.  While I could see someone deciding to leave the **sessionToken** out for security reasons, it seemed like a strange choice considering that the User info was shared.

What is really strange to me now is that it passes the User information without Keychain sharing turned on.  How is that possible?

One thing I wondered was if you are using Keychain sharing, where is the configuration option for the _** kSecAttrAccessGroup**_?  Seems like this must be set or else the default Keychain would be used and not the shared one.

@flovilmart to your point, is there an option for setting the Security Access Group?  I couldn't find one.

**Comment by MobileVet** [comment]
@flovilmart I am having trouble getting the SDK to run locally... but I have been browsing the code.   I think I identified the a potential issue, at least something doesn't seem right in the *PFCurrentUserController.m* file.  The *_saveSensitiveUserDataAsync* and *_loadSensitiveUserDataAsync* do not appear to be mirror images of each other.  The *sessionToken* is saved from **_user.sessionToken_** but loaded into a property on **_user._state_**

Line 272 is where the load function starts, with the relevant lines being
`
                PFMutableUserState *state = [user._state mutableCopy];
                NSString *sessionToken = userData[PFUserSessionTokenRESTKey] ?: userData[@"session_token"];
                if (sessionToken) {
                    state.sessionToken = sessionToken;
                }
                user._state = state;
`

**Comment by MobileVet** [comment]
Hmm, actually I understand now... that doesn't look like the issue.  I did place some NSLog statements there and I do see that when I run my main application, I see the __loadSensitiveUserDataAsync_ read in the **sessionToken** correctly.  When the Today Widget runs and initializes Parse, it doesn't trigger __loadSensitiveUserDataAsync_.  

So that seems like an issue.

**Comment by MobileVet** [comment]
@flovilmart Ok...I am embarrassed.  This was a configuration error on my part.  I was appropriately choosing to only set the **containingApplicationBundleIdentifier** for the Today Widget... however, I was incorrectly setting it to **Bundle.main.bundleIdentifier** (which resolves to the Today Widget's bundle ID).  Facepalm.

What confused me was that the **Parse.user** was correctly recovering the _objectId_, just not the _sessionToken_.  I made the bad assumption that these were stored in the same place, when actually, they are not.  Yea for open source as I was able to track down the various saves and find that they were stored in different places.  Once that was clear, it was easy to double check the Keychain values and see that they were different... which led back to my incorrect initialization.

**Comment by flovilmart** [comment]
I'm glad you found the solution yourself! The codebase can be somewhat intimidating by it's size and complexity, but you went the right road down, and tracked down what could be wrong. Perhaps we should emphasize it in the docs? Would you have time to make a PR on the docs repo for properly configuring the extensions if the current docs isn't clear enough?

**Comment by MobileVet** [comment]
@flovilmart I will definitely review the docs and see what things could be added to clarify the persistence of the User object as well as extension setup.

I also plan to start spending my 'dev day' periods at work to helping with the Swift port.  Of course I had wanted to start that yesterday and got pulled into other things... so we will see how that goes. :)

**Comment by flovilmart** [comment]
Awesome!
