### ISSUE TITLE
Query result sorted by distance from the user

### ISSUE THREAD

**Issue by nharbo** [parse-community/Parse-SDK-iOS-OSX#1222]
Hey! 
Is it possible to sort the result of a query by the distance from the users current location? I need to filter some objects, and I can't do it clientside, as the list loads more and more when the user is scrolling (limit and skip).. So I need the result to be sorted in the query, so the closest element is first, and so on..
Is this possible? I haven't been able to find a solution

/Nicolai

**Comment by flovilmart** [comment]
See in the docs: http://parseplatform.org/Parse-SDK-iOS-OSX/api/Classes/PFQuery.html#/c:objc(cs)PFQuery(im)whereKey:nearGeoPoint:

**Comment by nharbo** [comment]
This doesn't really answer my question @flovilmart :-) I have looked the documentation, and I haven't been able to find the answer there - that's why I'm asking here.. Is it possible or not? :)

**Comment by nharbo** [comment]
I'm using this now: query.whereKey("geoLocation", nearGeoPoint: currentLocation!, withinKilometers: 100)

But that doesn't sort the result..

**Comment by nharbo** [comment]
Can you please re-open this one?..

**Comment by nharbo** [comment]
Oh, I see that the whereKey:nearGeoPoint: should sort by distance - but this is not happening.. Is this a known problem, or do you have an idea of what could be wrong?

**Comment by nharbo** [comment]
Oops! My bad! Nevermind ;) I found out that I had an addAscendingOrder added before the nearGeoPoint, and that one was overruling my geo-sorting.. Sorry! It's working now (Y)
