### ISSUE TITLE
Installation deviceToken is undefined 

### ISSUE THREAD

**Issue by adammlevy** [parse-community/Parse-SDK-iOS-OSX#1224]
I have noticed that after a period of time receiving push notifications on my device I will suddenly stop receiving push notifications on that device.  One thing I have noticed is that the deviceToken is set to (undefined) in the dashboard as seen in the included screenshot.  How is it possible that the deviceToken goes from some value to undefined. 

<img width="792" alt="screen shot 2017-12-20 at 12 13 03 am" src="https://user-images.githubusercontent.com/599680/34197355-f572bd00-e51a-11e7-8a1f-5dcd9062c212.png">

**Comment by montymxb** [comment]
It should not. Can you provide more details regarding the circumstances and number of times you have seen this happen?

**Comment by adammlevy** [comment]
I see other users in the dashboard which have subscribed to push notifications and do not have a device token either so it's not just happening on my device.  Deleting the app and reinstalling will cause the app to create a new Installation with a defined deviceToken but after around 1-2 weeks the deviceToken is back to nil.    

I thought maybe the deviceToken coming back from didRegisterForRemoteNotifications was nil so I first check if the deviceToken has data before setting it to the Installation

```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    PFInstallation *currentInstallation = [PFInstallation currentInstallation];
    if (deviceToken) {
         [currentInstallation setDeviceTokenFromData:deviceToken];
         [currentInstallation saveInBackground];
    }
}
```

The docs recommend registering for remote notifications when applicationDidFinishLaunching is called however since I don't want the notification prompt to come up on first launch I am only registering notifications when the user begins subscribing to channels.

**Comment by montymxb** [comment]
So in your this only happening for iOS related devices? By chance do you also have any android installs as well that are not doing this? If so that helps narrow it down to something more specifically regarding just this sdk.

It should be noted that the server-side requirement is either a **deviceToken** _or_ an **installationId**. If you need to guard against strange behavior with null deviceTokens you can always setup a beforeSave hook to provide a check to require a deviceToken.
```js

Parse.Cloud.beforeSave('_Installation', function(request, response) {
    if(!request.object.get('deviceToken')) {
      // prevent from saving
      response.error('installation blocked from being saved! Device token missing!');
    } else {
      // note the bad installation
      // maybe do something else to help track it with details...
      response.success();
    }
});
```

**Comment by brianyyz** [comment]
Any chance you're using the configuration parameter PARSE_SERVER_CLEANUP_INVALID_INSTALLATIONS 

when you start your parse server ?

**Comment by adammlevy** [comment]
@brianyyz am running parse server on Heroku and have PARSE_SERVER_CLEANUP_INVALID_INSTALLATIONS set to 1 in config vars.

**Comment by adammlevy** [comment]
@montymxb I don't have push enabled for Android (yet) so would have no way of knowing if it's just an iOS issue.  I'll try adding the beforeSave logic and see if that fixes the issue.  Thanks!

**Comment by flovilmart** [comment]
So if you have that feature flag enabled, this is actually the expected behavior. Remove the feature flag if you don’t want to cleanup the invalid device tokens.

**Comment by adammlevy** [comment]
@flovilmart According to [this post](https://github.com/parse-community/parse-server-push-adapter/issues/90) you said this should be the default behavior so won't I experience the same issue even without the flag?

**Comment by flovilmart** [comment]
It’s still feature flagged, as of today, so removing the flag would be ok if you don’t need the feature

**Comment by adammlevy** [comment]
How does parse-server decide a token is invalid? If I remove this feature then won't my installation be filled with invalid device tokens?

**Comment by flovilmart** [comment]
The server removed the invalid tokens based on the response from the push adapter. APNS or GCM return explicit responses when trying to send a push to a token that is no longer valid. Depending on your use cases, you may wanna keep the feature or not.

**Comment by adammlevy** [comment]
I will try without this feature.  Thanks.

**Comment by halvini** [comment]
I can confirm that setting PARSE_SERVER_CLEANUP_INVALID_INSTALLATIONS to 1 actually clears VALID deviceTokens for iOS users.

Setting this parameter is actually dangerous for your service! 30% of our iOS users lost the ability to receive push notifications after we set the variable to 1.

**Comment by flovilmart** [comment]
@halvini, I’m curious why it would clean those valid tokens when APNS returns clearly an error for the particular token

**Comment by halvini** [comment]
@flovilmart, I'm curious too. 

@adammlevy said: "Deleting the app and reinstalling will cause the app to create a new Installation with a defined deviceToken but after around 1-2 weeks the deviceToken is back to nil."

We had exactly the same issue with the users who had valid deviceTokens. When we switched the PARSE_SERVER_CLEANUP_INVALID_INSTALLATIONS  to 1, iOS users started massively reporting that they don't get any Push Notifications. Android users didn't experience such problems though.

I guess the BAD_DEVICE_TOKEN is not the only error, which results in unsetting the deviceToken field in _Installation collection.

**Comment by halvini** [comment]
@flovilmart any ideas how to resolve this issue?
