### ISSUE TITLE
import Parse -> No Such Module

### ISSUE THREAD

**Issue by gfelot** [parse-community/Parse-SDK-iOS-OSX#1225]
Just get my hands dirty with swift since a year or so. Just setup my own parse server and everything is working right.

Install parse SDK from cocoapod but when I try to `import Parse` in my `AppDelegate` I got `No such module Parse`. I try to clean and build but I have an error. I remove every files from cocoapod and reinstall again... got the same.

Something wrong in the current build or did I forgot something ?

**Comment by MobileVet** [comment]
![screen shot 2017-12-27 at 9 19 18 am](https://user-images.githubusercontent.com/1977118/34383972-102310e2-eae7-11e7-9f96-890026959ec1.png)
Is the Parse framework listed in your *Link Binary with Libraries* section of *Build Phases*

**Comment by gfelot** [comment]
You are right. At first I thought it had something to do with an update in the SDK. But it was an XCode config.

This is how I did it in case something similar happen to someone.

https://stackoverflow.com/questions/47979276/issue-with-import-parse-no-such-module-parse
