### ISSUE TITLE
Application crashes if user has no internet connection

### ISSUE THREAD

**Issue by knishant90** [parse-community/Parse-SDK-iOS-OSX#1226]
I am calling `Parse.initialize(with: configuration)` on main thread in `applicationDidLaunch` which is not failing for ~20 seconds (if application has no/slower internet connectivity) and the application crashes coz of it. What is a good suggested practice to avoid scenarios like these ?
Do tell if I need to provide more information.

**Comment by brianyyz** [comment]
Are you testing for network connectivity before you try to use a network resource like your parse server? There are all kinds of use cases where the device might not have any visibility to your server. There are packages available e.g. ReachabilitySwift or you can figure it out yourself.

**Comment by flovilmart** [comment]
@knishant90 the application should not crash on launch just by calling the initialize method.
I believe @brianyyz is putting you on the right track, perhaps you could provide a stacktrace which would help investigate the issue.

In the meantime, I'm closing the issue.
