### ISSUE TITLE
Can't use ParseLiveQuery 2.3.0 with ParseFacebookUtilsV4 1.11.2

### ISSUE THREAD

**Issue by seQVAER** [parse-community/Parse-SDK-iOS-OSX#1234]
When I installed ParseFacebookUtilsV4 1.11.2 it automatically decreases ParseLiveQuery to version 2.2.3.

When I try install last version ParseLiveQuery the ParseFacebookUtilsV4 automatically decreases to version 1.11.1

Any idea how I can fix it?

**Comment by flovilmart** [comment]
With the latest version of the Parse SDK through cocoapods, Facebook utils is distributes alongside the Parse pod as a subspec.
Just remove ParseFacebookUtilsV4 pod, and add

pod ‘Parse/FacebookUtils’

Then in your project you can remove all imports related to ParseFacebookUtils as it will be available part of the Parse imports

**Comment by jjmaceda** [comment]
I did that however even though the autocompletion show me PFFacebookUtils, when I run the app this simulator can't find the class 

dyld: Symbol not found: _OBJC_CLASS_$_PFFacebookUtils

any ideas?

**Comment by flovilmart** [comment]
Do you still have imports imports for PFFacebookUtils anywhere in your code?

**Comment by jjmaceda** [comment]
none, just using the class

<img width="334" alt="screen shot 2018-01-19 at 6 35 18 pm" src="https://user-images.githubusercontent.com/779887/35177754-b12511bc-fd47-11e7-9084-a7e39db72e9e.png">

**Comment by flovilmart** [comment]
Do you use the `use_frameworks!` directive?

**Comment by jjmaceda** [comment]
yes, yes??

**Comment by flovilmart** [comment]
I just tried in an empty project and I have no issue building it, try cleaning your derived data folder perhaps?

**Comment by flovilmart** [comment]
Here if you want to have a look: [TestingBolts.zip](https://github.com/parse-community/Parse-SDK-iOS-OSX/files/1648347/TestingBolts.zip)

**Comment by jjmaceda** [comment]
I really appreciate your help, the only different is that u don't include pod 'Parse', just pod 'Parse/FacebookUtils', but even that way is not working, the other difference is that I'm also using pod 'ParseLiveQuery', any more ideas? also the first time works, but if I stop and run again the problem start after I change something to the podfile

**Comment by flovilmart** [comment]
I added the same pods, 
[TestingBolts.zip](https://github.com/parse-community/Parse-SDK-iOS-OSX/files/1648392/TestingBolts.zip) and the project is still building / running as expected, I'M not sure what's wrond. Double check your build settings / phases, link phases, search paths etc...

**Comment by dplewis** [comment]
@flovilmart I ran into some issues like this but I resolved them. It occurred when I was asked to convert to swift 4. I deleted my podfile.lock, ran pod install, did not update to swift 4, deleted the derived folder, clean and rebuild and everything worked.

**Comment by jjmaceda** [comment]
great, I did all what u suggested, but also I discovered I had a carthage version of the framework, not sure if it was conflicting, but now is working, thanks again for the help!

**Comment by flovilmart** [comment]
Awesome! Closing now
