### ISSUE TITLE
No known class method for selector 'taskWithException:'

### ISSUE THREAD

**Issue by JulienLevallois** [parse-community/Parse-SDK-iOS-OSX#1235]
I got this error with :

Parse 1.16.0,
ParseFacebookUtilsV4 1.11.1,
ParseLiveQuery 2.3.0,
Bolts 1.9.0

After a Pod Update

![image](https://user-images.githubusercontent.com/5727223/35114278-7dfee3da-fc84-11e7-94ac-bd1be3011eb1.png)

**Comment by jjmaceda** [comment]
Had the same issue the pod update show that ParseFacebookUtilsV4 is deprecated, remove the pod from Podfile and only add
pod 'Parse'
pod 'Parse/FacebookUtils'

that did the trick with me

**Comment by andrewfashion** [comment]
It's not letting me install Bolts 1.8.4

`[!] CocoaPods could not find compatible versions for pod "Bolts/Tasks":
  In Podfile:
    Bolts (~> 1.8.4) was resolved to 1.8.4, which depends on
      Bolts/Tasks (= 1.8.4)

    Parse/FacebookUtils was resolved to 1.16.0, which depends on
      Parse/Core (= 1.16.0) was resolved to 1.16.0, which depends on
        Bolts/Tasks (~> 1.9)

Specs satisfying the `Bolts/Tasks (= 1.8.4), Bolts/Tasks (~> 1.9)` dependency were found, but they required a higher minimum deployment target.`

**Comment by andrewfashion** [comment]
:(

**Comment by andrewfashion** [comment]
Thanks @jjmaceda  -- just removed bolts, and it works fine :)
