### ISSUE TITLE
Newly registered Facebook user is briefly un-saveable

### ISSUE THREAD

**Issue by ceramicatheist** [parse-community/Parse-SDK-iOS-OSX#1239]
(migrated from discussion on #1202)

After updating from version 1.15.3 to 1.15.4, with the corresponding Bolts update

When a new user signs up by authenticating to Facebook:

In the successful completion block of `PFFacebookUtils.logInInBackground(withReadPermissions:)`, we immediately set some properties on the new User object and attempt to save it. This reliably produces a NSInternalInconsistencyException, claiming "User cannot be saved unless they are already signed up. Call signUp first."

If we postpone that save until after some other async work (grabbing a few extra data from Facebook, in our case), and then save the User, it saves fine. In either case, the User is inserted into the database as expected.

```
Fatal Exception: NSInternalInconsistencyException
User cannot be saved unless they are already signed up. Call signUp first.
0  CoreFoundation                 0x181fa9d04 __exceptionPreprocess
1  libobjc.A.dylib                0x1811f8528 objc_exception_throw
2  CoreFoundation                 0x181fa9c4c -[NSException initWithCoder:]
3  Hidrate                        0x10277ea8c -[PFUser(Private) _checkSaveParametersWithCurrentUser:] (PFUser.m:142)
4  Hidrate                        0x10272fd44 __81+[PFObject(Private) _deepSaveAsyncChildrenOfObject:withCurrentUser:sessionToken:]_block_invoke_3 (PFObject.m:465)
5  Hidrate                        0x1026fe860 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke (BFTask.m:331)
6  libdispatch.dylib              0x18192d088 _dispatch_call_block_and_release
7  libdispatch.dylib              0x18192d048 _dispatch_client_callout
8  libdispatch.dylib              0x181934090 _dispatch_queue_override_invoke$VARIANT$mp
9  libdispatch.dylib              0x18193a1c8 _dispatch_root_queue_drain
10 libdispatch.dylib              0x181939f10 _dispatch_worker_thread3
11 libsystem_pthread.dylib        0x181bd3120 _pthread_wqthread
12 libsystem_pthread.dylib        0x181bd2c20 start_wqthread
```

I'm sorry, I wish I had nice succinct code snippets to share with you. The way Bolts works, it's very hard to tell which bit of our app is even at fault.

Posting this before I go try to reproduce it with 1.17.0

**Comment by flovilmart** [comment]
@ceramicatheist keep me posted on this one.

Are you using the block login or the bolts task login?

**Comment by ceramicatheist** [comment]
(sorry, didn't see your edit)
We use the completion-block version of all the methods, including this one.

**Comment by flovilmart** [comment]
Can you check with bolts tasks based login?
