### ISSUE TITLE
ParseFacebookUtilsV4 1.16.0 Error

### ISSUE THREAD

**Issue by fxchou123** [parse-community/Parse-SDK-iOS-OSX#1240]
I'm keeping get this issue when integrate latest ParseFacebookUtilsV4.framwork into my project. Below is the error:

Undefined symbols for architecture arm64:
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in ParseFacebookUtilsV4(PFFacebookAuthenticationProvider.o)
      ___llvm_profile_runtime_user in ParseFacebookUtilsV4(PFFacebookUtils.o)
      ___llvm_profile_runtime_user in ParseFacebookUtilsV4(PFFacebookMobileAuthenticationProvider.o)
      ___llvm_profile_runtime_user in ParseFacebookUtilsV4(PFFacebookPrivateUtilities.o)
     (maybe you meant: ___llvm_profile_runtime_user)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by GreatAppStudio** [comment]
same here

**Comment by flovilmart** [comment]
I’ll have a look

**Comment by luispiura89** [comment]
Hello everyone

Does anyone has news about this?

**Comment by flovilmart** [comment]
IM looking into it, stay tuned

**Comment by luispiura89** [comment]
Thanks!

**Comment by vandutran** [comment]
I'm still having this issue with the latest Xcode 9.4.1 and Parse iOS SDK 1.17.1

```
Undefined symbols for architecture x86_64:
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in ParseFacebookUtilsV4(PFFacebookPrivateUtilities.o)
      ___llvm_profile_runtime_user in ParseFacebookUtilsV4(PFFacebookAuthenticationProvider.o)
      ___llvm_profile_runtime_user in ParseFacebookUtilsV4(PFFacebookMobileAuthenticationProvider.o)
      ___llvm_profile_runtime_user in ParseFacebookUtilsV4(PFFacebookUtils.o)
     (maybe you meant: ___llvm_profile_runtime_user)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
