### ISSUE TITLE
Conflicting class names: Class FBSDK... is implemented in both

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-iOS-OSX#1244]
I always used the Parse iOS SDK
- `Parse.framework`
- `Bolts.framework`
- `ParseFacebookUtilsV4.framework`

and the Facebook iOS SDK
- `FBSDKCoreKit.framework` 
- `FBSDKLoginKit.framework` 
- `FBSDKShareKit.framework` 

together in one project.

After updating to `Parse-SDK-iOS-OSX 1.16.0` and `facebook-ios-sdk 4.30.0` these warnings occur during runtime:

> objc[96053]: Class FBSDKSystemAccountStoreAdapter is implemented in both /Users/<...>/Library/Developer/CoreSimulator/Devices/7B842C67-C851-416D-99EC-6EF3F62D5DD9/data/Containers/Bundle/Application/B6894BB3-976A-4598-B29A-8F0CB4F69DEC/MyApp.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit (0x10a5751c8) and /Users/<...>/Library/Developer/CoreSimulator/Devices/7B842C67-C851-416D-99EC-6EF3F62D5DD9/data/Containers/Bundle/Application/B6894BB3-976A-4598-B29A-8F0CB4F69DEC/MyApp.app/Frameworks/ParseFacebookUtilsV4.framework/ParseFacebookUtilsV4 (0x1061f1da0). One of the two will be used. Which one is undefined.

So apparently the Parse SDK registers objC classes with the same name as the Facebook SDK. This seems to be a bug because how would I add a framework from the Facebook SDK, e.g. `FBSDKShareKit.framework` which has `FBSDKCoreKit.framework` as dependency?

**Comment by flovilmart** [comment]
Where did you pull the SDK from? Downloaded from the release page?

**Comment by mtrezza** [comment]
I used carthage:

```
github "parse-community/Parse-SDK-iOS-OSX" ~> 1.15
github "facebook/facebook-ios-sdk" ~> 4.26
```

**Comment by flovilmart** [comment]
Ok, we’ll have a look. It seems that the Facebook SDK is statically linked into Facebook utils

**Comment by mtrezza** [comment]
I should add, the naming conflict also exists between `ParseFacebookUtilsV4.framework` and `Bolts.framework`:

> objc[18091]: Class BFTaskCompletionSource is implemented in both /private/var/containers/Bundle/Application/9CF97C76-01EA-4D0C-B0EF-4721F647BF0C/MyApp.app/Frameworks/ParseFacebookUtilsV4.framework/ParseFacebookUtilsV4 (0x105c6e998) and /private/var/containers/Bundle/Application/9CF97C76-01EA-4D0C-B0EF-4721F647BF0C/MyApp.app/Frameworks/Bolts.framework/Bolts (0x10432d378).

**Comment by flovilmart** [comment]
I believe I messed up the linking stage, linking statically :/ I’ll patch the release before Monday.

**Comment by flovilmart** [comment]
Sorry it took a while here, can you test with the branch ` fix/dynamic-builds`

**Comment by flovilmart** [comment]
@mtrezza this should be resolved when using the master branch, I've spent a good amount of time ensuring dynamic targets are properly built without extaneous symbols.
