### ISSUE TITLE
Undefined bool breaks local datastore

### ISSUE THREAD

**Issue by omarzl** [parse-community/Parse-SDK-iOS-OSX#1245]
I have an app in production and I am adding new functionality.
I added a new Boolean column called isAdmin, as you can see in the image, the users that already use the app has an (undefined) value, and the new users have either a False or a True

![captura de pantalla 2018-01-27 a la s 12 53 30](https://user-images.githubusercontent.com/6267487/35475279-277d3ba4-0361-11e8-8968-f1ac6f154560.png)

The problem comes when in the iOS App I fetch any object that has an (undefined) value and then pin it to the local datastore.

When I pin the object it says that was successful and without an error, but when I fetch the object from the local datastore it shows this error:
**This object is not available in the offline cache.**

![captura de pantalla 2018-01-27 a la s 13 14 44](https://user-images.githubusercontent.com/6267487/35475441-1566dd14-0364-11e8-9462-745280fd1c90.png)

This is my subclass, as you can see I added the bool property
![captura de pantalla 2018-01-27 a la s 12 56 48](https://user-images.githubusercontent.com/6267487/35475316-affb381e-0361-11e8-8fc3-bdc2ffb7a4a1.png)

I tried making it an optional, but it is not permitted by Swift
![captura de pantalla 2018-01-27 a la s 12 58 16](https://user-images.githubusercontent.com/6267487/35475321-cabb5d6e-0361-11e8-84f3-4df1bd7b1876.png)

I guess the local datastore have a problem saving undefined Bool values, I tried many options but I can't find a solution.

**Comment by flovilmart** [comment]
Try to set them as NSNumber, I believe Bool are not properly reported in the objc runtime

**Comment by omarzl** [comment]
I changed to an optional NSNumber, but it stills shows the same error

![captura de pantalla 2018-01-27 a la s 13 20 53](https://user-images.githubusercontent.com/6267487/35475486-f03eae12-0364-11e8-981b-92748d810e3e.png)

**Comment by omarzl** [comment]
I fetch all my local objects of that class (not using containedIn on the query) and it fetches correctly, as you can see the only one that doesn't have isAdmin is the object with Id: F2Z19ZGuLc

If I manually change to False the isAdmin property on my Parse Server the error goes away on the iOS App.

![captura de pantalla 2018-01-27 a la s 13 22 43](https://user-images.githubusercontent.com/6267487/35475497-2ed2c226-0365-11e8-84d2-94ad272e0eec.png)

**Comment by flovilmart** [comment]
So we’ll need to investigate the pinning or the fetching?

**Comment by flovilmart** [comment]
So what’s the issue then?

**Comment by omarzl** [comment]
I created a new project to replicate the problem and everything works there, it seems is an error with my logic/data.

Sorry about that and thanks for your help!
