### ISSUE TITLE
ParseFacebookUtils deployment target - back to iOS 8.0?

### ISSUE THREAD

**Issue by promisenxu** [parse-community/Parse-SDK-iOS-OSX#1246]
In the v1.11.2 ParseFacebookUtils podspec, the deployment target is set to iOS 9.0 while the main Parse iOS SDK is at iOS 8.0.

Is it possible to set the deployment target of ParseFacebookUtils back to iOS 8.0?

**Comment by flovilmart** [comment]
I believe Facebook Utils leverage iOS 9+ features otherwise, feel free to open a PR

**Comment by promisenxu** [comment]
@flovilmart It seems that the deployment target is changed from iOS 7.0 to iOS 9.0 at version 1.11.2 and there doesn't seem to change that required iOS 9.0+. I will give it a try at the PR. Thanks!

**Comment by flovilmart** [comment]
CLosing as resolved
