### ISSUE TITLE
Crash in [PFACL resolveUser:] (nil dictionary key)

### ISSUE THREAD

**Issue by iainmerrick** [parse-community/Parse-SDK-iOS-OSX#1248]
I have an old, previously working app that I've just updated from the old parse.com SDK to use a new server with the new open source SDK. Some users are experiencing a crash in [PFACL resolveUser:].

Here's a representative stack trace:

> [Error]: {"code":1,"message":"Internal server error."} (Code: 1, Version: 1.15.4)
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil'
> *** First throw call stack:
> (
> 	0x000000010bfb912b __exceptionPreprocess + 171
> 	0x000000010b655f41 objc_exception_throw + 48
> 	0x000000010bff90cc _CFThrowFormattedException + 194
> 	0x000000010c05eaba -[__NSDictionaryM setObject:forKeyedSubscript:] + 970
> 	0x0000000105a4027e __21-[PFACL resolveUser:]_block_invoke + 112
> 	0x0000000105a9b48b -[PFACLState initWithState:mutatingBlock:] + 137
> 	0x0000000105a9b642 -[PFACLState copyByMutatingWithBlock:] + 78
> 	0x0000000105a40195 -[PFACL resolveUser:] + 305
> 	0x0000000105a414ed __31-[PFACL prepareUnresolvedUser:]_block_invoke.141 + 64
> 	0x0000000105a3cbbf -[PFMulticastDelegate invoke:error:] + 237
> 	0x0000000105a68cf1 __43-[PFObject(Private) handleSaveResultAsync:]_block_invoke.548 + 151
> 	0x0000000105a35ce4 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke + 79
> 	0x0000000105a36ee7 __29+[BFExecutor defaultExecutor]_block_invoke_2 + 124
> 	0x0000000105a37421 -[BFExecutor execute:] + 65
> 	0x0000000105a35b49 -[BFTask continueWithExecutor:block:cancellationToken:] + 315
> 	0x0000000105a360b4 -[BFTask continueWithBlock:] + 92
> 	0x0000000105a68a97 -[PFObject(Private) handleSaveResultAsync:] + 575
> 	0x0000000105ab2525 -[PFUser(Private) handleSaveResultAsync:] + 48
> 	0x0000000105ab2af8 __52-[PFUser(Private) _handleServiceLoginCommandResult:]_block_invoke + 67
> 	0x0000000105a35ce4 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke + 79
> 	0x0000000105a36ee7 __29+[BFExecutor defaultExecutor]_block_invoke_2 + 124
> 	0x0000000105a37421 -[BFExecutor execute:] + 65
> 	0x0000000105a35b49 -[BFTask continueWithExecutor:block:cancellationToken:] + 315
> 	0x0000000105a359e8 -[BFTask continueWithExecutor:withBlock:] + 53
> 	0x0000000105a352d5 +[BFTask taskFromExecutor:withBlock:] + 163
> 	0x0000000105ab2a73 -[PFUser(Private) _handleServiceLoginCommandResult:] + 171
> 	0x0000000105ab4ae8 __40-[PFUser(Private) resolveLazinessAsync:]_block_invoke.264 + 171
> 	0x0000000105a35ce4 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke + 79
> 	0x000000010c5622f7 _dispatch_call_block_and_release + 12
> 	0x000000010c56333d _dispatch_client_callout + 8
> 	0x000000010c56f3a2 _dispatch_root_queue_drain + 1444
> 	0x000000010c56eda0 _dispatch_worker_thread3 + 132
> 	0x000000010caff1ca _pthread_wqthread + 1387
> 	0x000000010cafec4d start_wqthread + 13
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException

Inspecting the code, this line is suspicious: https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/5cb05c036afd6f0ea7c379b961579d7a81548342/Parse/Parse/PFACL.m#L111

If `user.objectId` is nil, that will throw the exception I see in the stack trace. The Parse framework doesn't catch it and I don't see any way for my code to catch it. I don't know how or why that field can be nil, though.

In our app's startup code, we were doing this:

```
        [PFUser enableAutomaticUser];        
        PFACL *defaultACL = [PFACL ACL];
        [defaultACL setPublicReadAccess:YES];
        [PFACL setDefaultACL:defaultACL withAccessForCurrentUser:YES];
```

On the theory that something about the ACL and the PFUser is going wrong, I've changed this to:

```
        [PFUser enableAutomaticUser];        
        PFACL *defaultACL = [PFACL ACL];
        [defaultACL setPublicReadAccess:YES];
        [defaultACL setPublicWriteAccess:YES];
        [PFACL setDefaultACL:defaultACL withAccessForCurrentUser:NO];
```

That seems to work around the crash (I imagine it isn't running that resolveUser: method at all now).

I'm afraid I don't have a cleaner way to reproduce the problem. We've noticed that our Parse server is now heavily loaded so that could be one of the contributing factors -- our pre-launch testing was on a lightly-loaded server.

**Comment by flovilmart** [comment]
What version of the SDK are you using?

**Comment by iainmerrick** [comment]
Version 1.15.4

**Comment by flovilmart** [comment]
@iainmerrick I understand why it may crash now, I'm looking into a fix. By any chance, did the save call failed?
