### ISSUE TITLE
Parse/UI with PFLoginViewController

### ISSUE THREAD

**Issue by jeffreyjackson** [parse-community/Parse-SDK-iOS-OSX#1249]
I noticed ParseUI was deprecated, so I moved on to using Parse/UI in cocoapods.  Everything seemed to install fine with cocoapods, and I was able to go through and clean out the existing `#import <ParseUI/ParseUI.h>` from my application.  Now when I build I'm getting some errors on my SignUp and Login delegates...

`Declaration of 'PFLogInViewControllerDelegate' must be imported from module 'Parse.PFLogInViewController' before it is required`

`Declaration of 'PFSignUpViewControllerDelegate' must be imported from module 'Parse.PFSignUpViewController' before it is required`

Any idea what I might be missing?

**Comment by davem2020** [comment]
I got this error as well.  None of the Parse/UI classes were recognized when importing the Parse framework.  This is for an objective-c project. I had to go back to the original ParseUI pod.

**Comment by flovilmart** [comment]
Could one of you share a sample project? This may help us find what’s wrong.

**Comment by davem2020** [comment]
My project is quite large and messy and not on github.  Are there specific settings, logs or screenshots that would be helpful?

**Comment by flovilmart** [comment]
Just a sample project, or detailed logs from the failing build as well as the imports statements for the files that are impacted

**Comment by davem2020** [comment]
I think I found the solution-
I changed all my import statements 
`#import <ParseUI/ParseUI.h>` and `#import <Parse/Parse.h>`
to
`@import Parse;`

I was not familiar with importing modules, but this seemed to do the trick.

**Comment by flovilmart** [comment]
@jeffreyjackson does it work for you?

**Comment by jeffreyjackson** [comment]
@flovilmart yes, using #import Parse; did the trick.  Thanks!
