### ISSUE TITLE
"B" ail or "F" ail

### ISSUE THREAD

**Issue by ananfang** [parse-community/Parse-SDK-iOS-OSX#1257]
I guess that is a typo in `branch release-1.17.0`

https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/6b066c905753399be162198b6916cb46fee38f08/Parse/Parse/Internal/PFAssert.h#L78

PFPrecondition "B" ailAndSetError or PFPrecondition "F" ailAndSetError?

https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/6b066c905753399be162198b6916cb46fee38f08/Parse/Parse/Internal/PFAssert.h#L87

PFPrecondition "B" ailOnError or PFPrecondition "F" ailOnError?

**Comment by flovilmart** [comment]
Bail means quitting so that’s as intended. It could have been PFPreconditionReturnOnError
