### ISSUE TITLE
Parse/UI is not available after deprecating ParseUI Framework

### ISSUE THREAD

**Issue by bfjfm2** [parse-community/Parse-SDK-iOS-OSX#1258]
In cocoapods( https://cocoapods.org/pods/ParseUI), 
it is mentioned that **This library is deprecated, it is recommended you look at Parse/UI**.
But Parse/UI is notavailable at  https://cocoapods.org/pods/Parse/UI

**Comment by flovilmart** [comment]
It’s distributed as a subspec, so it’s available under the Parse Pod

**Comment by bfjfm2** [comment]
I tried with following in my podFile
pod 'Parse', '1.15.4'
pod 'Parse/UI','~> 1.15.4'

**Got the following message in terminal:-**
`[!] Unable to satisfy the following requirements:

- `Parse/UI (~> 1.15.4)` required by `Podfile`
- `Parse/UI (~> 1.15.4)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Parse/UI (~> 1.15.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.`

**Comment by flovilmart** [comment]
Try 1.1.6

**Comment by bfjfm2** [comment]
Not working, I tried replacing  with 1.16 my podFile

pod 'Parse', '1.16.0'
pod 'Parse/UI','~> 1.16.0'
#pod 'ParseUI'

pod install
**Got the following message in terminal:-**
[!] Unable to satisfy the following requirements:


- `Parse/UI (= 1.16.0)` required by `Podfile`
- `Parse/UI (= 1.16.0)` required by `Podfile`

Specs satisfying the `Parse/UI (= 1.16.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by flovilmart** [comment]
> Specs satisfying the Parse/UI (= 1.16.0) dependency were found, but they required a higher minimum deployment target.

According to the error message, the minimum deployment target is too low in your project

**Comment by bfjfm2** [comment]
Thank you, it is working from 9.1. 
Before It is working for ios target 8.1 for both pods Parse 1.6.0 and ParseUI. 
Now I need to update with 9.1 for using ParseUI in  Parse/UI 1.6.0
