### ISSUE TITLE
App crashes when running tests

### ISSUE THREAD

**Issue by yingmu52** [parse-community/Parse-SDK-iOS-OSX#1260]
```
'Tried to register both AiReceiptsTests.TapAction and AiReceipts.
TapAction as the native PFObject subclass of TapAction. 
Cannot determine the right class to use because neither inherits from the other.'
```

I am getting this crash when I run my unit-tests, any idea why?

**Comment by nebitrams** [comment]
I had this problem long time ago.  I cannot remember exactly how I solve it.  Try to add @testable import... 

import XCTest
import Parse
@testable import TapAction

**Comment by yingmu52** [comment]
thanks
