### ISSUE TITLE
getting a lot of warning: Block implicitly retains 'self';

### ISSUE THREAD

**Issue by ranhsd** [parse-community/Parse-SDK-iOS-OSX#1261]
Hi, I'm using xCode 9.2 and get a lot of warnings of: 

> Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior

currently I see **301 warnings** in my project from various files of the SDK.

<img width="453" alt="screen shot 2018-02-13 at 13 49 10" src="https://user-images.githubusercontent.com/3685671/36148439-bc20005a-10c4-11e8-9ba0-6976e33d936d.png">

Thanks,
Ran

**Comment by speedyacme** [comment]
Same here! Xcode 9.2

Thanks
Speedy

**Comment by flovilmart** [comment]
Merged to master. Stay tuned for next release

**Comment by tahoecoop** [comment]
Hello, I'm on Xcode 9.2 running Parse 1.17.1, I'm still seeing a few dozen of these warnings, anyone else still seeing these? Thanks!

**Comment by flovilmart** [comment]
There’s is still a few in the secondary SDK’s, feel free to open a PR to fix them

**Comment by MaveyMa** [comment]
@tahoecoop, I had the same problem on my Xcode 9.3, but after I ran `pod update` to install Parse 1.17.1 (was 1.16.0), the warnings went away.
