### ISSUE TITLE
Query add order

### ISSUE THREAD

**Issue by MattiaConfalonieri** [parse-community/Parse-SDK-iOS-OSX#1269]
Hi i am trying to make a query with two oder value

 query.order(byDescending: "createdAt")
 query.addAscendingOrder("prize")

createdAt is a date
prize is a number

 query.addAscendingOrder("prize") is always ignored... anybody are experiencing this issue?

**Comment by MattiaConfalonieri** [comment]
Up, nobody?

**Comment by flovilmart** [comment]
Can you provide the server logs when running with VERBOSE=1 please?
