### ISSUE TITLE
Could not build Objective-C module 'ParseFacebookUtilsV4'

### ISSUE THREAD

**Issue by sverin** [parse-community/Parse-SDK-iOS-OSX#1271]
I'm trying to use ParseFacebookUtilsV4 in my Swift project but receive an error:

`import ParseFacebookUtilsV4`

`Could not build Objective-C module 'ParseFacebookUtilsV4'`

I'm using carthage and have tried both stable 1.16.0 and 1.17.0-alpha.3.
Someone else experiencing this, or what am I'm doing wrong?

**Comment by sverin** [comment]
If I specify "master" branch in the Carthage file it seems to work:

`github "ParsePlatform/Parse-SDK-iOS-OSX" "master"`

However, if I just specify the library it doesn't download the facebook-ios-sdk.

`github "ParsePlatform/Parse-SDK-iOS-OSX"`

**Comment by flovilmart** [comment]
If it works on master that's perfect, stay tuned for the next release.
