### ISSUE TITLE
findObjectsInBackground always results in nil

### ISSUE THREAD

**Issue by sverin** [parse-community/Parse-SDK-iOS-OSX#1272]
I have been using `findObjectsInBackground` of PFQuery before. But after updating to **master** branch it always returns nil. I have tried to create a new simple project with the same results.

Carthage file:
`github "ParsePlatform/Parse-SDK-iOS-OSX" "master"`

This works (results in expected count 100):

```
let query = PFQuery(className: "Name")
        
do {
    let objects = try query.findObjects()
    print(objects.count)
} catch {
    print("error")
}
```

This does NOT work (results in -1 (nil)):

```
let query = PFQuery(className: "Name")

query.findObjectsInBackground { (objects, error) in
    print("count: ", objects?.count ?? -1)
}
```

**Comment by flovilmart** [comment]
How does it behave with using the Bolts method instead of the callback?

**Comment by sverin** [comment]
How do you mean? Never used Bolts method. Could you give an example?

**Comment by flovilmart** [comment]
``` 
let query = PFQuery(className: "Name")

query.findObjectsInBackground().continueWithTask { (task) -> Void in
    let objects = task.result as? NSArray
    print("\(objects.?count)")
    return task
}
```

or something similar.

**Comment by sverin** [comment]
Adjusted a bit, but also returns -1 (nil)
```
query.findObjectsInBackground().continueWith { (task) -> Any? in
    let objects = task.result
    print("count: ", objects?.count ?? -1)
    return task
}
```

**Comment by flovilmart** [comment]
Can you provide the server logs please when runninh with VERBOSE=1?

**Comment by sverin** [comment]
That's the thing. If I use `findObjects()` I see the call and the results in the log. But if I use the asynchronous call `findObjectsInBackground()`, I see nothing. Like the call never happens.

**Comment by sverin** [comment]
Using VERBOSE logging

**Comment by flovilmart** [comment]
So I believe the query is never executed because not retained

**Comment by sverin** [comment]
Then I may have some rewriting to do. Thanks for great support.
