### ISSUE TITLE
iOS App crashes on production

### ISSUE THREAD

**Issue by 99thpixel** [parse-community/Parse-SDK-iOS-OSX#1278]
Hi, I have sent an update with parse version 1.16.0 (updated from 1.15.3).
The app is crashing in production since the update.

My app uses local databases. Users have reported that removing the crashing app and re-installing it solves the issue.

Below is a screenshot from the crash report I received through iTunes crash reporting.

<img width="2269" alt="screen shot 2018-03-18 at 1 15 04 pm" src="https://user-images.githubusercontent.com/37496864/37563798-9e326f70-2aae-11e8-88bc-3688d8cb18c0.png">

I'm currently trying to re-create the issue locally. At the moment, I'm testing the app migration process from the previous version to the current version.

I will enrich this issue reporting as I get more information on this.

If it seems like I'm doing something wrong, please point me in the right direction.
Any tips would be highly appreciated too.

**Comment by flovilmart** [comment]
1.17.0 was released, please update to this version.
