### ISSUE TITLE
Failure to Build 1.17.1

### ISSUE THREAD

**Issue by LilMoke** [parse-community/Parse-SDK-iOS-OSX#1282]
I am sorry but that did not work, actually what you sent me is the first command in the doc and I did those steps. Here is a transcript of my session:

Last login: Thu Mar 22 10:20:06 on ttys001
Tonys-iMac:~ ######$ cd /Users/T#####/Downloads/Parse-SDK-iOS-OSX-master-2
Tonys-iMac:Parse-SDK-iOS-OSX-master-2 T####$ ls
CHANGELOG.md	Carthage	Parse	ParseTwitterUtils	Vendor
CONTRIBUTING.md	Gemfile	Parse.podspec	ParseUI
Cartfile	Gemfile.lock	Parse.xcworkspace	README.md
Cartfile.private	LICENSE	ParseFacebookUtils	Rakefile
Cartfile.resolved	PATENTS	ParseStarterProject	Scripts
Tonys-iMac:Parse-SDK-iOS-OSX-master-2 T####$ git submodule update --init --recursive
Tonys-iMac:Parse-SDK-iOS-OSX-master-2 T####$ gem install bundler
Successfully installed bundler-1.16.1
Parsing documentation for bundler-1.16.1
Done installing documentation for bundler after 9 seconds
1 gem installed
Tonys-iMac:Parse-SDK-iOS-OSX-master-2 T####$ bundle install
Using rake 11.2.2
Using CFPropertyList 2.3.6
Using concurrent-ruby 1.0.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 4.2.10
Using atomos 0.1.2
Using bundler 1.16.1
Using claide 1.0.2
Using fuzzy_match 2.0.4
Using nap 1.1.0
Using cocoapods-core 1.4.0
Using cocoapods-deintegrate 1.0.2
Using cocoapods-downloader 1.1.3
Using cocoapods-plugins 1.0.0
Using cocoapods-search 1.0.0
Using cocoapods-stats 1.0.0
Using netrc 0.11.0
Using cocoapods-trunk 1.3.0
Using cocoapods-try 1.1.0
Using colored2 3.1.2
Using escape 0.0.4
Using fourflusher 2.0.1
Using gh_inspector 1.1.3
Using molinillo 0.6.4
Using ruby-macho 1.1.0
Using nanaimo 0.2.3
Using xcodeproj 1.5.6
Using cocoapods 1.4.0
Using ffi 1.9.18
Using mustache 0.99.8
Using open4 1.3.4
Using redcarpet 3.4.0
Using rouge 1.11.1
Using rb-fsevent 0.10.2
Using rb-inotify 0.9.10
Using sass-listen 4.0.0
Using sass 3.5.3
Using sqlite3 1.3.13
Using liferaft 0.0.6
Using xcinvoke 0.3.0
Using jazzy 0.9.0
Using naturally 1.3.2
Using plist 3.2.0
Using xcpretty 0.2.2
Bundle complete! 7 Gemfile dependencies, 47 gems now installed.
Use bundle info [gemname] to see where a bundled gem is installed.
Tonys-iMac:Parse-SDK-iOS-OSX-master-2 T####$ bundle exec rake package:frameworks
rake aborted!
LoadError: cannot load such file -- /Users/T####/Downloads/Parse-SDK-iOS-OSX-master-2/Vendor/xctoolchain/Scripts/xctask/build_task
/Users/T####/Downloads/Parse-SDK-iOS-OSX-master-2/Rakefile:10:in require_relative' /Users/T####/Downloads/Parse-SDK-iOS-OSX-master-2/Rakefile:10:in<top (required)>'
/Users/T####/.rvm/gems/ruby-2.3.4/gems/rake-11.2.2/exe/rake:27:in <top (required)>' /Users/T####/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:ineval'
/Users/T####/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `

'
(See full trace by running task with --trace)
Tonys-iMac:Parse-SDK-iOS-OSX-master-2 T####$ --init --recursive
-bash: --init: command not found
Tonys-iMac:Parse-SDK-iOS-OSX-master-2 T####$
please advise?

Tony

**Comment by flovilmart** [comment]
Can you please comment on the other issue ?
