### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [parse-community/Parse-SDK-iOS-OSX#1288]
Have been looking for means of contributing to the documentation.

Any links that can be shared as to the process of updating the documentation?

**Comment by mtrezza** [comment]
Simply submit a PR?

**Comment by flovilmart** [comment]
Yes, a Pr is nice ;) all docs are in the docs repo, API documentation is generated from source

**Comment by ianbradbury-bizzibody** [comment]
I'll go hunting.  It's the Guides that I'm looking for.
