### ISSUE TITLE
Subclass PFObject...

### ISSUE THREAD

**Issue by LilMoke** [parse-community/Parse-SDK-iOS-OSX#1289]
Hello,

This may be a bug, or by design, but when I subclass PFObject with another subclassed PFObject which is @NSManaged like so:

```
class Listing: PFObject, PFSubclassing {
	@NSManaged var buyerInfo: BuyerInfo
	@NSManaged var creator: String
	@NSManaged var id: String
	@NSManaged var status: Int32
	@NSManaged var statusDate: Date?
	
	override init() {
		super.init()
	}

	// PFSubclassing
	static func parseClassName() -> String {
		return "Listing"
	}
}

class BuyerInfo: PFObject, PFSubclassing {
	@NSManaged var buyerId: String
	@NSManaged var datePurchased: Date
	@NSManaged var sStatusMessage: String
	@NSManaged var sId: String
	
	override init() {
		super.init()
	}

	// PFSubclassing
	static func parseClassName() -> String {
		return "BuyerInfo"
	}
}
```

Reading the first object (listing) does not load the second object (buyerInfo).  It reads the first objects data, but the second objects items are nil.

Am I doing this wrong or is it not possible... or maybe I misunderstand how it should work.

**Comment by LilMoke** [comment]
Hmmm, thanks so much for the speedy reply!!  I will try adding includeKey.  I actually did see that and read about it but I thought I tried adding it and it did not work.  I will try again and if I still have an issue I will post back with with my query.  Can I ask what the cachePolicy is?  I do not remember reading about that.  Is that something I should be doing on my queries?

**Comment by brianyyz** [comment]
cachePolicy really depends on the volatility of your data. If you have quite static data then caching is great for performance e.g. first query retrieves the answer set and then subsequent queries are satisfied from cache but if it is quite volatile e.g. updated by many users then you'd likely want to disqualify the query from caching.

**Comment by LilMoke** [comment]
Ok, so adding includeKey does not seem to work.  Here is my query function:

```
	func listingsInProgressSeller(userId: String = (PFUser.current()?.objectId)!, type: ListingSellType, success: @escaping ([Listing]) -> ()) {
		let query = PFQuery(className: "Listing")
		query.whereKey("creator", equalTo: userId)
		switch type {
		case .onSale:
			query.whereKey("status", lessThanOrEqualTo: 1)
		case .inProgress:
			query.whereKey("status", greaterThan: 1)
			query.whereKey("status", lessThan: 99)
		case .completed:
			query.whereKey("status", equalTo: 99)
		default:
			break
		}
		query.cachePolicy = PFCachePolicy.ignoreCache
		query.includeKey("buyerInfo")
		query.findObjectsInBackground { (listings, error) -> Void in
			if let listings = listings as? [Listing] {
				success(listings)
			}
		}
	}

```

So I call this like so:
```
				Manager.sharedInstance.listingsInProgressSeller(userId: Manager.sharedInstance.userId, type: type, success: { (listings) in
					self.listings = listings
					self.tableView.reloadData()
				})

```

When the closure happens, right before self.tableView.reloadData(), if I break and check listings[0] all the first level properties are there, but if I look at listings[0].buyerInfo it is nil and if I try listings[0]["buyerInfo"] it is also nil. Here is what I get when I break and look at the vars:

```
(lldb) print listings[0].buyerInfo.buyerId
(String) $R7 = ""
(lldb) print listings[0]["buyerInfo.buyerId"]
(Any?) $R8 = nil

```

**Comment by brianyyz** [comment]
I'm a bit hazy on this but I think if you try something like this in success
```
      for listing in listings {
          var buyerInfo = listing["buyerInfo"] as? BuyerInfo
          print("buyer id is: \(buyerInfo.id)")
      }
```

**Comment by LilMoke** [comment]
That still produces:

```
buyer id is: nil
buyer id is: nil

```

Not sure what is going on all the other properties for listing are ok except BuyerInfo.  Is there something special i need to do when I subclass PFObject that I am not doing?

**Comment by brianyyz** [comment]
Here's an example that proves the includeKey approach works. The only other catch I can think of is that something is going out of scope in your closures.

There are two classes in this example: Location which has a name and Street which has a Location to which it belongs and a public indicator

```
import Foundation
import Parse

class Location: PFObject, PFSubclassing {
    
    @NSManaged var locationName: String
    
    class func parseClassName() -> String {
        return "Location"
    }
    
    override class func query() -> PFQuery<PFObject>? {
        // retrieve the list of Locations
        let query = PFQuery(className: Location.parseClassName())
        return query
    }
    
    override init() {
        super.init()
    }

  }
```

```
import Foundation
import Parse

class Street: PFObject, PFSubclassing {
    
    @NSManaged var streetLocationId: Location
    @NSManaged var streetIsPublic: Bool
    
    class func parseClassName() -> String {
        return "Street"
    }
    
    override class func query() -> PFQuery<PFObject>? {
        // retrieve the list of Locations
        let query = PFQuery(className: Street.parseClassName())
        query.includeKey("streetLocationId")
        return query
    }
    
    override init() {
        super.init()
    }
}
```
And here is the view controller that retrieves the Streets and for each of them prints out the Location to which it belongs name and public indicator.

```
import Foundation
import UIKit
import Parse


class AppInitializationViewController: UIViewController {
    
    //MARK: - outlets and actions
    
    var locations = [Location]()
    var streets = [Street]()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let query = Street.query()
        query!.findObjectsInBackground { (objects:[PFObject]?, error:Error?) in
            if error == nil {
                if let objects = objects {
                    self.streets = (objects as? [Street])!
                    for street in self.streets {
                        print("street public is \(street.streetIsPublic)")
                        let location = street["streetLocationId"] as? Location
                        print("location public is \(location?.locationIsPublic ?? false)")
                        print("location name is \(location?.locationName ?? "blah")")
                    }
                }
            } else {
            }
        }
    }
}

```

**Comment by LilMoke** [comment]
Yes, that works ok, it was not exactly what i was thinking of how it would work, but i understand much better about parse usage, thank you.
