### ISSUE TITLE
User authentication after an iCloud restore on a new device

### ISSUE THREAD

**Issue by Muesly** [parse-community/Parse-SDK-iOS-OSX#1291]
I am seeing that when a user upgrades their iPhone and restores their data via iCloud, the app reacts as if the PFUser details are not copied across.  If this because they are in the keychain, what is the strategy to handle this?

Do we have to ask users to login again?

**Comment by flovilmart** [comment]
I believe Data stored in the keychain should be preserved. Do you have any documentation on that and if Apple provides anything in their SDKs

**Comment by Muesly** [comment]
Thanks for the quick response.

I can see mention of kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly in PFKeychainStore.m

According to this: https://developer.apple.com/documentation/security/ksecattraccessiblealwaysthisdeviceonly

"This is not recommended for application use. Items with this attribute do not migrate to a new device. Thus, after restoring from a backup of a different device, these items will not be present."

**Comment by Muesly** [comment]
I'll try and look into doing this next week.

**Comment by flovilmart** [comment]
Thanks!

**Comment by Muesly** [comment]
I had a quick look and running on an existing session results in a blank session token, so the keychain would have to be migrated in some way.  Not so simple as changing the setting value!  Maybe this also needs to be a configuration setting in case other users have different requirements?

**Comment by flovilmart** [comment]
I believe that if the migration can be safely executed, tested and is robust, we can update the behavior, given the only visible change for the user is this issue being fixed ;)

**Comment by flovilmart** [comment]
@Muesly I'm closing as it's been merged, can you report if everything is working as expected?
