### ISSUE TITLE
PFCloud.callFunction will not time out. 

### ISSUE THREAD

**Issue by yingmu52** [parse-community/Parse-SDK-iOS-OSX#1293]
we have a cloud code function that does not call either `response.success()` or `response.error()`. and I found `PFCloud.callFunction(inBackground` kept running forever. and did not time out after some time (i.e 30 seconds). Is there a way to manually timeout `PFCloud.callFunction` ??

**Comment by flovilmart** [comment]
You need to call response.error after a certain amount of time or response.success. If the expected behaviour is to run forever, you should call response.success as soon as possible, the execution won’t be stopped.
