### ISSUE TITLE
Crash when pinning

### ISSUE THREAD

**Issue by tahoecoop** [parse-community/Parse-SDK-iOS-OSX#1295]
Hello! I'm seeing a weird crash having to do with pinning.  I'm querying for an object with an array of child objects using includeKey on the query. However, when I try to pin those child objects, I'm getting a crash as seen below. I am not pinning the parent object at all, just the child objects (if they exist). Also I was checking to see if any Zombies and I'm getting ``` *** -[__NSSingleObjectArrayI retain]: message sent to deallocated instance ....``` I've included the stack trace as well, any insight you have is greatly appreciated. Thanks a lot!! 

![screen shot 2018-04-19 at 11 44 10 am](https://user-images.githubusercontent.com/12720941/39011863-8793daf6-43c7-11e8-8e7b-adf464096824.png)

* thread #8, queue = 'PFSQLiteDatabase.synchronizationQueue', stop reason = EXC_BREAKPOINT (code=1, subcode=0x184b74500)
    frame #0: 0x0000000184b74500 CoreFoundation`___forwarding___ + 1180
    frame #1: 0x0000000184a5a41c CoreFoundation`_CF_forwarding_prep_0 + 92
  * frame #2: 0x00000001032c0638 Parse`__68-[PFPinningObjectStore pinObjectsAsync:withPinName:includeChildren:]_block_invoke(.block_descriptor=0x00000001c0a72280, task=0x00000001c0a72140) at PFPinningObjectStore.m:97
    frame #3: 0x0000000102ed7da8 Bolts`__62-[BFTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke(.block_descriptor=0x00000001c0a57e50, task=0x00000001c0a72140) at BFTask.m:398
    frame #4: 0x0000000102ed729c Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke(.block_descriptor=0x00000001c0a72240) at BFTask.m:331
    frame #5: 0x0000000102ed2fac Bolts`__29+[BFExecutor defaultExecutor]_block_invoke_2(.block_descriptor=0x0000000102ee4598, block=0x0000000102ed7230) at BFExecutor.m:65
    frame #6: 0x0000000102ed39dc Bolts`-[BFExecutor execute:](self=0x00000001c401ce90, _cmd="execute:", block=0x0000000102ed7230) at BFExecutor.m:131
    frame #7: 0x0000000102ed7858 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke.126(.block_descriptor=0x00000001c0a57e80) at BFTask.m:363
    frame #8: 0x0000000102ed6ce8 Bolts`-[BFTask runContinuations](self=0x00000001c0a72140, _cmd="runContinuations") at BFTask.m:307
    frame #9: 0x0000000102ed658c Bolts`-[BFTask trySetResult:](self=0x00000001c0a72140, _cmd="trySetResult:", result=0x00000001c04aa380) at BFTask.m:247
    frame #10: 0x0000000102ed89b0 Bolts`-[BFTaskCompletionSource setResult:](self=0x00000001c0205930, _cmd="setResult:", result=0x00000001c04aa380) at BFTaskCompletionSource.m:45
    frame #11: 0x0000000102ed75e4 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2(.block_descriptor=0x00000001c484b580, task=0x00000001c4a6ef80) at BFTask.m:340
    frame #12: 0x0000000102ed729c Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke(.block_descriptor=0x00000001c4a6f300) at BFTask.m:331
    frame #13: 0x0000000102ed2fac Bolts`__29+[BFExecutor defaultExecutor]_block_invoke_2(.block_descriptor=0x0000000102ee4598, block=0x0000000102ed7230) at BFExecutor.m:65
    frame #14: 0x0000000102ed39dc Bolts`-[BFExecutor execute:](self=0x00000001c401ce90, _cmd="execute:", block=0x0000000102ed7230) at BFExecutor.m:131
    frame #15: 0x0000000102ed7858 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke.126(.block_descriptor=0x00000001c4a50950) at BFTask.m:363
    frame #16: 0x0000000102ed6ce8 Bolts`-[BFTask runContinuations](self=0x00000001c4a6ef80, _cmd="runContinuations") at BFTask.m:307
    frame #17: 0x0000000102ed658c Bolts`-[BFTask trySetResult:](self=0x00000001c4a6ef80, _cmd="trySetResult:", result=0x00000001c04aa380) at BFTask.m:247
    frame #18: 0x0000000102ed89b0 Bolts`-[BFTaskCompletionSource setResult:](self=0x00000001c42038a0, _cmd="setResult:", result=0x00000001c04aa380) at BFTaskCompletionSource.m:45
    frame #19: 0x0000000102ed75e4 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2(.block_descriptor=0x00000001c4a50890, task=0x00000001c4a6f200) at BFTask.m:340
    frame #20: 0x0000000102ed729c Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke(.block_descriptor=0x00000001c4a6f2c0) at BFTask.m:331
    frame #21: 0x0000000102ed2fac Bolts`__29+[BFExecutor defaultExecutor]_block_invoke_2(.block_descriptor=0x0000000102ee4598, block=0x0000000102ed7230) at BFExecutor.m:65
    frame #22: 0x0000000102ed39dc Bolts`-[BFExecutor execute:](self=0x00000001c401ce90, _cmd="execute:", block=0x0000000102ed7230) at BFExecutor.m:131
    frame #23: 0x0000000102ed7858 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke.126(.block_descriptor=0x00000001c4a508f0) at BFTask.m:363
    frame #24: 0x0000000102ed6ce8 Bolts`-[BFTask runContinuations](self=0x00000001c4a6f200, _cmd="runContinuations") at BFTask.m:307
    frame #25: 0x0000000102ed658c Bolts`-[BFTask trySetResult:](self=0x00000001c4a6f200, _cmd="trySetResult:", result=0x00000001c04aa380) at BFTask.m:247
    frame #26: 0x0000000102ed89b0 Bolts`-[BFTaskCompletionSource setResult:](self=0x00000001c4206d40, _cmd="setResult:", result=0x00000001c04aa380) at BFTaskCompletionSource.m:45
    frame #27: 0x0000000102ed745c Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke(.block_descriptor=0x00000001c4a6f240) at BFTask.m:354
    frame #28: 0x0000000102ed2fac Bolts`__29+[BFExecutor defaultExecutor]_block_invoke_2(.block_descriptor=0x0000000102ee4598, block=0x0000000102ed7230) at BFExecutor.m:65
    frame #29: 0x0000000102ed39dc Bolts`-[BFExecutor execute:](self=0x00000001c401ce90, _cmd="execute:", block=0x0000000102ed7230) at BFExecutor.m:131
    frame #30: 0x0000000102ed7858 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke.126(.block_descriptor=0x00000001c4a50860) at BFTask.m:363
    frame #31: 0x0000000102ed6ce8 Bolts`-[BFTask runContinuations](self=0x00000001c4a6f180, _cmd="runContinuations") at BFTask.m:307
    frame #32: 0x0000000102ed658c Bolts`-[BFTask trySetResult:](self=0x00000001c4a6f180, _cmd="trySetResult:", result=@"1 element") at BFTask.m:247
    frame #33: 0x0000000102ed89b0 Bolts`-[BFTaskCompletionSource setResult:](self=0x00000001c4206d10, _cmd="setResult:", result=@"1 element") at BFTaskCompletionSource.m:45
    frame #34: 0x0000000102ed75e4 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2(.block_descriptor=0x00000001c0a59050, task=0x00000001c4a6fbc0) at BFTask.m:340
    frame #35: 0x0000000102ed73b0 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke(.block_descriptor=0x00000001c4a6f1c0) at BFTask.m:348
    frame #36: 0x0000000102ed2fac Bolts`__29+[BFExecutor defaultExecutor]_block_invoke_2(.block_descriptor=0x0000000102ee4598, block=0x0000000102ed7230) at BFExecutor.m:65
    frame #37: 0x0000000102ed39dc Bolts`-[BFExecutor execute:](self=0x00000001c401ce90, _cmd="execute:", block=0x0000000102ed7230) at BFExecutor.m:131
    frame #38: 0x0000000102ed7858 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke.126(.block_descriptor=0x00000001c4a507a0) at BFTask.m:363
    frame #39: 0x0000000102ed6ce8 Bolts`-[BFTask runContinuations](self=0x00000001c4a6f100, _cmd="runContinuations") at BFTask.m:307
    frame #40: 0x0000000102ed658c Bolts`-[BFTask trySetResult:](self=0x00000001c4a6f100, _cmd="trySetResult:", result=0x0000000000000000) at BFTask.m:247
    frame #41: 0x0000000102ed89b0 Bolts`-[BFTaskCompletionSource setResult:](self=0x00000001c4203680, _cmd="setResult:", result=0x0000000000000000) at BFTaskCompletionSource.m:45
    frame #42: 0x0000000102ed75e4 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2(.block_descriptor=0x00000001c4a512e0, task=0x00000001c4a6fe40) at BFTask.m:340
    frame #43: 0x0000000102ed729c Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke(.block_descriptor=0x00000001c4a6ff00) at BFTask.m:331
    frame #44: 0x0000000102ed2fac Bolts`__29+[BFExecutor defaultExecutor]_block_invoke_2(.block_descriptor=0x0000000102ee4598, block=0x0000000102ed7230) at BFExecutor.m:65
    frame #45: 0x0000000102ed39dc Bolts`-[BFExecutor execute:](self=0x00000001c401ce90, _cmd="execute:", block=0x0000000102ed7230) at BFExecutor.m:131
    frame #46: 0x0000000102ed7858 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke.126(.block_descriptor=0x00000001c4a51340) at BFTask.m:363
    frame #47: 0x0000000102ed6ce8 Bolts`-[BFTask runContinuations](self=0x00000001c4a6fe40, _cmd="runContinuations") at BFTask.m:307
    frame #48: 0x0000000102ed658c Bolts`-[BFTask trySetResult:](self=0x00000001c4a6fe40, _cmd="trySetResult:", result=0x0000000000000000) at BFTask.m:247
    frame #49: 0x0000000102ed89b0 Bolts`-[BFTaskCompletionSource setResult:](self=0x00000001c4206ff0, _cmd="setResult:", result=0x0000000000000000) at BFTaskCompletionSource.m:45
    frame #50: 0x0000000102ed75e4 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2(.block_descriptor=0x00000001c4a57880, task=0x00000001c4a74140) at BFTask.m:340
    frame #51: 0x0000000102ed729c Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke(.block_descriptor=0x00000001c4a74200) at BFTask.m:331
    frame #52: 0x0000000102ed2fac Bolts`__29+[BFExecutor defaultExecutor]_block_invoke_2(.block_descriptor=0x0000000102ee4598, block=0x0000000102ed7230) at BFExecutor.m:65
    frame #53: 0x0000000102ed39dc Bolts`-[BFExecutor execute:](self=0x00000001c401ce90, _cmd="execute:", block=0x0000000102ed7230) at BFExecutor.m:131
    frame #54: 0x0000000102ed7858 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke.126(.block_descriptor=0x00000001c4a578e0) at BFTask.m:363
    frame #55: 0x0000000102ed6ce8 Bolts`-[BFTask runContinuations](self=0x00000001c4a74140, _cmd="runContinuations") at BFTask.m:307
    frame #56: 0x0000000102ed658c Bolts`-[BFTask trySetResult:](self=0x00000001c4a74140, _cmd="trySetResult:", result=0x0000000000000000) at BFTask.m:247
    frame #57: 0x0000000102ed89b0 Bolts`-[BFTaskCompletionSource setResult:](self=0x00000001c42092a0, _cmd="setResult:", result=0x0000000000000000) at BFTaskCompletionSource.m:45
    frame #58: 0x0000000102ed75e4 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2(.block_descriptor=0x00000001c0846c90, task=0x00000001c4a6f500) at BFTask.m:340
    frame #59: 0x0000000102ed73b0 Bolts`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke(.block_descriptor=0x00000001c4a74180) at BFTask.m:348
    frame #60: 0x0000000104001220 libdispatch.dylib`_dispatch_client_callout + 16
    frame #61: 0x0000000104013e24 libdispatch.dylib`_dispatch_sync_invoke_and_complete_recurse + 124
    frame #62: 0x0000000104013848 libdispatch.dylib`_dispatch_sync_wait + 552
    frame #63: 0x000000010330f288 Parse`PFThreadsafetySafeDispatchSync(queue=0x00000001c435dfe0, block=0x0000000102ed7230) at PFThreadsafety.m:31
    frame #64: 0x0000000103306208 Parse`__33-[PFSQLiteDatabase initWithPath:]_block_invoke_2(.block_descriptor=0x00000001c4a57850) at PFSQLiteDatabase.m:78
    frame #65: 0x0000000104001260 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #66: 0x0000000104001220 libdispatch.dylib`_dispatch_client_callout + 16
    frame #67: 0x000000010400d284 libdispatch.dylib`_dispatch_queue_override_invoke + 968
    frame #68: 0x000000010401284c libdispatch.dylib`_dispatch_root_queue_drain + 604
    frame #69: 0x0000000104012584 libdispatch.dylib`_dispatch_worker_thread3 + 136
    frame #70: 0x0000000184793fac libsystem_pthread.dylib`_pthread_wqthread + 1176
    frame #71: 0x0000000184793b08 libsystem_pthread.dylib`start_wqthread + 4

**Comment by tahoecoop** [comment]
I went through everything a little more. It seems that the array of the child objects that I am pinning is there at the beginning of the method I posted screenshot of above. However once it gets into the return block, that array was deallocated for some reason. Have you seen this behavior at all or is it something that I am doing? Thanks!

**Comment by flovilmart** [comment]
@tahoecoop why did you close it? Any workaround?

**Comment by tahoecoop** [comment]
No real solution, I just extricated that part of the query out as well as the pinning and my functionality is working properly. I'm not sure if this is a bug in the framework, or that I have too many child objects being referenced that the local datastore doesn't like. Not sure what that array of objects being pinned is empty. I can re-open the issue if you'd like for visibility.

**Comment by flovilmart** [comment]
I’m not sure either, i’ll Reopen if I find anything
