### ISSUE TITLE
Unable to install Pod subspecs in single targets

### ISSUE THREAD

**Issue by tealshift** [parse-community/Parse-SDK-iOS-OSX#1296]
**Situation:**
Simple iOS app with iMessage extension. (2 targets)
Both targets use Parse Core, but FacebookUtils is needed only in the main app.

**Podfile:**
```
platform :ios, '11.0'
use_frameworks!
target 'MyApp' do
    pod 'Parse/UI'
    pod 'Parse/FacebookUtils'
end
target 'MyApp iMessage' do
    pod 'Parse/Core'
end
```
**Problem:**
When the pods are installed, cocoapods cannot seem to link the source files in FacebookUtils with the main app, causing a crash on launch.

**Hint:**
When adding `pod 'Parse/FacebookUtils'` to the iMessage target, the files are linked correctly to both targets. This is both sub-optimal _and problematic_ because FacebookUtils is not fully compatible with extensions since it references UIApplication.

**Possible solutions:**
- Make FacebookUtils extension-friendly?
- Raise issue with Cocoapods community?
- Find circumvention with Cocoapods install process?

**Comment by flovilmart** [comment]
Can you provide the crash on startup logs as well as an example project if possible?

**Comment by tealshift** [comment]
Sure thing!
```
dyld: Symbol not found: _OBJC_CLASS_$_PFFacebookUtils
  Referenced from: .../Developer/CoreSimulator/Devices/934B4A5B-E376-451A-9DF3-F4EDF4FC2750/data/Containers/Bundle/Application/37009285-989A-4E47-8B29-A4857C52BE2E/ParseTest.app/ParseTest
  Expected in: .../Developer/CoreSimulator/Devices/934B4A5B-E376-451A-9DF3-F4EDF4FC2750/data/Containers/Bundle/Application/37009285-989A-4E47-8B29-A4857C52BE2E/ParseTest.app/Frameworks/Parse.framework/Parse
 in .../Library/Developer/CoreSimulator/Devices/934B4A5B-E376-451A-9DF3-F4EDF4FC2750/data/Containers/Bundle/Application/37009285-989A-4E47-8B29-A4857C52BE2E/ParseTest.app/ParseTest
(lldb) 
```
Example project: https://www.dropbox.com/s/78ssvq8gjpbfh6y/ParseTest.zip?dl=0

**Comment by nebitrams** [comment]
@flovilmart Does Parse still provide Parse-SDK-iOS-OSX releases in the format of downloadable Parse-iOS.zip?  I wish to upgrade to 1.17.1 but could not find the zip file.

**Comment by flovilmart** [comment]
@nebitrams I just uploaded them back, there was an issue on travis for the ipload step.

**Comment by nebitrams** [comment]
Thanks.  I upgraded Parse-iOS SDK to 1.17.1 and it is working fine.
