### ISSUE TITLE
Invalid class name. Class names cannot start with an underscore.

### ISSUE THREAD

**Issue by MrSMAK** [parse-community/Parse-SDK-iOS-OSX#1297]
I have created a Custom Class with a pointer to the User Class. I am getting the following assert exception for the referenced user pointer. Since the "User" pointer's class name is "_User".

https://ibb.co/jp5aJc

**Comment by flovilmart** [comment]
Can you share your code please?

**Comment by MrSMAK** [comment]
Sure!
I am using the following code:

let parseObject = PFObject.init(className: "MY_CLASS_NAME")
let userTypePointer = PFObject.init(withoutDataWithClassName:  PFUser.parseClassName(), objectId: "MY_USER_OBJ_ID")
//Code is throwing exception on the above line of code.
parseObject["user"] = userTypePointer
parseObject.saveInBackground(block: { (isSuccessful: Bool, error: Error?) in
        if isSuccessful && error == nil {
             log.verbose("MY_CLASS_NAME saved successfully!")
        }
})

**Comment by flovilmart** [comment]
if you use:

```
let userPointer = PFUser()
userPointer.objectId = "MY_USER_OBJ_ID"
```

does it work?

**Comment by MrSMAK** [comment]
It works like a charm!, Thanks a lot!
