### ISSUE TITLE
[Idea] Register cloud functions

### ISSUE THREAD

**Issue by JacobJT** [parse-community/Parse-SDK-iOS-OSX#1305]
I have run into network retry issues. I have several cloud functions that should NOT have retry attempts made. But, I don't want to set the retryLimit to 0, as we also have a lot of users heading to remote areas and needing to upload photos, so we don't want temporary network disconnections to cause issues either.

I was thinking, similar to how we can register subclasses, it would be awesome to be able to register cloud functions.  We could pass in a configuration object that will allow us to add timeout and retry policies on a function by function basis.  Additionally, we could provide actual method signatures for our cloud functions, rather than using a dictionary of parameters without strong enforcements. 

I did a search to see if this had been discussed elsewhere and could not find it. I'd be interested in contributing to this effort if there was a discussion about what it should look like, what features it should include.  And, if there's any glaringly obvious issues that has prevented it from happening before, I'd love to hear what they are, as i did not see them.

**Comment by flovilmart** [comment]
@JacobJT is it a feature you'd like to get working on?

**Comment by flovilmart** [comment]
I’m in favor of adding per call options, seems more flexible

**Comment by JacobJT** [comment]
Cool. I'll dive in and see how the retry limit is currently implemented, and see if it looks like there's a way to override it, or if I'll have to modify that implementation in order for the options to work.

Do you know of any other options that may be worth adding at this time, or should we leave it as the number of retries for now?

I suppose the passed in parameter validation could be done here if we wanted. Have an option that takes an array of strings that each need to be a key of the parameters dictionary. We only do this validation if the option has a value.

I suppose this does seem a bit unnecessary. I would use it, but I could also implement it in a different way myself. The retry limit option would allow functionality that isn't available in any other manner with the SDK at this time.

**Comment by flovilmart** [comment]
My motto is Keep It Stupid Simple, You Ain’t Gonna Need It... so let’s deliver one thing perfectly before we start thinking of more options a to provide
