### ISSUE TITLE
PFObject.deleteAll crashes?

### ISSUE THREAD

**Issue by sambing** [parse-community/Parse-SDK-iOS-OSX#1307]
Hello this may just be me, however refrencing some Stackoverflow questions and answers seems that the following code should work correctly? 

```
let query = PFQuery(className: "Messages")

 query.findObjectsInBackground { (objects, error) in
       
            if error == nil {
                
                guard let objects = objects else { print("no objects found"); return}

                    PFObject.deleteAll(inBackground: objects, block: { (success, error) in
                        
                        if error == nil {
                            
                            if success {
                                
                                print("all objects deleted")
                                
                            }
                            
                        } else {
                            
                            print("error deleting objects")
                            
                        }
                        
                    })
                    
            } else {
                
             print(error)
                
            }
            
        }
```
The error i'm getting is 
`attempt to insert nil object from objects[1]'`

What am i missing? 

Attached the Stack trace below.

[Trace.txt](https://github.com/parse-community/Parse-SDK-iOS-OSX/files/2084560/Trace.txt)

**Comment by flovilmart** [comment]
Stacktrace please?

**Comment by sambing** [comment]
@flovilmart Attached the trace, thanks for taking a look.

**Comment by flovilmart** [comment]
Also, the push configuration is the first link on the first line of the README of this repository.

**Comment by sambing** [comment]
@flovilmart how is that related?

**Comment by flovilmart** [comment]
Wrong thread sorry.

**Comment by sambing** [comment]
@flovilmart did you have a chance to take a look, is there anything i'm missing or is there a bug? The custom class is a sample one with some 20 dummy rows and a couple of custom columns including a pointer to the user class. I still can't get it to work.

**Comment by flovilmart** [comment]
No I haven’t had a chance to look at it nor reproduce it. You can very well spend some time trying to identify what is nil and causing the issue. If you have issues with debugging, the advanced debugging talk from WWDC is a must watch:

https://developer.apple.com/videos/play/wwdc2018/412/

**Comment by sambing** [comment]
@flovilmart i recall that it worked in the past, however i wasn't able to get to the root of the cause. However since i would be using cloud code anyhow for that functionality i simply implemented it and it works as expected. I'll take a look further, and thank you.
