### ISSUE TITLE
ParseUI in 1.17.1 not supporting bitcode?

### ISSUE THREAD

**Issue by nebitrams** [parse-community/Parse-SDK-iOS-OSX#1314]
I had upgraded Parse-SDK-iOS-OSX from 1.15.4 to 1.17.1.

When I try to run "archive" on Xcode, I hit this linking error.  Is ParseUI compiled with full bitcode?

ld: bitcode bundle could not be generated because '/Users/Xxx/Documents/Xcode/SportsChallenge/ParseUI.framework/ParseUI(PFLogInViewController.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

Xcode version 9.2
Parse-SDK-iOS-OSX: 1.17.1 (downloaded zipped file)

**Comment by flovilmart** [comment]
In order to support bitcode all the frameworks should be built with Bitcode support. You'll need to provide a custom configuration for al the build dependedncies. Also, are you building the static or dynamic version of this framework?

**Comment by nebitrams** [comment]
I wish to clarify on this.  Are you planning to rebuilt the 1.17.1 framework with bitcode support?  My project had bitcode support for Parse 1.15.4 framework and was working fine.

Regarding the static/dynamic, I would prefer dynamic version.

**Comment by flovilmart** [comment]
So you can build the projects. The only versions we provide are the static framework ones without bitcode.

**Comment by nebitrams** [comment]
@flovilmart, I don't mind static or dynamic library since I only release one App with Parse.  It won't make much difference for me.  Is it possible for parse to release iOS Library with bitcode support?  I think bitcode support is useful and also the previous version 1.15.4 does support bitcode.

**Comment by nebitrams** [comment]
@flovilmart,  Is it possible to support Parse iOS Library with bitcode support for future releases?

I don't mind static or dynamic library since I only release one iOS App with Parse framework. It won't make much difference for me.

I could built/archive my app before I upgraded to 1.17.1. When I upgrade to 1.17.1, I also dropped support for deployment target for iOS 8.1 (i.e. support from iOS 9 onwards). Could this be the reason for Xcode to perform bitcode check during archive process?

For now, I switch off bitcode support and can compile, link and archive successfully

**Comment by flovilmart** [comment]
It is not likely, as bitcode enabled builds will not suit other users that may not want bitcode.

**Comment by nebitrams** [comment]
bitcode offers app thinning and I don't see any disadvantage.  Also, I believe bitcode is backward compatible with non-bitcode.  Let me check on this and get confirm later.

**Comment by flovilmart** [comment]
@nebitrams I am well aware of the the advantages of bitcode, but to use it, ALL your dependencies have to be built with bitcode. And sometimes, is is not possible to do so.

**Comment by mman** [comment]
Bitcode is definitely backwards compatible and more over mandatory on watchOS and tvOS, IIRC becoming mandatory on iOS at some point in the future.

**Comment by flovilmart** [comment]
@nebitrams the projects are fully maintained by the community now.

The main issue I see with compiling static + bitcode, it’s that it just addresses your needs. Many people may want the dynamic + bitcode. Another part is using Carthage, and a majority uses cocoapods. If it was up to me, i’d remove the prebuilt frameworks as they only fit for a minority of users and cause a great deal of pain

**Comment by nebitrams** [comment]
@flovilmart Does switching to Cocoapods solve this?  I can switch to Cocoapods.

**Comment by flovilmart** [comment]
I believe it will work properly, you can use either the dynamic or static frameworks with Cocoapods and  you can toggle bitcode on / off depending on your needs : https://stackoverflow.com/questions/32640149/disable-bitcode-for-project-and-cocoapods-dependencies-with-xcode7

**Comment by nebitrams** [comment]
Thanks.  I will try to use Parse and ParseUI from cocoapods with ENABLE_BITCODE build setting.

**Comment by nebitrams** [comment]
I have successfully switched to using Parse and ParseUI 1.17.1 using cocoapods.  It supports bitcode well.  Thanks.
