### ISSUE TITLE
Method initialize defines Objective-C class method, which is not permitted by Swift

### ISSUE THREAD

**Issue by KingJammin** [parse-community/Parse-SDK-iOS-OSX#1318]
I'm having some troubles with initialize(), it's was working fine with Swift3 but we just converted to Swift4. The error is: Method 'initialize()' defines Objective-C class method 'initialize', which is not permitted by Swift. Any help or knowledge would be much appreciated.

import Foundation
import Parse

class HeartedVideo: PFObject, PFSubclassing {
    
    open override class func initialize() {
        super.initialize()
    }
}

**Comment by KingJammin** [comment]
@flovilmart any ideas?

**Comment by flovilmart** [comment]
those methods are deprecated in Swift 4. You can still do something similar but they won’t be called automatically IIRC. Note that in the latest version of the SDK, the PFSubclasses are automatically registered. So the need for those calls is likely not high.

**Comment by KingJammin** [comment]
So if the need to call Initialize isn't high then what is the preferred route? because we really aren't doing anything crazy in there.

**Comment by flovilmart** [comment]
What do you mean the prefered route? You can add any static method to your classes and call it in your app delegate. The behaviour changed in Swift 4 IIRC.
