### ISSUE TITLE
PFUser.current()?.object(forKey: "image") as! PFFile crashes when no image

### ISSUE THREAD

**Issue by marcesh** [parse-community/Parse-SDK-iOS-OSX#1319]
to retrieve a user image from the database i use

let image = PFUser.current()?.object(forKey: "image") as! PFFile
however there are circumstances when a user doesnt have an image in his profile
so it returns nil and crashes upon trying to unwrap. how can this be prevented?

**Comment by marcesh** [comment]
already solved. there seems to have been a problem with the userdate cached on the phone, as the image column has been added at a later state. reinstalling the app worked. if no image simply no image is displayed.

**Comment by flovilmart** [comment]
> it returns nil and crashes upon trying to unwrap

Use the guard / let pattern instead:

```
guard let image = PFUser.current()?.object(forKey: "image") as? PFFile else { return } 

// do something with the image
```
