### ISSUE TITLE
Graph API v2.6 getting deprecated

### ISSUE THREAD

**Issue by ashish-naik** [parse-community/Parse-SDK-iOS-OSX#1320]
Facebook says Graph API v2.6 will be deprecated on Jul 13, 2018. Please use the API Upgrade Tool to understand how this might impact your app."

Parse iOS SDK seems to be using 4.28.0 versions of FBSDKLoginKit and FBSDKCoreKit.

How to upgrade these frameworks for iOS ? 

i am using Cocoapods.

Thanks
Ashish

**Comment by flovilmart** [comment]
The master branch uses the 4.33 version of the SDK on iOS, 4.28 on tvOS as there's a bug in facebook's releases ;/ above this point (https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse.podspec#L117)

THe graph api v2.6 is for the remote endpoints, and I believe we're not affected.

**Comment by ashish-naik** [comment]
Yes I saw that line but when I update my pods, loginkit and corekit do not get upgraded. I have them in my podfile. 

I fetch some use info post authentication using graph API which may be the reason I am receiving the mail from Facebook. 

From your response, I think my issue is not with Parse iOS SDK but would you have any idea why my loginkit and corekit pods are not getting upgraded?

Thanks
Ashish

**Comment by flovilmart** [comment]
> fetch some use info post authentication using graph API which may be the reason I am receiving the mail from Facebook.

So this is the reason you have this email, the endpoint in your graph API is probably still pointing to an earlier version OR you’re fetching data that will not be available in the next versions of the API.

**Comment by ashish-naik** [comment]
so i am using ParseUI and using Facebook for login so my podfile has pod 'Parse/FacebookUtils'.

Would this be stopping cocoapods to update FBSDKCoreKit and FBSDKLoginKit to update to latest version?

I tried removing import FBSDKCoreKit and import FBSDKLoginKit to see whether i can make graph call using Parse FacebookUtils and it is working fine.
So i guess i need not have these two frameworks separately imported.

You mentioned below which i didn't understand. 

> THe graph api v2.6 is for the remote endpoints, and I believe we're not affected.

I am using below to get user details which seems to be the reason of Facebook asking me to upgrade API to 3.0.

`FBSDKGraphRequest(graphPath: "/me", parameters: ["fields" : "email, name, id, gender"])
                .start(completionHandler:  { (connection, result, error) in`

So i have to check whether Graph API v3.0 has different way to get these details.

**Comment by foobar8675** [comment]
I just noticed this message from facebook 
```
Your App, XXX, is currently accessing Graph API v2.7 which will reach the end of its 2-year 
lifetime on 05 October, 2018. We estimate 1 endpoint that XXX calls will be impacted by this change
and may stop working after the automatic upgrade push. To ensure a smooth transition, please
migrate all calls to Graph API v2.8 or higher. Use the API Upgrade Tool to understand exactly how this
change will impact your app.

Note: If you do not see any impacted calls in the API Upgrade Tool, your app/code may not be
affected by this upgrade.

Visit our changelog to see the full list of changes in all Graph API versions.` 
```
and wanted to know what version facebook graph api does the Parse-iOS-OSX sdk use?
