### ISSUE TITLE
Failed to request authorization token from Twitter

### ISSUE THREAD

**Issue by GokmenAkar** [parse-community/Parse-SDK-iOS-OSX#1322]
User can't log in the app with Twitter.  

The initialize settings in AppDelegate, 

`        PFTwitterUtils.initialize(withConsumerKey: "CorrectConsumerKey", consumerSecret: "CorrectSecretKey")
`

This is the simple login code; 
```
      PFTwitterUtils.logIn { (user, error) in
            if error != nil {
                print(error!.localizedDescription)
            } else {
                print(user)
            }
        }
```

And when I tap the login button, It throws authorization error:
 **"Failed to request authorization token from Twitter."**

It was working well before but not anymore.

What I have done so far, 

- [x] I updated the pods,
- [x] I regenerated the keys, 
- [x] I checked this issue: [https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1310](url)

But didn't work. 

I really need help with this issue, thank you. I can provide more information if needed.

**Comment by flovilmart** [comment]
Can you put a breakpoint there in this [file](https://github.com/parse-community/ParseTwitterUtils-iOS/blob/master/ParseTwitterUtils/PF_Twitter.m#L377) and provide the response string?

**Comment by GokmenAkar** [comment]
<?xml version="1.0" encoding="UTF-8"?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>

Is this what you looking for?

**Comment by flovilmart** [comment]
Yes can you try: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1310

**Comment by flovilmart** [comment]
@GokmenAkar I just checked on my side and the resolution in #1310 is correct and valid. I can effectively get valid access tokens when I add the callback URL to this provided value.

<img width="945" alt="capture d ecran le 2018-07-04 a 12 48 50" src="https://user-images.githubusercontent.com/364568/42288422-a007f318-7f88-11e8-987c-d8a99239f2b0.png">

**Comment by flovilmart** [comment]
Also documented here: http://docs.parseplatform.org/ios/guide/#setting-up-twitter

**Comment by flovilmart** [comment]
There is no / in the end of the one indicated

**Comment by GokmenAkar** [comment]
@flovilmart Thank you a lot! This problem solved thanks to you. But we have new one :) 

"Twitter auth is invalid for this user."

**Comment by GokmenAkar** [comment]
Solved! Thank you a lot!
