### ISSUE TITLE
Expected method to read dictionary element not found on object of type 'id<FBOpenGraphObject>' - error

### ISSUE THREAD

**Issue by gingerdudley** [parse-community/Parse-SDK-iOS-OSX#1324]
Hello- I am currently trying to link up my parse with facebook login using objective c. I just installed the   pod 'ParseFacebookUtils' and am now receiving this error upon building the app. I have not changed this file, so was wondering if i need to install an updated pod or something else. Thanks

<img width="1440" alt="screen shot 2018-07-20 at 5 17 37 pm" src="https://user-images.githubusercontent.com/35350591/43030069-090c660e-8c41-11e8-802a-27a89e843434.png">

**Comment by flovilmart** [comment]
You should use the pod ‘Parse/FacebookUtils’ instead

**Comment by gingerdudley** [comment]
thank you! i switched the pods and am now getting errors upon installatio
<img width="1440" alt="screen shot 2018-07-22 at 9 44 31 pm" src="https://user-images.githubusercontent.com/35350591/43057720-b328cfca-8df8-11e8-911a-8c99f61bc33d.png">
ns. Can't seem to find many answers about this online so i thought id post here[](url)

**Comment by zackshapiro** [comment]
@flovilmart how do I import `Parse/FacebookUtils` in an objc file?

**Comment by flovilmart** [comment]
You don,t need to import it, ti should be imported alongside the rest of the Parse SDK as it's a single pod now.
