### ISSUE TITLE
Missing dependency target "Bolts-iOS (from Bolts.xcodeproj)" 

### ISSUE THREAD

**Issue by greensmartdev** [parse-community/Parse-SDK-iOS-OSX#1326]
I am getting the warning 
Missing dependency target "Bolts-iOS (from Bolts.xcodeproj)"

when I drag the Parse.xcodeproj file into my project and try to build. I don't see the Bolts.xcodeproj file anywhere in the Parse-SDK-iOS-OSX-master folder. Help appreciated.

Background: 

I was able to successfully run my app on device in Xcode by dragging just the Parse, ParseUI and Bolts framework into my project WITHOUT dragging the Parse.xcodeproj into the project.

However I could not archive the project because I kept getting the invalid bitcode signature error, no matter if I set ENABLE_BITCODE to YES or NO, use "-fembed-bitcode" in Other C Flags and Other Linker Flags, add new user defined setting BITCODE-GENERATION_MODE and set that to "marker" for debug and "bitcode" for release, clean project, delete derived data, close Xcode and restart etc. Nothing worked.

So I am trying the new approach of removing the individual frameworks (Parse, ParseUI and Bolts), which obviously were not compiled with bitcode, and just dragging the Parse.xcodeproj file into my project, and try to set appropriate bitcode settings there, which leads me to the error I mentioned above.

**Comment by flovilmart** [comment]
The bolts project is distributed as a sub module. If you added the parse project as a sub module, your can get it with `git submodule update —init —recursive`

**Comment by greensmartdev** [comment]
Thanks. Running "git submodule update —init —recursive" as you suggested fixed that problem. The Bolts-iOS target is now being found, but the build now fails with the same old problem. "Invalid bitcode signature".

**Comment by flovilmart** [comment]
>  but the build now fails with the same old problem. "Invalid bitcode signature".

Try cleaning derived data folder etc... If it doesn't work, can you share a demo project with the issue?

**Comment by greensmartdev** [comment]
Thanks for your quick response, flovilmart! I have tried cleaning the derived data folder(basically deleting it each time and restarting Xcode before rebuilding) and all that I listed above. I will try again I guess. On a conceptual level, why would I be getting the "Invalid bitcode signature" linker error after I have disabled bitcode for the project and each individual sub project?

**Comment by flovilmart** [comment]
> why would I be getting the "Invalid bitcode signature" linker error after I have disabled bitcode

I'm not sure, without the project on hands it's impossible for me to have an idea of what's wrong.
Did you check this issue: https://stackoverflow.com/questions/43180258/bitcode-signature-failure-in-xcode

**Comment by greensmartdev** [comment]
Thanks. I saw that before. Now I implemented their suggestion of checking the deployment targets for all the targets in the project(Mine are all set to iOS 10.0). 

Now I am getting errors like:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PFQueryTableViewController", referenced from

"_OBJC_CLASS_$_PFTableViewCell", referenced from:

Am I missing another library or dependency?

**Comment by flovilmart** [comment]
Looks like you're missing ParseUI

**Comment by greensmartdev** [comment]
Thanks. I will add the ParseUI project and post an update.

**Comment by flovilmart** [comment]
But you should not need ParseUI if you don't require it, nor reference it.

parseUI is part of the ParseSDK.

Please share your project for future reference. The original issue being solved. I'm closing the issue.
