### ISSUE TITLE
Parse UI contains file reference paths to developer's user

### ISSUE THREAD

**Issue by JacobJT** [parse-community/Parse-SDK-iOS-OSX#1329]
>note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.

I realized while I had updated the Parse iOS framework I had neglected to update the ParseUI framework in ages. Did that, and am getting these warnings.

Note: The blocked out bits are `/User/<MyUser>/<ProjectPath>/`, for my own project.

<img width="1007" alt="screen shot 2018-08-07 at 16 41 35" src="https://user-images.githubusercontent.com/5605965/43801470-2f2f5804-9a61-11e8-8d5c-1bd680579c5c.png">

**Comment by flovilmart** [comment]
Ok, so it seems that the build scripts are not spitting out the right thing. Are you willing to open a Pr with the fix?

**Comment by JacobJT** [comment]
I'll take a look tonight and see if it's something I can spot. I've never built a framework locally via Xcode so it's new turf, will be poking in the dark. Let me know if you know where I should start looking.

**Comment by flovilmart** [comment]
Looks like it should be a build setting somewhere, but I dont know either :)

**Comment by JacobJT** [comment]
@flovilmart Looks like it's just changing a default value for `CLANG_ENABLE_MODULE_DEBUGGING`, which defaults to true. So, I'm putting together the PR with that, but I don't know how to build the module and test to ensure this fixes the issue. Do you know who is a little more familiar with this SDK that could drop some quick instructions?

https://stackoverflow.com/questions/36265490/turning-off-clang-enable-module-debugging-consequences

**Comment by flovilmart** [comment]
you can use `bundle exec rake package:frameworks` this will build all the modules at once (it takes some time)

**Comment by JacobJT** [comment]
As does the Carthage installation, it seems. Longest dev:test ratio of my life. I'll Open the PR once I've confirmed this works. Thanks.

**Comment by flovilmart** [comment]
That's one of the drawbacks of using a mono repo, in terms of maintenance however it's a breeze as we can test the integrity of the whole ecosystem at once. 

For the ruby based build, we should be able to update it to build a single traget.

For carthage, I highly recommend you pass `--platform iOS` if you only need iOS :)

**Comment by JacobJT** [comment]
Ahh I always forget about that until I get the build errors for platforms I don't have OS SDKs installed for.. Gotta alias out my carthage calls to add that. 

Seems I am running into an issue, though.
`LoadError: cannot load such file -- <My_Fork_Path>/Vendor/xctoolchain/Scripts/xctask/build_task`

From running `bundle exec rake package:frameworks`

My `/Scripts/` directory exists but is empty, missing both fo the specified scripts from `RakeFile`

**Comment by flovilmart** [comment]
Yeah, seems that you didn’t run all the commands to properly initialize the clone. Check above:

`git submodule update —init —recursive`

And the other commands to install the gem dependencies etc...

**Comment by JacobJT** [comment]
Oh I had my branch set up for this but hadn't tested the output to make sure I didn't some how screw anything up. Will do that today and get a PR up.
