### ISSUE TITLE
No documentation on how to use Parse/FacebookUtils

### ISSUE THREAD

**Issue by sunshineo** [parse-community/Parse-SDK-iOS-OSX#1341]
We have this warning: 
```
[!] ParseFacebookUtilsV4 has been deprecated in favor of Parse/FacebookUtils
```
So we switched to the Parse/FacebookUtils in our Podfile
But then we cannot figure out how to update our code.

https://docs.parseplatform.org/ios/guide/#facebook-users is still for ParseFacebookUtilsV4
We cannot even figure out how to import Parse/FacebookUtils in our objc file

![import](https://user-images.githubusercontent.com/1072766/44817419-4114de00-ab9a-11e8-81b4-132a75fa1700.jpg)
![usage](https://user-images.githubusercontent.com/1072766/44817422-43773800-ab9a-11e8-9af3-4c8347965639.jpg)

**Comment by flovilmart** [comment]
I'll point you to the README:

https://github.com/parse-community/Parse-SDK-iOS-OSX#cocoapods

**Comment by sunshineo** [comment]
The key seems to be 
```
#import <Parse/PFFacebookUtils.h>
```
Which is not in the README or the document. I'll try to create a couple PRs

**Comment by flovilmart** [comment]
DID YOU READ IT???


Note that in this case, the Parse framework will contain all headers and classes, so you just have to use:

```
import Parse
@import Parse;
```

**Comment by flovilmart** [comment]
Posting a screenshot as well just to be sure:

<img width="925" alt="capture d ecran le 2018-08-29 a 17 57 17" src="https://user-images.githubusercontent.com/364568/44817899-040a1500-abb5-11e8-917e-7545fe32ab5d.png">

**Comment by flovilmart** [comment]
Did you try before asking the question?

**Comment by flovilmart** [comment]
As for your second question, I presume you would already know the answer. So yes, the guide references an import statement that isn’t valid anymore if you’re using cocoapods, and only cocoapods. So it’s more yes and no than yes, it’s outdated. It’s still valid for all other package managers, as well as using the static libs.
