### ISSUE TITLE
[__NSDictionaryI UTF8String]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by AlessandroRiet** [parse-community/Parse-SDK-iOS-OSX#1342]
Parse usually works fine, but sometimes (it randomly started occurring), the app crashes with the error below and Xcode takes me to the code in the screenshot.

<img width="1382" alt="screen shot 2018-08-30 at 21 08 24" src="https://user-images.githubusercontent.com/25309184/44873573-e910d100-ac98-11e8-97c7-c3bb760318c9.png">

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryI UTF8String]: unrecognized selector sent to instance 0x1d0a6ae00'
*** First throw call stack:
(0x1846bad8c 0x1838745ec 0x1846c8098 0x1846c05c8 0x1845a641c 0x102a13814 0x10513919c 0x1051469bc 0x102a136dc 0x102a57618 0x102a8cd5c 0x102705fd8 0x10270532c 0x102700598 0x102700fd4 0x102705204 0x102705ee0 0x102706100 0x102a8c850 0x102705fd8 0x10270532c 0x102700598 0x102700fd4 0x102705a88 0x102704d64 0x102704418 0x102706c04 0x1027055d4 0x102700598 0x102700fd4 0x102705a88 0x102704d64 0x102704418 0x102706c04 0x102705808 0x102705528 0x10513919c 0x1051469bc 0x102add6d4 0x102ad5dcc 0x1051391dc 0x10513919c 0x105145200 0x10514a7c8 0x10514a500 0x1842dffac 0x1842dfb08)
libc++abi.dylib: terminating with uncaught exception of type NSException

I don't understand the cause of the error; the error is thrown as soon as I launch the application, and the only code that I call is that in the AppDelegate to load Parse.

Parse: 1.15.3
Bolts: 1.8.4
Swift: 4.0

**Comment by AlessandroRiet** [comment]
That shouldn't be the case, as I'm using the latest version of the SDK and I've been using it for quite a while now. Could it be related to the "pinAll inBackground" method?

**Comment by brianyyz** [comment]
It was a long shot :-)  Try stripping back one thing at a time to isolate would be my only suggestion.

**Comment by flovilmart** [comment]
This is a dangling pointer issue. The object at the address being sent the UTF8String message is being swapped out for an NSDictionary.

Those crashs are painful as it because of memory and race conditions.

First thing to do, is to find all callsites of the UTF8String

**Comment by flovilmart** [comment]
Then in your case, it’s perhaps some corrupted data inside your local datastore. If you’re able to identify which object sends a dictionary instead of a string, this may help

**Comment by AlessandroRiet** [comment]
I noticed that the app starts crashing after I call this code:

```
let query = PFQuery(className:"Splits")
        query.limit = 10000;
        query.whereKey("user", equalTo: PFUser.current()!)
        query.includeKey("transaction")
        query.includeKey("user")
        query.findObjectsInBackground { (objs: [PFObject]?, error: Error?) in
            if error == nil {
                 PFObject.saveAll(inBackground: objs)
...
```

Both "user" and "transaction" are pointers to another PFObject in another class. Many of the "user" are NULL. Could that be the case?

**Comment by flovilmart** [comment]
Did you put a breakpoint at the call site that crashs?
