### ISSUE TITLE
Parse Installation objectId is nil after saving.

### ISSUE THREAD

**Issue by Ukumar246** [parse-community/Parse-SDK-iOS-OSX#1346]
There is a bug on the server or the client SDK, why is the objectId null after saving it?

Inside of AppDelegate.swift:

        let install = PFInstallation.current()!;
        install["osVersion"] = "SIMULATOR";
        
        install.saveInBackground(block: { (saved, error) in
            guard error == nil else {  print(error); return; }
            let id = PFInstallation.current()!.objectId;
            assert(id != nil, "Install ID cannot be null after save!");   // CRASHES on this line, even though the object is getting saved on the server.
        })

**Comment by tealshift** [comment]
I've been seeing this too for a long time. I still don't know what to make of it. :(

**Comment by Ukumar246** [comment]
It doesn't happen on all installations, only on some. It might be something on how it's talking to mongo db

**Comment by Ukumar246** [comment]
I resolved this error - turns out you should never set ACL for installations, this is bc if the user logs out he/she cannot modify her installation data. Furthermore if you login with another account then you cannot modify your installation

**Comment by tealshift** [comment]
Great find!
Perhaps this can be addressed in the SDK by explicitly forbidding alterations to a PFInstallation ACL.

**Comment by Ukumar246** [comment]
Yea they should do that

**Comment by flovilmart** [comment]
I don’t believe this should be done in the SDK, as some people may rely on the current behavior. However, a new installation should be returned in this case.

**Comment by Ukumar246** [comment]
I agree, the SDK should just make a note about this and leave the behavior to the user

**Comment by Ukumar246** [comment]
@flovilmart a quick question - I wrote a script to iterate over all the user's installation and set it to Public Read+Write, and used beforeSave to force set the ACL as public RW. 

The issue is - Existing installations cannot fetch, save, or update themselves bc the SDK is missing PFInstallation.current().objectId. Is there any way to set the object manually (i.e. from a cloud code?)
Current users who have the app will have to **re-install** and get a fresh installation, looking to avoid this.

**Comment by Ukumar246** [comment]
Ok, thanks for your help. I love the Parse SDK & server, it has really come a long way since being closed source
