### ISSUE TITLE
Parse Compatibility With Xcode 10

### ISSUE THREAD

**Issue by fprospato** [parse-community/Parse-SDK-iOS-OSX#1347]
I just updated my Xcode to Xcode 10 and now my project will not run and I get the error:

```
ld: library not found for -lstdc++.6
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Xcode took out compatibility with lstdc++.6 in their simulators. I tried googling everywhere for the answer and came up with nothing. The only thing that seemed useful was a forum from 2015 where a user was asking the parse community to switch parse from lstdc++.6 to libc++., but they did not change it because they thought they still had time. But now it seems like we don’t. How should I go about fixing this?

**Comment by flovilmart** [comment]
I find it very odd as parse is not linked against libstdc++.

You project may be linked against it, but not the Parse SDK itself.

**Comment by duffek** [comment]
I've compiled on Xcode 10 without any issues so far.

**Comment by dplewis** [comment]
Just remove `libstdc++.6.tbd` from your project. You won't need it if you have `libstdc++.tbd` in your project. (I'm using build with legacy system)

If you really really need it you can copy it over from an Xcode 9 build
