### ISSUE TITLE
SDK fails to compile in Xcode 10

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-iOS-OSX#1348]
The SDK fails to compile in Xcode 10.

`ParseFacebookUtilsV4-iOS-Dynamic` fails to compile with carthage v0.30.1.

Here is the an extract of the carthage error log:

```
CopyStringsFile /<removed>/Carthage/Checkouts/Parse-SDK-iOS-OSX/ParseFacebookUtils
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding binary --outdir /<removed>/Carthage/Checkouts/Parse-SDK-iOS-OSX/ParseFacebookUtils/Resources/Localizable.strings
error: could not decode input file using specified encoding: Unicode (UTF-8), and the file contents appear to be encoded in Unicode (UTF-16)

** ARCHIVE FAILED **

The following commands produced analyzer issues:
	AnalyzeShallow /<removed>/Carthage/Checkouts/Parse-SDK-iOS-OSX/Parse/Parse/PFObject.m normal arm64
(1 command with analyzer issues)

The following build commands failed:
	CopyStringsFile /<removed>/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/Parse-SDK-iOS-OSX/1.17.1/Build/Intermediates.noindex/ArchiveIntermediates/ParseFacebookUtilsV4-iOS-Dynamic/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ParseFacebookUtilsV4.framework/Localizable.strings /<removed>/Carthage/Checkouts/Parse-SDK-iOS-OSX/ParseFacebookUtils/Resources/Localizable.strings
(1 failure)
```

**Comment by flovilmart** [comment]
Can you try the xcode10 branch? it's sill failing in CI but it should be OK.

**Comment by mtrezza** [comment]
I get another error:

```
The following build commands failed:
	Ld /<removed>/org.carthage.CarthageKit/DerivedData/10.0_10A255/Parse-SDK-iOS-OSX/81549b616674408b5303fe70c308051210a4532a/Build/Intermediates.noindex/ArchiveIntermediates/ParseFacebookUtilsV4-iOS-Dynamic/IntermediateBuildFilesPath/ParseFacebookUtils.build/Release-iphoneos/ParseFacebookUtilsV4-iOS-Dynamic.build/Objects-normal/armv7/ParseFacebookUtilsV4 normal armv7
(1 failure)
```

**Comment by flovilmart** [comment]
you can probably investigate on your own then.

**Comment by mtrezza** [comment]
Yes, building it in Xcode instead of carthage gives more details about the error:

```
Undefined symbols for architecture armv7:
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in Parse(PFUser.o)
      ___llvm_profile_runtime_user in Parse(Parse.o)
      ___llvm_profile_runtime_user in Parse(PFConstants.o)
      ___llvm_profile_runtime_user in Parse(PFAnonymousUtils.o)
      ___llvm_profile_runtime_user in Parse(PFApplication.o)
      ___llvm_profile_runtime_user in Parse(PFCategoryLoader.o)
      ___llvm_profile_runtime_user in Parse(PFErrorUtilities.o)
      <removed>
      ...
     (maybe you meant: ___llvm_profile_runtime_user)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The `ParseFacebookUtilsV4-iOS` build successfully, but `ParseFacebookUtilsV4-iOS-Dynamic` fails. It seems there has been the similar issue #1159 in the past; changing the value of `Enable Code Coverage Support` has no effect however, the build still fails.

**Comment by mtrezza** [comment]
`xcode10` branch building successfully now, commit 8f513ad054cc5ba910d7e1028d48b6515117cd08 solved the issue.

Thanks @flovilmart 👍

**Comment by cliftonlabrum** [comment]
I'm running into this. My `Cartfile` on Carthage `0.30.1` looks like this:

```
github "parse-community/Parse-SDK-iOS-OSX" "xcode10"
```

I'm building for **iOS and Mac** and this is the result:
```
*** Building scheme "FBSDKCoreKit-Universal" in FacebookSDK.xcworkspace
Build Failed
Task failed with exit code 65:
/usr/bin/xcrun xcodebuild 
  -workspace /.../facebook-ios-sdk/FacebookSDK.xcworkspace 
  -scheme FBSDKCoreKit-Universal 
  -configuration Release 
  -derivedDataPath /.../facebook-ios-sdk/sdk-version-4.36.0 
  -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive 
  -archivePath /var/folders/.../facebook-ios-sdk SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /.../facebook-ios-sdk)
```
Any idea what else I can try?

**Comment by flovilmart** [comment]
The Xcode10 branch is highly unstable and I don’t provide any support for it as it’s a work in progress. I can’t give a timeline on when it will be stable. In the meantime feel free to investigate.

**Comment by mtrezza** [comment]
@cliftonlabrum This is a known issue of the Facebook SDK. Downgrade to Carthage 0.29 and try again.

**Comment by mtrezza** [comment]
@cliftonlabrum I suggest you build in Xcode to get error details and take it from there.

**Comment by flovilmart** [comment]
It’s not merged to master and I’m pushing commits to it as the tests don’t pass on it... so do not use!

**Comment by cliftonlabrum** [comment]
@mtrezza I'll see if I can build it in Xcode and let you know. Can you successfully install Parse with Carthage in a test project that has a macOS target? I'm just wondering if it's my setup or if it's the framework.

**Comment by mtrezza** [comment]
I installed for iOS.

**Comment by cliftonlabrum** [comment]
@mtrezza Could you try installing it on a macOS target in a test project?

**Comment by mtrezza** [comment]
@cliftonlabrum What errer details did you get when copiling in Xcode?

**Comment by cliftonlabrum** [comment]
I'm happy to do that, but I'm not sure how. :) I followed the instructions in **Compiling for yourself** here: https://github.com/parse-community/Parse-SDK-iOS-OSX/tree/xcode10

But I'm unsure what to do next.

**Comment by mtrezza** [comment]
After compiling you should find the compiled macOS framework in Parse-macOS.zip

**Comment by cliftonlabrum** [comment]
Building on my own succeeded. I installed everything via Carthage, then just added `Parse.framework` from the `Parse-macOS.zip` file to my project and it works.

Thanks everyone! :)

**Comment by flovilmart** [comment]
Again, the Xcode 10 branch tests don’t pass...

**Comment by mtrezza** [comment]
Should stay open.

**Comment by mrmarcsmith** [comment]
I cloned the iOS/OSX project but I couldn’t find out how to run the OCMock tests. I also checked the OCMock website with no luck. I’ve never worked with OCMock, so any guidance would be appreciated.

**Comment by mman** [comment]
Just to update, I was able to successfully compile the iOS part of the SDK using the following Carthage setup:

```
$ cat Cartfile |grep Parse
github "parse-community/Parse-SDK-iOS-OSX"

$ carthage update --no-build
$ carthage build --cache-builds --platform iOS
```

**Comment by Samigos** [comment]
Is the SDK now compatible with Swift 4.2-5?

**Comment by noobs2ninjas** [comment]
@Samigos it is. Have you tried this recently? Has this issue been solved?

**Comment by Samigos** [comment]
> @Samigos it is. Have you tried this recently? Has this issue been solved?

Yep! Everything works!

**Comment by noobs2ninjas** [comment]
Perfect! Ill close the issue! Thanks
