### ISSUE TITLE
logInWithAuthTypeInBackground for Google fails

### ISSUE THREAD

**Issue by larceneaux** [parse-community/Parse-SDK-iOS-OSX#1349]
I'm attempting to authenticate users with Google sign in. I've created a simple authentication delegate but the Parse server continues to reject my request for sign up.

here's my code: 
in app delegate after configuring parse server  in didFinishLaunchingWithOptions i have 

`    [PFUser registerAuthenticationDelegate:[WLGGoogleAuth new] forAuthType:@"google"];
`
then the delegate return method that executes after google sign up is this
```
- (void)signIn:(GIDSignIn *)signIn didSignInForUser:(GIDGoogleUser *)user
     withError:(NSError *)error {
    NSString *userId = user.userID;                  // For client-side use only!
    NSString *idToken = user.authentication.idToken; // Safe to send to the server
    NSString *fullName = user.profile.name;
    NSString *givenName = user.profile.givenName;
    NSString *familyName = user.profile.familyName;
    NSString *email = user.profile.email;
    
     [[PFUser logInWithAuthTypeInBackground:@"google"
                                  authData:@{@"id": userId, @"accesstoken" : idToken}] continueWithSuccessBlock:^id(BFTask *task) {

        return nil;
    }];
}
```
here's the error returned from the method logInWithAuthTypeInBackground
`[Error]: {"code":1,"message":"Internal server error."} (Code: 1, Version: 1.15.4)
`
the task returned shows this:

`<BFTask: 0x600000fd0c40; completed = YES; cancelled = NO; faulted = YES; result = (null)>
`
so the task it's returning a PFUser, the authentication delegate i've made is very simple

```
#import <Foundation/Foundation.h>
#import <Parse/Parse.h>


@interface WLGGoogleAuth : NSObject <PFUserAuthenticationDelegate>

@end
```
and implementation file
```
#import "WLGGoogleAuth.h"

@implementation WLGGoogleAuth

- (BOOL)restoreAuthenticationWithAuthData:(nullable NSDictionary<NSString *,NSString *> *)authData {
    return true;
}

@end
```
I kept this as simple as possible to debug, but it's just not working, i'm not sure what i'm doing wrong here. any help would be greatly appreciated 

update: i tried this following the outline for the server Oauth insturcitons for parse and it doesn't work either
```
- (void)signIn:(GIDSignIn *)signIn didSignInForUser:(GIDGoogleUser *)user
     withError:(NSError *)error {
    NSString *userId = user.userID;                  // For client-side use only!
    NSString *idToken = user.authentication.idToken; // Safe to send to the server
    NSString *fullName = user.profile.name;
    NSString *givenName = user.profile.givenName;
    NSString *familyName = user.profile.familyName;
    NSString *email = user.profile.email;
    
    
    [[PFUser logInWithAuthTypeInBackground:@"google"
                                  authData:@{@"id": userId, @"id_token" : idToken, @"access_token" : user.authentication.accessToken}] continueWithSuccessBlock:^id(BFTask *task) {

        return nil;
    }];
}


```

and this gives the same error
```
- (void)signIn:(GIDSignIn *)signIn didSignInForUser:(GIDGoogleUser *)user
     withError:(NSError *)error {
    NSString *userId = user.userID;                  // For client-side use only!
    NSString *idToken = user.authentication.idToken; // Safe to send to the server
    NSString *fullName = user.profile.name;
    NSString *givenName = user.profile.givenName;
    NSString *familyName = user.profile.familyName;
    NSString *email = user.profile.email;
    
    
    [[PFUser logInWithAuthTypeInBackground:@"google"
                                  authData:@{@"id": user.userID, @"access_token" : user.authentication.accessToken}] continueWithSuccessBlock:^id(BFTask *task) {

        return nil;
    }];
}
```

**Comment by flovilmart** [comment]
What are the server logs? What is the result of attempting the same with the JS SDK?

**Comment by larceneaux** [comment]
@flovilmart 
here from the dashboard

> 2018-09-27T02:57:22.394Z - Uncaught internal server error. TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type undefined
>     at write_ (_http_outgoing.js:595:11)
>     at ClientRequest.write (_http_outgoing.js:567:10)
>     at Promise (/app/node_modules/parse-server/lib/Adapters/Auth/httpsRequest.js:36:9)
>     at new Promise (<anonymous>)
>     at new F (/app/node_modules/parse-server/node_modules/core-js/library/modules/_export.js:36:28)
>     at Object.request (/app/node_modules/parse-server/lib/Adapters/Auth/httpsRequest.js:33:10)
>     at googleRequest (/app/node_modules/parse-server/lib/Adapters/Auth/google.js:47:23)
>     at validateIdToken (/app/node_modules/parse-server/lib/Adapters/Auth/google.js:8:10)
>     at Object.validateAuthData (/app/node_modules/parse-server/lib/Adapters/Auth/google.js:28:12)
>     at /app/node_modules/parse-server/lib/Adapters/Auth/index.js:56:20 TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type undefined
>     at write_ (_http_outgoing.js:595:11)
>     at ClientRequest.write (_http_outgoing.js:567:10)
>     at Promise (/app/node_modules/parse-server/lib/Adapters/Auth/httpsRequest.js:36:9)
>     at new Promise (<anonymous>)
>     at new F (/app/node_modules/parse-server/node_modules/core-js/library/modules/_export.js:36:28)
>     at Object.request (/app/node_modules/parse-server/lib/Adapters/Auth/httpsRequest.js:33:10)
>     at googleRequest (/app/node_modules/parse-server/lib/Adapters/Auth/google.js:47:23)
>     at validateIdToken (/app/node_modules/parse-server/lib/Adapters/Auth/google.js:8:10)
>     at Object.validateAuthData (/app/node_modules/parse-server/lib/Adapters/Auth/google.js:28:12)
>     at /app/node_modules/parse-server/lib/Adapters/Auth/index.js:56:20
and then this

> 2018-09-27T02:57:22.382Z - REQUEST for [POST] /parse/users: {
>   "authData": {
>     "google": {
>       "id": "111926845491582427345",
>       "id_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImEwN2VjN2JkYThjY2M0Mzg1NTY1NWI5ZjIyNDVhNGUyZGUyMGFlNWMifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI4MTc5NDYxMDM5OTQta3NxanNjb2ltdm5nbmE2M3Z0MmRjdmNrMGZzcTlwZ2ouYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI4MTc5NDYxMDM5OTQta3NxanNjb2ltdm5nbmE2M3Z0MmRjdmNrMGZzcTlwZ2ouYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTE5MjY4NDU0OTE1ODI0MjczNDUiLCJlbWFpbCI6InRoYXRzYXByZXR0eWdvb2RpZGVhQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiY0Q0OXdHT0Q3eXNsNTZhSzVfblV5ZyIsImlhdCI6MTUzODAxNjg0MiwiZXhwIjoxNTM4MDIwNDQyfQ.OpiKeOV7iqj3eoL-QtPif-4s1vDbRkYzTGRXL0ijXT4Ej0KSRZlyLGoBkna3OqRBJTJJJzDlgw5gAaSiOBUW8_dPTEPsXoR5jnuoom07EufdSuRfBrs361P6oHkoE-A24wIhj2ElEvWMa3i7GKrdYdMRBNUcNwxoGHCGNkgMTeZsJdpFjo_KwC4U3CbZHXdM0UgnePb9qbY7sozRBY6p3g960hOXCwT2Na_syniu2DhG4cyR-TkEp8B0gsrcV3ByU75HSXWGECJI4ASS-ZSE4WzzYGjZUh_ztrssteVnxgh5yj3QpJIa3D5QZyvXz7hMMElupAdkKJ_G7ErdFcsocg"
>     }
>   }
> }
>

**Comment by flovilmart** [comment]
What version of the server are you running?

**Comment by flovilmart** [comment]
This is fixed by this commit: https://github.com/parse-community/parse-server/commit/c7357ed1095d5cbc2be2211ac3e483076bdeac6f

You can use master branch in the meantime or wait till next release.

**Comment by larceneaux** [comment]
@flovilmart thank you sir
