### ISSUE TITLE
Error trying to compile Parse-SDK-iOS-OSX with carthage

### ISSUE THREAD

**Issue by guidupas** [parse-community/Parse-SDK-iOS-OSX#1350]
I am trying to compile Parse-SDK-iOS-OSX using Carthage and I am getting this error:

> *** Building scheme "FBSDKCoreKit_TV-Dynamic" in FacebookSDK.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/guilhermedupas/Dropbox/Desenvolvimento/XCode/ProjetosXCode/GCDBarcodeReadAndSend/Carthage/Checkouts/facebook-ios-sdk/FacebookSDK.xcworkspace -scheme FBSDKCoreKit_TV-Dynamic -configuration Release -derivedDataPath /var/root/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/facebook-ios-sdk/sdk-version-4.37.0 -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/facebook-ios-sdk SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/guilhermedupas/Dropbox/Desenvolvimento/XCode/ProjetosXCode/GCDBarcodeReadAndSend/Carthage/Checkouts/facebook-ios-sdk)

>This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.QgkAVf.log

I tried using XCode 9 and XCode 10, Carthage 0.29 and Carthage 0.31

How could I solve this?

**Comment by flovilmart** [comment]
This is an issue with an upstream dependency, open on the Facebook SDK repo please

**Comment by guidupas** [comment]
> This is an issue with an upstream dependency, open on the Facebook SDK repo please

How do I open on the Facebook SDK repo?

**Comment by guidupas** [comment]
> This is an issue with an upstream dependency, open on the Facebook SDK repo please

Where can I do that? The repo inside Parse Community  (ParseFacebookUtils-iOS) is signed as [ARCHIVE] so I cannot open an issue there.

**Comment by flovilmart** [comment]
Ahah awesome! So I guess we need to revisit that

**Comment by flovilmart** [comment]
The failing SDK is the Facebook SDK. 
https://github.com/facebook/facebook-objc-sdk

**Comment by asielgil88** [comment]
is there any current solution or workaround for this?
