### ISSUE TITLE
No way to configure the sdk with master key?

### ISSUE THREAD

**Issue by gngeorgiev** [parse-community/Parse-SDK-iOS-OSX#1351]
Hi, from the docs and API reference I couldn't find a way to initialize the SDK with master key. Is this by design or I am missing something? For reference: https://parseplatform.org/Parse-SDK-iOS-OSX/api/Classes/ParseClientConfiguration.html#/c:objc(cs)ParseClientConfiguration(py)server

**Comment by dplewis** [comment]
https://stackoverflow.com/questions/51583711/parse-server-questionable-security-of-masterkey

This is by design. You MasterKey should be used server side only. If you use it client side, I could decrypt your app and obtain your MasterKey.

**Comment by gngeorgiev** [comment]
Yes, thank you. I am aware of the implications. Was wondering since the JS SDK supports it.

This can be closed.

**Comment by flovilmart** [comment]
The JS SDK supports it only in node environments
