### ISSUE TITLE
Keychain race condition

### ISSUE THREAD

**Issue by davbeck** [parse-community/Parse-SDK-iOS-OSX#1352]
We have been using the latest code on master in development and have run into an issue fetching an object at launch. It’s difficult to reproduce, but it seems to happen when upgrading from our last version to the one using master. We’ve traced it back to the sessionToken being nil (but the current user being valid) and think it might be a race condition in the keychain conversion that was recently introduced in ‘[PFKeychainStore _dataForKey:]’. Here’s what I think is happening:

1. Thread a fetches the new item and fails.
2. Thread b fetches the new item and fails.
3. Thread a fetches the old item and succeeds.
4. Thread a converts the old item into the new item.
5. Thread b fetches the old item, which has just been converted, and fails, assuming that the user is not logged in and returns nil.

Does that make sense? What would be the best approach to fixing this? I could just throw an ‘@sychronized(self)’ block around the method but I don’t see anything else in the codebase using that.

**Comment by flovilmart** [comment]
Thanks for reporting the issue.
The SDK doesn’t use `@synchonized(self)` to prevent concurrent access but serial queus. You should be able to find many examples of this pattern in the codebase and in the PFKeychainStore file.

**Comment by claesjacobsson** [comment]
I think I'm having problems related to this issue. Could you please have a look at my questions in #1418? Would be much appreciated :-)
