### ISSUE TITLE
Pass PFObject to cloud code

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-iOS-OSX#1354]
Currently I pass an objectId then query for the object in cloud code.

Is there something similar to `object.toJSON()` that converts to PFObject to dictionary? Or something we have to implement.

I’m currently getting  "caught an exception in the continuation block. This behavior is discouraged and will be removed in a future release. Caught Exception: PFObjects are not allowed here." 

https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/5bf27a2d173d822c8e8d955ca9f25efccd7c0787/Parse/Parse/PFEncoder.m#L142

Is there a reason for this?

**Comment by dplewis** [comment]
```
PFObject *object = [PFObject objectWithClassName:@"TestObject"];
    
NSDictionary *params = @{@"object" : object};
    
[PFCloud callFunctionInBackground:@"passInObject" withParameters:params block:^(id object, NSError *error) {
  ALog("Message: %@", object);
}];
```

**Comment by Tom-Fox1** [comment]
To remove the need for the query couldn't you use [`createWithoutData(id)` from the JavaScript SDK](https://parseplatform.org/Parse-SDK-JS/api/2.1.0/Parse.Object.html#.createWithoutData).

I haven't tried it but I assume it's the equivalent of `PFObject(withoutDataWithClassName: "Class", objectId: "objectId")` from the iOS SDK.

**Comment by Tom-Fox1** [comment]
I've tried it now and at least for my use case doing the following works:
```
var Orders = Parse.Object.extend("Orders");
var order = Orders.createWithoutData(objectId)
```
