### ISSUE TITLE
1.17.2 release?

### ISSUE THREAD

**Issue by benpackard** [parse-community/Parse-SDK-iOS-OSX#1358]
Would it be possible to get a new release with the changes on `master` since `1.17.1` in March? If not, is there some criteria for what qualifies for a new release? A Cocoapods release would be awesome too (not sure if that's automatic with a new release?).

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1372
