### ISSUE TITLE
Got error when install with Carthage

### ISSUE THREAD

**Issue by zhanswift** [parse-community/Parse-SDK-iOS-OSX#1363]
I got error when install Parse with carthage `carthage update --platform iOS --no-use-binaries`. I use Xcode 10

In terminal:

    *** Building scheme "ParseFacebookUtilsV4-iOS" in Parse.xcworkspace
        Build Failed

In console report:

	Task failed with exit code 65:
    fatal error: 'FBSDKCoreKit/FBSDKAccessToken.h' file not found
    #import <FBSDKCoreKit/FBSDKAccessToken.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by mtrezza** [comment]
The iOS SDK is not yet Xcode 10 compatible. Feel free to take a look at `xcode10` branch and see if you can give a hand. Related to #1348.

**Comment by mmuiz** [comment]
![screen shot 2018-11-04 at 3 32 20 pm](https://user-images.githubusercontent.com/19355715/47961946-f48cc980-e046-11e8-868e-86946cb66f71.png)
In my case the problem is generated in FacebookSDK.xcworkspace
I am using Xcode9.3 and Carthage 0.31.0

**Comment by drdaz** [comment]
> The iOS SDK is not yet Xcode 10 compatible. Feel free to take a look at `xcode10` branch and see if you can give a hand. Maybe related to #1348, #1350.

Where do you have this from? If this is true it needs to be displayed pretty prominently in the README.

I'd been using it without issue under Xcode 10 right up until I upgraded to Xcode 10.1. Then CocoaPods broke. I couldn't build using Carthage until I made the minor change in https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1359.

@zhanswift This looks like the same error. Maybe try applying the change in my PR.

**Comment by brianyyz** [comment]
Echo @drdaz - I'm having no issues on xCode 10.1 with CocoaPods.

**Comment by drdaz** [comment]
> Echo @drdaz - I'm having no issues on xCode 10.1 with CocoaPods.

With CocoaPods, really? Vanilla, release CocoaPods?

**Comment by brianyyz** [comment]
To be clear, I've got a Parse project that uses the following Podfile

```
platform :ios, '10.0'

target 'xxxxx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for xxxxx
    pod 'Parse', inhibit_warnings: true
    pod 'Parse/UI'
    pod 'Parse/FacebookUtils', inhibit_warnings: true
    pod 'ReachabilitySwift', '~> 4'

  target 'xxxxxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'xxxxxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
I have three different environment build configurations - Dev, QA, and Prod so I have to embed the generated .xcconfig file in my environment specific .xcconfig.

I am able to do pod update and build within xCode 10.1 with no issues.

Hope that helps - let me know if you want any more details.

**Comment by drdaz** [comment]
@brianyyz thanks so much for the info.

You know what? I confused myself... it's the iOS Live Query client that doesn't currently build from CocoaPods as-is. I added it as a dependency on the same day Xcode got updated. The Parse iOS SDK builds fine for me using CocoaPods. 

I experienced issues with other deps in other projects too that day, so I blamed it all on CocoaPods not playing nice with Xcode 10.1. Feeling this was the straw that finally broke the camels back, I tried recreating my deps using Carthage, only to run into the same issue with the iOS SDK as @zhanswift, which I proceeded to debug and fix.

It turned into a very long day.

**Comment by brianyyz** [comment]
@drdaz yw ! 

Another build related issue that I've run into has been the very large number of warnings in Parse and FBUtils

`Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior`

I've tried a couple of things but adding the following line to the podfile silences the warnings. Have you used this? Any side effects I should be aware of? 

`pod 'Parse', inhibit_warnings: true`
`pod 'Parse/FacebookUtils', inhibit_warnings: true`

**Comment by drdaz** [comment]
I've been using inhibit_warnings, yes. I think it just inhibits the warnings :)

The side effect is we don't see the warnings about the code in our project. That can almost certainly cause problems in the long run.

**Comment by Droppix** [comment]
Pb with Carthage (ParseFacebookUtilsV4-iOS): carthage update --platform iOS

-------------
CopyStringsFile /Users/XXXXX/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/Parse-SDK-iOS-OSX/1.17.1/Build/Intermediates.noindex/ArchiveIntermediates/ParseFacebookUtilsV4-iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ParseFacebookUtilsV4.framework/Localizable.strings /Users/XXXXX/Dev/VALAP/VALAP/Carthage/Checkouts/Parse-SDK-iOS-OSX/ParseFacebookUtils/Resources/Localizable.strings (in target: ParseFacebookUtilsV4-iOS)
    cd /Users/XXXXX/Dev/VALAP/VALAP/Carthage/Checkouts/Parse-SDK-iOS-OSX/ParseFacebookUtils
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding binary --outdir /Users/XXXXX/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/Parse-SDK-iOS-OSX/1.17.1/Build/Intermediates.noindex/ArchiveIntermediates/ParseFacebookUtilsV4-iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ParseFacebookUtilsV4.framework -- /Users/robertjuzyna/Dev/VALAP/VALAP/Carthage/Checkouts/Parse-SDK-iOS-OSX/ParseFacebookUtils/Resources/Localizable.strings
error: could not decode input file using specified encoding: Unicode (UTF-8), and the file contents appear to be encoded in Unicode (UTF-16)

** ARCHIVE FAILED **


The following commands produced analyzer issues:
	AnalyzeShallow /Users/XXXXX/Dev/VALAP/VALAP/Carthage/Checkouts/Parse-SDK-iOS-OSX/Parse/Parse/PFObject.m normal arm64
(1 command with analyzer issues)

The following build commands failed:
	CopyStringsFile /Users/XXXXX/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/Parse-SDK-iOS-OSX/1.17.1/Build/Intermediates.noindex/ArchiveIntermediates/ParseFacebookUtilsV4-iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ParseFacebookUtilsV4.framework/Localizable.strings /Users/XXXXX/Dev/VALAP/VALAP/Carthage/Checkouts/Parse-SDK-iOS-OSX/ParseFacebookUtils/Resources/Localizable.strings
(1 failure)

**Comment by drdaz** [comment]
@Droppix 
https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1359 fixes this.

**Comment by Droppix** [comment]
Ok, thanks.
