### ISSUE TITLE
Rename PFFileObject factory method to reflect the new class name

### ISSUE THREAD

**Issue by benpackard** [parse-community/Parse-SDK-iOS-OSX#1367]
>let imageFile = PFFileObject(name: "postImage.jpg", data: imageData)
>
>This resulted in an error: Argument passed to call that takes no arguments

Right now you can change your code to

`let imageFile = PFFileObject.file(withName: "postImage.jpg", data: imageData)`

I'll try to find some time to submit a new PR that solves this + update the changelog / migration guide.

_Originally posted by @Woildan in https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1325#issuecomment-433040044_

**Comment by benpackard** [comment]
Spinning this off into a separate issue since the original is fixed. The one place I have found `PFFileObject.file(withName: "postImage.jpg", data: imageData)` lacking is that it can't be used in a convenience initializer, e.g.:

```
convenience init?(image: UIImage, maxWidthAndHeight: CGFloat? = nil, jpegCompressionQuality: CGFloat = 1) {
...
// need to use `self.init(data: data, contentType: "image/jpeg")` here
...
}

**Comment by kennic** [comment]
I fixed the problem and made a PR here:
https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1368
