### ISSUE TITLE
Facebook login error, "The operation couldn’t be completed. (Com.facebook.sdk.core error 3.)"

### ISSUE THREAD

**Issue by seQVAER** [parse-community/Parse-SDK-iOS-OSX#1378]
I have a problem with FacebookUtils, when I login through the facebook 

PFFacebookUtils.logInInBackground(withReadPermissions: ["public_profile", "email"]) { (user, error) in

I get an error 
("The operation couldn’t be completed. (Com.facebook.sdk.core error 3.)")

How can I solve this problem?

pod versions
Parse (1.17.2)

FBSDKCoreKit (4.39.0)
FBSDKLoginKit (4.39.0)

**Comment by henriqueiv** [comment]
Apparently this is a bug on the `FBSDKCoreKit` and `FBSDKLoginKit` and the solution seems to be to downgrade to `4.38.0`. Any idea how to do it?

https://stackoverflow.com/questions/35248412/ios-facebook-login-error-unknown-error-building-url-com-facebook-sdk-core-e

**Comment by SSB95** [comment]
> Apparently this is a bug on the `FBSDKCoreKit` and `FBSDKLoginKit` and the solution seems to be to downgrade to `4.38.0`. Any idea how to do it?
> 
> https://stackoverflow.com/questions/35248412/ios-facebook-login-error-unknown-error-building-url-com-facebook-sdk-core-e
> 
> [facebook/facebook-objc-sdk@fe67bdb](https://github.com/facebook/facebook-objc-sdk/commit/fe67bdb3f72a2e69422b2f609bc871c1dba2005a)

Delete your Pods-Folder, the Podfile.lock and add the following Lines to your Podfile

`pod 'FBSDKCoreKit', '~> 4.38.0'`
`pod 'FBSDKLoginKit', '~> 4.38.0'`

**Comment by OlKir** [comment]
Issue is solved in version 4.39.1
Here is the tracker for it https://github.com/facebook/facebook-swift-sdk/issues/298
