### ISSUE TITLE
Anonymous data after updating from Apple Store

### ISSUE THREAD

**Issue by alecsechechel** [parse-community/Parse-SDK-iOS-OSX#1380]
Hi,

I have app, when user download app he started automatically as anonymous. He made photo and so on. All data keep in his account before he delete this app. But when realise new version I saw that all data deleted.

Is it possible save all data after update new version from Apple Store?

Thanks a lot!

**Comment by brianyyz** [comment]
If the user deleted the app and the subsequently reinstalled a newer version the installation id is going to be different. If you need to preserve access to user data on the server across a delete / reinstall I think you’ll need to create a user identity that they could log back in to. Keep in mind that the anonymous user doesn’t survive a logout either.

If the user just does an update in place then I think you should be ok.
