### ISSUE TITLE
PFObject.unpinAllObjectsInBackground(block:) doesn't work and corrupts the LocalDatastore

### ISSUE THREAD

**Issue by chriscborg** [parse-community/Parse-SDK-iOS-OSX#1389]
`PFObject.unpinAllObjectsInBackground(withName: block:)` works fine but I wanted to unpin all the objects from the local data store on log out or when importing new data. I tried doing this using `PFObject.unpinAllObjectsInBackground(block:)` method, but every time I did this the object is retained in the LocalDatastore and there is no way of deleting it afterwards. New data is saved on top of the previously pinned objects and there's no way on unpinning them after that even if I use `PFObject.unpinAllObjectsInBackground(withName: block:)`. Am I missing something or is this a bug?

**Comment by brianyyz** [comment]
Could you post your code?

**Comment by brianyyz** [comment]
In the first example you're not testing the success or error of the call to unpin. Does it always "succeed" or would you get some indication of a problem in the case you're trying to debug?

**Comment by chriscborg** [comment]
I'm going to build a test case for this as you suggested as soon as possible and post it here. Apologies for the wait
