### ISSUE TITLE
Unexpected CFBundleExecutable Key all of a sudden

### ISSUE THREAD

**Issue by acegreen** [parse-community/Parse-SDK-iOS-OSX#1392]
<img width="745" alt="screen shot 2019-02-22 at 10 06 21 am" src="https://user-images.githubusercontent.com/10794609/53250966-8a497480-3689-11e9-8638-450ba301719e.png">

According to StackOverflow, deleting the key and changing `CFBundlePackageType` to "BNDL" should fix the problem but it doesn't.

**Comment by acegreen** [comment]
Had to delete the bundles from the "Copy Bundle Resources" of Parse

<img width="953" alt="screen shot 2019-02-24 at 3 05 37 pm" src="https://user-images.githubusercontent.com/10794609/53304644-ad208800-3845-11e9-873a-472dabde6d2f.png">

**Comment by qunwang6** [comment]
same problem in Xcode 10.2 beta3

**Comment by jotterstrom02** [comment]
same problem in Version 10.2 beta 3 (10P99q)
