### ISSUE TITLE
Parse Configuration Reset

### ISSUE THREAD

**Issue by SaluBhayo** [parse-community/Parse-SDK-iOS-OSX#1393]
I would like to reset Parse Configuration in app delegate by calling app delegate function from a view controller. I am getting this error 

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Parse is already initialized.'

Is there anyway to remove previous configuration and reconfigure Parse

**Comment by Tom-Fox1** [comment]
This seems to be the same issue as #1390, if that is the case could you close this and follow the conversation in #1390.

**Comment by Tom-Fox1** [comment]
This discussion also exists in #1209 which has the most details.

**Comment by nebitrams** [comment]
Short answer is that it is **not** possible to re-initialize.  I have a work around that requires closing app and restart.  See #1390.

**Comment by SaluBhayo** [comment]
@nebitrams yeah bro that's only solution is available to restart app...:(

**Comment by Tom-Fox1** [comment]
As there is a historic discussion about this in #1209 I will close this, please feel free to join that discussion or submit a PR with this feature.
