### ISSUE TITLE
Let's consider the swift.

### ISSUE THREAD

**Issue by ShawnBaek** [parse-community/Parse-SDK-iOS-OSX#1399]
We have other repositories of iOS SDK.
https://github.com/parse-community/Parse-Swift

I think It could be better to create a new swift branch in Parse-SDK-iOS-OSX.

**Comment by mrmarcsmith** [comment]
This is a great idea!

**Comment by SSB95** [comment]
Is there still something going on with a Parse SDK written in Swift? The repo mentioned above is not maintained anymore I think. Or is it just a too big effort to change to Swift yet? This would probably require to maintain two versions of the iOS-SDK? Thanks!

**Comment by drdaz** [comment]
There's nothing active right now. But I plan on spending a little time with that repo soon to see where it was heading.

**Comment by ShawnBaek** [comment]
I think https://swiftify.com is useful for converting to swift code.

**Comment by SSB95** [comment]
How does it look like currently? @drdaz did you find some time to dive into it? Or what are the plans in general @TomWFox ?

**Comment by drdaz** [comment]
@SSB95 Take a look at the Parse-Swift repo. @cbaker has been putting in a lot of work there.
