### ISSUE TITLE
How about making a plan?

### ISSUE THREAD

**Issue by ShawnBaek** [parse-community/Parse-SDK-iOS-OSX#1408]
I found existing issues on Parse-SDK-iOS-OSX.

I want to make and share the next plan. But I can't create Projects tap on GitHub.

@TomWFox Could you make a plan on Projects?

Refer https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1332

<img width="1025" alt="Screen Shot 2019-05-12 at 12 00 06 AM" src="https://user-images.githubusercontent.com/12643700/57571420-f77ad380-7448-11e9-90f0-7a098d4d8e69.png">

**CI Settings**
- fix macOS build and test cases
- fix iOS test cases
- add test cases and CI Setups for tvOS, watchOS

**Converting Swift**

**Authentification**
- add google logins
- fix twitter logins

**Add new features like a Parse-JS-SDK.**

P.S My English writing skill is not perfect. I'd love to get your feedback on my mistakes. 😅

**Comment by TomWFox** [comment]
I'm not aware what issues there are with Twitter auth - is there an existing issue or can you open one?

**Comment by TomWFox** [comment]
I've make a new project with most of your suggestions and the ones from `#1332`.
