### ISSUE TITLE
No results matched the query. (Code: 101, Version: 1.17.0)

### ISSUE THREAD

**Issue by Ramesh23iphone** [parse-community/Parse-SDK-iOS-OSX#1414]
let query = PFQuery(className:"userDataBase")
    query.getObjectInBackground(withId: objectId){(objects: PFObject?, error: Error? ) in
        if error != nil {
            print(error as Any)
        } else if let rating = objects {
            rating["Rating"] = Double(self.ratingSlider.value)

            rating.saveInBackground()
        }
    }

**Comment by TomWFox** [comment]
That error doesn't necessarily indicate a bug, are you sure there is actually an object with that objectId in the `userDataBase` class?

I would also suggest trying to update to v1.17.2 (latest version) to see if that fixes your issue.

**Comment by Ramesh23iphone** [comment]
Using Parse (1.17.2), yes there is a object with objectId , i have debugged and checked the objectId its there in userDatabase.

**Comment by TomWFox** [comment]
Are you sure you are using v1.17.2? - the error in the title says v1.17.0

**Comment by Ramesh23iphone** [comment]
my mistake, i have used wrong classname, Thanks
