### ISSUE TITLE
No results matched the query. (Code: 101, Version: 1.17.2)

### ISSUE THREAD

**Issue by Ramesh23iphone** [parse-community/Parse-SDK-iOS-OSX#1415]
```
 let parseObject = PFQuery(className:"User")
         parseObject.getObjectInBackground(withId: userObjectId){(objects: PFObject?, error: Error? ) in
            objects?["CartColumnName"] =  { "cart": ["objectId" : self.productObjectId , "qyt" : 1]}
        objects?.saveInBackground {
            (success: Bool, error: Error?) in
            if (success) {
                // The object has been saved.
            } else {
                // There was a problem, check error.description
            }
            }
        }
```

**Comment by Ramesh23iphone** [comment]
i want to store cart data in the json formate.

**Comment by TomWFox** [comment]
Are you actually experiencing the error in the title - "No results matched the query. (Code: 101, Version: 1.17.2)" or is that a mistake?

**Comment by Ramesh23iphone** [comment]
yes am actually experiencing the error, i want to store data in json array formate 

{
  "cart": [
    {
      "productobjectId": 12345,
      "qty": 0
    }
  ]
}

**Comment by TomWFox** [comment]
I think you might find that the issue is with your class name like last time. The ‘default’/reserved classes in Parse Server (User, Installation, Session, Role) are actually all prefixed with a underscore...

e.g. `PFQuery(className: “_User”)`

So your code is more ‘safe’ I would recommend querying the user class as shown below...
```swift
 var query = PFUser.query()
```

**Comment by Ramesh23iphone** [comment]
it worked, thanks

**Comment by TomWFox** [comment]
No problem
