### ISSUE TITLE
Parse 1.13.0 Issue

### ISSUE THREAD

**Issue by khawarb** [parse-community/Parse-SDK-iOS-OSX#1419]
Whenever i try to install Parse by using below pod command
pod 'Parse'
It install 1.13.0 version, How i can install latest version 1.17.2. Due to this am having problem in 
pod 'ParseLiveQuery'.

**Comment by TomWFox** [comment]
You should be able to get the latest version by running `pod update POD_NAME`.

Alternatively in your podfile you can change `pod 'Parse'` to `pod 'Parse', '~>1.17.2'`.

**Comment by khawarb** [comment]
Tried but It's saying

CocoaPods could not find compatible versions for pod "Bolts/Tasks":
  In snapshot (Podfile.lock):
    Bolts/Tasks (= 1.7.0)

  In Podfile:
    Parse (~> 1.17.2) was resolved to 1.17.2, which depends on
      Parse/Core (= 1.17.2) was resolved to 1.17.2, which depends on
        Bolts/Tasks (~> 1.9)

Specs satisfying the `Bolts/Tasks (= 1.7.0), Bolts/Tasks (~> 1.9)` dependency were found, but they required a higher minimum deployment target.

**Comment by khawarb** [comment]
Using 
platform :ios, '10.0'

**Comment by TomWFox** [comment]
So I think you will either have to say on 1.13.0 of the Parse SDK or increase the minimum deployment target.

I don't believe this is an issue with this SDK so if you require further help I suggest posting a question on our community forum.

**Comment by khawarb** [comment]
I have already changed my minimum deployment target to 10.0 and it still showing above issue.

**Comment by khawarb** [comment]
What should be the deployment target for Parse 1.17.2?

**Comment by TomWFox** [comment]
I'm not sure about this, it seems that the minimum deployment target for Parse & Bolts/Tasks is 8.0. I'll reopen this for now, in case someone else can help out here.

**Comment by khawarb** [comment]
Thanks, basically am having issues in ParseLiveQuery version 1.0.1, which depends on Parse 1.17.2.

**Comment by khawarb** [comment]
hi @TomWFox 
I have solved this by removing all pods and pod file from project, and then re installing the pod.
Now issue is: 
Parse install Bolts and Bolts-Swift pods along with it's own pod having Bolts version 1.9.0.
I have also installed ParseFacebookUtilsV4 pod. And in this am facing issue due to Bolts file named BFTask.m. I have checked Bolts version 1.17 and it's fine.

**Comment by khawarb** [comment]
Now my question is:
How i can install parse along with Bolts version 1.17.0 rather than version 1.19.0?

**Comment by khawarb** [comment]
Now issue is:
Whenever i try to install following pods

pod 'ParseLiveQuery'
pod 'Parse'
pod 'ParseFacebookUtilsV4'

Bolts and Bolts-Swift auto installed. And Bolts pod have issues due to it's version 1.9.0.

Now how can i install Bolts 1.7.0 version along with Parse and ParseLiveQuery latest version?

**Comment by TomWFox** [comment]
Sorry for leaving this, are you still experiencing this issue?

I noticed that you are installing the archived ParseFacebookUtilsV4 in your pod file you should instead have...
```
pod 'Parse/FacebookUtils'
```
