### ISSUE TITLE
Develop a "how to" guide for new SDK contributors

### ISSUE THREAD

**Issue by brianyyz** [parse-community/Parse-SDK-iOS-OSX#1422]
Objective is to consolidate existing resources and document a step by step process for new contributors to the SDK.

**Comment by TomWFox** [comment]
So current issues...

- [ ] Test suite not documented i.e. where to find tests, how to run
- [ ] How to run linter (does it exist)/what is the coding style

**Comment by TomWFox** [comment]
@brianyyz @drdaz see #1423 - I've added some details about where the tests are and how to run them as well as removing irrelevant sections & broken links.

I'm pretty sure as @drdaz suggested that there is no linter so I've changed that to 'follow the style guide'. Feel free to review that PR and suggest other changes.

**Comment by ShawnBaek** [comment]
+ Swift Package Manager

**Comment by TomWFox** [comment]
I don’t think this library currently supports SPM but we would happily review a PR to add it.

**Comment by ShawnBaek** [comment]
This repo was written in objective-c. 
`SPM` does not support that. 

So We have to decide to convert Swift or not.
(I found a good converter: Swiftify https://objectivec2swift.com/#/home)


https://forums.swift.org/t/spm-library-with-bridging-header/4945
