### ISSUE TITLE
downloadAssetForTransaction 接口返回错误

### ISSUE THREAD

**Issue by WellsYoo** [parse-community/Parse-SDK-iOS-OSX#1429]
I got the transaction from itunes connect and then an error occurred while downloading. Here is my code

```
[PFPurchase addObserverForProduct:productId block:^(SKPaymentTransaction *transaction) {
[PFPurchase downloadAssetForTransaction:transaction completion:^(NSString * _Nullable filePath, NSError * _Nullable error) {
                    
                } progress:^(int percentDone) {
                    
                }];
            }];
```

This is the database information
![image](https://user-images.githubusercontent.com/5734525/61360472-149caa00-a8b1-11e9-9ea4-be810a1f0218.png)

This is the error I received...
> Error Domain=Parse Code=101 "Object not found." UserInfo={code=101, temporary=0, error=Object not found., NSLocalizedDescription=Object not found.}

**Comment by TomWFox** [comment]
What version of the Parse iOS SDK are you using? Which version of Parse Server are you using?
