### ISSUE TITLE
Should Parse.setApplicationId() be removed?

### ISSUE THREAD

**Issue by noobs2ninjas** [parse-community/Parse-SDK-iOS-OSX#1433]
Im doing some iOS documentation updates and I noticed an example that runs `Parse.setApplicationId("appId", clientKey: "clientKey")` and I realized that this is a function thats a remnant from when Parse was a hosted service and you didn't need any further configuration to initialize Parse. 

I checked and I noticed that this function initializes parse itself. From what I could see theres no way of pre-setting either the server url separately or the ParseClientConfiguration. Without that,  I see no way for this function to ever succeed initialization. Am I missing something?

**Comment by davimacedo** [comment]
I think you're right. We should replace `setApplicationId` by `initializeWithConfiguration` in all examples.

**Comment by noobs2ninjas** [comment]
It's actually still available in the framework too FYI. Also many functions in the Parse class give warnings that references it 

> 'enableDataSharingWithApplicationGroupIdentifier:' must be called before 'setApplicationId:clientKey'
