### ISSUE TITLE
Why is ParseUI's deployment target 9.0 instead of 8.0?

### ISSUE THREAD

**Issue by noobs2ninjas** [parse-community/Parse-SDK-iOS-OSX#1434]
Couldn't help but notice that backing ParseUI's deployment target to match Parses minimum deployment target of (8.0) builds just fine. So I'm confused why it was increased.

**Comment by noobs2ninjas** [comment]
Could anyone Answer this. @TomWFox ?

**Comment by TomWFox** [comment]
Sorry, no idea.

**Comment by noobs2ninjas** [comment]
@TomWFox Ok. Since this was left open long enough for someone else to answer and you don't know. Is it ok if I return it back so that its minimum is on par with everything else?

**Comment by TomWFox** [comment]
I guess, if we find any issues we can always revert.
