### ISSUE TITLE
Xcode 11 beta: TARGETED_DEVICE_FAMILY warning

### ISSUE THREAD

**Issue by tealshift** [parse-community/Parse-SDK-iOS-OSX#1437]
From build target `Parse-watchOS-Parse`:

> TARGETED_DEVICE_FAMILY value (1,2) does not contain any device family values compatible with the watchOS platform. Please add the value '4' to the TARGETED_DEVICE_FAMILY build setting to indicate that this target supports the 'watch' device family.

**Comment by drdaz** [comment]
Some more context would be useful. What did you do that produced this output?

**Comment by tealshift** [comment]
So far as I can tell, removing the targets with the white 'plugin' icon has no consequence besides eliminating the warning caused by `Parse-watchOS-Parse`. Possibly an issue with the Podspec? I'm not exactly a framework dev myself.

**Comment by noobs2ninjas** [comment]
I think this also ties in with a issue with getting parse to build on ParseLiveQuery. https://github.com/parse-community/ParseLiveQuery-iOS-OSX/pull/210

Primarily effecting macOS. Not only are the dynamic libraries for parse causing issues like what your facing but building the dynamic Parse frameworks also is building the dynamic frameworks for its dependencies like Bolts which has issues of including iOS/UIKit specific files for macOS as well.  Dynamic frameworks being so new and with some definite behavior changes when building for XCode 11 I think we should really take a look what all our targets are building.
