### ISSUE TITLE
Ambiguous use of 'logInWithUsernameInBackground'

### ISSUE THREAD

**Issue by grantespo** [parse-community/Parse-SDK-iOS-OSX#1438]
The docs seem to need updating.

I am pasting this snippet from Parse iOS docs

`PFUser.logInWithUsernameInBackground("myname", password:"mypass") {
  (user: PFUser?, error: NSError?) -> Void in
  if user != nil {
    // Do stuff after successful login.
  } else {
    // The login failed. Check error to see why.
  }
}`

However, I get an error: 

> Ambiguous use of 'logInWithUsernameInBackground'

**Comment by TomWFox** [comment]
It should look like this...
```swift
PFUser.logInWithUsername(inBackground: "username", password: "password") { (user, error) in

}
```

Could you open a PR on the [docs repo](https://github.com/parse-community/docs) or make an issue with reference to the specific section(s) where you see this error?
