### ISSUE TITLE
Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by mgkcortyw** [parse-community/Parse-SDK-iOS-OSX#1443]
Hello, guys!

Today we received this message from apple:

> Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs. See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

We detect that one of multiple usage in our projects of UIWebView in Parse iOS SDK, could you migrate from UIWebView to WKWebView?
We worry about it, because on next app deploy we can stuck on this issue.

Thank in advance!

**Comment by drdaz** [comment]
This is certainly something we should look at, but UIWebView was deprecated in iOS 12. Usually Apple doesn't start rejecting apps that use deprecated APIs, and they don't get fully removed for a long time.

It's irritating that they don't put any timeframe on when they will stop accepting apps with UIWebView.

It looks like it isn't just the Parse iOS SDK affected by this, but also the underlying Bolts framework.

**Comment by mgkcortyw** [comment]
Thanks you for fast answer, @drdaz !
Understood,
Related issue on Bolts https://github.com/BoltsFramework/Bolts-ObjC/issues/331

**Comment by tealshift** [comment]
I forked Bolts and removed all usage of App Links and UIWebView, and works in my Parse project. https://github.com/tealshift/Bolts-ObjC

You can get this version of Bolts with the pod config:
```
pod 'Bolts', :git => 'https://github.com/tealshift/Bolts-ObjC.git'
pod 'Parse', :git => 'https://github.com/parse-community/Parse-SDK-iOS-OSX.git'
```
Of course, if you have lots of code that relies on Bolt's App Links API, then this solution probably isn't for you.

**Comment by sarojkumarojha** [comment]
Are we getting a new release from Parse? @drdaz .
BTW I am not able to upgrade to 'Parse' , '1.17.3' , got an error **CocoaPods could not find compatible versions for pod "Parse": In Podfile: Parse (= 1.17.3)**.

Thanks in advance.

**Comment by drdaz** [comment]
@sarojkumarojha The release is there. You can grab the source or install via Carthage.

The CocoaPods entry needs updating though. We've had some issues with that. I'll see if I can do it manually. 

@TomWFox you offered me access to the pod?

**Comment by drdaz** [comment]
@sarojkumarojha Were you talking about the 1.17.3 release, or something related to this thread?

**Comment by TomWFox** [comment]
@drdaz I can give you access, what email address should I use? - I think it has to be registered with cocoa pods trunk before I add you as an owner (you could send it to me on the forum by PM if you want to)

**Comment by drdaz** [comment]
@sarojkumarojha 1.17.3 is now available on CocoaPods.

**Comment by sarojkumarojha** [comment]
@drdaz Thanks, now I am able to use  1.17.3 through CocoaPods, But still, it uses UIWebView APIs.
Any plan on it?

**Comment by tealshift** [comment]
I have a suggestion: It seems the Bolts/AppLinks subspec can be removed from the `FacebookUtils` & `FacebookUtils-tvOS` subspec in this project's podspec file:
`s.dependency 'Bolts', '~> 1.9'`
change to ->
`s.dependency 'Bolts/Tasks', '~> 1.9'` so the AppLinks subspec is no longer a dependency
I may be wrong, but it seems like the logical solution. I made a PR in case you guys agree.

**Comment by mrmarcsmith** [comment]
I’m assuming we fixed this in #1452. Someone let me know if there is more to be done here

**Comment by sarojkumarojha** [comment]
```
pod 'Parse/FacebookUtils','1.17.3'
pod 'Parse/TwitterUtils','1.17.3'
pod 'Parse','1.17.3'
pod 'Parse/UI','1.17.3'
```
I am using parse 1.17.3 , still UIWebView APIs are there in it , @mrmarcsmith could you please confirm to address this, is there a release planned ?

**Comment by drdaz** [comment]
@sarojkumarojha We're working on it. There are some final PRs that need a little polish... but we're working on it :)

**Comment by sarojkumarojha** [comment]
> @sarojkumarojha We're working on it. There are some final PRs that need a little polish... but we're working on it :)

Thank you !

**Comment by noobs2ninjas** [comment]
Bolts just released 1.9.1 which fixes this. We have a release pretty much already to go. Just going through build tests right now. Look out for Parse 1.18.0!

**Comment by fmendoza** [comment]
Any updates? Apple is rejecting our apps due to the uiwebview deprecation

**Comment by TomWFox** [comment]
1.18.0 has been out for a while now, this should solve the deprecation issue. Let us know if you are still having issues on 1.18.0.

**Comment by fmendoza** [comment]
ty will try the update today

**Comment by tshort15-ford** [comment]
I think PFTwitterUtils also has references to UIWebView?

**Comment by noobs2ninjas** [comment]
You are correct @fmendoza. Wanna open A issue for that and we'll get it cleaned up right away.

**Comment by davewhipps** [comment]
> 1.18.0 has been out for a while now, this should solve the deprecation issue. Let us know if you are still having issues on 1.18.0.

This is actually still broken in Parse-UI. The ParseTwitterUtils::PFOAuth1FlowDialog uses UIWebView.
