### ISSUE TITLE
CNCopyCurrentNetworkInfo change

### ISSUE THREAD

**Issue by Samigos** [parse-community/Parse-SDK-iOS-OSX#1444]
Apple had sent this email last month... are Parse apps affected by this change?

> As we announced at WWDC19, we're making changes to further protect user privacy and prevent unauthorized location tracking. Starting with iOS 13, the CNCopyCurrentNetworkInfo API will no longer return valid Wi-Fi SSID and BSSID information. Instead, the information returned by default will be:
> 
> SSID: “Wi-Fi” or “WLAN” (“WLAN" will be returned for the China SKU)
> BSSID: "00:00:00:00:00:00"
> 
> If your app is using this API, we encourage you to adopt alternative approaches that don’t require Wi-Fi or network information. Valid SSID and BSSID information from CNCopyCurrentNetworkInfo will still be provided to VPN apps, apps that have used NEHotspotConfiguration to configure the current Wi-Fi network, and apps that have obtained permission to access user location through Location Services.
> 
> Test your app on the latest iOS 13 beta to make sure it works properly. If your app requires valid Wi-Fi SSID and BSSID information to function, you can do the following:
> 
> For accessory setup apps, use the NEHotSpotConfiguration API, which now has the option to pass a prefix of the SSID hotspot your app expects to connect to.
> For other types of apps, use the CoreLocation API to request the user’s consent to access location information.

**Comment by drdaz** [comment]
I use Parse in some live apps, and didn't receive this.

Have you tried searching your codebase for stuff from the relevant API?

**Comment by Samigos** [comment]
I did, but didn't find anything... I just wanted to make sure!

**Comment by drdaz** [comment]
Sure.

I mean I haven't looked, but I'm not aware of any Parse functionality that would go there. This looks entirely related to WiFi access.

Anybody correct me if I'm wrong.
