### ISSUE TITLE
xcode11/iOS 13

### ISSUE THREAD

**Issue by parveenBanuS** [parse-community/Parse-SDK-iOS-OSX#1465]
Xcode11/iOS 13 UIcollection view not working it was not navigate to another view. less than Xcode11 iOS 13 is woking fine no issues at the same time Xcode11 less than iOS 13(iOS 12,iOS 4.1, iOS 5.1, iOS 6.1, iOS 7.1.2, iOS 8.4.2, iOS 9.0, iOS 11.0, iOS 11.3) working fine.

The issues is,

"The behavior of the UICollectionViewFlowLayout is not defined because:
2019-10-29 10:55:17.781597+0530 Storefront[360:20094] the item width must be less than the width of the UICollectionView minus the section insets left and right values, minus the content insets left and right values"

**Comment by TomWFox** [comment]
Hi, I’m not seeing anything to indicate that this is an issue related to the Parse SDK.

Perhaps try searching stackoverflow for similar issues.

**Comment by drdaz** [comment]
@parveenBanuS Do you mean [PFQueryCollectionViewController](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/ParseUI/Classes/QueryCollectionViewController/PFQueryCollectionViewController.h) doesn't work?

**Comment by parveenBanuS** [comment]
uicollectionview showing this it was running not crash but can't able to
navigate next page

**Comment by parveenBanuS** [comment]
"The behavior of the UICollectionViewFlowLayout is not defined because: >
2019-10-29 10:55:17.781597+0530 Storefront[360:20094] the item width must
be less than the width of the UICollectionView minus the section insets
left and right values, minus the content insets left and right values"




this is the issue

**Comment by ashish-naik** [comment]
Praveen,

Try checking your layout constraints. This does not seem related to Parse. You can seek help in Stackoverflow if you are not able to find the issue.

**Comment by parveenBanuS** [comment]
ok thank you

**Comment by TomWFox** [comment]
I’ll close this for now, feel free to make a new issue if you find any issues related to the Parse SDK.

**Comment by parveenBanuS** [comment]
sure
