### ISSUE TITLE
Missing Bolts.framework Parse-iOS.zip in for version 1.17.3

### ISSUE THREAD

**Issue by funnel20** [parse-community/Parse-SDK-iOS-OSX#1466]
Hi,

We always download the iOS source ZIP file from https://github.com/parse-community/Parse-SDK-iOS-OSX/releases. It normally consists of 2 files (e.g. version 1.17.2):

1. Bolts.framework
2. Parse.framework

However, the [ZIP for iOS 1.17.3](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/download/1.17.3/Parse-iOS.zip) only contains the Parse.framework.
Is this intentional? And can the Bolts.framework from version 1.17.3 still be used?

Thanks

**Comment by TomWFox** [comment]
Hi, I don’t believe this is intentional. Due to an issue with the release build we made the release manually so I suspect that’s why it’s not there.

@drdaz I think you attached the assets manually, right?

**Comment by drdaz** [comment]
> @drdaz I think you attached the assets manually, right?

Nope, they appeared there automagically. That might mean some of the magic is broken I guess.

**Comment by funnel20** [comment]
@drdaz Thanks for confirming that we can use the existing Bolts.framework.

**Comment by TomWFox** [comment]
Well I believe we can change the assets manually on the existing release so we could do that as a temporary fix.

**Comment by funnel20** [comment]
I hope the is still on the radar for next release.

**Comment by noobs2ninjas** [comment]
@funnel20 currently we have two things going. 

1) We are currently working on updating bolts ourselves on our own fork and 
2) We are in talks with Faceboook to see if we can get the Bolts repo turned over to us. 

Till we get bolts up and running and working with Xcode 11.3 we will not be able to release via Travis. Manual release means we have to build and upload it ourselves.

**Comment by noobs2ninjas** [comment]
@funnel20 actually nevermind. It was your message that got me back on this and last night I decided to knock it out. Should have a new release soon. Not sure if well update 1.17.3

**Comment by funnel20** [comment]
@noobs2ninjas For me it's not required to update 1.17.3, because based on your previous answers we used the existing Bolts.framework from 1.17.2.
But it would be much appreciated when future releases would contain all required files in the ZIP file.
