### ISSUE TITLE
Objects fetched with selectKeys cannot be pinned

### ISSUE THREAD

**Issue by aprato** [parse-community/Parse-SDK-iOS-OSX#1467]
I recently ran into this problem which was previously mentioned in #386 

This appears to be intentional as laid out here:
https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/5de23b30c4aa22b27cac47e9456694a467e76b83/Parse/Parse/PFObject.m#L827

I haven't fully figured out all of the code involved with pinning but if it would be a large change to allow pinning of partial objects the docs should be updated. I would be happy to help if given an idea how to do so. 

The other change I think that should be made is the result when pinning an incomplete object. Right now when I call `object.pinInBackground { (success: Bool, error: Error?) -> Void` I get `true` with nil error which gave me the impression things were working. If I'm following all of this It seems like the code here should indicate the pinning was not successful as with select keys a fetched object will never have `_pfinternal_state.complete == YES` (and therefor `isDataAvailable` will also always be `NO`)
https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/5bf27a2d173d822c8e8d955ca9f25efccd7c0787/Parse/Parse/Internal/LocalDataStore/OfflineStore/PFOfflineStore.m#L369-L372

**Comment by TomWFox** [comment]
Hi, sorry for the delayed response. We don’t currently have any maintainers who have detailed knowledge of the inner workings of the SDK so we may not be able to give particularly helpful advice.

@parse-community/ios-osx anyone who can help with this?
