### ISSUE TITLE
iOS 13 compatibility

### ISSUE THREAD

**Issue by Samigos** [parse-community/Parse-SDK-iOS-OSX#1468]
Hello to the community!

Where exactly are we with the iOS 13 branch? Approximately when will it be merged?

**Comment by TomWFox** [comment]
Hi, sorry for the delayed response. There isn’t currently an iOS 13 branch.

Are you having any particular issues with the latest version of the SDK on iOS 13?

**Comment by Samigos** [comment]
Hi Tom! I meant the Swift 5 branch... Apologies :D

**Comment by drdaz** [comment]
@Samigos We should be fully compatible with Xcode 11 at this point. Is there something specific you're thinking of? Any issues you're encountering with Xcode 11?

**Comment by Samigos** [comment]
So is the SDK compatible with Swift 5 now?

**Comment by drdaz** [comment]
I'm using it in a Swift 5 project without any trouble.

This SDK is written in Objective C, so it doesn't really get directly affected by changes to Swift.

**Comment by Samigos** [comment]
That's a relief!! I was asking because of what @noobs2ninjas to another thread of mine... He had said "Working on trying to get ourselves up to XCode 11/ iOS 13 before it officially drops"... I thought he meant updating the SDK 😝

**Comment by drdaz** [comment]
Oh he might have! He did a lot of work on the build infrastructure for this project in that regard, and finished up with that a while back 🙂

**Comment by Samigos** [comment]
Oh ok! Thank you very much man!
