### ISSUE TITLE
Nightly Cocoapods is failing

### ISSUE THREAD

**Issue by drdaz** [parse-community/Parse-SDK-iOS-OSX#1470]
https://circleci.com/gh/parse-community/Parse-SDK-iOS-OSX/3641?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

This started a few days ago. There haven't been any source changes to trigger this. Has our environment been changed? 

@parse-community/ios-osx 

EDIT: Full disclosure, I posted this before I tested it locally. I think I just wanted attention.

But `bundle exec rake test:cocoapods` locally fails at the same spot with Xcode 11.2.

**Comment by noobs2ninjas** [comment]
I took a look. Heres our error. 

-> Parse (1.17.3)
    - NOTE  | [Parse/Core, Parse/FacebookUtils, Parse/FacebookUtils-tvOS, and more...] xcodebuild:  note: Using new build system
    - NOTE  | [Parse/Core, Parse/FacebookUtils, Parse/FacebookUtils-tvOS, and more...] xcodebuild:  note: Planning build
    - NOTE  | [Parse/Core, Parse/FacebookUtils, Parse/FacebookUtils-tvOS, and more...] xcodebuild:  note: Constructing build description
    - NOTE  | [Parse/Core, Parse/FacebookUtils, Parse/TwitterUtils, and more...] xcodebuild:  warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the App editor. (in target 'App' from project 'App')
    - NOTE  | [Parse/Core, Parse/FacebookUtils, Parse/TwitterUtils, and more...] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | [Parse/Core] xcodebuild:  warning: TARGETED_DEVICE_FAMILY value (1,2) does not contain any device family values compatible with the watchOS platform. Please add the value '4' to the TARGETED_DEVICE_FAMILY build setting to indicate that this target supports the 'watch' device family. (in target 'Parse-Parse' from project 'Pods')
    - ERROR | [Parse/FacebookUtils,Parse/FacebookUtils-tvOS] xcodebuild: Returned an unsuccessful exit code.

Whats odd is that the last note before the error says something about watch OS. The error however was building FacebookUtils-tvOS.

**Comment by noobs2ninjas** [comment]
Did we ever get our CircleCI build fixed?

**Comment by noobs2ninjas** [comment]
Our build shows as passing for Travis. First time in who knows how long!.

**Comment by drdaz** [comment]
This still fails.

**Comment by noobs2ninjas** [comment]
Running nightly build now. Fingers crossed.
