### ISSUE TITLE
Parse memory leaks

### ISSUE THREAD

**Issue by nobat1** [parse-community/Parse-SDK-iOS-OSX#1472]
logic error
 Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue

Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue

nil returned from a method that is expected to return a non-null value

**Comment by noobs2ninjas** [comment]
Not a lot of info here. What language? Was this in a subclass? etc...

**Comment by AshrafAbuBakr** [comment]
I was running analysis on ly app and found 8 possible leaks in the SDK.
They are as follows:
1- PFPush.m (Line 322) :Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
2- PFCommandCache.m (Line 250): Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
3- PFOperationSet.m (Line 119): Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
4- PFSQLiteDatabaseResult.m (Line 169): Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
5- PFRESTPushCommand.m (Linde 46): Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
6- PFCommandURLRequestConstructor.m (Line 113): Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
7- PFQuery.m (Line 1092): Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
8- PFDateFormatter.m (Methd: preciseStringFromDate): nil returned from a method that is expected to return a non-null value
