### ISSUE TITLE
Twitter login cancellation crashes app

### ISSUE THREAD

**Issue by ashish-naik** [parse-community/Parse-SDK-iOS-OSX#1474]
I am using Twitter authentication without ParseUI framework.

When i initiate twitter auth session using `PFTwitterUtils.logIn { (loggedInUser, error) in`, the Twitter login page opens. 

i am able to login using valid credentials. 
But if i tap Cancel and then tap **Return to _app_** then app crashes with below error at line 61 in PFTwitterAuthenticationProvider.m

`*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
`
 
Parse/TwitterUtils (1.17.3)
iOS 13.2.2 simulator

i tried breakpoints to catch flow in my code but crash happens before control returns to `PFTwitterUtils.logIn { (loggedInUser, error)`

What could be the issue?

Thanks
Ashish

**Comment by ashish-naik** [comment]
@nlutsenko I saw https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/348 
i am seeing similar error but in a different use case.

i had created this issue five days back but didn't get any response. I tried looking for answers on Stackoverflow also.

I have checked twitter authentication related posts but could not find any answer. 

Setting callback URL is mentioned at many place. I have set it in my app dashboard and able to login also.
it fails when tap Cancel and then Return to myapp on Twitter webpage popup inside my iOS app.

Could you please suggest what could be the issue?

**Comment by drdaz** [comment]
Hi Ashish

It's hard to be certain exactly what's failing without more code for context, but line 61 in that file looks like this:
```
    NSDictionary *authData = @{_PFTwitterAuthDataIdKey : twitterId,
                               _PFTwitterAuthDataScreenNameKey : screenName,
                               _PFTwitterAuthDataAuthTokenKey : authToken,
                               _PFTwitterAuthDataAuthTokenSecretKey : authTokenSecret,
                               _PFTwitterAuthDataConsumerKeyKey : self.twitter.consumerKey,
                               _PFTwitterAuthDataConsumerSecretKey : self.twitter.consumerSecret};
```
The error occurs because one (or more) of the variables after the ':' in the dictionary literal evaluate to nil at the time of the crash. My advice would be to set a breakpoint on that line and recreate the crash scenario. Once you hit that line, you'll be able to use the debugger to find out which of the variables is nil. You will likely be able to work from there to ensure that it isn't nil.

I hope this helps.

**Comment by drdaz** [comment]
@ashish-naik Also, you've specified that this occurs when you don't use ParseUI. Do you know whether ParseUI behaves better?

**Comment by ashish-naik** [comment]
@drdaz I was using ParseUI but replaced that with my custom classes because Sign in with Apple is not available yet and added email/password based authentication. Not sure whether i was hitting this issue then with ParseUI.

I tried with the breakpoint. See attached screenshot. All variables are nil. I have also attached screenshots of Twitter screens. 

Steps to reproduce are 

1. On my custom VC i tap Twitter Button
2. Call` PFTwitterUtils.logIn { (loggedInUser, error) in`
3. Twitter login popup opens
4. I tap Cancel (first screenshot)
5. Twitter Show page with button **Return to _app_**
6. I tap **Return to _app_**  button (second screenshot)
7. App crash on line 61

This is happening on iOS 12.2 simulator and 13.3 device, simulator

yes after cancel i dont need to handle login but exception occurs before my login handler is called after Cancel.

![TW login SS 1](https://user-images.githubusercontent.com/4936420/71322279-d48ac480-24eb-11ea-94c9-32f071b650b4.jpeg)
![TW login SS 2](https://user-images.githubusercontent.com/4936420/71322277-d48ac480-24eb-11ea-9119-70da1e8f032b.jpeg)
<img width="1262" alt="breeakpoint screenshot" src="https://user-images.githubusercontent.com/4936420/71322280-d48ac480-24eb-11ea-9b83-a9692a4f08ca.png">

Does this help?

**Comment by drdaz** [comment]
This looks like a bug. I don't use the Twitter login feature myself, and I can't seem to test it using the ParseUI Demo project, so it's a little hard for me to reproduce.

But it looks like it's trying to authenticate the user even though they pressed cancel. Which is... wrong.

**Comment by ashish-naik** [comment]
@drdaz No i am not trying to authenticate after cancel. 

My PFTwitterUtils.logIn { (loggedInUser, error) call opens the login page and then i wait to check error if any but control does not return.

**Comment by drdaz** [comment]
So I've just taken a look at the Twitter auth code, and it's very outdated. It still assumes that iOS has local Twitter accounts, which hasn't been the case for several years.

Do you absolutely need Twitter login? Looking at the state of things in there, if you can avoid it, do so. Otherwise, perhaps you can take a look at the code causing the trouble. I can't spend much time on it right now.

**Comment by drdaz** [comment]
That's just my opinion btw; the opinion of a guy who hasn't attempted to use the Twitter login feature at all before today.

If anybody else has been using it successfully, by all means chime in.

**Comment by ashish-naik** [comment]
No I can remove Twitter. 

Thanks for looking in.

**Comment by brianyyz** [comment]
FWIW I abandoned Twitter as an authentication provider for the reasons above. Even back then it was in a bit of a mess and didn't take into account the changes that Twitter has made.
