### ISSUE TITLE
App doesnt start on real device - Xcode 11.3.1 - ios 13.3.1 Parse 1.17.3

### ISSUE THREAD

**Issue by MoSchaub** [parse-community/Parse-SDK-iOS-OSX#1480]
I tried to create an iOS App using the Parse SDK. I installed the SDK via CocoaPods and when I try it in Simulator it works perfectly but on a real device it doesn't start and I get the following error message: 

dyld: Library not loaded: @rpath/Bolts.framework/Bolts
  Referenced from: /private/var/containers/Bundle/Application/94AC3B28-51D8-4F9A-9AF4-1B4CAEF257B8/Skills.app/Skills
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/94AC3B28-51D8-4F9A-9AF4-1B4CAEF257B8/Skills.app/Frameworks/Bolts.framework/Bolts: code signature invalid for '/private/var/containers/Bundle/Application/94AC3B28-51D8-4F9A-9AF4-1B4CAEF257B8/Skills.app/Frameworks/Bolts.framework/Bolts'
	/private/var/containers/Bundle/Application/94AC3B28-51D8-4F9A-9AF4-1B4CAEF257B8/Skills.app/Frameworks/Bolts.framework/Bolts: stat() failed with errno=25
	/private/var/containers/Bundle/Application/94AC3B28-51D8-4F9A-9AF4-1B4CAEF257B8/Skills.app/Frameworks/Bolts.framework/Bolts: code signature invalid for '/private/var/containers/Bundle/Application/94AC3B28-51D8-4F9A-9AF4-1B4CAEF257B8/Skills.app/Frameworks/Bolts.framework/Bolts'
	/private/var/containers/Bundle/Application/94AC3B28-51D8-4F9A-9AF4-1B4CAEF257B8/Skills.app/Frameworks/Bolts.framework/Bolts: stat() failed with errno=1
	/private/var/containers/Bundle/Application/94AC3B28-51D8-4F9A-9AF4-1B4CAEF257B8/Skills.app/Frameworks/Bolts.framework/Bolts: code signature invalid for '/private/var/containers/Bundle/Application/94AC3B28-51D8-4F9A-9AF4-1B4CAEF257B8/Skills.app/Frameworks/Bolts.framework/Bolts'
	/private/var/containers/Bundle/Application/94AC3B28-51D8-4F9A-9AF4-1B4CAEF257B8/Skills.app/Frameworks/Bolts.framework/Bolts: stat() failed with errno=1

Btw. I also checked a plain new App with the SDK: same issue. But on an iOS App without the SDK it works perfectly on the real device and on Simulator.

**Comment by TomWFox** [comment]
Please specify specifically what version of Xcode, iOS and the Parse iOS SDK you are using. Also do you have any other dependencies?

**Comment by MoSchaub** [comment]
Xcode 11.3.1 iOS 13.3.1 Parse 1.17.3 Bolts 1.9.0

**Comment by MoSchaub** [comment]
In my Podfile there is only Parse as a Pod

**Comment by noobs2ninjas** [comment]
@MoSchaub Bolts was originally created for Parse and is an integral part of our system. Unfortunately, Facebook both didnt open source it when they open sourced Parse. Also, they have stopped maintaining it. We are currently in talks to get it back but until then we are working on a new release that will use Parse's own fork that is updated for iOS 13. My goal is to hopefully have a new Parse release by next week. Till then I'll double check a new release will definitely work. Sorry for the trouble though!

**Comment by noobs2ninjas** [comment]
Update, Facebook is having a meeting this week about turning Bolts over to us. If they decide that wont work we will release our own version of Bolts. Either way. A fix is on its way.

**Comment by MoSchaub** [comment]
Thanks I hope this issue is going to get fixed soon. Are there any plans about translating Parse into Swift?

**Comment by noobs2ninjas** [comment]
@MoSchaub we've talked about it. right now we have so much catching up to do with issues. When we finally get a little room to breath, I'm sure we'll talk about it again. 

Good news is that Facebook has agreed to give us access and we'll be able to move forward quickly on getting a new release out.

**Comment by andluizlima** [comment]
I'm still having the same problem... Any news about it?

**Comment by hunterh37** [comment]
Is this fixed?

**Comment by bayareahank** [comment]
I assume you run the code with an unpaid iOS developer account. 

I think this came from Apple side, changes made to XCode/iOS. You would need a paid developer account to sign the library to run it on a real device, otherwise it will come as an unsigned, thus rejected by security mechanism on real device. 

I ran into the same problem around Feb., after XCode update. The solution is to upgrade my account into a paid one, so my signing of the library be accepted as authentic, then everything starts working again (with real device). Work around is either to downgrade to earlier XCode version, or to borrow some other's paid account to sign your code to run it on real device. Well, Apple's way to make more money. 

I think this bug could be closed, as this isn't related to Parse here.
