### ISSUE TITLE
Crash: Offline query sort results. Looks like it's trying to sort objects that are null

### ISSUE THREAD

**Issue by eeallen1** [parse-community/Parse-SDK-iOS-OSX#1481]
This has been happening to many of our users, however I haven't been able to reproduce. It looks like it's caused from attempting to sort pinned objects that for some reason are `null`

It seems to be happening over and over to certain users even after deleting and reinstalling the app. 

I understand that the SDK doesn't have much active support right now, but if someone with more knowledge could at least help me circumvent this issue, I'd appreciate it. 

code:
```
func getPinnedObjects(_ callback:(() -> Void)? = nil){
        let q = TrendingCategory.query()?.fromPin(withName: "trendingCategories")
        q?.order(byDescending: "position")
        q?.findObjectsInBackground(block: {
            (objects, error) in
            if let pinned = objects as? [TrendingCategory]{
                self.categories = pinned
                self.view?.loadCategories(self.categories)
            }
            callback?()
        })
    }
```
stack trace: 

> NSInvalidArgumentException
[NSNull objCType]: unrecognized selector sent to instance 0x1c59480b0
0	CoreFoundation	0x1a140496c	<redacted>	+ 224
1	libobjc.A.dylib	0x1a111d028	objc_exception_throw	+ 60
2	CoreFoundation	0x1c0ba6dcc	[NSOrderedSet initWithSet:copyItems:]	+ 144
3	CoreFoundation	0x1c0cad048	<redacted>	+ 1328
4	CoreFoundation	0x1c0caf3a0	_CF_forwarding_prep_0	+ 96
5	CoreFoundation	0x1872f37cc	<redacted>	+ 64
6	Parse	0x68914	__49-[PFOfflineQueryLogic _sortResults:ofQueryState:]_block_invoke.302	+ 596
7	CoreFoundation	0x187428640	__52-[NSMutableArray sortRange:options:usingComparator:]_block_invoke	+ 36
8	CoreFoundation	0x1873a84cc	__CFSimpleMergeSort	+ 180
9	CoreFoundation	0x1873a8528	__CFSimpleMergeSort	+ 272
10	CoreFoundation	0x1873a8510	__CFSimpleMergeSort	+ 248
11	CoreFoundation	0x1873a8528	__CFSimpleMergeSort	+ 272
12	CoreFoundation	0x1873a7f50	CFSortIndexes	+ 260
13	CoreFoundation	0x1872f75c8	[NSMutableArray sortRange:options:usingComparator:]	+ 444
14	Parse	0x683bc	-[PFOfflineQueryLogic _sortResults:ofQueryState:]	+ 392
15	Parse	0x68154	-[PFOfflineQueryLogic resultsByApplyingOptions:ofQueryState:toResults:]	+ 148
16	Parse	0x6ce98	__67-[PFOfflineStore findAsyncForQueryState:user:pin:isCount:database:]_block_invoke.251	+ 116
17	Bolts	0xeae8	__62-[BFTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke	+ 92
18	Bolts	0xe4d8	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke	+ 88
19	Bolts	0xbdd4	__29+[BFExecutor defaultExecutor]_block_invoke_2	+ 128
20	Bolts	0xc2fc	-[BFExecutor execute:]	+ 76
21	Bolts	0xe0d8	-[BFTask runContinuations]	+ 352
22	Bolts	0xdc40	-[BFTask trySetResult:]	+ 144
23	Bolts	0xf11c	-[BFTaskCompletionSource setResult:]	+ 80
24	Bolts	0xe6e4	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2	+ 220
25	Bolts	0xe4d8	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke	+ 88
26	Bolts	0xbdd4	__29+[BFExecutor defaultExecutor]_block_invoke_2	+ 128
27	Bolts	0xc2fc	-[BFExecutor execute:]	+ 76
28	Bolts	0xe0d8	-[BFTask runContinuations]	+ 352
29	Bolts	0xdc40	-[BFTask trySetResult:]	+ 144
30	Bolts	0xf11c	-[BFTaskCompletionSource setResult:]	+ 80
31	Bolts	0xe6e4	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2	+ 220
32	Bolts	0xe4d8	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke	+ 88
33	Bolts	0xbdd4	__29+[BFExecutor defaultExecutor]_block_invoke_2	+ 128
34	Bolts	0xc2fc	-[BFExecutor execute:]	+ 76
35	Bolts	0xe0d8	-[BFTask runContinuations]	+ 352
36	Bolts	0xdc40	-[BFTask trySetResult:]	+ 144
37	Bolts	0xf11c	-[BFTaskCompletionSource setResult:]	+ 80
38	Bolts	0xe6e4	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2	+ 220
39	Bolts	0xe4d8	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke	+ 88
40	Bolts	0xbdd4	__29+[BFExecutor defaultExecutor]_block_invoke_2	+ 128
41	Bolts	0xc2fc	-[BFExecutor execute:]	+ 76
42	Bolts	0xe0d8	-[BFTask runContinuations]	+ 352
43	Bolts	0xdc40	-[BFTask trySetResult:]	+ 144
44	Bolts	0xf11c	-[BFTaskCompletionSource setResult:]	+ 80
45	Bolts	0xe5a8	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke	+ 296
46	Bolts	0xbdd4	__29+[BFExecutor defaultExecutor]_block_invoke_2	+ 128
47	Bolts	0xc2fc	-[BFExecutor execute:]	+ 76
48	Bolts	0xe0d8	-[BFTask runContinuations]	+ 352
49	Bolts	0xdc40	-[BFTask trySetResult:]	+ 144
50	Bolts	0xf11c	-[BFTaskCompletionSource setResult:]	+ 80
51	Bolts	0xe6e4	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2	+ 220
52	Bolts	0xe58c	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke	+ 268
53	Bolts	0xbdd4	__29+[BFExecutor defaultExecutor]_block_invoke_2	+ 128
54	Bolts	0xc2fc	-[BFExecutor execute:]	+ 76
55	Bolts	0xe0d8	-[BFTask runContinuations]	+ 352
56	Bolts	0xdc40	-[BFTask trySetResult:]	+ 144
57	Bolts	0xf11c	-[BFTaskCompletionSource setResult:]	+ 80
58	Bolts	0xe6e4	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2	+ 220
59	Bolts	0xe4d8	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke	+ 88
60	Bolts	0xbdd4	__29+[BFExecutor defaultExecutor]_block_invoke_2	+ 128
61	Bolts	0xc2fc	-[BFExecutor execute:]	+ 76
62	Bolts	0xe0d8	-[BFTask runContinuations]	+ 352
63	Bolts	0xdc40	-[BFTask trySetResult:]	+ 144
64	Bolts	0xf11c	-[BFTaskCompletionSource setResult:]	+ 80
65	Bolts	0xe6e4	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2	+ 220
66	Bolts	0xe58c	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke	+ 268
67	Bolts	0xbdd4	__29+[BFExecutor defaultExecutor]_block_invoke_2	+ 128
68	Bolts	0xc2fc	-[BFExecutor execute:]	+ 76
69	Bolts	0xe0d8	-[BFTask runContinuations]	+ 352
70	Bolts	0xdc40	-[BFTask trySetResult:]	+ 144
71	Bolts	0xf11c	-[BFTaskCompletionSource setResult:]	+ 80
72	Bolts	0xe6e4	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2	+ 220
73	Bolts	0xe58c	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke	+ 268
74	Bolts	0xbdd4	__29+[BFExecutor defaultExecutor]_block_invoke_2	+ 128
75	Bolts	0xc2fc	-[BFExecutor execute:]	+ 76
76	Bolts	0xe0d8	-[BFTask runContinuations]	+ 352
77	Bolts	0xdc40	-[BFTask trySetResult:]	+ 144
78	Bolts	0xf11c	-[BFTaskCompletionSource setResult:]	+ 80
79	Bolts	0xe5a8	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke	+ 296
80	Bolts	0xbdd4	__29+[BFExecutor defaultExecutor]_block_invoke_2	+ 128
81	Bolts	0xc2fc	-[BFExecutor execute:]	+ 76
82	Bolts	0xe0d8	-[BFTask runContinuations]	+ 352
83	Bolts	0xdc40	-[BFTask trySetResult:]	+ 144
84	Bolts	0xf11c	-[BFTaskCompletionSource setResult:]	+ 80
85	Bolts	0xe6e4	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2	+ 220
86	Bolts	0xe58c	__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke	+ 268
87	libdispatch.dylib	0x1870c1fd8	<redacted>	+ 20
88	libdispatch.dylib	0x1870cebdc	<redacted>	+ 68
89	libdispatch.dylib	0x1870ce6b4	<redacted>	+ 172
90	Parse	0xa2664	PFThreadsafetySafeDispatchSync	+ 80
91	libdispatch.dylib	0x1830ecb7c	<redacted>	+ 32
92	libdispatch.dylib	0x1870c1fd8	<redacted>	+ 20
93	libdispatch.dylib	0x18a4ec414	<redacted>	+ 672
94	libdispatch.dylib	0x1adba8bd4	<redacted>	+ 348
95	libdispatch.dylib	0x1adba9384	<redacted>	+ 120
96	libsystem_pthread.dylib	0x1adbff690	_pthread_wqthread	+ 216
97	libsystem_pthread.dylib	0x18712d9e8	start_wqthread

**Comment by eeallen1** [comment]
Looking more at the sdk, it looks like the crash is coming specifically from line 874 of PFOfflineQueryLogic.m

I'm nearly illiterate when it comes to objc, but if I understand this correctly, one of the values being compared, `lhsValue` or `rhsValue` appears to be type `NSNull`, but is that not the same as `nil`? 

![Screen Shot 2020-02-27 at 9 41 36 AM](https://user-images.githubusercontent.com/6464213/75470357-6926fe00-5945-11ea-95f9-b58601d55a5c.png)

**Comment by drdaz** [comment]
One of objc's quirks is that you can only add object types in collections. I haven't checked the surrounding code, but it looks like this code is iterating over the keys in an NSDictionary, and the .keys value of an NSDictionary is stored in an NSArray / a collection type. 

nil is not an object type, and therefore can't be used in collections in objc. NSNull represents a null value in object form and therefore can be used in collections.

I hope this helps. I've been a little ill for the past week or so, so I haven't had time or energy to work on the SDK or look more closely at this problem.

**Comment by eeallen1** [comment]
@drdaz I'm sorry you've been unwell-- I hope you get better soon!

I'm assuming as a short-term fix I could just check for NSNull before comparing the two objects?

**Comment by drdaz** [comment]
Can you reproduce the error reliably with some of your input data? If you can, then you can test it :)

**Comment by eeallen1** [comment]
No, unfortunately, I haven't been able to reproduce, but it's a chronic issue for certain users. I can try it out in the next release and see what happens

**Comment by drdaz** [comment]
Alright; that's kind of a necessity when fixing issues. You need to be able to reproduce the issue so that you know when you've fixed it 🙂

So if you could get in touch with your users to find out what queries they're executing when the failure occurs, we'll be able to write tests that show the issue, and then fix it.

**Comment by eeallen1** [comment]
There are only 2 queries in my app that use offline storage - one uses a sort and the other doesn't . So It's one of the following: 

```
let q = PFQuery(className:"Item")?.fromPin(withName:"DailyEdit")
q?.includeKeys(["sale", "owner", "brand"])
q?.findObjectsInBackground(block: ...
```
```
 let q = PFQuery(className: "TrendingCategory")?.fromPin(withName: "trendingCategories")
 q?.order(byDescending: "position")
 q?.findObjectsInBackground(block: ...
```

I can also add some logging and remove the sort from the second query. If removing the sort fixes the issue, then we'll know which one it was.

**Comment by eeallen1** [comment]
Ok so I was finally able to reproduce it on my device, and I can confirm that removing the sort from the query fixed the issue.

However, I forgot to prevent the objects from being re-pinned, so when I restarted my app, it worked normally. 

I'm sorry I can't provide more insight, but I'll comment here if it pops up again and I'm able to do more extensive debugging. 

In the meantime, if anyone else runs into this specific issue, it seems that removing the sort from the query can prevent a crash.
