### ISSUE TITLE
Putting together Parse 1.18.0 release.

### ISSUE THREAD

**Issue by noobs2ninjas** [parse-community/Parse-SDK-iOS-OSX#1482]
I was wondering if everyone could help me put together release notes. Also, wanted to make sure its cool with everyone that we change this version to 1.18. Seems a bit big to call it 1.17.4. 

Heres what I have so far.

- Removed using NSURLCache in Catalyst. @toto @mman 
- Add get and set server functions. @mtrezza 
- Parse is now compatible with Swift 5. @noobs2ninjas 
- Updated project build targets to work with Catalyst. @noobs2ninjas 
- Created, Updated, and released Bolts fork at [parse-community/Bolts-ObjC](https://github.com/parse-community/Bolts-ObjC) to allow Parse to move forward with new Swift and OS versions. @mman @noobs2ninjas 
- Parse as well as its dependencies are now compatible with macOS 10.15. @mman 

Where Parse's CI and CD are concerned @noobs2ninjas, @drdaz, and @acinader did some hard work to catch Parse back up with our Travis and Circle environments we can hopefully resume having a more regular release schedule.  

Thats just what I got from our commit history. Anything you guys could add would be great. Also, if I over simplified something let me know. Better yet, tell me what you'd like it to say instead!

@drdaz or @TomWFox do either of you know whats the status of Apple Sign In? Will it make it in once my PR goes in?

**Comment by noobs2ninjas** [comment]
I take it back. Travis isnt building but for some reason its from running release.

**Comment by mtrezza** [comment]
@noobs2ninjas Any breaking changes?

**Comment by TomWFox** [comment]
I generally don’t think it’s worth adding info about testing etc to release notes/changelog as it has little relevance to people using the SDK.

**Comment by noobs2ninjas** [comment]
@TomWFox easy for you to say. You didnt spend dozens of hours doing it! lol If you dont want me to add it I wont.

**Comment by noobs2ninjas** [comment]
@mtrezza shouldnt be any breaking changes. We now support swift 5, catalyst, apple sign-in(I think) and macOS 10.15 which we didn't before.

**Comment by mtrezza** [comment]
Amazing! Is support for Swift 5 and macOS 10.15 only relevant for SDK contributors or also for SDK users?

**Comment by noobs2ninjas** [comment]
@TomWFox help me remember. It's been a long time. Do we support just all versions of Parse server? or is there a minimum/max version we support?

**Comment by noobs2ninjas** [comment]
@mtrezza as far as I know using 1.17.3 with cocoapods will give you errors with Swift 5 and macOS 15. So will Parse's dependency Bolts. This new release will fix that.

**Comment by mtrezza** [comment]
@noobs2ninjas Great, maybe macOS 10.15 compatibility is worth mentioning in the notes.

Also, I think if a release has important changes for *contributors*, it's worth mentioning them in release notes as well, maybe under a separate section at the bottom. We want to keep contributors engaged and up-to date.

**Comment by TomWFox** [comment]
@noobs2ninjas I don't mean in any way that the work you and @drdaz have been doing isn't necessary or helpful - it is definitely both of those, its just that the changlog is there to show bugs/new features to help devs migrate to new versions and adopt features. But please do include a note about all the great work you've been doing getting the CI up to speed!

**Comment by TomWFox** [comment]
@noobs2ninjas I think the aim is to maintain backwards compatibility with Parse Server where possible, I don't think there is anything in this release that would change that?

**Comment by noobs2ninjas** [comment]
@TomWFox haha I was just giving ya a hard time. I wasn't thinking about it in terms of changlog. Although, I should have. For some reason I was in "newsletter" mode lol. I updated it. Tell me what you think. Need to get some issue links added too. 

Do you know the status of the Apple Sign-In? Think that will make it in?

**Comment by noobs2ninjas** [comment]
@TomWFox Thanks for the info on the server. I know those guys are constantly working and releasing updates. I was pretty sure we where compatible with that. Just wanted to make sure.

**Comment by TomWFox** [comment]
@noobs2ninjas 😅 looks good we can polish and add PR links etc in a PR to update the changelog when we’re ready.

The server guys to a good job at not making changes that would break the client SDKs

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by drdaz** [comment]
Apple Sign-In isn't ready for this release. I'll need to merge my Apple Sign In branch with the enormous conflicting changeset to master 😭. And I waited for master to work, so... I'll get to it as soon as I can.

**Comment by drdaz** [comment]
I'd honestly still call this 1.17.x tbh. There are no new features or bug fixes here, and I think that's usually a requirement for any kind of new versioning.

I'm using the current version in a project with Swift 5 and Xcode 11, and I'm seeing no warnings.

Maybe we could wait until Apple Sign In is done, and then there will actually be something new for users too?

**Comment by noobs2ninjas** [comment]
@drdaz I’m fine with the versioning either way. Also I’m fine with waiting for Apple Sign in. Whatever you guys think is best. I’m just exited to push out an actual release. Been way too long.

**Comment by noobs2ninjas** [comment]
@TomWFox of course! This release has just been in the works for so long I just wanted to make sure we didn’t forget anything or anyone. I’ll use previous release notes/change log as a guide to writing the new one.

**Comment by TomWFox** [comment]
Awesome, I say we go for 1.18.0, there is a new feature (from @mtrezza) + support for catalyst(ish?) + swift 5. It is pushing it a bit but you generally do a minor when new functionality is added ([semver](https://semver.org)) and we've been stuck on 1.17.x for ages 😅.

**Comment by TomWFox** [comment]
Personally I wouldn't hold out for Apple Sign In, its been too long since the last release and I think regularity is important for developer confidence & contributor motivation.

We can publish 1.19.0 with Apple Sign In.

**Comment by TomWFox** [comment]
Also, what is the status with the deploy phase of travis?

**Comment by drdaz** [comment]
Afaik, Parse/UI doesn't work with Catalyst... I had to disable the macOS 10.15 target in my Apple Sign In branch to work with it. Just an FYI.

**Comment by noobs2ninjas** [comment]
@TomWFox going to have to look at it. The big thing I need to look at is changing our podspec to pull from our fork. need to get my pull request merged before I can really look at it. Once thats done Ill take a look at travis to see if its ready to go.

**Comment by noobs2ninjas** [comment]
So the script to deploy to github isnt working on travis. Also, its being ran every merge for some reason. Do we need this fixed or are we going to manually upload?

**Comment by acinader** [comment]
@noobs2ninjas anything I can do to help out with Travis?

**Comment by noobs2ninjas** [comment]
@acinader That would be amazing! we got two things:

1. the deploy script that archives each target and uploads to github tries to run every time PR is made. It should only be doing it if there is a new release. 

2. That same script that keeps running also is failing. 

If you’d like to take a look at it I would be forever grateful.

**Comment by benpackard** [comment]
Correct me if I'm wrong, but I believe the Bolts fork will remove the use of deprecated `UIWebView`, which currently prompts a warning email for every App Store submission of an iOS build. If so, that might be worth calling out in the release notes since it is one of the main reasons I check back periodically on the project.

Regarding versioning - no strong opinion on the numbering except to say I'm in favor of releasing whatever is ready as soon as possible rather than waiting for Apple Sign In or any other changes that are not quite ready. Getting a 1.18.0 release out with a 1.18.1 quickly following behind would create some nice momentum (or 1.18.0 following 1.17.4).

**Comment by noobs2ninjas** [comment]
@benpackard that's the plan. We hit a brick wall with using our fork. The primary issue is that cocoapods doesn't allow use of git for dependencies. They only allow other pods or system frameworks. 

The good news is that Facebook has responded. We are getting maintenance access and a PR of Bolts with the removal of UIWebView etc has already been accepted. Now I just need to update the changelog and we will be good to go to put out a new release of bolts enabling us to put out a new release of Parse. 

As per following releases. I'd love to see one with Apple Sign In. Then follow that up another release with additional tuning for Catalyst on both Bolts and Parse.

**Comment by noobs2ninjas** [comment]
Ok so I got everything bolts needs to update. Going to start adding changlog and everything and get prepared for our own release. Did we decide that 1.18.0 is ok or do we want 1.17.4?

**Comment by TomWFox** [comment]
Awesome. 1.18.0
