### ISSUE TITLE
Circle Update

### ISSUE THREAD

**Issue by noobs2ninjas** [parse-community/Parse-SDK-iOS-OSX#1483]
So according to [this](https://discuss.circleci.com/t/rollout-of-pipelines-functionality/34651) article Circle is already in the process of enabling pipelines. They are also about to move everyone over to the new UI. What stinks about this is we will see nothing on the new UI unless we update our config to V2.

**Comment by noobs2ninjas** [comment]
Hopefully someone comes along who knows something.

**Comment by TomWFox** [comment]
So pipelines are enabled for all projects on the 9th, seems v2.1 is the most appropriate to update to.

**Comment by TomWFox** [comment]
I’ll try and spend some time today looking, but I know no more than you.

**Comment by noobs2ninjas** [comment]
I can probably get by on my own. It took me a lot of time time to figure this all out when I updated this the first time. It just would have been nice to save some time. I think you are right though. Since we have to update anyway we might as well do it to the absolute latest version.
