### ISSUE TITLE
Cocoapod Dependency Issue

### ISSUE THREAD

**Issue by noobs2ninjas** [parse-community/Parse-SDK-iOS-OSX#1484]
I was thinking about what else needs updated before our next release and realized we have a BIG problem  when it comes to our Podspec. The main issue being you cannot add git repos as dependencies to your Podspec. As some of you know, we had to create and update our own Bolts fork in order to make it compatible with the latest version of macOS and Swift 5. Being unable to update our Podspec means the original Bolts pod will be loaded instead causing lots of devs to encounter errors when building.

So, I need ideas on how we should tackle this. Should we just release our own Bolts pod? Should we just incorporate bolts right into our project files? @TomWFox or @drdaz can I get your thoughts?

**Comment by TomWFox** [comment]
Btw looks like they achieved the bolts-obj repo recently

**Comment by TomWFox** [comment]
Looking at the [license](https://github.com/facebookarchive/Bolts-ObjC/blob/master/LICENSE) I think we’d be ok to publish our own bolts pod.

**Comment by TomWFox** [comment]
I’m guessing getting the repo transferred hasn’t been successfully yet?

**Comment by noobs2ninjas** [comment]
@TomWFox 

Just sent another telling them that we saw it had been added to archive. Told them I hope it was done by someone who is unaware of our conversation. That it would be a real shame if they really did decide they'd rather bury the repo than turn it over to us. Specifically since the iOS Parse framework is the reason bolts was created to begin with. Anyway, I asked for a final answer one way or the other. I also asked if they are planning on keeping it are they planning on removing it from cocoapods.

**Comment by TomWFox** [comment]
Thanks for chasing it up! I’d say if we don’t hear from them in a few days we go ahead and publish our own.

**Comment by noobs2ninjas** [comment]
@TomWFox We got a reply! Joel said a bit about how things get archived and explained that it was probably their automated system. Then he said this:

"I will set up a meeting internally with Nikita and some others to discuss what we want to do with Bolts-Objc, understanding that you want it transferred to you. I am advocating that position, actually. We will also look at other Bolts-based repos as well." So, fingers crossed but it seems this may actually happen!

**Comment by TomWFox** [comment]
Awesome, great work chasing it up. Hopefully there will at least be a decision even if it’s not the one we want!

**Comment by noobs2ninjas** [comment]
They got back with me and they’ve proposed what I think is a perfect compromise. Let me hit you up on slack and I’ll give you the details. This is going to work out perfect.

**Comment by mgheraie** [comment]
Hello, I have the same problem. Did you found a solution?

**Comment by noobs2ninjas** [comment]
@mgheraie yup. We are already getting access to Bolts. They've accepted a PR and all I need to do is update the changelog so we can push a new release!
