### ISSUE TITLE
Xcode 11.4, App Store Upload Error - Minimum OS Version

### ISSUE THREAD

**Issue by terryworona** [parse-community/Parse-SDK-iOS-OSX#1491]
Updated to latest via `Carthage`: `github "parse-community/Parse-SDK-iOS-OSX"`. 

Screenshot attached when I try to upload to AppStore via Xcode archive tool:

<img width="734" alt="Screen Shot 2020-03-29 at 12 41 28 PM" src="https://user-images.githubusercontent.com/358709/77858820-b56e9380-71ba-11ea-835e-098e8d0296ae.png">

**Comment by drdaz** [comment]
What's the minimum OS version specified in your app's Info.plist? If it's below 8.0, this version of the SDK doesn't support that.

**Comment by terryworona** [comment]
My minimum deployment target is actually iOS 13. 

<img width="538" alt="Screen Shot 2020-03-29 at 12 50 31 PM" src="https://user-images.githubusercontent.com/358709/77859031-e602fd00-71bb-11ea-9461-c4d56f213871.png">

**Comment by TomWFox** [comment]
This seems odd. Can you check what the min version is for the Parse.framework info.plist? - it should be 8.0 but it would be good to check in case it’s been changed somehow.

**Comment by drdaz** [comment]
Yeah it's at 8.0.

**Comment by drdaz** [comment]
Hmm... ParseUI is at 7.0 ^^

**Comment by TomWFox** [comment]
@drdaz I was meaning @terryworona installation but useful to know about the Parse UI version!

**Comment by terryworona** [comment]
Parse-iOS
<img width="526" alt="Parse-iOS" src="https://user-images.githubusercontent.com/358709/77860748-b22cd500-71c5-11ea-8d00-5bcc98f391d8.png">

Parse-UI
<img width="539" alt="Parse-UI" src="https://user-images.githubusercontent.com/358709/77860754-b822b600-71c5-11ea-858d-e8917de7ef50.png">

ParseTwitter-Utils
<img width="534" alt="ParseTwitter-Utils" src="https://user-images.githubusercontent.com/358709/77860761-bce76a00-71c5-11ea-8010-602efc370d7a.png">

**Comment by terryworona** [comment]
@TomWFox: my `Parse.framework info.plist` is `iOS 6`. That's weird. 

<img width="583" alt="Screen Shot 2020-03-29 at 2 03 24 PM" src="https://user-images.githubusercontent.com/358709/77860820-236c8800-71c6-11ea-95b8-74bca4c6da05.png">

**Comment by terryworona** [comment]
Manually changing the `Parse.framework info.plist` to `8.0` resolved the issue (no surprise). 

Should this be bumped?

**Comment by terryworona** [comment]
Spoke too soon. Not sure if this is related?

<img width="688" alt="rejection" src="https://user-images.githubusercontent.com/358709/77861074-b0641100-71c7-11ea-842a-9d880882bfd2.png">

**Comment by TomWFox** [comment]
parseui should probably be bumped to 8.0, I’m not sure why  there is a different version on your first and third screen shot - are then not both of the main Parse-iOS info.plist

The Parse-iOS does have multiple platforms ([link](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Parse/Resources/Parse-iOS.Info.plist)).

**Comment by terryworona** [comment]
I completely cleared out my **Carthage** build folder and re-built everything. 

Still results in a `Parse.framework` `Info.plist` with a minimum version of `6.0`:

<img width="253" alt="Screen Shot 2020-03-29 at 2 59 57 PM" src="https://user-images.githubusercontent.com/358709/77862085-1bb0e180-71ce-11ea-886f-cfd687620eae.png">

Cartfile entry:

`github "parse-community/Parse-SDK-iOS-OSX"`

Running Carthage:

`$ carthage update --platform iOS --no-use-binaries`

**Comment by terryworona** [comment]
@TomWFox I saw your earlier comment in [1495](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1495) so I updated my Cartfile to point to `release-1.18.0`. 

I cleared my Carthage `build` folder and rebuilt: `carthage update --platform iOS --no-use-binaries`. 

Good news is that the app built and uploaded to Apple (no more minimum OS version error). But now I'm faced with another error from iTunes Connect:

<img width="713" alt="Screen Shot 2020-04-14 at 6 16 31 PM" src="https://user-images.githubusercontent.com/358709/79288667-347eef80-7e7c-11ea-956f-0b0221622ed6.png">

**Comment by TomWFox** [comment]
Ok, this appears to be the same issue faced in #1495 although I have no idea why you get this message via iTunes connect and they are getting it whilst uploading through Xcode.

I would suggest you also try removing “iPhoneSimulator” from CFBundleSupportedPlatforms so that it only contains “iPhoneOS”. You could do a project wide search for CFBundleSupportedPlatforms as it is present in multiple info.plist files.

**Comment by TomWFox** [comment]
I know this isn’t a long term solution but it would be good to see if you can successfully upload & deploy with those changes made.

**Comment by terryworona** [comment]
Works! I removed `iPhoneSimulator` from the `Parse.framework` `Info.plist`. 

<img width="477" alt="Screen Shot 2020-04-14 at 6 35 26 PM" src="https://user-images.githubusercontent.com/358709/79289697-dd2e4e80-7e7e-11ea-84c6-95046e1f416c.png">

**Comment by TomWFox** [comment]
Awesome, I know you're using Parse UI, it would also be good to know if you are using Facbook and/or Twitter Utils?

**Comment by TomWFox** [comment]
Also just to confirm you still have `iPhoneSimulator` in your `ParseUI` `Info.plist`?

**Comment by terryworona** [comment]
Hey @TomWFox -- unfortunately I don't use `ParseUI`, `FacebookUtils` or `TwitterUtils` - I only use `Parse.framework`.

**Comment by noobs2ninjas** [comment]
This is all super weird. The config files are supposed to be setting all these automatically when each target is runs throught the rake files. However, the actual info.plist on the projects arent updated. Which makes me wonder if half our config files arent actually being used.

**Comment by noobs2ninjas** [comment]
The next release will fix the minimum OS version as well. Parse 1.18.0 coming within the next day or so!

**Comment by TomWFox** [comment]
> Hey @TomWFox -- unfortunately I don't use `ParseUI`, `FacebookUtils` or `TwitterUtils` - I only use `Parse.framework`.

Thanks for the clarification, in that case I would suggest we also remove ‘iPhonesSimulator’ from the other files.
