### ISSUE TITLE
Could not export ipa using Carthage

### ISSUE THREAD

**Issue by rizumi** [parse-community/Parse-SDK-iOS-OSX#1495]
I using Parse-SDK-iOS-OSX with Carthage.
I have issue when export ipa file for iOS App.

![スクリーンショット 2020-04-14 11 54 49](https://user-images.githubusercontent.com/22917246/79193518-bca5ca80-7e65-11ea-90dd-9c8590c52765.png)

## Enviroment
Xcode 11.4
Carthage 0.34.0

**Comment by TomWFox** [comment]
This issue has been readied in #1491 so I’d like to keep any discussion about this over there.

**Comment by TomWFox** [comment]
However, just to say as a quick fix you could probably go and edit this [file](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Parse/Resources/Parse-iOS.Info.plist) and remove iPhoneSimulator on line 21.

**Comment by TomWFox** [comment]
You might need to remove it else where if you are using other dependencies e.g. https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/ParseUI/Resources/Info.plist
