### ISSUE TITLE
Not building on real device

### ISSUE THREAD

**Issue by hunterh37** [parse-community/Parse-SDK-iOS-OSX#1499]
Not building on real device, iOS 13.3 Xcode 11.3, Any fixes?

I even went back to multiple versions between now and version 1.15.3, all broken on app launch.. this is frightening after spending weeks building a prototype in simulator.

**Comment by drdaz** [comment]
Which version of the SDK did you install? How did you install it? What errors are you getting? What changes did you make immediately before the issue started?

**Comment by hunterh37** [comment]
I ended up fixing this - updated to iOS 13.4 and the app now builds on iPhone 11.  Previously the app did build fine using iPhone 6S iOS 12.x
