### ISSUE TITLE
Framework bundle not building, as instructed, out-of-the-box

### ISSUE THREAD

**Issue by konkontos** [parse-community/Parse-SDK-iOS-OSX#1501]
I'm running:

- macOS 10.15.4
- Xcode 11.4.1

Attempting to build manually the frameworks, as instructed.
Everything runs fine up to `bundle install`.

The last command (`bundle exec rake package:frameworks`) returns:

```
rake aborted!
LoadError: cannot load such file -- /Users/cookeecut/Desktop/Parse SDK Update/Parse-SDK-iOS-OSX/Vendor/xctoolchain/Scripts/xctask/build_task
/Users/cookeecut/Desktop/Parse SDK Update/Parse-SDK-iOS-OSX/Rakefile:10:in `require_relative'
/Users/cookeecut/Desktop/Parse SDK Update/Parse-SDK-iOS-OSX/Rakefile:10:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/lib/rake/rake_module.rb:29:in `load'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/lib/rake/rake_module.rb:29:in `load_rakefile'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:703:in `raw_load_rakefile'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:104:in `block in load_rakefile'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:103:in `load_rakefile'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:82:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

My Ruby is: `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]`

**Comment by drdaz** [comment]
I'm running the same versions, and I'm not seeing this. I'm seeing other issues related to Simulators though. I'm working on a PR to fix.

I'm not sure if this will help, but for your own sanity, don't have spaces in the names of your files and folders. That breaks things where you least expect it.

**Comment by konkontos** [comment]
@drdaz 
Many thanks for your quick response 🙏
Spaces in the path, was the problem.
Simulators issue is there. I edited `Rakefile` and `build_third_party.rb` and all targets built except for `ParseUI`.

It fails with:

`error: Multiple commands produce '/Users/cookeecut/Desktop/Parse-SDK-Update/Parse-SDK-iOS-OSX/build/iOS/Release-ios-iphoneos/Bolts.framework/Bolts':
`

**Comment by drdaz** [comment]
Umm... that's not the issue that I'm seeing 😃

The thing I'm fixing involves the build not being able to find the right Simulator version for all the builds using the current Xcode release. That looks like something else...

Did you manually install older Simulators to get the script to run? Do you have simulator versions 13.2.2 installed?

**Comment by konkontos** [comment]
No. I just edited the old OS spec. in the scripts (e.g. 13.2.2) to much what I have (13.4.1).

**Comment by drdaz** [comment]
Ahh ok. That's basically what I'm fixing with my PR.

I don't see the issue you're presenting here; the package:frameworks command finishes without error here. I also don't recognise it... is the message translated?

**Comment by konkontos** [comment]
No. Straight copy-paste. 
Still trying to see if I can figure it out. 
Will post if I have anything.

**Comment by konkontos** [comment]
Switching `Parse.xcworkspace` to `legacy build system` seems to have resolved the issue.
Not sure why 🤷‍♂️

**Comment by drdaz** [comment]
🧐

I suspect there's something fishy going on with your development environment if that's necessary. Try doing this on a clean system; you shouldn't need to do that.

**Comment by konkontos** [comment]
Will look into it though I find this unlikely. 
I'm not installing anything else other than Xcode on this machine, and only final builds via App Store.
I'm even very reluctant to manually build Parse (doing it for the first time) because I had to install `unknown` Ruby gems 😁.

Anyway, I'm now having another issue: unable to build my test app with the new frameworks
(Bolts framework not found).

**Comment by drdaz** [comment]
Is this still an issue?

Looking through this, I should ask, how did you get the code? From a release package or from master?

**Comment by konkontos** [comment]
Master.

It's been sometime since my last post, so I can't recall the exact details of what I did.
I finally managed, somehow, to resolve the issue, but not by simply following the regular build process outlined in the README. This would not work for me , no matter what I did. 

I'm sorry I can't go into more detail - I'll make another attempt at it when I have the time and document my steps. This is important for us, as well, as Parse is critical to our work.

**Comment by konkontos** [comment]
Just downloaded the 1.19.0 release.

After running `bundle exec rake package:frameworks` build process fails with the following error:

```
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/cookeecut/Downloads/Parse-SDK-iOS-OSX/build/Release-ios-iphoneos/Parse.framework/Parse and /Users/cookeecut/Downloads/Parse-SDK-iOS-OSX/build/Release-ios-iphonesimulator/Parse.framework/Parse have the same architectures (arm64) and can't be in the same fat output file
Failed to lipo iOS framework.
```
