### ISSUE TITLE
Please update dependency for FBSDK to 6.x

### ISSUE THREAD

**Issue by markuswinkler** [parse-community/Parse-SDK-iOS-OSX#1503]
Hi,

Great job on the 1.18.0 release!
One slight oversight, the FB SDK is on 6.x for a while now, not 5.x.
Can you please update the dependency?

Thanks,
Markus

**Comment by TomWFox** [comment]
Would you be willing to make a PR?

**Comment by markuswinkler** [comment]
@TomWFox done

**Comment by brunomunizaf** [comment]
Please merge this 🙏
