### ISSUE TITLE
When adding a relation with the same keyword as the Class name, related objects doesn't save properly.

### ISSUE THREAD

**Issue by jaysonng** [parse-community/Parse-SDK-iOS-OSX#1508]
So I've been testing out creating and pulling data from Parse and I was stuck for quite a bit on the creating a relationship between my object using PFRelation (not Pointer).

I finally got it working when I changed the name of my key to something other than the Classname. 

I started out with

```
let tag = post.relation(forKey: "tag")
tag.add(PFObject(withoutDataWithClassName: "Tag", objectId: "0ngpdctMer"))
```

But saving this gives me a WHITE SCREEN when I try to access the relationship via the Parse backend . 

<img width="191" alt="Screen Shot 2020-05-08 at 6 00 51 PM" src="https://user-images.githubusercontent.com/440445/81395468-4475b080-9156-11ea-9b75-84c3701af355.png">

It took me while but I fixed this by simply renaming my column from "tag" to "tags" on my object. Still pointing to the Tag class.

<img width="189" alt="Screen Shot 2020-05-08 at 6 01 16 PM" src="https://user-images.githubusercontent.com/440445/81395545-6a02ba00-9156-11ea-9b9a-6ca492344eb6.png">

This now works fine and I can see the related tags to my object with no problems, no White Screen of Death.

```
let tag = post.relation(forKey: "tags")
tag.add(PFObject(withoutDataWithClassName: "Tag", objectId: "0ngpdctMer"))
```

So I'm assuming somewhere deep in Parse's code there's bug that doesn't account for case sensitivity ?

**Comment by noobs2ninjas** [comment]
You mean the column is case insensitive? Or the class name? @drdaz do you have any insight on this?

**Comment by jaysonng** [comment]
I'm sorry, I don't know if it a dashboard only problem. Though I should have thought of that and tried testing pulling the data. I didn't get to. But I was already frustrated and kept getting the white screen on the dashboard and was just relieved when I got it working. :O

**Comment by jaysonng** [comment]
so I did a few more tests now, reverting back my code to try and recreate this, I don't believe it even saves the relationship at all as retrieving the object after saving gives me:

`found tags are: 
Optional([])`

as compared to normally saved objects

`found tags are: 
Optional([<Tag: 0x600000df0c00, objectId: 1MzD26nxWH, localId: (null)> {\n    relatedTags = \"<PFRelation: 0x600002823580, 0x0.(null) -> Tag>\";\n    tag =.... <TRUNCATED>"`

So problem might be during saving the object.
