### ISSUE TITLE
Bolts dependency uses the deprecated UIWebView

### ISSUE THREAD

**Issue by dotWasim** [parse-community/Parse-SDK-iOS-OSX#1510]
New apps that use UIWebView are no longer accepted. Bolts dependency uses UIWebView.

**Comment by drdaz** [comment]
Try release 1.18.0. This should be fixed.

**Comment by noobs2ninjas** [comment]
Yes the bolts version that fixes this is 1.9.1

**Comment by dotWasim** [comment]
thanks
