### ISSUE TITLE
Cocoapods is broken on master

### ISSUE THREAD

**Issue by drdaz** [parse-community/Parse-SDK-iOS-OSX#1512]
While working on Apple Sign In, I'm trying to test the login feature in a project using Cocoapods. It doesn't build. When I switch branches from mine to master, the issues persist. Looks like that update to the new FB libs didn't go by without causing some damage 😬. 

First build fails like this:
<img width="610" alt="Screenshot 2020-05-21 at 14 29 11" src="https://user-images.githubusercontent.com/845731/82559185-71bb5900-9b6f-11ea-90c5-3b8d85048171.png">

Next build fails like this:

<img width="603" alt="Screenshot 2020-05-21 at 14 29 53" src="https://user-images.githubusercontent.com/845731/82559239-8bf53700-9b6f-11ea-9a06-4a1c0e0a7ad1.png">

Podfile:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tester' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tester
  pod 'Parse', :path => '~/Documents/Development/Others/Parse-SDK-iOS-OSX'
  pod 'Parse/UI', :path => '~/Documents/Development/Others/Parse-SDK-iOS-OSX'
  pod 'Parse/FacebookUtils', :path => '~/Documents/Development/Others/Parse-SDK-iOS-OSX'
  
  target 'TesterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TesterUITests' do
    # Pods for testing
  end

end
```

**Comment by drdaz** [comment]
@noobs2ninjas Could you have a look at this? I've thrown quite a few hours at this, and I'm no wiser 🙁. There aren't actually duplicate definitions that I can see. So this is the result of *something* else.

To reproduce, make a Tester app and use the Podfile included here to install pods. Then build.

This should cause a failing test tbh.

**Comment by drdaz** [comment]
@noobs2ninjas This is a blocking issue - we can't release any changes as long as this persists. Could you please look at this?

**Comment by noobs2ninjas** [comment]
I started a brand new project and linked to my files from path set to master after switching from your branch. Everything works fine. What is strange to me is that you have Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal. Seems like you have framework folders nested inside of framework folders. Also, there is no Internal inside of FBSDKCoreKit anymore. 

<img width="235" alt="Pods_xcodeproj" src="https://user-images.githubusercontent.com/3413855/85686083-44455c00-b695-11ea-8dbe-049a2c3b3430.png">

Not sure if its the version of cocoapods that you use or maybe your cocoapod repos are out of date as pod update and pod install doesnt update cocoapods anymore. 

Heres where I am

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
    RubyGems : 3.0.8
        Host : Mac OS X 10.15.5 (19F101)
       Xcode : 11.5 (11E608c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/nathankellert/.rvm/rubies/ruby-2.6.6/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 7d193f9a1589d29549e3aea7891956270823c695
```

Heres my Podfile. Still says Tester on it. I didnt add unit tests or anything though.

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testmaster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tester
  pod 'Parse', :path => '~/Desktop/Parse-SDK-iOS-OSX'
  pod 'Parse/UI', :path => '~/Desktop/Parse-SDK-iOS-OSX'
  pod 'Parse/FacebookUtils', :path => '~/Desktop/Parse-SDK-iOS-OSX'


end
```

**Comment by drdaz** [comment]
Thanks! Interesting to hear that it works for you. Hopefully this is a red herring and something specific to my environment then. I'll give it another try soon with a fresh project and perhaps a different machine to see.

It does look odd with the triple-nested files - I didn't notice that. My pod command is at 1.9.1.

**Comment by noobs2ninjas** [comment]
Actually, whats strange is that its trying to build from ParseUI/Vendor. In my file system I dont have frameworks in the vendor folder anymore.

**Comment by drdaz** [comment]
Really? Because this build script puts them there...

<img width="1870" alt="Screenshot 2020-06-25 at 11 18 31" src="https://user-images.githubusercontent.com/845731/85692337-9c9c4e00-b6d5-11ea-9f50-4a08709c8c3c.png">

**Comment by drdaz** [comment]
<img width="1864" alt="Screenshot 2020-06-25 at 11 25 37" src="https://user-images.githubusercontent.com/845731/85693505-99559200-b6d6-11ea-9e80-293d972a175a.png">

This script puts files in there by the looks of things. So I guess this could be a complication from building ParseUIDemo first in the source repo, then building from that repo in my tester.

**Comment by noobs2ninjas** [comment]
When I try to build the demo it gives me a whole bunch of different erros about duplicate commands building bolts. Looking at its framework linking, it hasnt been touched in a very very long time.

**Comment by noobs2ninjas** [comment]
Now I get why the additional fbsdk is in vendor but it doesnt explain why its trying to build all those different ones. It feels like something is out of date. Go to carthage.resolve and make sure that fbsdk shows that its over 6.0.

**Comment by drdaz** [comment]
Yeah it's a mess. I did get it to build here last time I toyed with it. But it runs that script before compiling our code... so I'd guess that there are files in ./Vendor after build.

**Comment by noobs2ninjas** [comment]
Oh wow. So, this is what is happening. So, the vendor file on my end is a group that just links the frameworks from the root directory. When you call the archive site, it downloads facebook 4.40.0. The last version that facebook hosted themselves. Now they are setup much like us. Maintain and host the files and release archives on [github](https://github.com/facebook/facebook-ios-sdk). Currently we are supporting version 6.5.  So, I now get why your file system is so messed up. The place its pulling from how has an old version in an actual folder called Vendor.

**Comment by noobs2ninjas** [comment]
Really now that we are using carthage we shouldnt be pulling the latest version of anything and just use whats on our Carthage.resolve and our Podspec. That eliminates 3rd party dependencies as a root cause.

**Comment by noobs2ninjas** [comment]
Want me to fix this thing up?

**Comment by drdaz** [comment]
> Really now that we are using carthage we shouldnt be pulling the latest version of anything and just use whats on our Carthage.resolve and our Podspec. That eliminates 3rd party dependencies as a root cause.

The thing is it's grabbing those libs from there because they're static builds. The alternative would be building them ourselves I suppose.

The FacebookUtils project has been updated to grab the newest binaries from the correct place.

**Comment by drdaz** [comment]
Super cool we're seeing the cause now though. That was really confusing 🤪
