### ISSUE TITLE
Unexpected error logging to console when getFirstObjectInBackground fails

### ISSUE THREAD

**Issue by benpackard** [parse-community/Parse-SDK-iOS-OSX#1513]
When using `getFirstObjectInBackground` to fetch a query, and that query has no matching results, the SDK logs "[Error]: No results matched the query. (Code: 101, Version: 1.17.3)" to the console.

I am not aware of any other places where the SDK logs errors that it encounters rather than letting the developer decide what to do with them. In my case, I would prefer to trap this particular error code and consider it successful - but I can't avoid having an error logged to my console, which every few months I re-discover and spend a half hour trying to figure out what went wrong.

By comparison, `countObjectsInBackgroundWithBlock` uses the same logic (count of `0` is considered an error by the SDK), but does not log anything to the console.

I thought this would be easy to find and am willing to create a PR, but couldn't figure out where this is being logged from. Any pointers?

**Comment by drdaz** [comment]
It gets logged in PFErrorUtilities.m and is triggered by both the getFirstObjectInBackground and getObjectInBackgroundWithId commands.

> I am not aware of any other places where the SDK logs errors that it encounters rather than letting the developer decide what to do with them.

You're getting a BFTask returned with that method, so you can handle the error how you want (or just ignore it by only using a continueOnSuccess method). And all errors in the SDK are logged to the console... I'm not sure how this is any different?

**Comment by benpackard** [comment]
> By comparison, countObjectsInBackgroundWithBlock uses the same logic (count of 0 is considered an error by the SDK), but does not log anything to the console.

Thank you, I was mistaken - there is no error for a `count` of `0`, which is why none was logged.
