### ISSUE TITLE
Error attempting to .pin() a new object. Old objectId is (null).

### ISSUE THREAD

**Issue by ritteraf** [parse-community/Parse-SDK-iOS-OSX#1514]
I have a class, `UserRelationship` which is a subclass of `PFObject`
I ran a simple test where I tried to create a single `UserRelationship` object, save it, and .pin() it. The logic is as follows:

1. Create the new `UserRelationship` object
2. Save the new `UserRelationship` object in the background
3. The creation of the new `UserRelationship` triggers a LiveQuery `Event.created()` block
4. In the `Event.created()` block, I check if the object is in the local datastore with a `PFQuery()`
5. If the object is not in the local datastore, then it is `.pinned()`
6. If it is in the local datastore, the object is ignored.

Running with this logic, the new `UserRelationship` is showing within the `Event.created()` block that it is not in the local datastore, and attempts to `.pin()` it. That is when the following error occurs:

`2020-06-03 14:44:06.650707-0500 SwagLeagues[1378:21947] [Error]: Attempted to change an objectId to one that's already known to the OfflineStore. className: UserRelationship old: (null), new: BjFwzHD4s7`

I triple and quadruple checked, and I am in no way calling a `.pin()` on the object except in the `Event.created()` block. The only logical explanation I can think of is that Parse is adding a sort of "placeholder" object, with no objectId, in the local datastore when I create the new UserRelationship object. That "placeholder" object is then conflicting with my attempt to `.pin()` the object post save to the local datastore.

Is this behavior intentional? If my logic is flawed, please correct me, but I feel this is a bug. Thanks.

Full context on how I came to this error can be found at:
https://stackoverflow.com/questions/62179454/swift-parse-platform-error-attempting-to-pin-an-object-to-local-datastore

EDIT 1:
After doing a bunch more testing.... I'm starting to draw a conclusion I don't like. There are some instances where the new object is pinned successfully without issue, and others where the error occurs. It APPEARS that the 'UserRelationship' objects that are causing this error are ones where the relationship previously existed in the offline storage, and the "ghost" of their existence is causing this error.

Let me explain:
In order to "flush" the offline storage for testing, I have been deleting the app off the device/simulator, assuming this would completely clear any and all data tables stored by the app. I would then rebuild the app on the device/simulator, assuming I had fresh and clear offline storage database tables.

This appears to not be the case. Does deleting the app not completely destroy any offline storage database tables created by the app?

Edit 2:
I found the option in the simulator to "Erase All Content And Settings". I performed this on the simulator and then ran the app. The error is still occurring sporadically, but I now know the issue cannot be blamed on some sort of "ghost table" existing through deletion/installation.

**Comment by noobs2ninjas** [comment]
@ritteraf Thanks for doing some research. 

Your findings seem to fall in line with our pin unit tests randomly passing or failing. You're running on iOS right?
