### ISSUE TITLE
App Store submission failed for MinimumOSVersion

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-iOS-OSX#1515]
After building the Parse iOS SDK with Carthage on Xcode 11.5 I get this error when validating the app for App Store submission:

![image](https://user-images.githubusercontent.com/5673677/83978491-1bd50800-a908-11ea-8a65-460e18c95a3c.png)

The solution was to manually bump the `MinimumOSVersion` in `ParseFacebookUtilsV4.framework/Info.plist` from `6.0` to `8.0`.

I am surprised that it matters at all because the app's deployment target is iOS 11.1. Maybe Swift 5 does not support iOS 6 anymore?

**Comment by noobs2ninjas** [comment]
I looked into this. I did a project wide search for 6.0 and couldnt find it anywhere. Everything said 8.0. I then went through every config file and ever info.plist just in case and couldnt find anything there either. I didnt check archives for 1.18.0 but at least for master its not in there.

**Comment by mtrezza** [comment]
@noobs2ninjas True, the `Target Version` in Xcode is correctly set to `8.0`, so the `MinimumOsVersion` should be the same. I can't build with carthage currently to test, but the issue was probably the carthage cache. Closing for now.

**Comment by mtrezza** [comment]
I only now had a change to retry, and the same issue occurred.

I'm using carthage version: 0.35.0 and building with:
```
carthage update --platform iOS
```

The `ParseFacebookUtilsV4.framework/Info.plist` has set `MinimumOSVersion: 6.0`:

![image](https://user-images.githubusercontent.com/5673677/87237206-a15e4300-c3f3-11ea-9236-58357b8d5103.png)

Also the `ParseTwitterUtils.framework/Info.plist` has set `MinimumOSVersion: 6.0`.
But the `Parse.framework/Info.plist` has set `MinimumOSVersion: 8.0`.

**Comment by mtrezza** [comment]
It seems the SDK references some plist files for FB and Twitter Utils where the minimumosversion was directly set to 6.0. I changed it to 8.0.
