### ISSUE TITLE
Important changes for ReadMe and Docs in  upcoming SwiftUI changes.

### ISSUE THREAD

**Issue by noobs2ninjas** [parse-community/Parse-SDK-iOS-OSX#1517]
For the upcoming Swift 5.3/XCode 12. SwiftUI applications by default will no longer have an app delegate. Instead, this is what is created by default.

```
@main
struct Xcode12TestApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

Since Apple is now pushing to use purely SwiftUI and move away from UIKit including storyboard and controllers. I feel we need to do some testing on how to initialize Parse, ParseFacebookUtils, and ParseTwitterUtils to work with SwiftUI. We then need to update our docs and ReadME, the later of which is way overdue for an update anyway..

**Comment by jbhannah** [comment]
In my tinkering, the following works just fine for initializing Parse in a pure-SwiftUI app:

```swift
import Parse
import SwiftUI

@main
class Xcode12TestApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }

    required init() {
        let config = ParseClientConfiguration { … }
        Parse.initialize(with: config)
    }
}
```

**Comment by noobs2ninjas** [comment]
Thanks @jbhannah for doing that! That is seriously helpful.

I think the most important thing is that we test facebook initialization and how it works within facebook utils. I'm betting we need to add documentation explaining that using a @main class will not work and an @UIApplicationMain app delegate will be required in order to initialize facebook and handle URI callbacks properly when being routed back to the application after logging in.

**Comment by Vortec4800** [comment]
Just to add to the conversation, you can add a traditional AppDelegate to a pure SwiftUI app as follows:

https://www.hackingwithswift.com/quick-start/swiftui/how-to-add-an-appdelegate-to-a-swiftui-app

```swift
class AppDelegate: NSObject, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        print("Your code here")
        return true
    }
}
```

```swift
@main
struct NewIn14App: App {
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

Note the `@UIApplicationDelegateAdaptor` which defines what object to use as the AppDelegate.

I'm not sure which is Better™ but just wanted to bring up an alternative method.
