### ISSUE TITLE
ParseTwitterUtils PFOAuth1FlowDialog uses deprecated UIWebView

### ISSUE THREAD

**Issue by davewhipps** [parse-community/Parse-SDK-iOS-OSX#1524]
This results in any new apps that use Parse-UI on iOS to be rejected from the AppStore.

I have a fork with most of this fixed, but writing unit tests for WKWebView in general and its use in PFOAuth1FlowDialog in particular are really ugly.

**Comment by drdaz** [comment]
Could you make a PR with the changes once you've gotten it working?

It looks like there's only one test this will break - testWebViewDelegate. It's the only test that directly does things with the UIWebView. WKWebView also has delegates, that should do at least equivalent things, so the test should be fixable.

**Comment by davewhipps** [comment]
I also don't have any kind of a test environment for this besides the unit tests. I have no way of checking any of it without building it into an app. ParseTwitterTestApplication doesn't seem to do anything.

**Comment by drdaz** [comment]
It was a unit test I was referring to. Only one of those looks like it will break due to these changes.

**Comment by davewhipps** [comment]
> It was a unit test I was referring to. Only one of those looks like it will break due to these changes.

Yes, but it would be nice for me to be able to see my changes in action somewhere. I'm kinda coding blind here.

I'll make a PR and we can discuss.

**Comment by dwhipps** [comment]
> It was a unit test I was referring to. Only one of those looks like it will break due to these changes.

Looks like someone has already done it, here:

https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1511/commits/da2c9572357041dd090c3dec276b9df0f12fbc6e

Do you still want me to issue a PR? This one is pretty good.

**Comment by dwhipps** [comment]
> It was a unit test I was referring to. Only one of those looks like it will break due to these changes.

I realize I'm now logged in with my work address, but it's still me. I see that the above PR is failing tests, but those tests failed for mine too (and failed BEFORE I did any work.)

**Comment by drdaz** [comment]
> I realize I'm now logged in with my work address, but it's still me.

You and your username look the same from here :)

> I see that the above PR is failing tests, but those tests failed for mine too (and failed BEFORE I did any work.)

It's ok. They've been failing for a while. I've got a PR waiting for review that should get that under control.

Are your changes more complete / ready for production than the PR we already have?

**Comment by dwhipps** [comment]
> Are your changes more complete / ready for production than the PR we already have?

No. In fact, they look almost exactly the same as mine, and they include the Unit Tests that I wasn't looking forward to writing. The sooner the better!

**Comment by dwhipps** [comment]
Any update on this PR? I'm hoping to pull and release a beta of my product this week!

**Comment by drdaz** [comment]
@dwhipps Sorry no. I think you're going to have to go with a patched version for your beta.

**Comment by dwhipps** [comment]
Just bumping this again. Any chance this PR will be accepted any time soon?

**Comment by drdaz** [comment]
1.19.0 was released this week with the fix :)

**Comment by dwhipps** [comment]
This is still broken somewhere (perhaps Bolts? Apple doesn't say), but my app is still being rejected from the store because of UIWebView usage.

**Comment by drdaz** [comment]
Are you certain you’re running 1.19.0?

**Comment by dwhipps** [comment]
My mistake. This was another library altogether, which was also using UIWebView (an older version of OneSignal.framework if you're curious.) Sorry for the false alarm. Apple doesn't say **_where_** they found the problem, so it's been a lot of frustrating trial and error.
