### ISSUE TITLE
Parse iOS SDK setServer function not working

### ISSUE THREAD

**Issue by AliZahr** [parse-community/Parse-SDK-iOS-OSX#1528]
[Parse setServer:@"https://serverNewUrl.com"];
NSLog(@"%@",Parse.server); -----> This prints the new server set, i.e https://serverNewURL.com
NSLog(@"%@",Parse.currentConfiguration.server); -----> This prints the old one set, i.e https://oldServerURL.com

I am using Parse iOS SDK 1.18

**Comment by mtrezza** [comment]
Thanks for reporting.


I have not looked into the implications of this bug yet but the feature underwent a lot of testing and there were no issues found. My initial guess is that the `currentConfiguration` is not used internally but for the developer to read the configuration, that’s why it would not have an implication on the actual feature, but that is just my guess as of now.

**Comment by AliZahr** [comment]
If someone was able to implement it and get it to work, please guide me through it if I have missed something.

**Comment by mtrezza** [comment]
As I said erlier, the server URL should be changed correctly, it just seems not to be updated in the `currentConfiguration`. You could read the property `serverUrl` instead until the bug is fixed.

**Comment by AliZahr** [comment]
> As I said earlier, the server URL should be changed correctly, it just seems not to be updated in the `currentConfiguration`. You could read the property `serverUrl` instead until the bug is fixed.

Correct me if I got this wrong.
After setting the server url, queries should pass through the new parse server right? When I print Parse.serverUrl, I can see the new url set but when turning verbose on the new server, no query is passing through it while I can confirm its flow through the old Parse server.
The use case is using different parse servers for different languages.

**Comment by mtrezza** [comment]
Thanks for clarifying and investigating. In that case my previous assumption was wrong. We'll need to look into this further. Do you think you could write a failing test case for this?

**Comment by AliZahr** [comment]
> Thanks for clarifying and investigating. In that case my previous assumption was wrong. We'll need to look into this further. Do you think you could write a failing test case for this?

Do you want me to follow any kind of guide for writing a failing test? Or it would be sufficient if I provide code to replicate the issue?

**Comment by AliZahr** [comment]
Any update on this?

**Comment by mtrezza** [comment]
@AliZahr Apologies, I missed your previous comment.

> Do you want me to follow any kind of guide for writing a failing test? Or it would be sufficient if I provide code to replicate the issue?

If you take a look at `ParseClientConfigurationTests.m` you can see existing tests and how they are written. If would be great if you could open a PR and add failing test case for the scenario you described above. If you need further guidance you can also look at other tests in the `Tests/Unit` folder, or let us know here.

**Comment by mtrezza** [comment]
Turns out that the SDK needs to be reinitialized to change the server URL. It's not possible to change it in the configuration since the URL is passed on and stored in many controllers that are only initialized with the SDK initialization.
