### ISSUE TITLE
Release version of the updated Bolts.framework (Parse-iOS)

### ISSUE THREAD

**Issue by UnlikelySassou** [parse-community/Parse-SDK-iOS-OSX#1534]
Hello,

I need to submit an update to the App Store, but my project includes a version of the SDK that still uses Bolts.framework with UIWebview.

It seems like this issue has been fixed in version 1.18.0, but I can't find the updated Bolts.framework. In previous releases (https://github.com/parse-community/Parse-SDK-iOS-OSX/releases), the zip file always contained Bolts.framework and Parse.framework, but it is not the case for the latest release.

Any help would be greatly appreciated,

Thanks

**Comment by jaysonng** [comment]
you can't use Parse SDK version 1.18?

**Comment by spiderguy84** [comment]
I'm curious on this as well. The starter packs for tvOS includes a link to where frameworks should be, but they're completely missing.
