### ISSUE TITLE
Parse pod does not compile on Xcode 12.0 beta 6 

### ISSUE THREAD

**Issue by kyralesov** [parse-community/Parse-SDK-iOS-OSX#1536]
After just recently updating to the new Xcode 12.0 beta 6  I am unable to build my project withe Parse SDK pod. 
Compiler error given in ParseClientConfiguration.m is:
Incompatible block pointer types sending 'void (^)(ParseClientConfiguration *__strong)' to parameter of type 'void (^ _Nonnull)(id<ParseMutableClientConfiguration>  _Nonnull __strong)'

Parse (1.18.0)

**Comment by ZacharyKhan** [comment]
Experiencing the exact same issue here

**Comment by TomWFox** [comment]
This is a duplicate of #1526, the issue was fixed by #1527 which has been merged into the master branch. Whilst you wait for the next release you could switch your podfile to the master branch.
