### ISSUE TITLE
Iterate through all Parse subclass properties. Eliminate "This object is not available in the offline cache" error once and for all!

### ISSUE THREAD

**Issue by ritteraf** [parse-community/Parse-SDK-iOS-OSX#1537]
I've been battling issues with Parse pinning for months now. It's literally gridding my development to a halt every every couple of days. I'm experiencing a constant battle with the error "This object is not available in the offline cache" when trying to fetch a pinned object, with name, from local storage.

From what I've been able to gather, this error occurs when you pin an object to offline storage, without fetching all of the pointed objects first, which creates a null reference in the offline storage, producing this error. I'm smashing my head against the wall trying to defeat this error once and for all. I've tried everything I can think of up to and including unpinning and repinning every object every time it is fetched (using both unpin() and unpin(withName:)), double triple and quadruple checking my includes list, and testing every object with isDataAvailable before pinning. One day it's working fine, the next the error resumes on the same class, or a different one.

I've concluded that the only way I can know FOR SURE that I have included every possible pointer object when fetching and pinning objects is to try an iterate through every property through my custom parse object subclass, check if the property is a PFObject or PFUser, and return an array of all property names matching that criteria for use in my query's include list. I would then use this custom function on every parse subclass to know for absolute certain I have included every possible pointer.

After researching this possibility, I've found the following:
https://stackoverflow.com/questions/27928279/how-to-list-all-variables-of-a-class-in-swift

It uses Swift's `Mirror(reflecting: self)` feature to list all the class properties. This approach, however, is not working. I'm assuming this is due to the fact that PFObject is a objc class. Using `MyObject.keys` does not work as well, since this only includes a property list of an instance of the class, and what properties that particular object is using.

Any... ANY help here is appreciated. I'm sure that my understanding of the "This object is not available in the offline cache." error is incomplete, but I'm struggling to find any help or documentation on how to nip this error in the bud. Am I on the right track with the above thought? If so, how would I get this parse subclass property list?

**Comment by drdaz** [comment]
Sorry for the complete lack of response.

Did you get this working?
