### ISSUE TITLE
Update configuration on the fly

### ISSUE THREAD

**Issue by Neirys** [parse-community/Parse-SDK-iOS-OSX#1539]
Hello,

I need to update the Parse configuration (server url, app ID, client key) on the fly for my use case.

I have forked the repo and removed the following line `PFConsistencyAssert(![self currentConfiguration], @"Parse is already initialized.");` which worked straightforward.
However, some comment said that `Re-setting the configuration after having previously sent requests through the SDK results in undefined behavior.`

Could you help me trying to understand what could be the possible problems I could run into by doing that ?

Thanks!

**Comment by jaysonng** [comment]
I'm not a Parse expert so I don't think i can help you out. but I am curious as to what you mean by updating the configuration on the fly means. 

Are you developing an app that you want to be able to connect to different Parse databases depending on the view / push of a button?
