### ISSUE TITLE
Where are frameworks for tvOS?

### ISSUE THREAD

**Issue by spiderguy84** [parse-community/Parse-SDK-iOS-OSX#1540]
I look at this and readme, and should have some frameworks that work with tvOS, but they're not there. Even in the starter project FOR tvOS, doesn't include the frameworks. It has them in the app, and gives a path for where they should be, but they're not actually there.

**Comment by drdaz** [comment]
Unfortunately we've been having issues with our release scripts, so the release assets aren't attached to the release. As I see it you've got a couple of options for getting binaries to use in your project:

- Build the frameworks from source and manually include them as described [here](https://github.com/parse-community/Parse-SDK-iOS-OSX#compiling-for-yourself) 
- Use a package manager (eg Cocoapods or Carthage)
