### ISSUE TITLE
Xcode 12 release compiling failed

### ISSUE THREAD

**Issue by beiguancyc** [parse-community/Parse-SDK-iOS-OSX#1545]
Using Xcode 12 release compiling for an iOS Simulator running iOS 14, the app cannot compile when the Parse pod is installed.

Repro steps
pod 'Parse','~> 1.19.0'
Then build and run,
![image](https://user-images.githubusercontent.com/12932389/93421263-6ee53080-f8e3-11ea-8b28-d68b0c0eb992.png)

**Comment by idefen1** [comment]
I'm getting compile errors also, but a different error:

File: ParseClientConfiguration.m

Method: - (instancetype)copyWithZone:(NSZone *)zone

Error: Incompatible block pointer types sending 'void (^)(ParseClientConfiguration *__strong)' to parameter of type 'void (^ _Nonnull)(id<ParseMutableClientConfiguration>  _Nonnull __strong)'

Anyone else seeing this one? I'm still using Objective-C

**Comment by beiguancyc** [comment]
> Got it.
> 
> Switch '@import Bolts' to '#import <Bolts/Bolts.h>' and my project compiled.
> 
> Hope this helps.

That is not a good idea

**Comment by idefen1** [comment]
> > Got it.
> > Switch '@import Bolts' to '#import <Bolts/Bolts.h>' and my project compiled.
> > Hope this helps.
> 
> That is not a good idea

I'm sorry =\ I don't know what else to do... I need to compile my code and this is the only way I can get it to work. Maybe someone else will help us find a fix.

**Comment by beiguancyc** [comment]
> > > Got it.
> > > Switch '@import Bolts' to '#import <Bolts/Bolts.h>' and my project compiled.
> > > Hope this helps.
> > 
> > 
> > That is not a good idea
> 
> I'm sorry =\ I don't know what else to do... I need to compile my code and this is the only way I can get it to work. Maybe someone else will help us find a fix.

I think it will be fixed soon.

**Comment by idefen1** [comment]
> > > > Got it.
> > > > Switch '@import Bolts' to '#import <Bolts/Bolts.h>' and my project compiled.
> > > > Hope this helps.
> > > 
> > > 
> > > That is not a good idea
> > 
> > 
> > I'm sorry =\ I don't know what else to do... I need to compile my code and this is the only way I can get it to work. Maybe someone else will help us find a fix.
> 
> I think it will be fixed soon.

Just a quick question: Why is my quick fix 'not a good idea'. My application appears to be compiling and working as expected? If I need to submit, what risk am I taking? Thanks!

**Comment by gutoim** [comment]
I think this is the fix. The build error occurs when building pod (including Parse) into a static library. Using `@import Bolts` requires using `use_frameworks!` in Podfile, which for sure I do not want.

**Comment by derekleerock** [comment]
> Just a quick question: Why is my quick fix 'not a good idea'. My application appears to be compiling and working as expected? If I need to submit, what risk am I taking? Thanks!

@idefen1 Based on my understanding of how Cocoapods works, if you change this line of code then anytime you update or refresh your pods then this change will be deleted. So while this may work for right now as a temporary solution, ideally the long term solution would be to have this change (or the appropriate change) made to the Parse SDK itself so that you (and me and others) don't have to continue to manually make this fix in the future. 

I'd like to make a PR but given other commitments at this time I'm not sure if I can carve out the time to look into this. I'll see what I can do as I ran into the same issue.

**Comment by findlife99** [comment]
Hi,

I also face the same problem, any idea to fix it ?

**Comment by derekleerock** [comment]
> Hi,
> 
> I also face the same problem, how can I solve it ?

@findlife99 The fix mentioned in [this comment](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1545#issuecomment-694279302) worked for me - however, as I noted above, making a change to the pod source code should be considered temporary, so I made a PR to be considered for inclusion in a future build.

**Comment by derekleerock** [comment]
Doesn't look like I have the ability to close this issue, but since the PR was merged I think was can close this. @TomWFox @drdaz could I trouble you to assist? Thanks! =)
