### ISSUE TITLE
Xcode 11.7 shows 8 Analyzer errors

### ISSUE THREAD

**Issue by funnel20** [parse-community/Parse-SDK-iOS-OSX#1547]
When running Xcode 11.7 Analyzer on our project with Parse 1.19, it shows the following 7 logic errors:

1. /Parse/Parse/Parse/PFPush.m:322:9: Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue

    <img width="419" alt="Screenshot 2020-09-17 at 14 14 21" src="https://user-images.githubusercontent.com/2139844/93468966-18322380-f8f0-11ea-9cea-ba485649518e.png">
2. /Parse/Parse/Parse/Internal/PFCommandCache.m:250:21: Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue

   <img width="531" alt="Screenshot 2020-09-17 at 14 15 18" src="https://user-images.githubusercontent.com/2139844/93469051-38fa7900-f8f0-11ea-9240-fa569fd97127.png">

and 5 more.

The last is a memory error:
8. /Parse/Parse/Parse/Internal/PFDateFormatter.m:85:5: nil returned from a method that is expected to return a non-null value

<img width="688" alt="Screenshot 2020-09-17 at 14 17 53" src="https://user-images.githubusercontent.com/2139844/93469290-955d9880-f8f0-11ea-9c50-e6769235e693.png">

**Comment by TomWFox** [comment]
Thanks for reporting. Would you be willing to submit a PR?

**Comment by funnel20** [comment]
I'll try if I can find the time.

**Comment by mtrezza** [comment]
Closing as release [2.0.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/2.0.0) supports import via Swift Package Manager.
