### ISSUE TITLE
Cocoapods installs TWO parse versions. Creating duplicate UUIDs

### ISSUE THREAD

**Issue by ritteraf** [parse-community/Parse-SDK-iOS-OSX#1552]
I'm running into an issue when attempting to install Parse via Cocoapods. My pod file is as such:

target 'SwagLeagues' do
  use_frameworks!

  pod 'Parse'
  pod 'Parse/TwitterUtils'
  pod 'Parse/UI'
  pod 'ParseLiveQuery'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  pod 'Hyperconnectivity'
  pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'

  target 'SwagLeaguesTests' do
    inherit! :search_paths
  end

  target 'SwagLeaguesUITests' do
  end

end

During the installation I'm shown that Parse was installed TWICE, version 1.15.4 and version 1.19.0. Here is the log:
Downloading dependencies
Installing AAInfographics (5.0.3)
Installing Alamofire (5.2.2)
Installing AlamofireImage (4.1.0)
Installing Bolts (1.9.1)
Installing Bolts-Swift (1.5.0)
Installing Hyperconnectivity (1.1.0)
Installing Parse (1.15.4)
Installing Parse (1.19.0)
Installing ParseLiveQuery (2.2.3)
Installing Starscream (2.1.1)
Installing SwiftyJSON (5.0.0)
Generating Pods project
Integrating client project

After the installation completes I'm show a MASSIVE block of yellow warning text grouped around the following warnings:
[!] [Xcodeproj] Generated duplicate UUIDs: 
PBXFileReference -- Pods.xcodeproj/mainGroup/children/children:children:

Is it normal for Parse to install TWO versions on the same application? Is that what is causing my duplicate UUID error?

**Comment by drdaz** [comment]
I think it's ParseLiveQuery. Try pointing at the current commit on master in your Podfile.

**Comment by ritteraf** [comment]
> I think it's ParseLiveQuery. Try pointing ParseLiveQuery at the current commit on master in your Podfile.

Sorry... how would I do that?

**Comment by drdaz** [comment]
No 2.7.2 isn't quite out on cocoapods yet.

Try this in your Podfile:

`pod 'ParseLiveQuery', :git => 'https://github.com/parse-community/ParseLiveQuery-iOS-OSX, :branch => 'master'`

**Comment by ritteraf** [comment]
That fixed it. Thanks @drdaz !

**Comment by drdaz** [comment]
np... 2.7.2 should be out really soon. You'll want to revert that change to the Podfile when it's released.
