### ISSUE TITLE
Release 1.19.0: Bolts Framework: Disable code coverage for RELEASE configuration

### ISSUE THREAD

**Issue by konkontos** [parse-community/Parse-SDK-iOS-OSX#1554]
Release builds cause problems when submitting to App Store.
Specifically, bitcode rebuilding on Apple's backend fails with unknown symbols errors.

Before Xcode 12, this could be resolved by enabling code coverage in the test scheme for targets.
In Xcode 12, this is no longer sufficient. Linked apps do not pass through Apple's checks.

Disabling  the following setting for Bolts framework targets, for release schemes, seems to fix the issue:

`CLANG_ENABLE_CODE_COVERAGE = NO;`

**Comment by akmarinov** [comment]
+1 I'm seeing the same issue

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        # Disabling Code Coverage for depedencies to avoid bitcode recompilation failures
        config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
    end
  end
end
```

For anyone that doesn't want to wait
