### ISSUE TITLE
Module 'Bolts' not found ParseModule.h

### ISSUE THREAD

**Issue by kazukiotsuka** [parse-community/Parse-SDK-iOS-OSX#1555]
A Parse file shows `Module Bolts not found`.

Build > Archive
<img width="1116" alt="Screen Shot 2020-09-24 at 12 59 13" src="https://user-images.githubusercontent.com/3203107/94099360-c0526a00-fe65-11ea-91b0-1628d1b9562c.png">

tried this pods clean but doesn't work.
```bash
pod deintegrate
pod clean
pod install
pod update
```

the Podfile is
```
source 'https://github.com/CocoaPods/Specs.git'

target 'MyApp' do
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'AFNetworking'
  pod 'Parse'
  pod 'XNProgressHUD'

end
```

So far, no solution found on the internet. I totally get stuck into this problem. 

XCode Version is 11.7

**Comment by Kiplol** [comment]
I am having a similar issue on Xcode 12.

**Comment by jaysonng** [comment]
I think this is the same as [issue 1545](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1545). 

You can check what helped them out there. But it's kinda a hack than a fix.

**Comment by kazukiotsuka** [comment]
from issue 1545
```swift
//@import Bolts;
#import <Bolts/Bolts.h>
```
worked for me. Thank you. @jaysonng
