### ISSUE TITLE
Xcode 12 Error: Incompatible block pointer...

### ISSUE THREAD

**Issue by abeticlairon** [parse-community/Parse-SDK-iOS-OSX#1556]
I get the following error when trying to compile my app on Xcode 12. The file with the problem is 
`ParseClientConfiguration.m`.
`Incompatible block pointer types sending 'void (^)(ParseClientConfiguration *__strong)' to parameter of type 'void (^ _Nonnull)(id<ParseMutableClientConfiguration>  _Nonnull __strong)'`

**Comment by drdaz** [comment]
This issue is fixed in the recently released version 1.19.0.

**Comment by SubhanAli94** [comment]
Hi, @drdaz I installed 1.19.0 but facing same issue. Moreover, I am unable to install the package using Swift Package Manager giving the GitHub URL of iOS repository.

**Comment by drdaz** [comment]
Can you verify that the relevant changes made in 1.19.0 are actually included in your code? If you're using Cocoapods, check that line in your pods source in your workspace.

It's very hard to see how [the changes included in 1.19.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1527/commits/f98c02866788fd75f709a6cd62bbe1ec046eea14) don't fix this.

**Comment by SubhanAli94** [comment]
Hey @drdaz , I apologize for: in the previous comment, I mentioned that I am using 1.190.0 but actually after verifying again I encountered that pod is installing 1.18.0. Is there any way I can target 1.19.0 in the pod file?

**Comment by drdaz** [comment]
You can; check the Cocoapods docs. Otherwise just running `pod update` should update all your pods to the latest releases.

**Comment by SubhanAli94** [comment]
> You can; check the Cocoapods docs. Otherwise just running `pod update` should update all your pods to the latest releases.

Hey @drdaz , I appreciate your quick help. `pod update` worked. 

Thanks
