### ISSUE TITLE
Incompatible block pointer types [XCODE 12 ISSUE]

### ISSUE THREAD

**Issue by arjun3396** [parse-community/Parse-SDK-iOS-OSX#1558]
When I try to build using Xcode 12 I am getting this error
ERROR: Incompatible block pointer types sending 'void (^)(ParseClientConfiguration *__strong)' to parameter of type 'void (^ _Nonnull)(id<ParseMutableClientConfiguration>  _Nonnull __strong)'

This seems like some typedef issue as per this link https://stackoverflow.com/questions/52073178/incompatible-block-pointer-types-sending-void-strong-strong-id-to-para

It was working fine until I updated to Xcode 12 and ios 14, just after updating I am facing this issue its blocking development for us as we are not able to build.

Steps to reproduce:
1. Run a Parse project in Xcode 12

**Comment by drdaz** [comment]
The fix for this was released with SDK version 1.19.0.
