### ISSUE TITLE
Xcode 12: incompatible block pointer

### ISSUE THREAD

**Issue by ferrlan** [parse-community/Parse-SDK-iOS-OSX#1559]
I am unable to build my project. I am seeing incompatible block pointer types in ParseClientConfiguration.m. 

I attached a screenshot. Any help would be appreciated. 

Here is the full error in the copyWithZone function: 
Incompatible block pointer types sending 'void (^)(ParseClientConfiguration *__strong)' to parameter of type 'void (^ _Nonnull)(id<ParseMutableClientConfiguration>  _Nonnull __strong)'

**Comment by obdodavid** [comment]
Hello,

Just had the same issue, and for now I fixed it as below : 
- (instancetype)copyWithZone:(NSZone *)zone {
    return [ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration>  _Nonnull configuration) {
        // Use direct assignment to skip over all of the assertions that may fail if we're not fully initialized yet.
        configuration.applicationId = [self->_applicationId copy];
        configuration.clientKey = [self->_clientKey copy];
        configuration.server = [self.server copy];
        configuration.fileUploadController = self->_fileUploadController;
        configuration.localDatastoreEnabled = self->_localDatastoreEnabled;
        configuration.applicationGroupIdentifier = [self->_applicationGroupIdentifier copy];
//        configuration.containingApplicationBundleIdentifier = [self->_containingApplicationBundleIdentifier copy];
        configuration.networkRetryAttempts = self->_networkRetryAttempts;
        configuration.URLSessionConfiguration = self->_URLSessionConfiguration;
    }];
}

Not so sure it does not break anything, but at least I can compile and continue on my project whilst experts will fix this :-)

**Comment by drdaz** [comment]
This issue is fixed in release 1.19.0. Please update your SDK.
