### ISSUE TITLE
XCode 12: Fail to compile

### ISSUE THREAD

**Issue by flamesoft** [parse-community/Parse-SDK-iOS-OSX#1560]
I have updated to the latest XCode 12.0.1. It fails to compile.
.../Pods/Parse/Parse/Parse/ParseClientConfiguration.m:129:61: Incompatible block pointer types sending 'void (^)(ParseClientConfiguration *__strong)' to parameter of type 'void (^ _Nonnull)(id<ParseMutableClientConfiguration>  _Nonnull __strong)'

I have updated to the latest Parse 1.19 and it still doesn't work.

**Comment by drdaz** [comment]
Can you verify that the relevant changes made in 1.19.0 are actually included in your code? If you're using Cocoapods, check that line in your pods source in your workspace.

It's very hard to see how [the changes included in 1.19.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1527/commits/f98c02866788fd75f709a6cd62bbe1ec046eea14) don't fix this.

**Comment by flamesoft** [comment]
I haven’t used new features in Parse in my code. I just updated it because the compilation error happened. I used 1.17 before this update and it didn’t work with Xcode 12. 


Yan

**Comment by drdaz** [comment]
You don't need to have used any new features.

The point is, if you check the PR I linked, that the failing line in your error is entirely changed in release 1.19.0. Which means you're not using the code from 1.19.0.

**Comment by jeffreyjackson** [comment]
@drdaz I've been investigating this issue also.  In my case, I am able to update to 1.19.0 with a `pod update`.  However once I add the pod `ParseLiveQuery` it reverts the parse sdk back to 1.18.0.

**Comment by drdaz** [comment]
Yeah there's still something holding up the release of ParseLiveQuery.

Point your pod at master on ParseLiveQuery and you'll get 1.19.0.

**Comment by drdaz** [comment]
@TomWFox I just tried to manually push the podspec for ParseLiveQuery; I don't have the permissions. Can you do it?

**Comment by flamesoft** [comment]
@drdaz I found that I didn't update the Parse. Now I have updated it to 1.19. It complains: "Module 'Bolts' not found". What shall I do?

**Comment by GustavoFRocha** [comment]
someone managed to update the pod? I try but it always fails

**Comment by flamesoft** [comment]
@GustavoFRocha I could update to 1.19 with "pod update". Maybe there were some network/server issue when you tried.

**Comment by TomWFox** [comment]
@drdaz Sorry only just saw your comment here. I just published ParseLiveQuery manually as someone kept nagging about it!

I've added you as an owner of ParseLiveQuery for future use.

**Comment by TomWFox** [comment]
I'm going to close this now as the original issue has long since been resolved and people seem to be getting along fine with it. If you have any separate issues please open a new issue and if you have any issue relating to ParseLiveQuery please open an issue on that repo.

**Comment by TomWFox** [comment]
@flamesoft with regard to your comment about `Module 'Bolts' not found` the solution may be in #1545 which has been addressed by a PR and merged into master.

**Comment by flamesoft** [comment]
Thanks for your solution!


Yan
