### ISSUE TITLE
Code signing “Bolts.framework” failed  xcode12

### ISSUE THREAD

**Issue by stuzoo** [parse-community/Parse-SDK-iOS-OSX#1562]
Trying to upload to the app store and I get the error 'Code signing “Bolts.framework” failed'

Using xcode12 and the latest bolts.framework.

I installed the frameworks with carthage. 

the app runs in the simulator and on the device but can't be uploaded.

**Comment by jesusmateos1234** [comment]
Same

**Comment by stuzoo** [comment]
Ok, looks like there is a carthage workaround, follow these steps - https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md
