### ISSUE TITLE
FR: Add pre-compiled binaries to version tag

### ISSUE THREAD

**Issue by jesusmateos-tfm** [parse-community/Parse-SDK-iOS-OSX#1573]
Add parse binaries to version tag, with purpose of not compile on local please.

An example:

carthage build --no-skip-current
carthage archive
and attach Parse.framework.zip to tag release.
It will be works.

https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

**Comment by jesusmateos1234** [comment]
@nilkanth987

**Comment by jesusmateos1234** [comment]
@kashif @mt81 @toto could someone response to this request?

**Comment by jesusmateos1234** [comment]
@cbaker6

**Comment by mtrezza** [comment]
Closing as release [2.0.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/2.0.0) supports import via Swift Package Manager. Assets are added to GitHub release.
