### ISSUE TITLE
FBSDKCoreKit dependency issue

### ISSUE THREAD

**Issue by notmani** [parse-community/Parse-SDK-iOS-OSX#1578]
Hello,

With Parse/FacebookUtils 1.19.1 use FBSDKCoreKit/Basics 6.5.2

Therefore, it's not possible to use latest version of FBAudienceNetwork (https://github.com/CocoaPods/Specs/blob/master/Specs/2/1/5/FBAudienceNetwork/6.2.0/FBAudienceNetwork.podspec.json)

"dependencies": {
    "FBSDKCoreKit/Basics": [
      ">= 7.0.1"
    ]

can you upgrade to FBSDKCoreKit to ">= 7.0.1"

by the way, same issue for other FB kits

**Comment by notmani** [comment]
merge but why new version is not available on https://cocoapods.org/pods/Parse ? there is still 1.19.1

**Comment by notmani** [comment]
Can you please provide a feedback !

**Comment by drdaz** [comment]
It's because it hasn't been [released](https://en.wikipedia.org/wiki/Software_release_life_cycle) yet.

**Comment by JulienLevallois** [comment]
What's the solution to use the latest version of FBAudienceNetwork

This is my configuration

  pod 'Parse/FacebookUtils'
  pod 'Parse/UI'
  pod 'Parse'
  pod 'ParseLiveQuery'
