### ISSUE TITLE
Parse/FacebookUtils latest still points to older FBSDK

### ISSUE THREAD

**Issue by sarojkumarojha** [parse-community/Parse-SDK-iOS-OSX#1579]
I am using **'Parse/FacebookUtils','1.19.0'**  in my app , but I could see 
these dependancies still points to very old versions(~> 6.0) of FBSDK 
**FBSDKCoreKit', 
'FBSDKLoginKit',
 'FBSDKShareKit',** 

Any plan or timeline to upgrade to latest ?

**Comment by drdaz** [comment]
PRs are welcome. Can you try updating the dependancies locally and seeing what (if anything) breaks?

Otherwise I might have time to look at this before new year.

**Comment by drdaz** [comment]
Current Parse release is 1.19.1 btw. Not that it updates the FB libs, but just for info 🙂

**Comment by sarojkumarojha** [comment]
> Current Parse release is 1.19.1 btw. Not that it updates the FB libs, but just for info 🙂

Thanks @drdaz for the information , but still I could see FB libs points to 6.x versions :(

**Comment by cbaker6** [comment]
Can you continue this discussion on #1578
