### ISSUE TITLE
[PFInstallation currentInstallation] is nil

### ISSUE THREAD

**Issue by jesusmateos1234** [parse-community/Parse-SDK-iOS-OSX#1582]
Sometimes in our app currentInstallation is nil, we tried to fetch it, but doesn't work.

````
NSString *installationId = PFInstallation.currentInstallation.installationId ?: [PFInstallation.currentInstallation fetch].installationId];
````

Could someone explain me what could be the cause of it?

Thanks

**Comment by jesusmateos1234** [comment]
@cbaker6

**Comment by cbaker6** [comment]
This looks like a duplicate of #1568. Can you continue the discussion there?
