### ISSUE TITLE
Facebook SDK 8 deprecated, mandating upgrade to SDK 9

### ISSUE THREAD

**Issue by chriscborg** [parse-community/Parse-SDK-iOS-OSX#1597]
Facebook has just launched Facebook SDK 9 and they are deprecating previous versions. This is therefore an upgrade that is required on Parse SDKs for both iOS and Android. Please find the message from Facebook below:

> Action required: Release of new SDKs require changes to preserve application functionality
>  
> Action required: You need to update the version of the Facebook SDK that you currently utilize for your applications. As part of our release of v9.0 SDKs, we are requiring developers to upgrade to our newest version. This upgrade will give developers new security features, enhanced resilience, and increased performance.
> 
> Your current SDK is deprecated and will no longer be supported by Facebook. We will continue to allow API calls from your SDK for a transition period of two years. Starting January 19, 2023 we will fail all calls from deprecated SDKs. We encourage you to upgrade to v9.0 as soon as possible to avoid disruption to your application and to access all the benefits of our newest SDK.
> 
> You can also find a complete list of changes in the changelog associated with the SDK you utilize and our blog post.

More details on their blog post [here](https://developers.facebook.com/blog/post/2021/01/19/introducing-facebook-platform-sdk-version-9/)

**Comment by TomWFox** [comment]
Thanks for reporting, would you be willing to make a PR?

**Comment by chriscborg** [comment]
@TomWFox This would be my first attempt at contributing, but I will give it a go.

**Comment by chriscborg** [comment]
@TomWFox this would be my first attempt as I haven't contributed yet. I will go through the project and see if this is something within my reach.

**Comment by kmaker** [comment]
FWIW, I've successfully compiled Parse iOS SDK (master) with FB SDK 9.0, no changes needed.
@TomWFox hope you can make a new release soon, so we can use a tagged version of Parse rather than the master.

**Comment by drdaz** [comment]
@kmaker would you be willing to submit a PR?

**Comment by drdaz** [comment]
The required changes would likely look something like this: https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1580/commits/366d69f7c3852d3ba4abc5b76f2f88c154121927

**Comment by kmaker** [comment]
done!

**Comment by kmaker** [comment]
It looks like some test cases need to be fixed though (not the SDK code, but the tests themselves) . I'll see if I can fix them, probably next week.

**Comment by JulienLevallois** [comment]
Hi, do you have news ? How can i update it ?
