### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by AshrafAbuBakr** [parse-community/Parse-SDK-iOS-OSX#1602]
I was running analysis on my app and found 8 possible leaks in the SDK.
They are as follows:
1- PFPush.m (Line 322) :Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
2- PFCommandCache.m (Line 250): Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
3- PFOperationSet.m (Line 119): Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
4- PFSQLiteDatabaseResult.m (Line 169): Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
5- PFRESTPushCommand.m (Linde 46): Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
6- PFCommandURLRequestConstructor.m (Line 113): Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
7- PFQuery.m (Line 1092): Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
8- PFDateFormatter.m (Method: preciseStringFromDate): nil returned from a method that is expected to return a non-null value

**I'm using Xcode 12.2 and Parse SDK Version 1.19.1**

**Comment by mman** [comment]
From my understanding these are not leaks but rather a semantics bug.

I have not looked at the details yet, but all the NSNumbers can actually be NULL, in which case the boolean expression will evaluate to false. And all the NSNumbers can be non-NULL, in which case the boolean expression will evaluate to true.

So TODO is to check all these expressions and understand whether the NSNumber is expected to hold bool value of true or false, or whether the expressions expect NULL/non-NULL and fix accordingly.

**Comment by cbaker6** [comment]
@drdaz I believe what @mman mentioned:

> I have not looked at the details yet, but all the NSNumbers can actually be NULL, in which case the boolean expression will evaluate to false. And all the NSNumbers can be non-NULL, in which case the boolean expression will evaluate to true.

is related to what I was talking about here: https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1581#discussion_r551999718

**Comment by mtrezza** [comment]
I'm closing this as it seems to be resolved. Feel free to comment if you have any questions and we can re-open this issue.
