### ISSUE TITLE
FR: Add XCFrameworks in tagged in version assets 

### ISSUE THREAD

**Issue by jesusmateos1234** [parse-community/Parse-SDK-iOS-OSX#1606]
We'll fall in love if you add in version assets xcframeworks in zip files. FacebookUtils.xcframerwork, Parse.xcframerwork, TwitterUtils.xcframework ....

**Comment by jesusmateos1234** [comment]
@nilkanth987
@kashif @mt81 @toto @drdaz could someone response to this request?
@cbaker6

Today you have fat frameworks in this zips, but it's a bad practice use it. Could you add inside them xcframeworks like other repos have?

Thanks for all

**Comment by cbaker6** [comment]
This is a duplicate issue by you which has a pull request #1561. Why would you open another issue on the subject? You can just comment on the already open issue or pull request.

If you want to help out with pull request feel free to contribute to the current one or if you have another way of doing it, implement it and open up a pull request.

Closing this issue
