### ISSUE TITLE
EXC_BAD_ACCESS crash on iOS 14 devices using Xcode 13 beta

### ISSUE THREAD

**Issue by bmueller** [parse-community/Parse-SDK-iOS-OSX#1618]
I'm getting an EXC_BAD_ACCESS crash whenever I run my project on an iOS 14 device using the Xcode 13 beta. Seems to be happening in the `registerSubclassesInBundle` method of the PFObjectSubclassingController class.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/2242284/128289338-e62bae70-a222-4504-8c4a-50f61aea4df0.png">

**Comment by bmueller** [comment]
Never mind, this is an issue with an iOS 15 class.

**Comment by RealKnappster** [comment]
Hi @bmueller - I'm currently seeing a similar issue on my end.  What ended up being the fix for you?

**Comment by bmueller** [comment]
@RealKnappster I had to go into PFObjectSubclassingController and, in `registerSubclassesInBundle`, change this loop to skip checking the classes (marked "XXXXXX" below) that are causing the crash:

`        for (unsigned i = 0; i < bundleClassCount; i++) {
            NSString *className = [NSString stringWithUTF8String:classNames[i]];
            if ([className isEqualToString:@"XXXXXXXX"]) {
                continue;
            }
            Class bundleClass = objc_getClass(classNames[i]);
            // For obvious reasons, don't register the PFObject class.
            if (bundleClass == pfObjectClass) {
                continue;
            }
            // NOTE: Cannot use isSubclassOfClass here. Some classes may be part of a system bundle (even
            // though we attempt to filter those out) that may be an internal class which doesn't inherit from NSObject.
            // Scary, I know!
            for (Class kls = bundleClass; kls != nil; kls = class_getSuperclass(kls)) {
                if (kls == pfObjectClass) {
                    // Do -conformsToProtocol: as late in the checking as possible, as its SUUUPER slow.
                    // Behind the scenes this is a strcmp (lolwut?)
                    if ([bundleClass conformsToProtocol:@protocol(PFSubclassing)] &&
                        ![bundleClass conformsToProtocol:@protocol(PFSubclassingSkipAutomaticRegistration)]) {
                        [self _rawRegisterSubclass:bundleClass];
                    }
                    break;
                }
            }
        }
        free(classNames);
`

**Comment by RealKnappster** [comment]
@bmueller Ah interesting- so you ended up forking the repo then?  I'm getting the EXC_BAD_ACCESS on the auto-generated model access files from each of my on-device CoreML models.  Are you using any .mlmodel files in your project?
