### ISSUE TITLE
PFActionButton configuration property conflicts with UIButton in iOS 15

### ISSUE THREAD

**Issue by bcbeta** [parse-community/Parse-SDK-iOS-OSX#1620]
`@property (nonatomic, strong) PFActionButtonConfiguration *configuration;`

gives error:
> Auto property synthesis will not synthesize property 'configuration'; it will be implemented by its superclass, use @dynamic to acknowledge intention

and
> Use of undeclared identifier '_configuration'; did you mean 'configuration'?

**Comment by davewhipps** [comment]
I'd just like to 'upvote' this. Apple automatically updated XCode last night, and the new/latest (iOS 15) SDK breaks this. I'm using the cocoapod, so my app won't build and I'm stuck in the water.

**Comment by idefen1** [comment]
> I'd just like to 'upvote' this. Apple automatically updated XCode last night, and the new/latest (iOS 15) SDK breaks this. I'm using the cocoapod, so my app won't build and I'm stuck in the water.

same here =*(

**Comment by gorillatapstudio** [comment]
Let's just change it from configuration to config to have a quick fix.

**Comment by ashish-naik** [comment]
@bcbeta @davewhipps @gorillatapstudio @idefen1 Till the time official fix arrives, one solution is to download  previous version of xcode from [download page](https://developer.apple.com/download/all/?q=xcode).

Once downloaded, unzip the file and rename it to add version number and move it to Applications folder. Renaming required so as to not overwrite version that exists in Applications folder. 

Open this version, go to Preferences -> Locations and set command line tools version if you build from command line using tools such as fastlane or your own build script. 

I tried and was able to compile and run the app without any issues.

You may have more than two versions as long as enough disk space is available.

[This article](https://hacknicity.medium.com/working-with-multiple-versions-of-xcode-e331c01aa6bc) explains in details as well.

Hope this helps.

**Comment by cbaker6** [comment]
This issue is currently open? The ParseSwift issue was closed because the comment you left was unrelated to that SDK.
