### ISSUE TITLE
Update FBSDK dependancy

### ISSUE THREAD

**Issue by matej494** [parse-community/Parse-SDK-iOS-OSX#1621]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Current Limitation

Facebook SDK dependancy -> Parse/FacebookUtils
Current maximum supported version is FBSDKCoreKit (9.3.0) and currently latest version is (11.2.1).
This blocks developers from introducing newer version of FBSDKCoreKit in their app because the two libraries with different versions are conflicting.

### Feature / Enhancement Description

Update the code to support the latest FBSDKCoreKit version. 

### Example Use Case

/

### Alternatives / Workarounds

I did not find any alternatives, but perhaps handling the dependancy internally (without exposing it) would allow the developers to include newer version of FBSDKCoreKit in their project, independently of the one in Parse SDK. 

### 3rd Party References

/

**Comment by alexionut** [comment]
We also get this 
![image](https://user-images.githubusercontent.com/6870703/138058422-2f08c4e0-d4b8-4853-a391-4d5f965c2da1.png)
And there's no way of updating it

**Comment by benpackard** [comment]
Just as an added incentive, apparently `12.1.0` includes a fix for all those `NSKeyedUnarchiver` console warnings (according to [this.](https://github.com/facebook/facebook-ios-sdk/issues/1887))
