### ISSUE TITLE
Login with AppleID Question... 

### ISSUE THREAD

**Issue by DevStreamLine** [parse-community/Parse-SDK-iOS-OSX#1624]
So I am using ParseUI to login with AppleID.  Everything works great, except I cannot seem to get the email address.  I have looked at the Poarse code and it seems to be requesting it.  I also see the box checked in the login dialog apple provides when I perform the login.

However, the PFUser Object shows the email as nil.  It does populate username.

Here is some code:

```
extension OnboardViewController: PFLogInViewControllerDelegate, PFSignUpViewControllerDelegate
{
	// LogInViewController Delegate Methods
	@available(iOS 13.0, *)
	func log(_ logInController: PFLogInViewController, didReceiveAppleCredential credential: ASAuthorizationAppleIDCredential, for user: PFUser)
	{
		print("didReceiveAppleCredential")
	}

	func log(_ logInController: PFLogInViewController, didLogIn user: PFUser)
	{
		print("didLogIn")
		if #available(iOS 13.0, *)
		{
			let storyboard = UIStoryboard(name: "Main", bundle: nil)
			let mainTabBarController = storyboard.instantiateViewController(identifier: "MainTabBarController")

			// This is to get the SceneDelegate object from your view controller then call the change root view controller function to change to main tab bar
			(UIApplication.shared.connectedScenes.first?.delegate as? SceneDelegate)?.changeRootViewController(mainTabBarController)
		}
		else
		{
			// Fallback on earlier versions
			print("Earlier Vers")
			(UIApplication.shared.delegate as! AppDelegate).switchRootViewToHome()
		}
	}
}

```

If I set a breakpoint at either of the functions above and check the PFUser username and email, the email always show nil.  The user name is populated and the user DB shows the same.

Is there something special I need to do to get the email address?

**Comment by drdaz** [comment]
@DevStreamLine This doesn't look like an SDK issue. It looks like you're not doing anything with the credential response from Apple; you're just printing something. The data you're looking for is available in that callback method on the first successful login.

**Comment by cbaker6** [comment]
> Is it as complete, or more complete, than the objc sdk? All of our apps are swift so using a swift SDK is much welcomed.

IMO, In terms of query and functionality it's probably the most complete or on par with the most complete SDK, the JS SDK. The only thing missing is local storage which probably won't be implemented anytime soon, but developers can handle that piece.

> Is it just a drop in replacement? I will check it out.

Definitely not, it's designed completely different, but some who have converted said it wasn't too hard.

**Comment by DevStreamLine** [comment]
Great, thank you.  I will check it out.  Also, I did see what I have to do to retrieve the email address.  My bad, I just thought the parse SDK magically filled it in.  It looks like the delegate gets called with the ASAuthorizationAppleIDCredential and I need to pull it from there.  Makes sense.  Thank you again for all your help.

**Comment by DevStreamLine** [comment]
@drdaz Yep, got it!!  Updated code and now I get the email and other info. Thank so much, I should have caught it myself, just thought there was some parse magic in there... my bad.  Thanks for the help.
