### ISSUE TITLE
Add release-automation

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-iOS-OSX#1628]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Current Limitation
Releases are still done manually.

### Feature / Enhancement Description
Add release automation.

### Example Use Case
n/a

### Alternatives / Workarounds
Manual release

**Comment by mtrezza** [comment]
@drdaz I haven't done a release in this repo yet, could you describe the manual process currently, so we can see how to automate these steps?

**Comment by drdaz** [comment]
Sure.

Make a release branch + PR
Update version numbers: `bundle exec rake package:set_version[X.X.X]`
Update Changelog
Tag release & push tag
Add notes to releases page on GitHub

I... I think that's it. Often the LiveQuery lib needs it's podfile updating too.

**Comment by mtrezza** [comment]
Thanks! 

> Often the LiveQuery lib needs it's podfile updating too.

What are these updates?

**Comment by drdaz** [comment]
> Thanks! So all the version numbers are updated with that single command? That means that aside from the changelog there are no manual edits, correct?

Generally yeah, assuming no last-minute tweaks. I usually dump the root folder in VSCode and search for the old version number after the script is run, just to make sure.

> > Often the LiveQuery lib needs its podfile updating too.
> What are these updates?

The version number of the Parse iOS SDK library in the podfile typically. Cocoapods often wants to select the previous version (even though it's specced using ~> notation).

**Comment by mtrezza** [comment]
Got it, I think we can make a script that updates all the version numbers and we should be good.

**Comment by drdaz** [comment]
Is this a thing that's happening Really Soon™️? Or should I manually create this release? 🙂

**Comment by mtrezza** [comment]
I'm looking into auto-release over the next days. If you need it urgently, I can manually release.

**Comment by mtrezza** [comment]
@drdaz I see that you are an owner on cocoapods. Could you add a new owner to there? I would send you the email via Slack if you are there.

**Comment by drdaz** [comment]
@mtrezza I can give it a shot, but I can't get into Slack. The 2FA emails just aren't getting to me 🤔

Any other channels?

**Comment by mtrezza** [comment]
could you email me at manueltrezza@parseplatform.org?

**Comment by mtrezza** [comment]
could you invite services[@]parseplatform.org?

**Comment by drdaz** [comment]
There's an invite elsewhere I've clicked on. I'm sure I've been in there before.

The auth just isn't working right now I think.

**Comment by mtrezza** [comment]
I don't think there's a publicly available Slack invite at the moment, they usually expire, so invite is only on a per-user basis now.

**Comment by drdaz** [comment]
That worked. And I've added that email you shared as an owner on the Pod.

**Comment by mtrezza** [comment]
Thanks, it worked indeed

**Comment by mtrezza** [comment]
@drdaz Do you thin you could stand-by when I merge the auto-release PR, just in case? 4 eyes would be better than 2.

**Comment by cbaker6** [comment]
The assets I added back in releases starting from 1.19.2 are missing from the auto-release:

1.19.3

<img width="937" alt="image" src="https://user-images.githubusercontent.com/8621344/142781873-f11ab006-fbde-44bc-8abb-172534be4b42.png">


1.19.2

<img width="933" alt="image" src="https://user-images.githubusercontent.com/8621344/142781890-c06e7fa6-3970-4f66-a456-24d0e9c7af4a.png">

**Comment by mtrezza** [comment]
they are currently being compiled

**Comment by mtrezza** [comment]
Re-opening, as we need to verify the assets and pods were build correctly before closing this.

**Comment by cbaker6** [comment]
I see the assets showing up. Just a long build I guess.

**Comment by mtrezza** [comment]
Yes, it takes about 25 minutes before the assets are added to the release.

**Comment by cbaker6** [comment]
I left this comment to speed up the cocoa pod release: https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1632#discussion_r753868927

**Comment by mtrezza** [comment]
@drdaz as I'm cleaning up the branches as well, there is a branch `xcode-12` from you. can i delete it or is it still needed?

**Comment by dplewis** [comment]
@mtrezza Can we close this? I found that assets comment you where talking about https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1628#issuecomment-974911439

**Comment by mtrezza** [comment]
Yes, I believe so; thanks
