### ISSUE TITLE
Upgrade Facebook SDK to latest version

### ISSUE THREAD

**Issue by KashifRizwan007** [parse-community/Parse-SDK-iOS-OSX#1635]
Facebook has asked to update the SDK to the latest version but Parse/FacebookUtils still uses version 11.0.1.
Would be thankful if this can we done asap as my work is on-hold because of this

**Comment by drdaz** [comment]
This is effectively impeded by https://github.com/facebook/facebook-ios-sdk/issues/1936

Tell them about it.

**Comment by mtrezza** [comment]
The FB issue has since been closed, so we could give this another try.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.0.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/2.0.0)
