### ISSUE TITLE
Saving New Child Object with Pointer to Parent Object Crashes when ParseConfig vars set in Environment

### ISSUE THREAD

**Issue by OpConTech** [parse-community/Parse-SDK-iOS-OSX#1637]
### Issue Description
Saving Child Object with Pointer to Parent Object Crashes when ParseConfig vars set in Environment (e.g. .xcconfig file). This only happens when saving a New child object and specifying a pointer to the Parent object. (e.g. New Comment for Existing Post).

### Steps to reproduce 

This is weird so I made some test code to isolate this and reproduce.
The following test code works as expected:

------ Start iOS  Swift Test file ------

import SwiftUI
import Parse

final class AppDelegate: NSObject, UIApplicationDelegate {
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
   
        let parseConfig = ParseClientConfiguration {
            $0.clientKey = ""
            $0.applicationId = "your serve app id"
            $0.server = "your server address"
            //$0.isLocalDatastoreEnabled = false
        }
        
        Parse.initialize(with: parseConfig)
        
        print()
        print("did finish launching with options...")
        print()
        
        return true
    }
    
    func applicationDidBecomeActive(_ application: UIApplication) {
        
        //application.registerForRemoteNotifications()
        print("App did become active...")
    }
}

@main

struct testing_chlld_parent_saveApp: App {
    
    @UIApplicationDelegateAdaptor(AppDelegate.self) var delegate
    
    var body: some Scene {
        WindowGroup {
            ContentView().onAppear(perform: postComment)
        }
    }
    
    func postComment() {
        print("Hello World!")
        
        //
        // Ref: Parse Server iOS SDK Guide
        // https://docs.parseplatform.org/ios/guide/
        // "Relational Data"
        //
        
        // Create the post
        let myPost = PFObject(className:"Post")
        myPost["title"] = "I'm Hungry"
        myPost["content"] = "Where should we go for lunch?"

        // Create the comment
        let myComment = PFObject(className:"Comment")
        myComment["content"] = "Let's do Sushirrito."

        // Add a relation between the Post and Comment
        myComment["post"] = myPost

        // This will save both myPost and myComment
        myComment.saveInBackground()
    }
}

Result:  
did finish launching with options...

Hello World!

Checking parse database shows as expected: New Post with New Comment

### Actual Outcome

So the above test works as expected and creates a new Post and a new Comment.

But when the Application Id and Server Address are not hardcoded and instead set in Environment vars 
(using .xcconfig files in this case)
 then the code fails:

        let parseConfig = ParseClientConfiguration {
            $0.clientKey = ""
            $0.applicationId = (Bundle.main.infoDictionary?["API_KEY_PARSE_APPLICATIONID"] as! String)
            $0.server = "https:\(Bundle.main.infoDictionary?["API_KEY_PARSE_SERVER"] as! String)"
            //$0.isLocalDatastoreEnabled = false
        }

Result: 
did finish launching with options...
Hello World!
2022-03-30 14:24:03.091294-0700 testing_chlld_parent_save[5874:2324931] [General] An uncaught exception was raised
2022-03-30 14:24:03.091332-0700 testing_chlld_parent_save[5874:2324931] [General] *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]

### Expected Outcome
All of the other queries and functions in the iOS SDK work normally when setting the ParseConfig vars in the Environment. But for some reason saving a new child object with a parent pointer does not. 

Note: Saving a new child object without the parent pointer does work and a new Comment is added but the pointer to its parent Post is of course blank.  e.g. - comment out myComment["post"] = myPost and it saves the new child object just fine:

// Add a relation between the Post and Comment
//      myComment["post"] = myPost  // comment out this line and it saves the new child object with blank pointer to Post

So the issue seems to revolve around saving the pointer in a new child object. Existing child objects don't need the pointer to be set and they save fine. 

If there anyone has suggestions on a better way not hard code the id and address that would be helpful too.

###  Environment
Macbook Air M1
iPhone X w/ iOS 15.4
My Mac App  (designed for iPad)

Client
- Parse ObjC SDK version:  1.9.3 (I checked 1.9.2 and .1 and they also fail in this context)

Server
- Parse Server version: 4.10.6
- Operating system: Macbook Air M1
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Heroku

Database
- System (MongoDB or Postgres): Mongo Atlas v4.4
- Database version: 4.4
- Local or remote host MongoDB Atlas

**Comment by mman** [comment]
@OpConTech Most likely not an issue with Parse SDK. If you want to configure via variables present in `.xconfig` files, you have to also manually add all those variables to your `Info.plist` where you are actually reading them from.

Since `Info.plist` is not present at all in newly created Xcode projects, I assume even if you did specify the variables via Xcode Info.plist editor, the values you put there simply got lost (a bug present in multiple versions of Xcode now).

Here is one way to address this: https://betterprogramming.pub/info-plist-is-missing-in-xcode-13-heres-how-to-get-it-back-1a7abf3e2514

**Comment by OpConTech** [comment]
Thanks @mman. To minimize the issue report, I didn't include the info.plist with environment vars and config.xcconfig with matching Parse keys in my sample test code.. But those files are configured in the full "Test App".  I think this is a bug because the environment vars  approach works just fine for the rest of the Parse SDK functions  and .saveInBackground() as long as you don't include a pointer. 

Just to re-confirm, .saveInBackground() only fails when environment vars are set, then setting the parent pointer in the child object (Comment) and then .saveInBackground() either a New child object  or updating a the pointer in an Existing child object.  If you never set the pointer then it will save a new child object (with undefined parent pointer) or updates the existing child object just fine.

**Comment by mman** [comment]
@OpConTech put a breakpoint or print into the `ParseClientConfiguration` closure and verify that you are reading correct values for `API_KEY_PARSE_APPLICATIONID` and `API_KEY_PARSE_SERVER`.

I can only guess from the minimal sample that you are having a problem with the `Info.plist`, reading nil values from there and crashing.

**Comment by OpConTech** [comment]
Good point!  @mman 

I added a print statement for the ParseConfig vars just before .saveInBackground: 


-------- Begin Struct -------

struct testing_chlld_parent_saveApp: App {
  
    @UIApplicationDelegateAdaptor(AppDelegate.self) var delegate
    
    var body: some Scene {
        WindowGroup {
            ContentView().onAppear(perform: postComment)
        }
    }
    
    func postComment() {
        print("Hello World!")
        
        //
        // Ref: Parse Server iOS SDK Guide
        // https://docs.parseplatform.org/ios/guide/
        // "Relational Data"
        //
        
        // Create the post
        let myPost = PFObject(className:"Post")
        myPost["title"] = "I'm Hungry"
        myPost["content"] = "Where should we go for lunch?"

        // Create the comment
        let myComment = PFObject(className:"Comment")
        myComment["content"] = "Let's do Sushirrito."

        // Add a relation between the Post and Comment
        myComment["post"] = myPost

        //
        // Check for nil Parse Key or Server:
        //
        let applicationId = self.delegate.applicationId
        let server = self.delegate.server
        
        print()
        print("applcationId: ", applicationId as Any)
        print("server: ", server as Any)
        print()

        // This will save both myPost and myComment
        myComment.saveInBackground()
    }
}

-----------  End Struct ----- 


Results: With Hardcoded ParseConfig Vars:
------------------------
Hello World!

applcationId:  x8jl...
server:  https:parseserver.myc...

-- Saves Parent and Child objects as Expected 


Results: With  ParseConfig Vars stored in .plist:
------------------------
Hello World!

applcationId:  x8jl...
server:  https:parseserver.myc...

2022-03-31 10:36:05.481710-0700 testing_chlld_parent_save[72613:3174368] [General] An uncaught exception was raised
2022-03-31 10:36:05.481752-0700 testing_chlld_parent_save[72613:3174368] [General] *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]

-----------------


So the print statement before the .saveInBackground shows that the Config Vars are there in both use cases. I am guessing that these objects:  "insert nil object from objects[1]" are ParseSDK objects?

**Comment by mman** [comment]
Sounds weird. Configure an exception breakpoint in Xcode and catch it live while running... https://www.hackingwithswift.com/example-code/xcode/how-to-create-exception-breakpoints-in-xcode

**Comment by OpConTech** [comment]
Yes...it is weird. 
Another way of looking at it: 
(in both cases ParseConfig vars are stored in .plist)

Works: 
--------------------
    func postComment() {
        // Create the post
        let myPost = PFObject(className:"Post")
        myPost["title"] = "I'm Hungry"
        myPost["content"] = "Where should we go for lunch?"

        // Create the comment
        let myComment = PFObject(className:"Comment")
        myComment["content"] = "Let's do Sushirrito."

        // Add a relation between the Post and Comment
       //myComment["post"] = myPost

        myComment.saveInBackground()
    }

Does Not Work:
--------------------
    func postComment() {
        // Create the post
        let myPost = PFObject(className:"Post")
        myPost["title"] = "I'm Hungry"
        myPost["content"] = "Where should we go for lunch?"

        // Create the comment
        let myComment = PFObject(className:"Comment")
        myComment["content"] = "Let's do Sushirrito."

        // Add a relation between the Post and Comment
       myComment["post"] = myPost

        myComment.saveInBackground()
    }

**Comment by OpConTech** [comment]
@mman the exception is flagging the issue here in the ParseSDK: 

PFRESTObjectBatchCommand

line 33:
      NSMutableDictionary *requestDictionary = [@{ @"method" : command.httpMethod,
                                                     @"path" : commandURL.path } mutableCopy];

Thread 4: "*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]"

**Comment by OpConTech** [comment]
I am guessing that PFRESTObjectBatchCommand is only used when saving a pointer....
And that breakpoint shows a problem with the url path to the parse server. 

So I left the appId in pList and hardcoded the server url and it worked. 
The way I have been using the server var in app del is: 
 server = "https:\(Bundle.main.infoDictionary?["API_KEY_PARSE_SERVER"] as! String)"

So still not making sense but getting closer.
