### ISSUE TITLE
Compiling iOS SDK manually fails (lipo error)

### ISSUE THREAD

**Issue by JohnRoxMySox23** [parse-community/Parse-SDK-iOS-OSX#1642]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description
I tried to compile Parse iOS SDK for myself, [as described in the README](https://github.com/parse-community/Parse-SDK-iOS-OSX#compiling-for-yourself).

The last command (`bundle exec rake package:frameworks`) gives this error:
> fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/me/Documents/Sandbox/Parse-SDK-iOS-OSX/build/Release-ios-iphoneos/Parse.framework/Parse and /Users/me/Documents/Sandbox/Parse-SDK-iOS-OSX/build/Release-ios-iphonesimulator/Parse.framework/Parse have the same architectures (arm64) and can't be in the same fat output file
> Failed to lipo iOS framework.

### Steps to reproduce
Run the 4 successive commands:

> git submodule update --init --recursive
> gem install bundler
> bundle install
> bundle exec rake package:frameworks

### Actual Outcome
The aforementioned error. Only `Parse-macOS.zip` is available in `build/release`.

### Expected Outcome
The available `Parse-iOS.zip` file in `build/release`.

###  Environment

Client
- Parse ObjC SDK version: 1.19.3

Server
Not relevant

Database
Not relevant

Thank you for your help.

**Comment by mtrezza** [comment]
Closing as release [2.0.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/2.0.0) supports import via Swift Package Manager.
