### ISSUE TITLE
Parse iOS framework doesn't work with Macbook M1

### ISSUE THREAD

**Issue by flamesoft** [parse-community/Parse-SDK-iOS-OSX#1644]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description

I get this error message "Parse/Parse.h file not found" when compiling with XCode 13.3.1 in Macbook Pro with Apple m1 chip. The OS version is Monterey 12.0.1.
 
### Steps to reproduce

Run "pod install" and Compile the app with XCode 13.3.1.
### Expected Outcome

"Parse/Parse.h file not found"
###  Environment

XCode 13.3.1
Mac OS version is Monterey 12.0.1

Client
- Parse ObjC SDK version: `1.19.1`

Server
- Parse Server version: `1.4.0`
- Operating system: `n/a`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Heroku`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `MongoDB5.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

### Logs
Parse/Parse.h file not found

**Comment by jferrer21** [comment]
I'm having the same problem
[test2.zip](https://github.com/parse-community/Parse-SDK-iOS-OSX/files/8776689/test2.zip)
.

**Comment by magnett** [comment]
macOS 12.3.1 with Xcode 13.4.1 works just fine my M1

**Comment by mtrezza** [comment]
I can confirm that it seems to work fine on Apple Silicon. Closing for now.
