### ISSUE TITLE
Carthage build fails in CircleCI

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-iOS-OSX#1656]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description

Carthage build [fails](https://app.circleci.com/pipelines/github/parse-community/Parse-SDK-iOS-OSX/1328/workflows/78eee610-8187-4bda-9532-b1cd33142354/jobs/7471) in CircleCI with error:
```
*** Building scheme "ParseFacebookUtilsV4-tvOS" in Parse.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/distiller/project/Parse.xcworkspace -scheme ParseFacebookUtilsV4-tvOS -configuration Release -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/project SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/distiller/project)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/carthage-xcodebuild.iAhzZv.log
Carthage Tests Failed!

Exited with code exit status 1
```

### Steps to reproduce

See https://app.circleci.com/pipelines/github/parse-community/Parse-SDK-iOS-OSX/1328/workflows/78eee610-8187-4bda-9532-b1cd33142354/jobs/7471

### Actual Outcome
Fails

### Expected Outcome
Passes

###  Environment
Current master branch

**Comment by mtrezza** [comment]
@cbaker6 do you remember why we run carthage still on CircleCI instead of GitHub Actions? I vaguely remember that it was about the resources because it takes a lot of time?

**Comment by cbaker6** [comment]
Yes, Carthage and some of the other obj-c builds take long time to finish, so it was left on circle

**Comment by mtrezza** [comment]
Got it. Maybe we should move this to Github Actions anyway; we don't see many CI runs here but it may be easier to debug in a single CI environment.

@parse-community/ios-sdk could anyone look into why carthage fails in CircleCI?

**Comment by drdaz** [comment]
@mtrezza Not 100% sure about this, but IIRC, it times out.

**Comment by mtrezza** [comment]
I increased the `no_output_timeout` to 30min in https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1657, let's see if that works

**Comment by mtrezza** [comment]
You were spot on, it requires a timeout of 1h, 30min even was too short. In total, carthage needs ~1h in total on CircleCI. It would be interesting to test this on GitHub Actions, because I suspect that CircleCI gives us little resources on the free plan and that may be one reason why it takes so long.
