### ISSUE TITLE
"Parse-Parse" target gets installed in Pods project with Cocoapods installation and provokes a compilation error

### ISSUE THREAD

**Issue by JohnRoxMySox23** [parse-community/Parse-SDK-iOS-OSX#1662]
### Issue Description
I have a project that needs Parse iOS SDK, so I still use Cocoapods for this library (all the other dependencies being handled with SPM).
Every time I run `pod install` or `pod update`, a `Parse-Parse` target gets installed in the Pods project, and provokes an error when building the project:

> Pods.xcodeproj error project: Signing for "Parse-Parse" requires a development team. Select a development team in the Signing & Capabilities editor.

### Steps to reproduce
Create a project and add a Podfile inside, with `Parse` as a dependency. Then call `pod install`.

### Actual Outcome
Here is the error that I get:

![Capture d’écran 2022-09-29 à 12 08 47](https://user-images.githubusercontent.com/103497627/193004232-4ea61cc7-588a-4ed5-bf40-108c43329ca2.png)

### Expected Outcome
No error on this

###  Environment

Client
- Parse ObjC SDK version: `1.19.3`
- Xcode version: `14.0`

**Comment by mtrezza** [comment]
Cocoapods is not officially supported anymore in this library, due to the fact that the SDK has several issues since Xcode 12; what is supported is carthage; there are instructions on how to use carthage up to the latest version Xcode 14.
