### ISSUE TITLE
Allow implementations of ParseObjects to set their own className

### ISSUE THREAD

**Issue by atonylai** [parse-community/Parse-SDK-iOS-OSX#1664]
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Current Limitation
struct extensions of ParseObject seem to force their name as the classTitle

`struct GameScore: ParseObject { ... }`

We use Stripe as another library - Stripe has a class called Event. One of the tables in our database that is heavily populated is already called Event.

### Feature / Enhancement Description
Allow extensions of ParseObject to function more like PFObject. While it's a lot of work for us to have to add in 

`struct SomeDatabaseTableName: ParseObject { ... }`

this is not impossible, albeit just a lot of boilerplate code.

### Example Use Case

```
struct RandomClassName: ParseObject { 

   var className = "ActualDatabaseClassName"

 }
```

### Alternatives / Workarounds
We could migrate the entire table into a new one and update all of the code to point to a new table, but that would still leave us at the mercy of any of our dependencies adding in a new class or struct that conflicts with ours.

### 3rd Party References

The original obj-c Parse SDK

**Comment by mtrezza** [comment]
Is this issue supposed for the Parse Swift SDK?

**Comment by atonylai** [comment]
My mistake, had too many tabs open and filed on the wrong one by accident!
