### ISSUE TITLE
MacOS unit test on Xcode crashes

### ISSUE THREAD

**Issue by ninjadev106** [parse-community/Parse-SDK-iOS-OSX#1680]
### New Issue Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [ ] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [ ] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [ ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description
Running macOS test using the Xcode test navigator crashes and the reason is "Thread11: "The class PFPin must be registered with registerSubclass before using Parse.""

### Steps to reproduce
1. Click on Test Navigator on the top of Navigator area of Xcode
2. Hold the pointer over the ParseUnitTests-macOS bundle and click the Run button that appears on the right.
3. When the Test case "[QueryUnitTests testCLearAllCachedResults]" starts, it crashes in dipatch_sync(queue, block) of the PFThreadsafetySafeDispatchSync method on the PFThreadsafety.m file 

### Actual Outcome
Test fails.

### Expected Outcome
Test passes.

###  Environment

Client
- Parse ObjC SDK version: `1.19.4`

**Comment by mtrezza** [comment]
Is this a duplicate of https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1677?

**Comment by ninjadev106** [comment]
When the Test case "[QueryUnitTests testCLearAllCachedResults]" starts, it crashes in dipatch_sync(queue, block) of the PFThreadsafetySafeDispatchSync method on the PFThreadsafety.m file
![Screenshot_1](https://user-images.githubusercontent.com/29223815/199005260-8ac9e061-a488-4e30-b908-709d3fc95bfa.png)

**Comment by ninjadev106** [comment]
> Is this a duplicate of #1677? Which test exactly fails?

I think it's not a duplicated of #1677

**Comment by mtrezza** [comment]
What is the test name?

**Comment by ninjadev106** [comment]
QueryUnitTests
Yes, that happens with almost every test except for another crash which sometimes happens too. The another crash reason is "Thread 8: "Invalid class name. Class names cannot start with an underscore"" 

![image](https://user-images.githubusercontent.com/29223815/199007942-711499f7-ad3c-40ed-8554-00240b79c311.png)

**Comment by ninjadev106** [comment]
The interesting point is that it doesn't happen when running all tests in the single QueryUnitTests class. It happens only when running all tests in the project bundle(ParseUnitTests-macOS)

**Comment by mtrezza** [comment]
The failing test in https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1681 is the same one described in https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1677. So is this issue a duplicate of #1677?

**Comment by ninjadev106** [comment]
Yes, this seems to be a duplicate of #1677

**Comment by mtrezza** [comment]
OK, I'll close this as duplicate and assign the PR to the former issue.

**Comment by mtrezza** [comment]
Closing as duplicate of https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1677
