### ISSUE TITLE
missing compatible architecture in xcode 14.2

### ISSUE THREAD

**Issue by adwenn** [parse-community/Parse-SDK-iOS-OSX#1686]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description

MBP [mid 2015] 
xcode 14.2 (14C18)
carthage 0.38.0
I'm using Carthage to build and deploy the parse-SDK-iOS into my project. It builds but when I try to run it on the iOS simulator I get the following error (snippet): 

> Frameworks/Parse.framework/Parse' (file does not start with MH_MAGIC[_64], file does not start with MH_MAGIC[_64], fat file, but missing compatible architecture (have 'arm64,x86_64', need 'x86_64'))
> '/Users/adwenn/Library/Developer/Xcode/DerivedData/adwennproject-bmvhaatqyaqfvqcbtweebkybniax/Build/Products/Debug-iphonesimulator/ParseUI.framework/Frameworks/ParseFacebookUtilsV4.framework/ParseFacebookUtilsV4' (errno=2)

###  Environment

I'm using version **v1.19.4** of Parse-SDK-iOS-OSX

Am I missing something here?

**Comment by mtrezza** [comment]
Could you please try out using Swift Package Manager pointing to the URL in this PR: https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1683

**Comment by adwenn** [comment]
Thanks for the quick reply. Ok I looked into [#1683](https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1683) but I'm not really sure what URL you mean that I should use. There is so much information in there. It is not clear what URL you are referring that I should use.  
e.g.  https://github.com/mman/Parse-SDK-iOS-OSX/tree/spm
https://github.com/vazarkevych/Parse-SDK-iOS-OSX/tree/SPM

**Comment by mtrezza** [comment]
The PR is based on this branch:
https://github.com/vazarkevych/Parse-SDK-iOS-OSX/tree/SPM

**Comment by mtrezza** [comment]
@adwenn Did you get a chance to try out adding the SDK using SPM?

**Comment by mtrezza** [comment]
Closing as release [2.0.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/2.0.0) supports import via Swift Package Manager.

**Comment by adwenn** [comment]
> 

Hi @mtrezza,

I forgot mention:  I used the Swift Package Manager (SPM) from Martin Man:
https://github.com/mman/Parse-SDK-iOS-OSX/tree/spm 

This one worked perfectly in my case. The newer one of vazarkevych [SPM] gave me some more errors. So I removed and continue with the other one.

Thanks alot for your help.  I owe you a cup of coffee.

**Comment by mtrezza** [comment]
Interesting, would you mind sharing the errors? Maybe it's something we need to fix in the official version.

**Comment by adwenn** [comment]
> Interesting, would you mind sharing the errors? Maybe it's something we need to fix in the official version.

To give you a proper answer to your question I'm going to provide you with a bit of context on the project I'm working on. It was created in 2019 with some 3rd party libraries (including this iOS Parse-SDK-iOS).  I had to bring this project back to live with minimal effort.  So basically build, run and deploy to the app store.  I didn't want to do any rewrite on the existing (2019) code for it to work.

In order for me to properly answer your question: I took a deep dive into it what was causing these errors and it seems that most of them came because I didn't properly remove the carthage (Parse-SDK) version out of the project. The only actual errors I was getting were:
1. Target Deployment  (I have minimum 11.0 but it was built for newer iOS Simulator version 12.0)
2. _import Parse_ should be change to either _import ParseUI_ or _import ParseCore_ and this implementation started working too.

So it seems that there is **no** errors or bugs in this version.  

If you have any other questions please let me know

**Comment by adwenn** [comment]
These are not error but warnings:
Object file (/Users/adwenn/Library/Developer/Xcode/DerivedData/undekabesta-bmvhaatqyaqfvqcbtweebkybniax/Build/Products/Debug-iphonesimulator/ParseTwitterUtils.o) was built for newer iOS Simulator version (12.0) than being linked (11.0)

Object file (/Users/adwenn/Library/Developer/Xcode/DerivedData/undekabesta-bmvhaatqyaqfvqcbtweebkybniax/Build/Products/Debug-iphonesimulator/ParseCore.o) was built for newer iOS Simulator version (12.0) than being linked (11.0)

Object file (/Users/adwenn/Library/Developer/Xcode/DerivedData/undekabesta-bmvhaatqyaqfvqcbtweebkybniax/Build/Products/Debug-iphonesimulator/ParseUI.o) was built for newer iOS Simulator version (12.0) than being linked (11.0)

Object file (/Users/adwenn/Library/Developer/Xcode/DerivedData/thisproject-bmvhaatqyaqfvqcbtweebkybniax/Build/Products/Debug-iphonesimulator/ParseTwitterUtils.o) was built for newer iOS Simulator version (12.0) than being linked (11.0)

Object file (/Users/adwenn/Library/Developer/Xcode/DerivedData/thisproject-bmvhaatqyaqfvqcbtweebkybniax/Build/Products/Debug-iphonesimulator/ParseCore.o) was built for newer iOS Simulator version (12.0) than being linked (11.0)

Object file (/Users/adwenn/Library/Developer/Xcode/DerivedData/thisproject-bmvhaatqyaqfvqcbtweebkybniax/Build/Products/Debug-iphonesimulator/ParseUI.o) was built for newer iOS Simulator version (12.0) than being linked (11.0)

Object file (/Users/adwenn/Library/Developer/Xcode/DerivedData/thisproject-bmvhaatqyaqfvqcbtweebkybniax/Build/Products/Debug-iphonesimulator/FacebookCore.o) was built for newer iOS Simulator version (12.0) than being linked (11.0)

**Comment by mtrezza** [comment]
@adwenn Thanks for clarifying. We want to make sure we provide a SDK that works so that developers don't have to rely on 3rd party repositories.
