### ISSUE TITLE
Adding via SPM doesn't work due to unstable Bolts dependency

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-iOS-OSX#1694]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description

Adding via SPM doesn't work due to unstable Bolts dependency.

### Steps to reproduce

Add SDK via Xcode SPM.

**Comment by mtrezza** [comment]
@noobs2ninjas @drdaz @mman 

Release 2.0.0 has SPM support, but this above issue occurs due to Bolts being "unstable".

We would need to make a Bolts release with the changes in https://github.com/vazarkevych/Bolts-ObjC/tree/spm, but our forked Bolts is out of sync with the original Bolts repo. There are 1 or 2 commits that are in our forks but not in the original and vice versa. Do you have any recommendation how to solve this? I assume we have to use our own fork because we cannot expect anyone to merge PRs in the original repo, which had it's last update 3 years ago?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [2.0.1](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/2.0.1)
