### ISSUE TITLE
Undefined symbols for architecture x86_64: "_swift_stdlib_isStackAllocationSafe" #2175

### ISSUE THREAD

**Issue by yasirmturk** [parse-community/Parse-SDK-iOS-OSX#1703]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description
I have added facebook SDK using SPM and using only Core/Share
I am using Parse for login

### Actual Outcome
```
"_swift_stdlib_isStackAllocationSafe", referenced from:
      function signature specialization <Arg[1] = Owned To Guaranteed> of generic specialization <FBSDKLoginKit.FBPermission> of Swift._NativeSet.intersection(Swift._NativeSet<A>) -> Swift._NativeSet<A> in FBSDKLoginKit(LoginManager.o)
      merged function signature specialization <Arg[1] = Owned To Guaranteed> of generic specialization <FBSDKLoginKit.FBPermission, Swift._NativeSet<FBSDKLoginKit.FBPermission>> of Swift._NativeSet.genericIntersection<A where A == A1.Element, A1: Swift.Sequence>(A1) -> Swift._NativeSet<A> in FBSDKLoginKit(LoginManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Expected Outcome
The app should build for simulator but it fails

###  Environment
Xcode version 13.2.1
Facebook iOS SDK version 15.1.0
Dependency Manager SPM

Client
- Parse ObjC SDK version: `2.0.2`

**Comment by mtrezza** [comment]
- You wrote that you are "using Parse for Login" - do you mean you are using the PFUser login method or the FacebookUtils?
- Does the issue also occur on a real device?
- Does the issue also occur when not adding and using FacebookUtils?

**Comment by yasirmturk** [comment]
- Yes, I am using `PFFacebookUtils` `PFFacebookUtils.logInInBackground`
- Yes, same error on building for device
- The issue remains if I remove all imports of `ParseFacebookUtils`, `FBSDKCoreKit` & `FBSDKLoginKit`

**Comment by mtrezza** [comment]
Could this be a FB SDK issue, since you're not using PFFacebookUtils and the error message refers to `FBSDKLoginKit.FBPermission`.

**Comment by yasirmturk** [comment]
Already reported there https://github.com/facebook/facebook-ios-sdk/issues/2175

**Comment by mtrezza** [comment]
I'm closing this for now as it seems to be a dependency issue.
