### ISSUE TITLE
PFFacebookUtilsDevice or initializeFacebook not found

### ISSUE THREAD

**Issue by yasirmturk** [parse-community/Parse-SDK-iOS-OSX#1706]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description

PFFacebookUtils.initializeFacebook(applicationLaunchOptions: launchOptions)
        PFFacebookUtilsDevice.initializeFacebook(applicationLaunchOptions: launchOptions)

### Steps to reproduce
Download binary, unzip and add to project
`import ParseFacebookUtilsV4`

### Actual Outcome
Should be able to initializeFacebook

### Expected Outcome
member not found

###  Environment

Client
- Parse ObjC SDK version: `2.0.2`

**Comment by alexionut** [comment]
Are there any updates on this issue?

**Comment by mtrezza** [comment]
The only supported install option is via SPM; closing as this issue describes downloading binaries and refers to an older version of the SDK.

**Comment by alexionut** [comment]
This issue is also in the latest version via SPM. PFFacebookUtils has no member 'initializeFacebook'. 
And from what I can tell, this issue has existed since the move from cocoapods to SPM. Or am I missing something?

**Comment by mtrezza** [comment]
It if wasn't removed, it will likely be removed in a future version. We do not plan to continue to support these convenient functions anymore, because the choice of Facebook and Twitter is not only arbitrary, but the functionality of 3rd party auth is there anyway and it's just a couple of lines of code more for the developer to integrate the auth provider of their choice.
