### ISSUE TITLE
Unable to install with SPM

### ISSUE THREAD

**Issue by bcbeta** [parse-community/Parse-SDK-iOS-OSX#1716]
When trying to add the package I get the following error:
> Failed to resolve dependencies Dependencies could not be resolved because 'parse-sdk-ios-osx' depends on 'facebook-ios-sdk' 15.1.0..<16.0.0 and root depends on 'facebook-ios-sdk' 12.0.0..<13.0.0.

**Comment by mtrezza** [comment]
Do you have an old FB SDK dependency in your Xcode project?

**Comment by bcbeta** [comment]
Ah yes I had an older version of Facebook SDK previously installed.

**Comment by bcbeta** [comment]
I am now able to install but 
`import ParseObjC` 
Gives the error "No such module".

**Comment by bcbeta** [comment]
nvm I see that ParseCore is the correct module.
