### ISSUE TITLE
'Parse/Parse.h' file not found when including Parse using SPM

### ISSUE THREAD

**Issue by ashish-naik** [parse-community/Parse-SDK-iOS-OSX#1729]
- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [ x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [ x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description
i am using Cocoapods but want to move to SPM so removed from podfile but getting error 'Parse/Parse.h' file not found. in bridging header file. I selected FacebookUtilsiOS, ParseObjc, ParseUI. 

i tried selecting all modules but facebookUtilstvOS kept giving compiling error. i Added tvOS in destinations also.

`facebook-ios-sdk/FBSDKTVOSKit.xcframework:1:1 While building for iOS, no library for this platform was found in`

Already raised on Community forum but no solution received yet so raising here.

### Steps to reproduce
Happening in fresh Xcode project also with latest version 2.2.0

###  Environment
Xcode 14.2
M1 Mac

Client
- Parse ObjC SDK version: 2.2.0

Server
- Parse Server version: N/A
- Operating system: macOS 13.1 (22C65)
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): N/A

Database
- System (MongoDB or Postgres): N/A
- Database version: N/A
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): N/A

### Logs
Attached [sample project](https://drive.google.com/file/d/1tAkWwEL0eIu1UnNxV1F0LjPl1xVX0HYp/view?usp=sharing) and [screenshots](https://drive.google.com/file/d/1fBTFWtuKjCz2BkFo7TBvUM1DYxdFxlxz/view?usp=sharing).

**Comment by santiagoprieto** [comment]
I got it to work by changing two settings:
`Targets > Your Target > Build Settings > Packaging > Defines Module > No`
`Targets > Your Target > Build Settings > Search Paths > Framework Search Paths > $(PROJECT_DIR) $(inherited)`

**Comment by mtrezza** [comment]
Could you take a look whether this is already fixed in https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1712?

**Comment by dplewis** [comment]
@mtrezza Since we have the Starter Projects should we add every submodule to every starter? In the original post if I added `FacebookUtilsiOS` to a tvOS app what should happen?

* Create a compatibility table for each submodule in the README
* Allow the tvOS app to run and the submodule just show warnings
