### ISSUE TITLE
ParseLiveQuery: 2 compilation errors related to Starscream

### ISSUE THREAD

**Issue by mathieulb** [parse-community/Parse-SDK-iOS-OSX#1738]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description
Xcode 14.3.1 cannot compile ParseLiveQuery in ParseObjC 2.7.0 nor 2.3.0 (using StarScream 4.0.6, auto-installed as dep of ParseObjC)

Also cannot compile ParseLiveQuery & ParseObjC 1.19.4 recently (using pod), but 1.19.4 worked until updating pod.

### Steps to reproduce

* remove Parse from Podfile and run pod update
* Xcode -> File -> Add Packages... -> add ParseObjC exact 2.7.0
* Product -> Clean build folder... -> Clean
* Product -> Build (2 errors)
* Xcode -> File -> Add Packages... -> remove ParseObjC exact 2.7.0
* Xcode -> File -> Add Packages... -> add ParseObjC exact 2.3.0
* Product -> Clean build folder... -> Clean
* Product -> Build (2 errors)
* Xcode -> File -> Add Packages... -> remove ParseObjC exact 2.3.0
* add back Parse 1.19.4 in Podfile and run pod update
* Product -> Clean build folder... -> Clean
* Product -> Build (2 errors, but this same version worked recently)

### Actual Outcome

With two errors :

ParseLiveQuery/ParseLiveQuery/Internal/ClientPrivate.swift:116:1 Type 'Client' does not conform to protocol 'WebSocketDelegate' / fix: add public func didReceive(event: Starscream.WebSocketEvent, client: Starscream.WebSocketClient)

ParseLiveQuery/ParseLiveQuery/Internal/ClientPrivate.swift:118:9 Switch must be exhaustive / fix: add case .peerClosed

Attempts to apply the 2 fixes require unlocking the file if installed as pod ; but if "Add Packages..." is used instead, those fixes cannot be apply because the file is read-only (note: buggy Xcode lets you apply the fix, then denies the possibility to remove the placeholders or typing anything)

### Expected Outcome

No errors

###  Environment

Client
- Parse ObjC SDK version: 2.7.0 or 2.3.0 (or fresh reinstall of 1.19.4 but not my former installation of the same version, which means an updated dep is causing the incompatibility)

Server
- Parse Server version: not relevant for a compilation error in the client
- Operating system: MacOS 13.5.1
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): not relevant for a compilation error in the client

Database
- System (MongoDB or Postgres): not relevant for a compilation error in the client
- Database version: not relevant until the client compiles
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): not relevant for a compilation error in the client

**Comment by mboyd1993** [comment]
Yes, I can confirm that I have this exact same issue after updating the Parse SDK in an existing project to version 2.7.0.  The two fixes that @mathieulb suggested do get the compilation error to go away, but since the files in the Swift package are read-only, I can only make changes by opening the files in another editor and then there's still no way to save the files.
