### ISSUE TITLE
Remove alternative install options

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-iOS-OSX#1740]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).

### Current Limitation

Additional installation methods are outdated and causes a lot of overhead on development. With the removal of CocoaPod and Carthage the focus should be on SPM only. The current CI takes ~40 minutes. Integration testing doesn't exist. The release build can't compile on XCode 14 without removing arm64 support or converting to release build to xcframework.

### Feature / Enhancement Description

- [x] Update [iOS Guide](https://docs.parseplatform.org/ios/guide/) get started instructions
- [x] Update README installation instructions
- [x] Update Contributing Guide for running Starter Projects and using SPM for integration testing.
- [x] Remove Release Assets from CI
- [x] Use SPM in Starter Projects
- [x] Remove Xcode 11 and macos-11 from CI

**Comment by dplewis** [comment]
> What is the motivation to remove the assets?

Should the CI ensures the project builds and compiles or build a framework for release? We also build a Bolts-Objc framework for release too.

> If we later find a significant demand for assets we can look into how to add them

If this happens we should handle assets properly. Converting the universal FAT framework into a xcframework and release it under SPM as a binaryTarget. This would provide a binary format for security, offline development, and Xcode 14+ support. I haven't tested the existing assets on Apple Silicon yet.

> this shouldn't stop the further SDK development

The main goal is to get the CI down to 5-10 minutes. This project needs a lot of cleanup to get there. A quicker development cycle would be helpful.

**Comment by mtrezza** [comment]
But this issue was broader than only assets, right? We'd still want to remove relicts from Cocoapods, Carthage, etc?

**Comment by dplewis** [comment]
>  Also, if we cannot upgrade the CI and Xcode tests to newer Xcode versions, we'll have a problem soon.

Technically there should be a problem now as Swift 5.5 isn't installed on older version of Xcode. 

```
xcodebuild: error: Could not resolve package dependencies:
  package at '/Users/runner/work/Parse-SDK-iOS-OSX/Parse-SDK-iOS-OSX' is using Swift tools version 5.5.0 but the installed version is 5.2.0
```

**Comment by dplewis** [comment]
@mtrezza Now that you understand the situation how do you want to proceed?

**Comment by mtrezza** [comment]
I'd say let's drop assets and upgrade as much as possible. The argument for this is that if we don't upgrade now, every developer using the SDK will be affected, not just the ones using the assets, which I assume is a minority. So I'd choose the less impactful path going forward.

**Comment by dplewis** [comment]
Sounds good, I'll finish my checklist
