### ISSUE TITLE
Remove Carthage Dependencies

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-iOS-OSX#1747]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description

Although Carthage support has been removed there is a lot of legacy code still in the repo. Carthage supports dynamic frameworks meaning we would have to recompile these dependencies. This can lead to longer build times and significant increases in indexing. We can simply swap them out for their SPM counterparts.

- [x] Use OCMock static xcframework
- [x] Use facebook-ios-sdk SPM
- [x] Use Bolts SPM
- [x] Use Bolts Swift SPM
- [x] Use Starstream SPM
- [x] Remove git submodules
- [x] Remove Cartfile
- [x] Remove Scripts/build_third_party.rb
- [x] Remove any unnecessary `.xcodeproj` references
- [x] Remove Carthage install from CI

**Comment by mtrezza** [comment]
Has this been closed via https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1754?

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1763
