### ISSUE TITLE
Bolts causing CI failure

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-iOS-OSX#1759]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description

```
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/runner/work/Parse-SDK-iOS-OSX/Parse-SDK-iOS-OSX/Carthage/Checkouts/Bolts-ObjC/Bolts.xcodeproj -scheme Bolts-iOS-Dynamic -configuration Release -derivedDataPath /Users/runner/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3.1_14E300c/Bolts-ObjC/1.9.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/r_/vbvvglrx3lvds6dp_mbyq3_c0000gn/T/Bolts-ObjC SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/runner/work/Parse-SDK-iOS-OSX/Parse-SDK-iOS-OSX/Carthage/Checkouts/Bolts-ObjC)
```

**Comment by mtrezza** [comment]
Interesting that the [CI](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/.github/workflows/ci.yml) [passed](https://github.com/parse-community/Parse-SDK-iOS-OSX/actions/runs/6438538921) for the PR branch but [failed](https://github.com/parse-community/Parse-SDK-iOS-OSX/actions/runs/6440880523) for the master branch.

**Comment by dplewis** [comment]
> Could that be because of the Cache Carthage step?

I already tried that https://github.com/dplewis/Parse-SDK-iOS-OSX/pull/10

**Comment by dplewis** [comment]
> Interesting that the CI [passed](https://github.com/parse-community/Parse-SDK-iOS-OSX/actions/runs/6438538921) for the PR branch

Thats old news

> Could that be because of the Cache Carthage step?

I already tried that https://github.com/dplewis/Parse-SDK-iOS-OSX/pull/10

**Comment by mtrezza** [comment]
Does this affect the SDK or only the CI?

**Comment by dplewis** [comment]
Seriously do I have to explain everything to you? Compile some code and figure it out. It's not my job to teach you. No offense
