### ISSUE TITLE
Undefined Symbols  _OBJC_CLASS_$_Parse

### ISSUE THREAD

**Issue by spiderguy84** [parse-community/Parse-SDK-iOS-OSX#1771]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [ x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [ x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description
<After adding Parse and attempting to initializeWithConfiguration builds failed>

### Steps to reproduce
<Install parse, initializeWithConfiguration in AppDelegate>

### Actual Outcome
<Failed>

### Expected Outcome
<App runs>

###  Environment
<Xcode 15.1, macOS 14.1.1, >

Client
- Parse ObjC SDK version: `2.7.3`

Server
- Parse Server version: `N/A`
- Operating system: `N/A`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `N/A`

Database
- System (MongoDB or Postgres): `N/A`
- Database version: `N/A`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `N/A`

### Logs
<ld: Undefined symbols:
  _OBJC_CLASS_$_Parse, referenced from:
       in AppDelegate.o
  _OBJC_CLASS_$_ParseClientConfiguration, referenced from:
       in AppDelegate.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
>

**Comment by JohnCaccavale** [comment]
I seem to be having a similar issue with the macOS SDK today (along with about a hundred `Double-quoted include "ParseHeader" in framework header, expected angle-bracketed instead` warnings)

My MacOS command line app builds fine when I do a debug build and run. When I try to Archive a Release version of the utility, these errors then occur with Xcode 15.3 running on an Intel based Mac.

There does not seem to be anything out of the ordinary with regard to my Build Settings. Architectures set to ARCHS_STANDARD. Nothing specified for Excluded Architectures.

My logs are as follows.

> ld: warning: ignoring file '/Users/John/Documents/MyProject/Parse/Bolts.framework/Versions/A/Bolts': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/John/Documents/MyProjectr/Parse/Parse.framework/Versions/A/Parse': found architecture 'x86_64', required architecture 'arm64'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PFObject", referenced from:
      _OBJC_CLASS_$_MyClass in MyClass.o
      _OBJC_CLASS_$_MyClass2 in MyClass2.o
       in MyClass3.o
  "_OBJC_CLASS_$_PFQuery", referenced from:
       in SomeClass.o
  "_OBJC_CLASS_$_Parse", referenced from:
       in SomeClass.o
  "_OBJC_CLASS_$_ParseClientConfiguration", referenced from:
       in SomeClass.o
  "_OBJC_METACLASS_$_PFObject", referenced from:
      _OBJC_METACLASS_$_SomeClass in SomeClass.o
      _OBJC_METACLASS_$_SomeClass in SomeClass.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by JohnCaccavale** [comment]
@spiderguy84 are you still having this issue. I removed the prebuilt compiled framework from my project, re-added the framework via Swift Package Manager, and these issues went away for me.

**Comment by mtrezza** [comment]
@JohnCaccavale If the issue is resolved for you, then I'll go ahead and close this issue. In case @spiderguy84 reports back that the issue still exists, we can re-open.
