### ISSUE TITLE
Xcode 15.3 and App Store Connect Issue

### ISSUE THREAD

**Issue by chriscborg** [parse-community/Parse-SDK-iOS-OSX#1775]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases).

### Issue Description
When archiving the app and attempting to upload it to App Store, the Facebook SDK causes an error.
 
This is reported on the Facebook SDK here: https://github.com/facebook/facebook-ios-sdk/issues/2353 and was resolved in version 17.0.0.

### Steps to reproduce
Archive the app using Xcode 15.3 and upload to the app store.

### Actual Outcome
The app should upload successfully

### Expected Outcome
The below error shows up on Xcode during submission.

```
Asset validation failed
Invalid Bundle. The bundle AdoreMe.app/Frameworks/FBSDKCoreKit.framework does not support the minimum OS Version specified in the Info.plist
```

###  Environment
- macOS: 14.4
- Xcode: 15.3

Client
- Parse ObjC SDK version: 2.7.3

**Comment by mtrezza** [comment]
Same question as in https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1774#issuecomment-2008740189. I'd suggestion to remove it and developers can use whatever Facebook SDK version they want.

**Comment by mtrezza** [comment]
@chriscborg Would you want to remove the FacebookUtils altogether?

**Comment by chriscborg** [comment]
I'm not sure if this issue is resolved yet. In order to upload using Xcode 15.3, we need to use Facebook SDK 17 and when I switch to this SDK, I'm getting an error from Parse `Facebook auth is invalid for this user. (Code: 101, Version: 4.0.1)`. With Facebook 17, the traditional approach of access tokens was changed to use JWT with the introduction of Limited Login. Do you have a working version of a Facebook integration now that ParseFacebookUtils has been removed? Not sure if I am misconfiguring something. @mtrezza do have some insight on this?

**Comment by mtrezza** [comment]
@chriscborg could you please open a new issue and provide details?
