### ISSUE TITLE
CI not working

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-iOS-OSX#1777]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description

Error in CI:

> Submodule 'Vendor/xctoolchain' (https://github.com/parse-community/xctoolchain.git) registered for path 'Vendor/xctoolchain'
> Cloning into '/Users/runner/work/Parse-SDK-iOS-OSX/Parse-SDK-iOS-OSX/Vendor/xctoolchain'...
> Submodule path 'Vendor/xctoolchain': checked out 'dc0ccfff8bfc62b9b87e6bcf6ee26d3e90e05509'
> ERROR:  Error installing bundler:
> 	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
> 	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.2.137.

### Steps to reproduce

See https://github.com/parse-community/Parse-SDK-iOS-OSX/actions/runs/8565540479/job/23492491652?pr=1776

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.0.0](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/3.0.0)
