### ISSUE TITLE
Several files not found when including Parse using SPM on Xcode 16

### ISSUE THREAD

**Issue by bmueller** [parse-community/Parse-SDK-iOS-OSX#1793]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-SDK-iOS-OSX/security/policy).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases). 

### Issue Description
I have an existing project that includes Parse via SPM. It builds just fine on Xcode 15. But when I try to build the same project on the Xcode 16 beta, I get several "file not found" error messages (PFObjectFileCodingLogic, PFAsset, PFOfflineStore, BFTask+Private, and ParseClientConfiguration_Private). I tried creating a brand new project, added Parse via SPM, and got similar errors when trying to build on Xcode 16.

### Steps to reproduce
Create a new project, add Parse via SPM, then try to build it on Xcode 16 beta.

### Actual Outcome
The compiler complains that it can't find some files.

### Expected Outcome
The project builds with no issues.

###  Environment
Xcode 16 beta 2.

Client
- Parse ObjC SDK version: 4.1.0

Server
- Parse Server version: N/A
- Operating system: N/A
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): N/A

Database
- System (MongoDB or Postgres): N/A
- Database version: N/A
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): N/A

**Comment by mtrezza** [comment]
Closing as duplicate of https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1792

**Comment by mtrezza** [comment]
Could this be related to https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1792?

**Comment by bmueller** [comment]
I did see the issue @mman raised and it seemed like it was building for him since he was using code to keep the app from crashing once it was run. Open question on whether he was using SPM to build his project, though. 

Is it possible to add a bug bounty to this issue? Happy to pay to have this fixed quickly!

**Comment by mtrezza** [comment]
@bmueller Sure, please see https://github.com/parse-community/Governance/blob/main/BOUNTY.md#sponsored-bounty.

**Comment by bmueller** [comment]
@mtrezza ok cool, so if I contribute via the "sponsor" button, how do I then get that applied to this issue? I didn't see an option for that on the sponsorship page. Also, I'd be happy to pay an additional amount if someone could get this addressed this week so I don't have to wait to continue work on my project - is there a mechanism to pay a bonus after the fact?

**Comment by mtrezza** [comment]
@bmueller For more info and to set up a sponsored bounty, please get in touch via our Slack.

**Comment by bmueller** [comment]
@mtrezza sounds great, how can I get an invite to the workspace?

**Comment by mtrezza** [comment]
It's open to anyone; I've added the Slack badge to the README, it was missing. Just click on it and get in touch.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.1](https://github.com/parse-community/Parse-SDK-iOS-OSX/releases/tag/4.1.1)
