### ISSUE TITLE
Background NSURLSession Support

### ISSUE THREAD

**Issue by nlutsenko** [parse-community/Parse-SDK-iOS-OSX#183]
This issue is to track a possibility of adding background NSURLSession support for all or some of the network requests in Parse SDK. While it would be useful for every piece of the SDK, `PFFile`s would benefit tremendously from it.

cc @grantland @richardjrossiii @jonathandann

**Comment by christianpbrink** [comment]
I'm implementing my own download+caching system for use with PFFile URLs because I need this.

**Comment by drbarto** [comment]
Any news on this feature?

Is there a way to get access to the `NSURLSession` or provide a custom (background-enabled) `NSURLSessionConfiguration` without patching the Parse lib?
