### ISSUE TITLE
fetchIfNeededInBackgroundWithBlock returns object whose subobjects return YES to isDataAvailable and it shouldn't

### ISSUE THREAD

**Issue by buttcmd** [parse-community/Parse-SDK-iOS-OSX#249]
I have an object that when received i don't know if is fetched or not so i make a fetchIfNeededInBackgroundWithBlock. Inside the callback i take one of its columns which is a pointer to another object. This object is empty. It is only a pointer. Till this point everything looks fine, but when i call fetchIfNeededInBackgroundWithBlock in this retrieved object it doesn't fetch anything from database and i have noticed that the call to isDataAvailable returns YES although it has no data and the object was never fetched (its father was fetched but the current object wasn't included)

This is the example code:

```
__weak PFImageView *weakGoalIcon = self.goalIcon;
[self.braceletGoal fetchIfNeededInBackgroundWithBlock:^(PFObject *object, NSError *error){
    //this works Ok and fetches the BraceletGoal Object
    BraceletGoal *bg = (BraceletGoal*)object;
    //this call always assume that it has data but it has not
    [bg.goalType fetchInBackgroundWithBlock:^(PFObject *object, NSError *error){
        //Here object is an object whose icon field is empty so 2 lines ahead gt.icon is null
        GoalType *gt = (GoalType*)object;
        weakGoalIcon.file = gt.icon;
        [weakGoalIcon loadInBackground];
    }];
}];
```

I have the debugger data that can help: (At the moment of the po commands i 'm stopped in a breakpoint just under "BraceletGoal _bg = (BraceletGoal_)object;" line)

```
(lldb) po bg
<BraceletGoal: 0x7ffc81471cd0, objectId: kZVfV5KXWV, localId: (null)> {
    bracelet = "<Bracelet: 0x7ffc83c4ad00, objectId: DJgKE7nfHB>";
    goalType = "<GoalType: 0x7ffc83e02ba0, objectId: nShDFkDOxG>";
    userGot = "<PFUser: 0x7ffc83cb1ab0, objectId: YzpLiIwkhw>";
}

(lldb) po bg.goalType
<GoalType: 0x7ffc83e02ba0, objectId: nShDFkDOxG, localId: (null)> {
}

(lldb) po [bg.goalType isDataAvailable]
YES
```

As you can see bg.goalType is an empty pointer but isDataAvailable says YES

**Comment by richardjrossiii** [comment]
Thanks for the report. Can I ask what your object schema looks like?

**Comment by buttcmd** [comment]
Yes of course you can. The objects are subclasses of PFObject

BraceletGoal has this properties:
    
    @interface BraceletGoal : PFObject <BraceletGoal,PFSubclassing>
    @property (strong) Bracelet *bracelet;
    @property (strong) GoalType *goalType;
    @property (strong) PFUser *userGot;

and GoalType has this ones:

    @interface GoalType : PFObject <GoalType,PFSubclassing>
    @property (strong) NSString *name;
    @property (strong) PFFile *icon;
    @property (strong) NSString *description;


And this is an example of the objects in JSON:

BraceletGoal
	  {
          "bracelet": {
              "__type": "Pointer",
              "className": "Bracelet",
              "objectId": "MIG3HpPYnh"
          },
          "createdAt": "2015-09-09T16:45:18.838Z",
          "goalType": {
              "__type": "Pointer",
              "className": "GoalType",
              "objectId": "m8bscOJEEy"
          },
          "objectId": "0fFeI3XhGF",
          "updatedAt": "2015-09-09T16:45:18.838Z",
          "userGot": {
              "__type": "Pointer",
              "className": "_User",
              "objectId": "1Yg7ZKOUij"
          }
      }

GoalType
	{
        "createdAt": "2015-04-01T17:17:17.093Z",
        "description": "Bracelet - Destiny reached",
        "icon": {
            "__type": "File",
            "name": "tfss-43d68516-a11a-4467-9909-aa12345616-goal11.png",
            "url": "http://files.parsetfss.com/d62a29fb-d104-4ed1-97f0-a85b935d948e/tfss-43d68516-a11a-4467-9909-aa12345616-goal11.png"
        },
        "name": "Destiny reached",
        "objectId": "nShDFkDOxG",
        "updatedAt": "2015-09-02T17:01:51.720Z"
    }

**Comment by buttcmd** [comment]
Is there anything new in reference to this issue?

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
