### ISSUE TITLE
parse query returns object with some key values out-of-date

### ISSUE THREAD

**Issue by geraldhinson** [parse-community/Parse-SDK-iOS-OSX#273]
I am seeing an issue wherein parse queries return a mix of updated and out-of-date values for a given object's keys.

My app runs on both OSX (10.10.3) (Parse v1.7.5) and IOS (8.3) (Parse v1.8.2). The apps on both platforms have the local datastore enabled.

The scenario is thus:
- update the values of two keys in an object on IOS, pin it local, saveEventually()
- watch the object via the web-based databrowser on parse.com until the update shows up in the cloud
- run a query on OSX to fetch the new values for said object

Results: the query returns the object on OSX but only one of the keys has its value updated.

Running this in the opposite direction (OSX does update/pin/saveEventually, IOS fetches it) seems to work fine (ie. both keys have their updated values).

**Comment by richardjrossiii** [comment]
As this is only happening on OS X, this most likely is an issue that has since been fixed in the latest SDK (1.8.4). I strongly recommend updating your SDK and seeing if that solves your issues.

**Comment by geraldhinson** [comment]
Weird. I downloaded both IOS and OSX on the same day (or very close). I didn't realize OSX had been updated since. I'll update now and test it.  Was there a known bug of this nature prior to 1.8.4?

**Comment by geraldhinson** [comment]
OK, removed old binaries. Downloaded latest, followed the quickstart guide as always and got this runtime error in XCode:

dyld: Library not loaded: @rpath/libclang_rt.asan_osx_dynamic.dylib
  Referenced from: /Users/[me]/[myappfolder]/Builds/MacOSX/build/Debug/Test1.app/Contents/Frameworks/Parse.framework/Versions/A/Parse
  Reason: image not found

Some new setup required to leverage the new libraries?

**Comment by richardjrossiii** [comment]
No, it would appear that we shipped the wrong binaries though. :( These are ones built for testing. We'll get this fixed ASAP.

If you're using Xcode 7 you should be able to enable address sanitizer for your scheme to make this go away for now.

**Comment by geraldhinson** [comment]
Well, since it was just released yesterday I'm not quite on it yet...  Best guess on eta for correct binaries?

**Comment by richardjrossiii** [comment]
Hopefully today or tomorrow, in the meantime, can you try with 1.8.3 on both platforms, and see if the issue persists?

**Comment by geraldhinson** [comment]
In progress...

**Comment by geraldhinson** [comment]
OK.  With both IOS and OSX built using 1.8.3, the bug repros as originally stated above.

**Comment by richardjrossiii** [comment]
Hmm, that is strange. I'll start investigating.

It would be really awesome if you could make a small repro project with this bug, to help us track it down faster, though!

**Comment by geraldhinson** [comment]
I *think* the issue may be a case of running a query against the cloud to see which rows match, but then the parse runtime returning them from the local datastore vs from the cloud. I ran an additional test this evening (prior to getting into update hell with IOS, XCode and OSX.. ha) and saw what I believe was a confirmation of this.

Here's the scenario in more detail:

Say you have an object class called Config that consists of a number and an array of strings. The array contains the deviceIDs (unique strings assigned by my app to each device) that have added that object into their local datastore. So, in addition, say you have two devices "IOS_Device" and "MacBook_Device". I'm implementing a simple "pull" replication model using the following 2 rules:

1) every time a device updates an object it removes all of the deviceIDs in the array except its own. It then pins the updated object and calls saveEventually on it resulting in the object (local and cloud) having only the last updater's deviceID in its array.
2) whenever a device wants to sync up with updates done by its peers, it queries the cloud class for objects that do not contain its own deviceID in the array. Any rows returned have their array updated with the local deviceID and are then pinned locally and saveEventually is called on the object. So, eventually (after sync is done on all devices) the object's array will have all deviceIDs in it.

So, if "IOS_Device" updates an object a la rule 1, the object will be found when "MacBook_Device" runs the query from rule 2. At that point "MacBook_Device" will add its deviceID into the array as well so ultimately both have the same value and the roll-your-own replication quiesces until the next update. (There is also a mechanism for delete but it is not relevant here so I'm not detailing it...)

What I saw in my final test of the evening was an object being returned that satisfied the query from rule 2... ie. the cloud version of that object's array did not contain "MacBook_Device" because it was most recently updated on "IOS_Device".  However, when I examined the object returned from the query in the background block, its array contained only "MacBook_Device" and the last number value that had been updated on "MacBook_Device" vs. the array containing "IOS_Device" and the last value that had been updated on "IOS_Device". So, it looks like the query is smart enough to run against the cloud, but the data retrieval gets confused and pulls the object from the local datastore vs. the cloud. (No, the query is not setup to use the local datastore. :)  That's what I'd be asking about now if I were you.)

Originally I thought the array value was correct and the number was wrong because the query was written to only return objects that did not include "MacBook_Device". But upon further examination, it appears the query was satisfied based on the values stored in the cloud, but the object returned was the one from the local datastore on "MacBook_Device" vs. the newly updated row in the cloud.

Does this make sense?

**Comment by geraldhinson** [comment]
Here's a bit more analysis in case it is helpful.

On IOS while watching the debugger during the query to retrieve updated objects from the cloud, the PFObject returned has _serverData and _estimatedData that have identical values. And when I update this same object I can see my updates being applied under _estimatedData.

On OSX, the PFObject returned has _serverData and _estimatedData with differing values. _serverData has the correct values (most recent updated from the app on IOS that is reflected in the cloud). _estimatedData has the out-of-date values.  And, when I update the object (add device to array of strings) I do not see this reflected in _estimatedData.

Any ideas what is wrong?

**Comment by mrchristopher124** [comment]
Is there any update on this issue? I am seeing some very strange behavior. I am issuing a query (NOT from the local data store) and I am debugging the actual response from the Parse Network code and the data is correct but the object that I get back PFQuery's getObjectInBackgroundWithId method does not match the network response. I am trying to get the latest data for my current user object.

**Comment by Tom-Fox1** [comment]
@mrchristopher124 are you still experiencing this issue?

**Comment by cmmash** [comment]
I'm facing the same but with node on Ubuntu. In production and local as well.

**Comment by Tom-Fox1** [comment]
@cmmash what versions of Parse Server and the iOS SDK are you using?

**Comment by cmmash** [comment]
so sorry, actually my issue is with the JS sdk.
totally forgot to look at the repo! so much headache with the issue.

Thanks & Regards,
Ashish Kumar,
Senior Full-stack Developer,
CodeMyMobile

**Comment by Tom-Fox1** [comment]
@cmmash no worries, please do look through the existing issues on the [js SDK repo](https://github.com/parse-community/Parse-SDK-JS/issues) and open a new one if you feel it is necessary.
