### ISSUE TITLE
Parse does not create Object ID when device is offline

### ISSUE THREAD

**Issue by PSIPhone** [parse-community/Parse-SDK-iOS-OSX#342]
Dear team,

I am running into trouble that parse does not create objectID when offline so i have to take my own primary key in order to update the entity later.

http://pastie.org/10447953

When i want to update any customer then it goes to fire a query and finds matching object then i put condition to identify. The whole process takes time when it comes to performance.

Looking for guidance for optimum way to add update objects offline.

**Comment by nlutsenko** [comment]
Known limitation. There have been a looooong debate on the implementation of local objectId creation here at Parse.
We didn't come to full conclusion on when and most importantly how we are going to tackle it.

cc @grantland @hallucinogen

**Comment by nlutsenko** [comment]
Current workaround: 
Create your own custom unique field and query based on that, instead of using `objectId`.

**Comment by PSIPhone** [comment]
So, it's like we have to query table->find object in background->compare and update object.

Right?

**Comment by nlutsenko** [comment]
If you add another unique field to your customer class and query based on that - it should work.
Then you can distinguish between an unsaved and saved customer by whether an object has objectId or not.

**Comment by PSIPhone** [comment]
We have done same way with our own unique key. But this process is not optimum if rows are over 1k.

Also, parse duplicates the row (entity) sometimes.

**Comment by FreudGit** [comment]
Also think objectID should always exists. (my 2 cents)

**Comment by PSIPhone** [comment]
Dear, In offline it does not and duplicates of PFObject is issue we can't take. Any solution you have?

**Comment by hhanesand** [comment]
So the problem here is that if we choose to generate an object id, it can't collide with any other `PFObjects` on the main parse server?

**Comment by klemenzagar91** [comment]
Is there anything new about thist issue?
