### ISSUE TITLE
Proposal: Add ability to directly specify the pinned objects for a pin with a specific name.

### ISSUE THREAD

**Issue by nlutsenko** [parse-community/Parse-SDK-iOS-OSX#415]
One of the basic use cases of Local Datastore - pinning a results of the query to Local Datastore or using a pin to designate the specific types of objects/relationships/views.
This only applies to a pin with a small number of objects (since you should avoid fetching large amounts of objects from network anyhow).

Currently - it requires 2 operations:
- unpin all objects for a given pin with name
- pin new results to the pin with a given name

The proposal is to add a new API to set a given array of objects for a given pin, with API that might look like this:

``` objc
@interface PFObject : NSObject

+ (BFTask *)setPinnedObjects:(NSArray <__kindof PFObject *> *)objects forPinWithName:(NSString *)name;

@end
```

Benefits of this approach:
- no 2 step operations to set the contents for a specific pin
- much better performance, since we don't need to perform double write/transaction/etc to LDS
- this fits as Update into CRUD for LDS, where pin/unpin would be Create and Delete
- easier to write list views backed by LDS and fetched from network
- Profit?

What does everyone think?
Sounds like a sane, useful idea that a lot of people are going to use or something that adds unnecessary complexity?

cc @grantland @richardjrossiii @wangmengyan95 @stanleyw

**Comment by grantland** [comment]
> no 2 step operations to set the contents for a specific pin

It's not clear to me how this solves unpin -> pin

**Comment by nlutsenko** [comment]
Instead of adding new objects and replacing the old ones - it will replace the old ones and delete the ones that are not in the set.
Roughly if you compare to how generic `Set` works:
- pin -> `union` operation on a set, where it adds new objects to the pin, or updates the existing ones
- unpin -> `minus` operation on a set, where it removes the objects that you specified
- setPinnedObjects -> `set` operation on a set, where it removes the objects that don't exist in the new array, as well as adds missing.

We can also add `intersect` operation, but I think that one is less useful.

**Comment by hhanesand** [comment]
:+1:

**Comment by nlutsenko** [comment]
@grantland You had some ideas/suggestions for naming here... Let me know if you came up with any good name.
also @richardjrossiii ideas about naming?
