### ISSUE TITLE
Parse 1.9.1 IOS6 support

### ISSUE THREAD

**Issue by nimrodYokee** [parse-community/Parse-SDK-iOS-OSX#493]
I upgraded parse from 1.8.5 to 1.9.1.
Now it looks like it does not support IOS6. 
Is there a workaround?

Thank you!

**Comment by nlutsenko** [comment]
Not really a workaround at this time, we deprecated support for iOS lower than 7.0 for the SDK starting from 1.8.0.
You can still continue to use a version below that (1.7.5), as that one will continue to work on iOS 6.

**Comment by nlutsenko** [comment]
Out of curiosity, what is your use case for iOS 6?
The amount of people on that version is very very low at this point.

**Comment by nimrodYokee** [comment]
Nikita, 5% of our user base are using IOS6. This is significant for us.

Thank you,

**Comment by mrFranklin** [comment]
Could you support iOS 6 again?
our develpoing game must support the iOS6 at this time.
if I use 1.7.5, it looks like not suppot iOS9.

**Comment by nlutsenko** [comment]
I'll look into what will it take for us to support iOS 6.
No guarantees at this point, but will definitely look into this.
