### ISSUE TITLE
Support for staged PFFiles in Local Datastore

### ISSUE THREAD

**Issue by nlutsenko** [parse-community/Parse-SDK-iOS-OSX#560]
Even though you can pin `PFObject`s to Local Datastore, all unsaved `PFFile`s are not persisted across runtimes of the application.
This issue is for tracking/discussing potential support for this as well as tracking implementation progress.

There are multiple reasons why this is not been implemented so far, including:
- The only unique identifier that a PFFile has is a url, that is generated only after the file is saved.
- Tracking object references to PFFiles in Local Datastore is tricky and gets even more tricky when the files should be deleted on object removal from LDS.

The rough ideas:
- Move PFFile staging outside of Caches directory (so we have a guarantee on persistence)
- When PFFile is staged - add a custom field to the file that would store a generated UUID
- This UUID would also be used for file name, so we can reconstruct a path for reading/saving
- Track PFFile references in Local Datastore, and at the moment where there are no more files - delete the actual contents of the staged files.

cc @grantland @hallucinogen @stanleyw

**Comment by FreudGit** [comment]
+1, sounds great. :)

**Comment by FreudGit** [comment]
@nlutsenko Any news on this?
