### ISSUE TITLE
Deadlock from Fetch, FetchIfNeeded not updating PFObjects

### ISSUE THREAD

**Issue by dtaitz** [parse-community/Parse-SDK-iOS-OSX#617]
Hello,

I use – [BFTask fetchAllInBackground] to update my view controller's objects when I start up my app. Recently when I make this call, I end up in a deadlock. Here is an example call stack of that deadlock:
https://gist.github.com/dtaitz/3fec6cf19e87b1ffaefe

I tried to get around this issue by instead calling -[BFTask fetchAllIfNeededInBackground]. This avoids the deadlock described, but does not update the PFObjects as desired. 

I cannot get to any core functionality of my app at this time as a result of the deadlock, or I am faced with not having the correct information present.

I am using the Parse SDK v.1.10.0 and Xcode 7.1.1.

Let me know what other information I can provide. Thanks as always.

David

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
