### ISSUE TITLE
Why does [PFPurchase buyProduct] requires me to login twice?

### ISSUE THREAD

**Issue by kross50** [parse-community/Parse-SDK-iOS-OSX#702]
I use PFPurchase's buyProduct method call to initiate the in-app purchase process. Although it requires me to enter the test account's email address and the password twice to complete the process.

When I enter the email and the password for the first time, the prompt just disappears and comes back after 2-3 seconds and I have to enter them again.  In the released app, this happens only for the first purchase on the device... if I go to purchase again, even after an app delete-reinstall, it doesn't seem to happen again.

I use non-renewing subscriptions.

THE SAME AS ANOTHER DEVELOPER'S ISSUE:
http://stackoverflow.com/questions/30332685/why-does-pfpurchase-buyproduct-requires-me-to-login-twice

**Comment by nlutsenko** [comment]
Hey @kross50, this is quite strange.
We are fully relying on StoreKit to make purchases for us and the code there is no different from a generic use case.

I am going to try to reproduce this issue, but any pointers would be helpful.

**Comment by kross50** [comment]
on main thread I simply do the following once:

[PFPurchase buyProduct:inAppProdName block:^(NSError *error) {
            if (!error) {
                // UI code that informs user the product has been purchased 
            }
            else {
                // UI error message and re-enable
            }
        }];

**Comment by kross50** [comment]
when using touchid to purchase it happens too... asks me twice to use touchid then asks do i want to buy

**Comment by Tom-Fox1** [comment]
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.
