### ISSUE TITLE
Please support swift-package-manager by adding Package.swift.

### ISSUE THREAD

**Issue by kconner** [parse-community/Parse-SDK-iOS-OSX#773]
Open source Swift apps can import packages using [swift-package-manager](https://github.com/apple/swift-package-manager). I'd like to import the Parse SDK in this manner.

Is this doable? Would the SDK even work in a shell app with no UIApplication?

**Comment by nlutsenko** [comment]
Hey @kconner, thanks for the request.
To the best of my knowledge Swift Package Manager is intended to support Swift code only.
Since, at the current stage, our SDK is fully written in ObjC, I am not sure whether this would work at all.

**Comment by kconner** [comment]
Ah yeah, you're probably right. Anyway, if you can recommended a best way to use Parse from a Swift shell script, that might help. For the time being I'm just using the REST API directly.

**Comment by nlutsenko** [comment]
It depends on how portable you want your shell script to be - if you want to be able to run on Linux, unfortunately we don't have an official solution/support at this point (it's coming, but depends on interest).

If you are ok it being OS X-only - you can use `CocoaPods` via static libraries + `Xcode`.
Linking statically would mean that you can distribute a single binary file for your app/script, compare to linking with frameworks. Also, attached frameworks to the releases on this repo will help, as those are precompiled static frameworks.

If nothing from this quite suits you - using a REST API is a good option.

P.S. I've just opened an issue to start a discussion about Linux and Swift native support - https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/774.

**Comment by funkenstrahlen** [comment]
I'd like to reopen this issue, because this is no longer true:

> To the best of my knowledge Swift Package Manager is intended to support Swift code only.
Since, at the current stage, our SDK is fully written in ObjC, I am not sure whether this would work at all.

Swift Package Manager does support objc projects: http://ankit.im/swift/2016/05/21/creating-objc-cpp-packages-with-swift-package-manager/

**Comment by flovilmart** [comment]
@funkenstrahlen, do you want to explore the feasibility?

**Comment by funkenstrahlen** [comment]
@flovilmart I will try to get it working and will open a PR. Let's see how far I get :)

**Comment by funkenstrahlen** [comment]
This will required the Bolts framework to support SPM too. I spend an issue there too: https://github.com/BoltsFramework/Bolts-ObjC/issues/308

**Comment by flovilmart** [comment]
Cool! Thanks!
