### ISSUE TITLE
Swift native SDK with Linux support

### ISSUE THREAD

**Issue by nlutsenko** [parse-community/Parse-SDK-iOS-OSX#774]
Hey everyone,

This issue is a proposal for implementation of Swift native SDK, including Linux support for it.
While we had few plans/discussions internally on this matter, we would love to hear your thoughts, as well as see how much interest there is and how valuable is it for you to have:
- Swift native SDK with native APIs that support more language features than currently
- Official Linux support, as Swift could compile and target Linux/FreeBSD.

Please comment here with your thoughts, suggestions or a simple `+1` if you like the idea.

**Comment by hhanesand** [comment]
+1

**Comment by JasonPanAD** [comment]
+2

**Comment by andrelind** [comment]
+1

**Comment by villepetersson** [comment]
+1

**Comment by jsslai** [comment]
+1

**Comment by maxcampolo** [comment]
+1

**Comment by netizen01** [comment]
+1

**Comment by fedort** [comment]
+1

**Comment by samwize** [comment]
+1

**Comment by cyring** [comment]
+1

**Comment by zirinisp** [comment]
+1

**Comment by skynext** [comment]
+1

**Comment by trejdych** [comment]
+1
