### ISSUE TITLE
Observables API on PFObject/Subclasses

### ISSUE THREAD

**Issue by nlutsenko** [parse-community/Parse-SDK-iOS-OSX#775]
Hey everyone,

This is a feature proposal to collect feedback/suggestions on potential APIs to observe fetch/save/delete on `PFObject` and subclasses.
At the current stage, my thoughts are as follows:
- Add `NSNotification`-based observation to fetch/update/delete of any `PFObject` that are going to be posted when an object is fetched/updated/deleted via call to Parse.
- Add multicast-delegate-based API for this
- Potentially add observables support to Bolts, that would allow the same approach, but without expanding our API by a lot (like multicast-delegate would do).

Please comment here with suggestions/ideas on the feature as well as whether this is useful for you.

**Comment by huguesbr** [comment]
:+1:

**Comment by hhanesand** [comment]
I've implemented this system manually in order to update tableviews with new information, so this would be something I'm interested in.

Bolts is growing on me as a great helper with async programming, so I would prefer option number 3.

**Comment by huguesbr** [comment]
I haven't dig into `Bolt`, so I would rather just piggy back of `NSNotification`. But always happy to play with something new :)
