### ISSUE TITLE
PFQuery Not Returning the Most Recent Data

### ISSUE THREAD

**Issue by mrchristopher124** [parse-community/Parse-SDK-iOS-OSX#822]
Hello,

I'm using the iOS SDK within an application and am experiencing some strange behavior. If I use the Parse API Console to query for my user using my user's objectId, the query via the API console returns the most up-to-date data for the user object.

However, if I do the same query from within my application code I do not get the most recent information back in my results. It's almost as if I'm getting back cached results somehow. Note that we are using the local datastore feature of Parse but that I've explicitly left out the fromLocalDatastore call when configuring the query. 

Another note. If I delete the application and log in fresh and perform the query then I get the latest results from the server. Note that we then pin the users results. On shutting down the app and starting it again, we get the current user via PFUser *currentUser = [PFUser currentUser]; and then attempt to fetch the latest information for the user from the server using a remote query but that remote query no longer returns the latest information for that user object.

It's definitely possible that I'm making a dumb user error when using the SDK but thus far have quadruple checked everything and tried various scenarios and everything seems in order. Any info at all would be great. 

Thanks!

**Comment by hhanesand** [comment]
Post your code?

**Comment by mrchristopher124** [comment]
That would be tricky as its a pretty large project. I did do a sanity check though and made a small stand alone project (https://github.com/mrchristopher124/parse-ios-test-app) and it of course works as expected. The login and start-up flow of our actual app is more or less in-line with what this sample app does except we are using facebook login via https://github.com/ParsePlatform/ParseFacebookUtils-iOS. I'll have to keep digging.

**Comment by darer** [comment]
I'm having the exact same problem as @mrchristopher124. The only difference is that this is happening to a custom class object. When I query the server I get the object with the old data, but I see that object.updatedAt is changed (up to date). Here's my code: 

`let query1 = PFQuery(className: "Conversations")
        query1.whereKey("user1", equalTo: user)
        let query2 = PFQuery(className: "Conversations")
        query2.whereKey("user2", equalTo: user)
        let query3 = PFQuery(className: "Conversations")
        query3.whereKey("user1", equalTo: "ALL")
        let query4 = PFQuery(className: "Conversations")
        query4.whereKey("user2Phones", equalTo: myPhone)
        let query = PFQuery.orQueryWithSubqueries([query1, query2, query3, query4])
        query.clearCachedResult()
            query.findObjectsInBackgroundWithBlock{(objects: [PFObject]?, error: NSError?) -> Void in
                if error == nil {
                    // The find succeeded.
                    // Do something with the found objects
                    if let objects = objects {
                        if objects.count > 0 {
                            for object in objects {
                                if object.objectId == "U25a0qCMsk" {
                                    print("server last updated: \(object.updatedAt)")
                                    print("user 1 unread: \(object["user1Unread"] as! Bool)")
                                    print("user 2 unread: \(object["user2Unread"] as! Bool)")
                                    print("user 2 lastName: \(object["user2LastName"] as! String)")
                                }
                            }
                        }
                    }
                } 
            }`

As you can see I even tried to clear the cache (I never enabled it) but still in my console I get this: 
`server last updated: Optional(2016-02-22 11:22:22 +0000) - Correct
user 1 unread: true - Incorrect
user 2 unread: false - Incorrect
user 2 lastName: Stanev - Incorrect`

The data that I see in Parse Website > Core > Browser is as follows:
`updatedAt: 2016-02-22T11:22:22.200Z
user1Unread: false
user2Unread: true
user2LastName: Stanev2`

Any ideas what might be wrong? Thanks!

**Comment by polo2244** [comment]
Hope this helps someone.
I was recently stuck on the same issue. 
This is my code, the way I fixed it is in the comments.


    self.alreadyFetchedObjectIds = @[];
    PFQuery* query = [PFQuery queryWithClassName:@"classname"];
    [query whereKey:@"A" equalTo:@"B"];
    [query whereKey:@"C" equalTo:@"D"];
    [query whereKey:@"objectId" notContainedIn:self.alreadyFetchedObjectIds];
    query.cachePolicy = kPFCachePolicyCacheElseNetwork;
    [query findObjectsInBackgroundWithBlock:^(NSArray* objects, NSError* error){ //.. the sdk cached the result for this query using my constraints. (Note the empty alreadyFetchedObjectIds array)
        
        //.. now also self.alreadyFetchedObjectIds was modified in the block
        //(AFTER PARSE CACHED ITS RESPONSE) now contains ["objectid1", "objectId2"]
        for (PFObject *object in objects) {
            [self.alreadyFetchedObjectIds addObject:object.objectId];
        }
        
    }];
    
    
    // so when @clearCachedResult is called later, the sdk will try to look for the query that it cached with the constraints that it cached it
    // but the catch is that the constraints are regenerated from the query
    // so the new constarints at this point ([query clearCachedResult];) contains the new array ["objectid1", "objectId2"]
    // that parse DID NOT CACHE
    // so nothing will be cleared
    [query clearCachedResult];
    
    //this will yield the same results as the previous query
    [query findObjectsInBackgroud...]
    
    //so the fix is i replaced [query whereKey:@"objectId" notContainedIn:self.alreadyFetchedObjectIds];
    //with [query whereKey:@"objectId" notContainedIn:[NSArray arrayWithArray:self.alreadyFetchedObjectIds]];
    //this will prevent the array from being changed inside the query's constraints by copying its content
    //untill you set the constraint again with the new array
