### ISSUE TITLE
Need a way to add HTTP Headers

### ISSUE THREAD

**Issue by conanoc** [parse-community/Parse-SDK-iOS-OSX#877]
I need a way to add custom HTTP headers to parse http requests.
Parse android SDK has an API to add "network interceptors" which can modify request object (or response object either).

It will be good if I can add or remove headers at any point before making requests. I can only set network interceptors at initialization time on android SDK.

**Comment by nlutsenko** [comment]
This sounds like a good feature request.
Network interceptors sounds like a little bit of overkill, because at that point you might as well fork the SDK and add that functionality.

In terms of headers, let me ask you few questions:
- Would you set the http headers once at the initialization time of the SDK or per every request is a requirement?
- What is your use case for the headers? Purely so we can understand it better and maybe extend more portions that just this, or suggest an alternative solution...

**Comment by conanoc** [comment]
Okay. Let me add some information.
I need additional http headers for authentication. The parse server will be placed inside of a kind of gateway and that gateway requires some headers.

The required headers are dependent to the user, so the headers could be changed. Not have to be changed per every request but can be changed at some point after the initialization time.

**Comment by nlutsenko** [comment]
This is challenging, though we probably can find a way to make this work.
You can definitely get this working using OSS fork of the SDK and exposing/changing `PFURLSessionCommandRunner`. Let me know if that solution works for you.

**Comment by conanoc** [comment]
Yes. If the commandRunner instance is accessible and it provides an API to set headers, it will be enough.

**Comment by nlutsenko** [comment]
Would a fork work in your case then?

**Comment by conanoc** [comment]
I'm not sure how to get the instance of PFURLSessionCommandRunner.

**Comment by conanoc** [comment]
I found a way to get the instance of PFURLSessionCommandRunner.
```
commandRunner = [[ParseManager currentParseManager_] commandRunner];
```
But that commandRunner is a singleton and has fixed headers already set. So I will not be able to change the headers later.

I think the following way might be possible.
1. add a setter in PFCommandURLRequestConstructor to set additional headers.
2. change _getURLRequestHeadersAsyncForCommand: to include the headers.

I think I could get the PFCommandURLRequestConstructor by `[commandRunner __requestConstructor]`
@nlutsenko what do you think? I hope It can be done without fork.

**Comment by janajri** [comment]
Bump, @conanoc were you able to find a work around for this?

**Comment by zuymanto** [comment]
This could be paired/a response to the [parse-server's issue #1059](https://github.com/ParsePlatform/parse-server/issues/1059) ?

**Comment by conanoc** [comment]
@jakeblakeley not yet.

**Comment by conanoc** [comment]
I end up use swizzling as an adhoc way.
It seems to work well and I could add headers without fork. Lynk and LynkRequestConstructor are classes in my app.

```
@implementation LynkRequestConstructor

///--------------------------------------
#pragma mark - Public
///--------------------------------------

+ (NSMutableURLRequest *)urlRequestWithURL:(NSURL *)url
                                httpMethod:(NSString *)httpMethod
                               httpHeaders:(NSDictionary *)httpHeaders
                                parameters:(NSDictionary *)parameters {
    NSDictionary *additionalHeaders = [[Lynk sharedInstance] neoidHeaders];
    NSMutableDictionary *headers = [NSMutableDictionary dictionaryWithDictionary:httpHeaders];
    [headers addEntriesFromDictionary:additionalHeaders];

    return [LynkRequestConstructor urlRequestWithURL:url httpMethod:httpMethod httpHeaders:headers parameters:parameters];
}

+ (void) swizzleMethod {
    SEL selector = @selector(urlRequestWithURL:httpMethod:httpHeaders:parameters:);
    Method originalMethod = class_getClassMethod(NSClassFromString(@"PFHTTPURLRequestConstructor") , selector);
    Method swizzledMethod = class_getClassMethod([self class] , selector);
    method_exchangeImplementations(originalMethod, swizzledMethod);
}

@end
```

**Comment by seejayuu** [comment]
I am trying to get Gzip working for all parse requests. I enabled and tested compression on my heroku-hosted Parse instance and all is good. However, my iOS app isn't setting Accept Encoding: Gzip. Am I doing something stupid or is this another instance where custom headers would help?

**Comment by richardjrossiii** [comment]
@seejayuu I remember testing this a long time ago (GZIP is enabled on all Parse.com responses over 1KB IIRC), and it seemed like `NSURLConnection` which we were using at the time automatically inserted that header.

It's possible that `NSURLSession` no longer shares that behavior, which would be quite odd, and a separate bug in its own regard.

**Comment by conanoc** [comment]
@seejayuu NSURLSession also sends  Accept Encoding: Gzip header by defaults. You don't have to do anything to enable gzip in your ios app. You could see your packets gzipped if you capture them by packet sniffers.

**Comment by seejayuu** [comment]
I found the problem. The node.js/express migration Parse version that I am hosting on Heroku does not enable gzip on the server side. I corrected that and now all is good.

**Comment by swami701** [comment]
Hi Guys
I ended up doing like the below for android. It worked.

```sh
Parse.initialize(new Parse.Configuration.Builder(this).server(Config.PARSE_SERVER_URL)
          .applicationId(Config.PARSE_APPLICATION_ID)
          .clientKey("")
          .addNetworkInterceptor(chain -> {
            ParseHttpRequest request = chain.getRequest();
            ParseHttpRequest.Builder builder =
                new ParseHttpRequest.Builder(request).addHeader(Config.HEADER_KEY,
                    Config.HEADER_VALUE);
            return chain.proceed(builder.build());
          })
          .enableLocalDataStore()
          .build());
```
But I don't know how to do in iOS. Please help if any of you has the answer.

Thank you.

**Comment by conanoc** [comment]
@swami701 Have you tried the above code (LynkRequestConstructor) that I had put as a comment? Swizzling can be used to intercept something.

**Comment by lukelan** [comment]
@seejayuu & @swami701 : can please share how to enable gzip at parse server side. 
Thank you

**Comment by seejayuu** [comment]
In lib/cli/parse-server, add:

app.use(require(‘compression’));

before:

app.use(options.mountPath, api);

**Comment by lukelan** [comment]
Thank @seejayuu for your answer. 

I still got the error respond "incorrect header check" when I do REST API request with Content-Encoding = gzip.

Please help to share how you enable it in your server.

"I found the problem. The node.js/express migration Parse version that I am hosting on Heroku does not enable gzip on the server side. I corrected that and now all is good."

Thank again!!

**Comment by lukelan** [comment]
I end up using cloudFlare, it is support gzip. thank all

**Comment by wooiliang** [comment]
Hi @conanoc , can you please provide the sample code how to use LynkRequestConstructor in initializing the parse? Thanks! :bowtie:

**Comment by conanoc** [comment]
@wooiliang Just call [LynkRequestConstructor swizzleMethod]; and it should be called only once.
