### ISSUE TITLE
Network connection failed Error

### ISSUE THREAD

**Issue by ekapradityagk** [parse-community/Parse-SDK-iOS-OSX#921]
Hi, recently i try to migrate our own parse server into our azure server,

all the proccess is working fine until i try to connect to new server.

here is the code which i used

```

    [Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration> configuration) {
        configuration.applicationId = @"XXXXX;
        configuration.clientKey = @"XXXXX;
        configuration.server = @"XXXXX;
    }]];
//    [Parse setApplicationId:@"XX"
//                  clientKey:@"XX"];
//    [PFAnalytics trackAppOpenedWithLaunchOptions:launchOptions];

```

at first im using the code commented below to connect to parse server, when i try to use my own server, using the first code i got this error : 

> 2016-05-17 16:17:36.807 XXXXX[805:469608] [Error]: The request timed out. (Code: 100, Version: 1.12.0)
> 2016-05-17 16:17:36.808 XXXXX[805:469608] [Error]: Network connection failed. Making attempt 2 after sleeping for 2.820020 seconds.

Been trying to solve this since 2-3 days ago,

Thanks.

**Comment by kwstasna** [comment]
Can you confirm that your parse-server actually runs??
In your info.plist file do you have the following?

```
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
```

**Comment by ekapradityagk** [comment]
yes, i have that setting, it seems because of windows azure server, one of my colleague move it to one of vs and its working.

**Comment by amsalt18** [comment]
I recently migrated to back4app using Parse server and I am suddenly now getting this error. Did you find a fix?

**Comment by AlecKriebel** [comment]
I don't think this is the solution, but I get this error when trying to load a PPFile with spaces in the filename. Normally the spaces would be replaced with %20, however, this doesn't seem to be done by default in the iOS client or the Parse server.

**Comment by flovilmart** [comment]
Closing as resolved. As for the issue with the spaces vs %20, feel free to open a new issue with proper details.
