### ISSUE TITLE
PFUser.currentUser hangs on saveEventually in Airplane mode

### ISSUE THREAD

**Issue by ramkalari** [parse-community/Parse-SDK-iOS-OSX#926]
I'm using offline storage and calling saveEventually on a parse object. In airplane mode, the saveEventually call does not complete and blocks on [PFUser currentUser]. The parse sdk version is 1.13.0.

**Comment by acegreen** [comment]
As far as I understand it saveEventually() will not complete until you get your internet connection back and the object is saved. So regardless of airplane mode or no internet or bad connection, as long as the object didn't save, it will not return.

**Comment by ramkalari** [comment]
There is a difference between completing the save on the server and returning to the client. The save to the server happens when the internet connection is restored but the app will hang sometimes when invoking saveEventually. I have since worked around this issue as I didn't have time to debug this further
