### ISSUE TITLE
"Tried to resolve a localId for an object with no localId."

### ISSUE THREAD

**Issue by GrandAyrat** [parse-community/Parse-SDK-iOS-OSX#932]
I have live query on object. When subscription calls on update, i display alert. On alert button i call object.saveInBackGround and then error: "NSInternalInconsistencyException" with reason "Tried to resolve a localId for an object with no localId."

**Comment by ideastouch** [comment]
Hi, this issue looks relate to issue #881 which is actually something that Parse-Server doesn't support. The limitation is Parse doesn't support live query client with LocalDataStore enabled and but they check a value called localId at save time. If you ask me I think that any use of any LiveQuery functionality should raise an exception if LocalDataStore is enable. Anyway, is what it is.

Un ugly work around could be comment the localId check at Parse/PFRESTCommand.m line 225:
   ```
   - (void)resolveLocalIds {
       [self forEachLocalId:^(PFObject *pointer) {
           //   [pointer resolveLocalId];    //THIS TEST WAS COMMENTED, UGLY UGLY
           return YES;
       }];
       [self maybeChangeServerOperation];
   }
  ```

A better solution probably is choose another way to save data locally, ej. [realm](https://realm.io/products/swift/)
