### ISSUE TITLE
Fetching hierarchical complex object return error from localDataStore

### ISSUE THREAD

**Issue by CiraciNicolo** [parse-community/Parse-SDK-iOS-OSX#936]
We have an object structured like this:

```
class ObjectA: PFObject, PFSubclassing {

    @NSManaged var simpleType: NSNumber
    @NSManaged var user: User?
    @NSManaged var objectB: ObjectB? 
    @NSManaged var objectC: ObjectC?
    @NSManaged var objectD: ObjectD?

    static func parseClassName() -> String {
        return "Notification"
    }
}
```

Where objectB, objectC and objectD contain other pointers to PFObject subclasses.

Fetching this kind of objects always fails with error:

> Error Domain=Parse Code=120 "This object is not available in the offline cache." UserInfo={error=This object is not available in the offline cache., NSLocalizedDescription=This object is not available in the offline cache., code=120},

This is pretty serious. 
Please don't close this, or mark it as duplicate because there is not even fix for the others.

**Comment by frederoni** [comment]
Do you get that error when you query the object or when to try to access it?
Do you set `includeKeys` on the query?

```
query.includeKeys(["objectB", "objectC", "objectD"])
```

**Comment by iStopped** [comment]
Nope, no errors. I can also 'double include'.

**Comment by ferrinho** [comment]
any news on this? I'm getting the same error... I have includeKeys on both server and offline queries. The local queries work fine on the beginning, but then when I pin or unpin some objects "withName", and redo local query, I get this error.
