### ISSUE TITLE
Can't connect to several Parse servers

### ISSUE THREAD

**Issue by Coladia** [parse-community/Parse-SDK-iOS-OSX#938]
We've having an issue with the open source version of Parse which seems not to allow connections to several Parser server. We have apps running on MacOS and iOS to manage several Parser server. To be clear, we do not want to access several Parse servers at the same time.

The initializeWithConfiguration method on Parse class throws an exception when called if Parse is already initialized, which  seems logica" since the method starts with " PFConsistencyAssert(![self currentConfiguration], @"Parse is already initialized.");"

I had a look at the code, and I see not obvious reason to restart a new Parse init.
It used to work with the "old" Parse. Is there any technical reasons why it cannot run the open source version ?

Fred

**Comment by groschovskiy** [comment]
@Coladia you can use traffic balancer for split traffic. In Google Cloud Platform and Amazon AWS this feature available from the box. You need have one application ident for all your parse servers. In AppDelegate you need replace your current server URL to load balancer URL.
