### ISSUE TITLE
iOS App no longer receiving push notifications

### ISSUE THREAD

**Issue by pirocso** [parse-community/Parse-SDK-iOS-OSX#962]
I know this is most likely a specific app issue but I need help here. Our iOS app is no longer receiving push notifications.

The push log on the Parse dashboard indicates that over 1000+ pushes are sent, the devices are registered properly via PFInstallation records and didRegisterForRemoteNotificationsWithDeviceToken.

The push is sent successfully via Parse Cloud Code according to the log, and the app is properly registered to receive push notifications.

I also verified that the certificates had not expired and that the provisioning profiles were correct. The p12 certificates are also correctly added to Parse.

All seems to be configured and programmed properly but push notifications have suddenly stopped working for the last 2 minor releases of our app.

The didReceiveRemoteNotification method is never called!

Anybody else experiencing these issues or know how to debug this such that we can figure out what's wrong?

**Comment by farhansyed9** [comment]
Can you show the code that you run for the push to go through? Is it in cloud code or client side?

**Comment by pirocso** [comment]
Sorry the code is private - it runs from Cloud code

**Comment by farhansyed9** [comment]
can't really help without knowing the exact code your trying to run to make a push

**Comment by orbinv** [comment]
This is my installation cloud code

 Make sure all installations point to the current user.
Parse.Cloud.beforeSave(Parse.Installation, function(request, response) {
  Parse.Cloud.useMasterKey();
  if (request.user) {
 request.object.set('user', request.user);
  } else {
  //request.object.unset('user');
  }
  response.success();
});

So for some reason user  becomes undefined when another user tries to send
push notification via following the user or liking a post or commenting on
a post.
