### ISSUE TITLE
99.99(field as Number) value is returned as 99.98999999999999

### ISSUE THREAD

**Issue by shineall** [parse-community/Parse-SDK-iOS-OSX#966]
some numbers are returned wrong. 
try 99.99 , 97.99

**Comment by matdimar** [comment]
@shineall Did you find a solution to this? We've encountered the same thing.

**Comment by matdimar** [comment]
I had a similar issue that I brought up in a separate Issue marker. This might help: 

At first, I converted the NSString to a float and then to an NSNumber. While it printed properly in my app, it saved improperly (e.g. 0.01 saved as 0.0099999999876...). The solution is to use the following code to avoid the problem altogether:

`NSNumberFormatter *f = [[NSNumberFormatter alloc] init]; f.numberStyle = NSNumberFormatterDecimalStyle; NSNumber *price = [f numberFromString:priceStringWithoutCurrencyCharacter];`

Hope that helps!
