### ISSUE TITLE
Missing library version

### ISSUE THREAD

**Issue by andrey-krukovskiy** [parse-community/Parse-SDK-iOS-OSX#998]
Hi!
When I have installed ParseTwitterUtils-iOS using Carthage, I have receiving next error while starting the app:
`dyld: Library not loaded: @rpath/Parse.framework/Parse`
`Referenced from:/Users/.../My.app/Frameworks/ParseTwitterUtils.framework/ParseTwitterUtils`
`Reason: Incompatible library version: ParseTwitterUtils requires version 1.0.0 or later, but Parse provides version 0.0.0` 
Seems, `DYLIB_CURRENT_VERSION` and `DYLIB_COMPATIBILITY_VERSION` is missed.
Point me please, how to better fix this issue. Should I change some specific config or just fix it in Xcode build settings?

**Comment by sherwinzadeh** [comment]
Hi @andrey-krukovskiy  I'm also getting this. Did you find a resolution? Thanks so much!

**Comment by andrey-krukovskiy** [comment]
@sherwinzadeh Yes, i have forked both `ParseTwitterUtils-iOS` and `Parse-SDK-iOS-OSX`.
In `Parse-SDK-iOS-OSX` I have changed `Compatibility version` and `Current library version` build settings of `Linking` section to `1`.
Then in my project's `Cartfile` I have changed path of these repos to my forks.
Now it works but I'm not sure that this is a best way to fix it. Probably we should make these changes in configuration files which I see in `Configurations` folder.

@sherwinzadeh You can use my forks for now if you wish.

**Comment by sherwinzadeh** [comment]
Thank you so much Andrey. Unfortunately I'm still getting the error with your fork. Not sure what I may be doing wrong. 

Here is my cartfile

```
github "BoltsFramework/Bolts-ObjC" ~> 1.6
github "andrey-krukovskiy/Parse-SDK-iOS-OSX"
github "andrey-krukovskiy/ParseTwitterUtils-iOS"
```

Any ideas? Would it be possible for you to just send me your framework binaries?

**Comment by andrey-krukovskiy** [comment]
@sherwinzadeh Seems, you do not specify specific commit or branch of your dependencies. So, I assume, carthage build last tagged version of framework. 
Try to specify master branch of my fork to tell carthage to build last commit from this branch. Like this:
`github "andrey-krukovskiy/Parse-SDK-iOS-OSX" "master"`

**Comment by sherwinzadeh** [comment]
Thank you so much -- yes that did it!
