### ISSUE TITLE
Issues connecting to AWS Parse Server relating to PFPush.subscribeToChannel

### ISSUE THREAD

**Issue by russell-davis** [parse-community/Parse-SDK-iOS-OSX#999]
When setting up a new starter project on beta 4, I get these flags. 
<img width="761" alt="screen shot 2016-08-01 at 5 35 10 pm" src="https://cloud.githubusercontent.com/assets/19596011/17311127/7eb1921c-580e-11e6-8c47-8baa0aa026e9.png">

Anyone have the fix?

**Comment by preshetin** [comment]
@russell-davis  Worked for me, when I changed `error: NSError?` to `error: Error?` in this line:

```
PFPush.subscribeToChannel(inBackground: "") { (succeeded: Bool, error: Error?) in
...
```
